import json
import uuid
import os

# Generate 10 unique IDs
ids = [str(uuid.uuid4()) for _ in range(10)]

assemblies = [
    {
        "id": ids[0],
        "slug": "large-tree-removal-chipping-hauling-stump-grinding",
        "version": "1.0.0",
        "trade": "Landscaping",
        "category": "Tree Service",
        "subcategory": "Removal",
        "name": "Large Tree Removal (Over 24\" DBH) with Chipping, Hauling, and Stump Grinding",
        "description": "Complete removal of a tree with a trunk diameter at breast height (DBH) exceeding 24 inches. Includes climbing or bucket truck access, piecemeal sectioning, chipping of brush, log hauling, stump grinding to 6 inches below grade, and cleanup.",
        "customerDescription": "Professional removal of a large tree (over 24 inches wide) on your property, including grinding down the stump and cleaning up all debris.",
        "contractorNotes": "Assess tree stability and lean prior to climbing. Rigging rope size must be checked. Ensure safety zone is cleared of all non-essential personnel.",
        "typicalUseCase": "Removal of hazardous, dead, or unwanted large trees near structures or power lines.",
        "projectTypes": ["Residential", "Commercial", "Municipal"],
        "constructionPhase": "Site Prep",
        "requiredInputs": ["Tree DBH (diameter at breast height)", "Access width to yard", "Proximity to power lines"],
        "optionalInputs": ["Wood retention by customer", "Cranes required for access", "Lawn restoration after grinding"],
        "materialCategories": ["Grass Seed", "Straw", "Topsoil"],
        "laborCategories": ["Certified Arborist", "Climber / Cutter", "Ground Crewman", "Equipment Operator"],
        "equipmentCategories": ["12\" Wood Chipper", "Bucket Truck (60ft)", "Stump Grinder", "Stihl MS461 Chainsaw"],
        "safetyRequirements": ["OSHA compliant hard hats", "Chainsaw safety chaps", "Hearing and eye protection", "High-visibility vests"],
        "riskFactors": ["Target proximity (house/shed)", "Utility lines within fall zone", "Internal rot/hollow trunk", "Drop zone slope"],
        "permitAwareness": "Many municipalities require a tree removal permit for trees over a certain DBH. Verify local ordinances before cutting.",
        "inspectionAwareness": "Arborist pre-removal evaluation report may be required by local urban forestry departments.",
        "codeConsiderations": "Adhere to local tree conservation bylaws and replacement planting requirements.",
        "dependencies": ["Utility company line dropping (if within 10ft of primary lines)", "Stump utility locate (811) before grinding"],
        "wasteDisposal": "All brush chipped and hauled; logs sectioned and hauled to local green waste facility; grindings left on site or hauled away.",
        "proposalScopeOfWork": "Provide all labor, materials, and equipment to safely remove one large tree (>24\" DBH), grind the stump, and clean up the work area.",
        "proposalAssumptions": "Assuming normal soil conditions, standard truck access within 50 feet of the tree base, and no hidden concrete or metal within the trunk.",
        "proposalExclusions": "Excludes replacement planting, underground utility redirection, and deep hole backfilling beyond standard ground stump area.",
        "warrantyLanguage": "Service guarantees removal of tree and stump to specified depth. No warranty is provided for turf damage due to heavy machinery access.",
        "productionNotes": "Production rate varies from 4 to 8 hours depending on canopy width and rigging complexity.",
        "futurePricingHooks": "Connect to local diesel price indices and landfill tip fee rates for automatic adjustments.",
        "futureAINotes": "AI should adjust labor hours based on yard slope and overhead line density inputs."
    },
    {
        "id": ids[1],
        "slug": "medium-tree-removal-chipping",
        "version": "1.0.0",
        "trade": "Landscaping",
        "category": "Tree Service",
        "subcategory": "Removal",
        "name": "Medium Tree Removal (12\" - 24\" DBH) with Chipping and Hauling",
        "description": "Removal of a medium tree (12 to 24 inches DBH) from site. Includes felling or sectioning, chipping all branches, sectioning logs into manageable pieces, and hauling debris away. Stump grinding is excluded.",
        "customerDescription": "Removal of a medium-sized tree (12 to 24 inches wide), chipping of branches, and hauling away all logs. (Stump grinding not included).",
        "contractorNotes": "Clear ground area before felling. Check wind direction and speed. Use tag lines for controlled drops.",
        "typicalUseCase": "Removal of standard yard trees for landscaping renovations or light hazard mitigation.",
        "projectTypes": ["Residential", "Commercial"],
        "constructionPhase": "Site Prep",
        "requiredInputs": ["Tree DBH", "Felling space vs rigging space", "Ground access restrictions"],
        "optionalInputs": ["Log splitting service", "Stump treatment with herbicide"],
        "materialCategories": ["Herbicide (optional)"],
        "laborCategories": ["Cutter / Climber", "Ground Crewman"],
        "equipmentCategories": ["9\" Wood Chipper", "Stihl MS261 Chainsaw", "Dump Truck"],
        "safetyRequirements": ["Chainsaw chaps", "Hearing protection", "Steel toe boots"],
        "riskFactors": ["Pedestrian traffic on nearby sidewalks", "Property boundaries", "Fences in drop zone"],
        "permitAwareness": "Check municipal zoning rules for tree protection overlays before starting.",
        "inspectionAwareness": "None expected, unless within a designated critical environmental zone.",
        "codeConsiderations": "Check if tree counts against minimum canopy density codes for the property.",
        "dependencies": ["Clear access path for wood chipper and truck."],
        "wasteDisposal": "Logs and wood chips hauled to a green recycling center.",
        "proposalScopeOfWork": "Furnish all labor and equipment to cut down one medium tree, chip branches, and remove wood from the site.",
        "proposalAssumptions": "Assumes direct felling is possible or minimal rigging is needed.",
        "proposalExclusions": "Stump grinding, stump removal, and backfilling are strictly excluded.",
        "warrantyLanguage": "Standard removal warranty. Excludes turf damage from tires.",
        "productionNotes": "Typically takes 2 to 4 hours with a standard 3-person crew.",
        "futurePricingHooks": "Tie pricing to regional green waste tipping rates.",
        "futureAINotes": "AI can predict felling vs rigging requirements based on nearby structures."
    },
    {
        "id": ids[2],
        "slug": "small-tree-removal-grubbing",
        "version": "1.0.0",
        "trade": "Landscaping",
        "category": "Tree Service",
        "subcategory": "Removal",
        "name": "Small Tree Removal (Under 12\" DBH) and Root Grubbing",
        "description": "Removal of small trees (under 12 inches DBH) and manual or machine grubbing of the root ball. Includes complete extraction of the root system to prevent regrowth.",
        "customerDescription": "Removal of a small tree (under 12 inches wide) including pulling out its roots so it does not grow back.",
        "contractorNotes": "Identify any shallow buried lines or irrigation heads near the root zone before grubbing.",
        "typicalUseCase": "Clearing small scrub trees, saplings, or invasive species before fence installation or planting.",
        "projectTypes": ["Residential", "Commercial"],
        "constructionPhase": "Site Prep",
        "requiredInputs": ["Tree DBH", "Root ball extraction depth"],
        "optionalInputs": ["Soil amendment after extraction"],
        "materialCategories": ["Clean Fill Dirt"],
        "laborCategories": ["Ground Laborer", "Mini-Excavator Operator"],
        "equipmentCategories": ["Mini-Excavator", "Root Shovel", "Chainsaw"],
        "safetyRequirements": ["Safety glasses", "Gloves", "Steel toe boots"],
        "riskFactors": ["Shallow underground utility lines (irrigation, cable)", "Soil instability"],
        "permitAwareness": "Usually exempt from permits due to small size, but verify local wetlands regulations.",
        "inspectionAwareness": "Usually none required.",
        "codeConsiderations": "Exempt in most jurisdictions, unless planting replacement mandates apply.",
        "dependencies": ["811 utility locate if using heavy machinery for grubbing."],
        "wasteDisposal": "Debris and root ball hauled away to clean fill and wood recycling centers.",
        "proposalScopeOfWork": "Complete removal of small tree and root ball, backfilling the resulting hole with clean fill dirt.",
        "proposalAssumptions": "Roots are accessible by mini-excavator without damaging adjacent paved surfaces.",
        "proposalExclusions": "Sod restoration and planting of new vegetation are excluded.",
        "warrantyLanguage": "Guaranteed no regrowth of the removed tree species from that root zone for 12 months.",
        "productionNotes": "Averages 1 to 2 hours per tree.",
        "futurePricingHooks": "Base machine pricing on regional diesel and mini-excavator rental indices.",
        "futureAINotes": "AI should flag potential root encroachment on nearby foundations or walkways."
    },
    {
        "id": ids[3],
        "slug": "tree-canopy-pruning-trimming",
        "version": "1.0.0",
        "trade": "Landscaping",
        "category": "Tree Service",
        "subcategory": "Pruning",
        "name": "Tree Canopy Pruning and Trimming (Up to 35ft Height)",
        "description": "Professional pruning of tree canopy up to 35 feet. Includes crown cleaning (removing dead/diseased wood), crown thinning (improving light penetration), and crown raising (low branch clearance). All cuts made to ANSI A300 standards.",
        "customerDescription": "Professional trimming and pruning of your tree's branches up to 35 feet high to remove dead wood and improve tree health.",
        "contractorNotes": "Ensure arborist makes proper collar cuts. Do not flush cut or leave long stubs. Do not remove more than 25% of live foliage in a single season.",
        "typicalUseCase": "Maintenance pruning for mature shade trees, fruit trees, or ornamental trees.",
        "projectTypes": ["Residential", "Commercial"],
        "constructionPhase": "Landscaping",
        "requiredInputs": ["Tree height", "Tree species", "Percentage of canopy to prune"],
        "optionalInputs": ["Mistletoe removal", "Tree cabling/bracing"],
        "materialCategories": ["Tree Wound Dressing (rarely used)"],
        "laborCategories": ["Certified Arborist", "Climber", "Ground Crewman"],
        "equipmentCategories": ["Pole Pruning Saw", "Chainsaw", "Wood Chipper"],
        "safetyRequirements": ["Climbing harness and ropes", "Helmets", "Eye protection"],
        "riskFactors": ["Falls from height", "Falling branches striking property", "Bee/wasp nests in canopy"],
        "permitAwareness": "Some heritage trees require permits even for structural pruning. Check local guidelines.",
        "inspectionAwareness": "Heritage tree trimming may require a post-pruning report from a certified arborist.",
        "codeConsiderations": "Pruning must comply with ANSI A300 standards and local urban forestry codes.",
        "dependencies": ["Favorable weather (no high winds or heavy rain)."],
        "wasteDisposal": "All trimmed branches chipped and hauled off-site.",
        "proposalScopeOfWork": "Pruning of designated tree canopy to remove deadwood, raise crown, and thin dense branches for wind resistance.",
        "proposalAssumptions": "Assuming tree is structurally sound for climbing and has standard ground access.",
        "proposalExclusions": "Excludes insect spraying, deep root feeding, and pruning of adjacent trees.",
        "warrantyLanguage": "All work completed by ISA Certified Arborists. No warranty on future tree health or storm survival.",
        "productionNotes": "Takes approximately 2 to 4 hours per tree.",
        "futurePricingHooks": "Tie to labor wage indices for certified tree care professionals.",
        "futureAINotes": "AI can verify species growth patterns to recommend ideal pruning seasons."
    },
    {
        "id": ids[4],
        "slug": "stump-grinding-site-backfill",
        "version": "1.0.0",
        "trade": "Landscaping",
        "category": "Tree Service",
        "subcategory": "Stump Grinding",
        "name": "Stump Grinding and Site Restoration Package",
        "description": "Grinding of an exposed tree stump to a depth of 6 to 8 inches below ground level, including grinding of surface lateral roots. Includes removal of stump grindings, backfilling with topsoil, tamping, and seeding with turf grass.",
        "customerDescription": "Grinding down an existing tree stump, cleaning up the wood chips, filling the hole with fresh soil, and planting grass seed.",
        "contractorNotes": "Verify utility lines (water, gas, electric, cable) have been marked. Stump grinders can easily cut shallow conduits.",
        "typicalUseCase": "Removal of unsightly stumps in lawns or pathways after tree removal.",
        "projectTypes": ["Residential", "Commercial"],
        "constructionPhase": "Landscaping",
        "requiredInputs": ["Stump diameter at widest point", "Depth requirement", "Restoration seed type"],
        "optionalInputs": ["Soil amendment", "Sod installation instead of seed"],
        "materialCategories": ["Premium Topsoil", "Turf Grass Seed", "Starter Fertilizer", "Straw Mulch"],
        "laborCategories": ["Equipment Operator", "Laborer"],
        "equipmentCategories": ["Self-Propelled Stump Grinder", "Dump Trailer", "Tamp / Rakes"],
        "safetyRequirements": ["Debris shields", "Face shield", "Steel toe boots", "Hearing protection"],
        "riskFactors": ["Flying debris hitting windows/vehicles", "Buried metal/rocks in stump base", "Underground utility strike"],
        "permitAwareness": "Normally exempt from permits unless in critical environmental overlays.",
        "inspectionAwareness": "None.",
        "codeConsiderations": "Ensure compliance with local stormwater runoff guidelines (prevent sediment from entering streets).",
        "dependencies": ["811 utility locate is mandatory prior to grinding."],
        "wasteDisposal": "Stump mulch shavings hauled away or left on-site as mulch per customer preference.",
        "proposalScopeOfWork": "Provide all equipment and labor to grind stump, remove grindings, backfill with topsoil, rake smooth, and seed.",
        "proposalAssumptions": "Assuming utility locate is clear and stump is free of concrete or steel supports.",
        "proposalExclusions": "Irrigation line repair (if hit due to incorrect/missing homeowner marking) and watering of new seed.",
        "warrantyLanguage": "Guarantees stump ground to specified depth. Grass growth depends on customer watering and is not warrantied.",
        "productionNotes": "Averages 1 to 2.5 hours depending on wood hardness (oak vs pine).",
        "futurePricingHooks": "Correlate with topsoil supply costs and dump tipping fees.",
        "futureAINotes": "AI should factor in proximity to structures to adjust for protective shielding needs."
    },
    {
        "id": ids[5],
        "slug": "emergency-storm-damage-tree-clearance",
        "version": "1.0.0",
        "trade": "Landscaping",
        "category": "Tree Service",
        "subcategory": "Removal",
        "name": "Emergency Storm Damage Tree Clearance and Safety Rigging",
        "description": "Rapid response clearance of fallen or dangerously hanging storm-damaged trees. Includes hazard stabilization, complex safety rigging, sectioning wood off structures or roadways, and emergency hauling of blockages.",
        "customerDescription": "24/7 emergency service to safely remove trees that have fallen on your house, car, or driveway during a storm.",
        "contractorNotes": "Conduct a dynamic risk assessment. Watch for spring poles, tensioned logs, and electrical hazards. Never work near downed wires.",
        "typicalUseCase": "Post-storm emergency mitigation of blocked paths or structural impacts.",
        "projectTypes": ["Residential", "Commercial", "Municipal"],
        "constructionPhase": "Site Prep",
        "requiredInputs": ["Structure impact status", "Downed power line proximity", "Tree diameter and suspension details"],
        "optionalInputs": ["Temporary tarping of roof", "Crane rental coordination"],
        "materialCategories": ["Tarping Materials (optional)", "Rope / Rigging slings"],
        "laborCategories": ["Emergency Arborist Lead", "Advanced Rigger", "Ground Crewman"],
        "equipmentCategories": ["70-Ton Crane (optional)", "Bucket Truck", "High-Capacity Chipper"],
        "safetyRequirements": ["Climber rescue gear", "High-visibility clothing", "Dynamic safety boundaries"],
        "riskFactors": ["Unstable suspended loads", "Live power lines", "Severe weather regrowth", "Fatigued crew"],
        "permitAwareness": "Emergency hazard mitigation is typically exempt from advance permitting, but photo documentation is required.",
        "inspectionAwareness": "City forester or insurance adjuster inspection usually occurs post-clearing.",
        "codeConsiderations": "Prioritize immediate life/property safety over standard preservation codes during emergency declarations.",
        "dependencies": ["Power company clearance (if electrical lines are entangled)."],
        "wasteDisposal": "Debris stabilized and moved to safe staging area, chipped immediately or hauled as logs.",
        "proposalScopeOfWork": "Perform emergency rigging and tree cutting to stabilize and remove immediate hazard to structures or access roads.",
        "proposalAssumptions": "Immediate structural stability is sufficient to support rigging anchors.",
        "proposalExclusions": "Structural repairs to roofs/walls, permanent fencing repair, and stump extraction.",
        "warrantyLanguage": "No warranty on survival of remaining damaged trees. Emergency work is billed hourly.",
        "productionNotes": "Charged on an emergency response portal base rate plus hourly crew rates.",
        "futurePricingHooks": "Emergency premium multipliers linked to severe weather declarations.",
        "futureAINotes": "AI can recommend emergency pricing premiums based on wind speed and damage density reports."
    },
    {
        "id": ids[6],
        "slug": "large-caliper-tree-planting-installation",
        "version": "1.0.0",
        "trade": "Landscaping",
        "category": "Tree Service",
        "subcategory": "Planting",
        "name": "Large Caliper Shade Tree Planting and Staking (2\" - 3\" Caliper)",
        "description": "Installation of a premium 2-inch to 3-inch caliper balled-and-burlapped (B&B) shade tree. Includes excavation of planting pit (2x root ball width), placement, removal of wire basket, backfill with organic soil mix, staking, and mulching.",
        "customerDescription": "Planting a new, high-quality shade tree (2 to 3 inches thick at the base), including staking it for support and applying protective mulch.",
        "contractorNotes": "Ensure root flare is level with or slightly above final grade. Do not bury the root flare. Cut top third of wire basket and burlap.",
        "typicalUseCase": "Adding mature trees to new home construction, streetscapes, or commercial parking lots.",
        "projectTypes": ["Residential", "Commercial"],
        "constructionPhase": "Landscaping",
        "requiredInputs": ["Tree species preference", "Planting location access", "Soil drainage quality"],
        "optionalInputs": ["Drip irrigation line tie-in", "Root barrier installation"],
        "materialCategories": ["B&B Shade Tree", "Organic Soil Amendment", "Tree Stakes", "Strap Ties", "Hardwood Mulch"],
        "laborCategories": ["Landscape Laborer", "Skid Steer Operator"],
        "equipmentCategories": ["Skid Steer with Auger", "Tree Dolly", "Hand Shovels"],
        "safetyRequirements": ["Lifting braces", "Steel toe boots", "Gloves"],
        "riskFactors": ["Back strain from heavy lifting", "Damage to irrigation lines", "Tree trunk bark damage during transport"],
        "permitAwareness": "Urban planting permits may be required for parkway or easement trees. Call city forestry office.",
        "inspectionAwareness": "Easement plantings may require inspection by city urban foresters.",
        "codeConsiderations": "Adhere to setback rules for property lines, water mains, and overhead utilities.",
        "dependencies": ["Underground utility locate (811)."],
        "wasteDisposal": "Clean up excavated sod and excess clay soil; haul to recycling yard.",
        "proposalScopeOfWork": "Supply, plant, stake, and mulch one large caliper tree at designated location.",
        "proposalAssumptions": "Assuming normal, diggable soil (no heavy ledge rock) and direct access for machinery.",
        "proposalExclusions": "Ongoing watering (homeowner responsibility), root barrier systems, and structural drainage installs.",
        "warrantyLanguage": "1-year warranty on tree survival, contingent upon proof of adequate watering system operations.",
        "productionNotes": "Typically takes 1.5 to 3 hours per tree.",
        "futurePricingHooks": "Link to wholesale nursery catalog price updates and fuel index.",
        "futureAINotes": "AI can verify planting zone suitability (USDA Hardiness Zones) based on zip code."
    },
    {
        "id": ids[7],
        "slug": "palm-tree-trimming-skinning",
        "version": "1.0.0",
        "trade": "Landscaping",
        "category": "Tree Service",
        "subcategory": "Pruning",
        "name": "Palm Tree Trimming and Trunk Skinning Package",
        "description": "Trimming of dead fronds, seed pods, and fruit clusters from palm trees. Optional skinning (shaving) of the trunk to remove old leaf bases, leaving a clean, smooth, diamonds-patterned or shaved finish.",
        "customerDescription": "Trimming dead branches and seed pods from palm trees, with optional shaving of the trunk for a neat, smooth look.",
        "contractorNotes": "Ensure safety ropes are protected against chainsaw cuts. Watch for palm tree pests like weevils. Skin only live fronds carefully.",
        "typicalUseCase": "Aesthetic maintenance of ornamental palm trees in coastal or warm climates.",
        "projectTypes": ["Residential", "Commercial"],
        "constructionPhase": "Landscaping",
        "requiredInputs": ["Palm height", "Palm species (e.g. Queen, Date, Fan)", "Skinning/shaving requirement"],
        "optionalInputs": ["Pest micro-injection treatment"],
        "materialCategories": ["Debris Bags"],
        "laborCategories": ["Climber", "Ground Crewman"],
        "equipmentCategories": ["Palm Skinning Knife", "Chainsaw", "Extension Ladders"],
        "safetyRequirements": ["Climbing spikes (if tree is to be removed, otherwise use ladders/lift)", "Eye protection", "Saddle"],
        "riskFactors": ["Stings from wasps nesting in old fronds", "Falling frond cluster collapse", "Chain slips during shaving"],
        "permitAwareness": "Usually none required, unless palms are part of a protected coastal zone registry.",
        "inspectionAwareness": "None.",
        "codeConsiderations": "Avoid over-trimming (no 'hurricane cuts'). Keep pruning between 9 and 3 o'clock positions.",
        "dependencies": ["Clear ground space around the palm for falling debris."],
        "wasteDisposal": "All fronds and shaved bark collected, loaded, and hauled to green recycling.",
        "proposalScopeOfWork": "Trim dead foliage and seed stalks from palms, shave trunks as specified, and haul away waste.",
        "proposalAssumptions": "Assuming palms are accessible without overhead power line interference.",
        "proposalExclusions": "Excludes root system pruning and soil fertilization.",
        "warrantyLanguage": "Service guarantees professional pruning and shaving. No warranty on disease susceptibility.",
        "productionNotes": "Averages 1 hour per palm for basic trim; 2 hours if full skinning is required.",
        "futurePricingHooks": "Base on local arborist labor rates and local green waste dumping fees.",
        "futureAINotes": "AI can adjust prices based on palm heights and frond denseness."
    },
    {
        "id": ids[8],
        "slug": "brush-clearing-underbrush-removal",
        "version": "1.0.0",
        "trade": "Landscaping",
        "category": "Tree Service",
        "subcategory": "Removal",
        "name": "Acreage Brush Clearing and Invasive Underbrush Removal",
        "description": "Clearing of dense underbrush, saplings up to 4\" diameter, and invasive species (such as buckthorn or honeysuckle). Includes brush cutting, mulching or chipping on-site, and optional stump herbiciding to prevent regrowth.",
        "customerDescription": "Clearing thick brush, overgrown weeds, and small wild trees from your property to open up the space.",
        "contractorNotes": "Check for hidden metal posts, barbed wire, and garbage in the brush before mowing. Wear protective gear to prevent poison ivy contact.",
        "typicalUseCase": "Reclaiming overgrown property boundaries, preparing land for construction, or forest fire fuel reduction.",
        "projectTypes": ["Residential", "Commercial", "Agricultural"],
        "constructionPhase": "Site Prep",
        "requiredInputs": ["Area size (SF or Acre)", "Brush density (Light, Medium, Heavy)", "Slope of the land"],
        "optionalInputs": ["Herbicidal stump treatment", "Sod seeding after clearing"],
        "materialCategories": ["Garlon Herbicide (optional)"],
        "laborCategories": ["Equipment Operator", "Ground Hand-Cutter"],
        "equipmentCategories": ["Skid Steer with Brush Cutter", "Chainsaw", "Brush Mower / Mulcher"],
        "safetyRequirements": ["Forestry helmet with mesh shield", "Safety boots", "Poison ivy barrier cream"],
        "riskFactors": ["Hidden ground obstacles", "Yellowjacket ground nests", "Steep slopes (rollover risk)"],
        "permitAwareness": "Clearing within environmental buffer zones (wetlands, steep slopes) may require conservation commission approval.",
        "inspectionAwareness": "Wetland boundary inspections may occur before clearing starts.",
        "codeConsiderations": "Adhere to local wetland protection acts and land disturbance limits.",
        "dependencies": ["Clearly marked property line stakes to prevent encroachment."],
        "wasteDisposal": "Debris mulched on-site and spread evenly, or piled and burned if permitted, or hauled.",
        "proposalScopeOfWork": "Provide mechanical clearing of underbrush on designated acreage, mulching material back into the soil.",
        "proposalAssumptions": "Assuming no large rocks or metal debris inside the clearing boundaries.",
        "proposalExclusions": "Excludes removal of trees larger than 4 inches DBH, and excludes grading.",
        "warrantyLanguage": "Clearing is a one-time service. Herbicidal treatments have a 90% success rate on regrowth prevention.",
        "productionNotes": "A single operator with a skid steer mulcher can clear about 0.5 to 1 acre per day depending on density.",
        "futurePricingHooks": "Correlate pricing with heavy machinery rental indices and diesel prices.",
        "futureAINotes": "AI can evaluate terrain slope and vegetation density from aerial imagery inputs."
    },
    {
        "id": ids[9],
        "slug": "deep-root-tree-fertilization",
        "version": "1.0.0",
        "trade": "Landscaping",
        "category": "Tree Service",
        "subcategory": "Fertilization",
        "name": "Deep Root Tree Fertilization and Soil Aeration Package",
        "description": "High-pressure soil injection of custom liquid fertilizer blend into the tree's root zone (2 to 6 inches deep). Designed to relieve soil compaction, deliver micro/macro nutrients, and improve root health of mature trees.",
        "customerDescription": "Deep feeding for your trees by injecting liquid fertilizer directly into the soil where the roots can absorb it best.",
        "contractorNotes": "Space injection grid 2 to 3 feet apart under the tree's drip line. Do not inject near primary root flares. Keep pressure below 200 PSI to avoid root damage.",
        "typicalUseCase": "Revitalizing stressed, yellowing, or urban compact-soil mature trees.",
        "projectTypes": ["Residential", "Commercial"],
        "constructionPhase": "Landscaping",
        "requiredInputs": ["Tree canopy radius (drip line area)", "Soil compaction level", "Number of trees"],
        "optionalInputs": ["Mycorrhizae soil inoculant add-on", "Systemic insecticide integration"],
        "materialCategories": ["Slow-release Liquid Fertilizer (12-4-8 or similar)", "Mycorrhizal Fungi", "Soil Surfactants"],
        "laborCategories": ["Arborist Technician"],
        "equipmentCategories": ["Deep Root Injection Probe", "High-Pressure Spray Rig / Tank Truck"],
        "safetyRequirements": ["Chemical resistant gloves", "Safety glasses", "Spill kit on-site"],
        "riskFactors": ["Chemical runoff into street drains", "Damaging shallow underground gas or communication lines"],
        "permitAwareness": "Usually none required, but check for local regulations on nitrogen fertilizer application window.",
        "inspectionAwareness": "None.",
        "codeConsiderations": "Follow state agricultural extension guidelines for nitrogen runoff prevention.",
        "dependencies": ["Access to water source on site to fill spray rig tanks if needed."],
        "wasteDisposal": "No physical waste generated; chemical containers triple-rinsed and recycled.",
        "proposalScopeOfWork": "Perform deep root liquid fertilization injections throughout the drip line of designated trees.",
        "proposalAssumptions": "Assuming grass area under canopy is accessible and soil is moist enough for probe penetration.",
        "proposalExclusions": "Excludes pest spraying, pruning, and soil testing laboratory fees.",
        "warrantyLanguage": "No warranty on survival of diseased trees. Fertilization is a preventative health treatment.",
        "productionNotes": "Takes 45 minutes to 1.5 hours per large tree.",
        "futurePricingHooks": "Link to liquid chemical fertilizer price sheets and fuel surcharges.",
        "futureAINotes": "AI can customize fertilizer formulations based on soil test inputs."
    }
]

# Write to knowledge/assemblies/tree-service/batch_1.json
os.makedirs("knowledge/assemblies/tree-service", exist_ok=True)
with open("knowledge/assemblies/tree-service/batch_1.json", "w") as f:
    json.dump(assemblies, f, indent=2)

print(f"Generated 10 Tree Service assemblies in knowledge/assemblies/tree-service/batch_1.json")
