"""ElectricalAgent — 100 items"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Service Entrance ───────────────────────────────────────
    {"id":uid(),"name":"200 Amp Overhead Service Entrance Install","category":"Electrical","unit":"EA","laborCost":485.00,"materialCost":385.00,"equipmentCost":35.00,"notes":"Complete 200A meter socket"},
    {"id":uid(),"name":"400 Amp Underground Service Install","category":"Electrical","unit":"EA","laborCost":850.00,"materialCost":685.00,"equipmentCost":65.00,"notes":"400A underground meter loop"},
    {"id":uid(),"name":"100 Amp Service Upgrade - Panel and Meter","category":"Electrical","unit":"EA","laborCost":285.00,"materialCost":225.00,"equipmentCost":25.00,"notes":"Upgrade to 100A service"},
    # ── Load Centers and Panels ────────────────────────────────
    {"id":uid(),"name":"200 Amp Main Panel Install - 40 Circuit","category":"Electrical","unit":"EA","laborCost":385.00,"materialCost":285.00,"equipmentCost":15.00,"notes":"200A 240/120V 40-circuit panel"},
    {"id":uid(),"name":"200 Amp Main Panel Install - 60 Circuit","category":"Electrical","unit":"EA","laborCost":425.00,"materialCost":365.00,"equipmentCost":15.00,"notes":"Full 60-circuit load center"},
    {"id":uid(),"name":"100 Amp Subpanel Install","category":"Electrical","unit":"EA","laborCost":285.00,"materialCost":185.00,"equipmentCost":10.00,"notes":"Subpanel for detached structure"},
    {"id":uid(),"name":"60 Amp Subpanel - Garage","category":"Electrical","unit":"EA","laborCost":225.00,"materialCost":125.00,"equipmentCost":8.00,"notes":"Garage or workshop subpanel"},
    {"id":uid(),"name":"Circuit Breaker Install - 15 Amp","category":"Electrical","unit":"EA","laborCost":22.00,"materialCost":8.50,"equipmentCost":0.50,"notes":"Single pole standard breaker"},
    {"id":uid(),"name":"Circuit Breaker Install - 20 Amp","category":"Electrical","unit":"EA","laborCost":22.00,"materialCost":10.00,"equipmentCost":0.50,"notes":"20A single pole breaker"},
    {"id":uid(),"name":"Dual Pole Breaker Install - 30 Amp","category":"Electrical","unit":"EA","laborCost":28.00,"materialCost":18.00,"equipmentCost":0.50,"notes":"240V 30A breaker for dryer"},
    {"id":uid(),"name":"Dual Pole Breaker Install - 50 Amp","category":"Electrical","unit":"EA","laborCost":28.00,"materialCost":22.00,"equipmentCost":0.50,"notes":"240V 50A breaker for range"},
    {"id":uid(),"name":"AFCI Circuit Breaker Install - 20 Amp","category":"Electrical","unit":"EA","laborCost":28.00,"materialCost":38.00,"equipmentCost":0.50,"notes":"Arc fault breaker bedroom circuits"},
    {"id":uid(),"name":"Whole House Surge Protector Install","category":"Electrical","unit":"EA","laborCost":85.00,"materialCost":95.00,"equipmentCost":5.00,"notes":"Panel mounted SPD"},
    # ── Wiring ────────────────────────────────────────────────
    {"id":uid(),"name":"14/2 NM-B Wire Installation - Per LF","category":"Electrical","unit":"LF","laborCost":0.45,"materialCost":0.35,"equipmentCost":0.02,"notes":"Romex for 15A circuits"},
    {"id":uid(),"name":"12/2 NM-B Wire Installation - Per LF","category":"Electrical","unit":"LF","laborCost":0.48,"materialCost":0.48,"equipmentCost":0.02,"notes":"Romex for 20A circuits"},
    {"id":uid(),"name":"12/3 NM-B Wire Installation - Per LF","category":"Electrical","unit":"LF","laborCost":0.52,"materialCost":0.65,"equipmentCost":0.02,"notes":"3-wire for MWBC circuits"},
    {"id":uid(),"name":"10/2 NM-B Wire Installation - Per LF","category":"Electrical","unit":"LF","laborCost":0.55,"materialCost":0.75,"equipmentCost":0.02,"notes":"30A appliance circuit"},
    {"id":uid(),"name":"10/3 NM-B Wire Installation - Per LF","category":"Electrical","unit":"LF","laborCost":0.60,"materialCost":0.98,"equipmentCost":0.02,"notes":"30A 240V 3-wire circuit"},
    {"id":uid(),"name":"6/3 NM-B Wire Installation - Per LF","category":"Electrical","unit":"LF","laborCost":0.85,"materialCost":2.25,"equipmentCost":0.03,"notes":"60A range or EV charger wire"},
    {"id":uid(),"name":"2/0 SER Cable Install - Per LF","category":"Electrical","unit":"LF","laborCost":1.25,"materialCost":4.50,"equipmentCost":0.05,"notes":"Service entrance conductor"},
    {"id":uid(),"name":"MC Cable Install - 12/2 Per LF","category":"Electrical","unit":"LF","laborCost":0.55,"materialCost":0.65,"equipmentCost":0.03,"notes":"Metal clad cable commercial"},
    # ── Conduit ───────────────────────────────────────────────
    {"id":uid(),"name":"1/2 Inch EMT Conduit Install - Per LF","category":"Electrical","unit":"LF","laborCost":1.25,"materialCost":0.65,"equipmentCost":0.05,"notes":"Electrical metallic tubing"},
    {"id":uid(),"name":"3/4 Inch EMT Conduit Install - Per LF","category":"Electrical","unit":"LF","laborCost":1.45,"materialCost":0.85,"equipmentCost":0.05,"notes":"3/4 EMT with wire pull"},
    {"id":uid(),"name":"1 Inch EMT Conduit Install - Per LF","category":"Electrical","unit":"LF","laborCost":1.65,"materialCost":1.15,"equipmentCost":0.05,"notes":"1 in EMT conduit"},
    {"id":uid(),"name":"1/2 Inch PVC Conduit Underground","category":"Electrical","unit":"LF","laborCost":1.85,"materialCost":0.45,"equipmentCost":0.15,"notes":"Schedule 40 PVC in trench"},
    {"id":uid(),"name":"3/4 Inch PVC Conduit Underground","category":"Electrical","unit":"LF","laborCost":2.00,"materialCost":0.58,"equipmentCost":0.15,"notes":"3/4 PVC Schedule 40"},
    {"id":uid(),"name":"2 Inch RGS Conduit - Exterior","category":"Electrical","unit":"LF","laborCost":3.25,"materialCost":5.50,"equipmentCost":0.15,"notes":"Rigid galvanized steel conduit"},
    # ── Devices ───────────────────────────────────────────────
    {"id":uid(),"name":"Duplex Outlet Install - Standard","category":"Electrical","unit":"EA","laborCost":18.00,"materialCost":3.50,"equipmentCost":0.50,"notes":"15A Decora or standard outlet"},
    {"id":uid(),"name":"GFCI Outlet Install - 20 Amp","category":"Electrical","unit":"EA","laborCost":22.00,"materialCost":18.00,"equipmentCost":0.50,"notes":"Ground fault interrupter outlet"},
    {"id":uid(),"name":"AFCI Outlet Install - Bedroom","category":"Electrical","unit":"EA","laborCost":22.00,"materialCost":28.00,"equipmentCost":0.50,"notes":"Arc fault outlet device"},
    {"id":uid(),"name":"Tamper Resistant Outlet Install","category":"Electrical","unit":"EA","laborCost":18.00,"materialCost":5.50,"equipmentCost":0.50,"notes":"TR outlet code compliant"},
    {"id":uid(),"name":"USB Combination Outlet Install","category":"Electrical","unit":"EA","laborCost":22.00,"materialCost":22.00,"equipmentCost":0.50,"notes":"Duplex with USB A and C ports"},
    {"id":uid(),"name":"Single Pole Switch Install","category":"Electrical","unit":"EA","laborCost":18.00,"materialCost":3.50,"equipmentCost":0.50,"notes":"Standard single pole switch"},
    {"id":uid(),"name":"3-Way Switch Install","category":"Electrical","unit":"EA","laborCost":22.00,"materialCost":5.50,"equipmentCost":0.50,"notes":"3-way switch lighting control"},
    {"id":uid(),"name":"4-Way Switch Install","category":"Electrical","unit":"EA","laborCost":28.00,"materialCost":12.00,"equipmentCost":0.50,"notes":"4-way for 3-point switch control"},
    {"id":uid(),"name":"Dimmer Switch Install - LED Compatible","category":"Electrical","unit":"EA","laborCost":22.00,"materialCost":28.00,"equipmentCost":0.50,"notes":"Single pole LED dimmer"},
    {"id":uid(),"name":"Smart Switch Install - Wi-Fi","category":"Electrical","unit":"EA","laborCost":28.00,"materialCost":45.00,"equipmentCost":0.50,"notes":"Wi-Fi enabled smart switch"},
    {"id":uid(),"name":"Weatherproof GFCI Outlet - Exterior","category":"Electrical","unit":"EA","laborCost":28.00,"materialCost":32.00,"equipmentCost":0.50,"notes":"In-use cover exterior GFCI"},
    {"id":uid(),"name":"20 Amp Dedicated Outlet - Appliance","category":"Electrical","unit":"EA","laborCost":85.00,"materialCost":18.00,"equipmentCost":5.00,"notes":"Full circuit to outlet"},
    {"id":uid(),"name":"220V Dryer Outlet Install - 30A","category":"Electrical","unit":"EA","laborCost":95.00,"materialCost":25.00,"equipmentCost":5.00,"notes":"4-wire 30 amp dryer outlet"},
    {"id":uid(),"name":"50 Amp Range Outlet Install","category":"Electrical","unit":"EA","laborCost":95.00,"materialCost":28.00,"equipmentCost":5.00,"notes":"4-wire range outlet"},
    # ── Lighting ──────────────────────────────────────────────
    {"id":uid(),"name":"Recessed Can Light - 4 Inch LED","category":"Electrical","unit":"EA","laborCost":55.00,"materialCost":25.00,"equipmentCost":2.00,"notes":"IC-rated airtight recessed"},
    {"id":uid(),"name":"Recessed Can Light - 6 Inch LED","category":"Electrical","unit":"EA","laborCost":65.00,"materialCost":32.00,"equipmentCost":2.00,"notes":"6 in IC-rated recessed"},
    {"id":uid(),"name":"Surface Mount Fixture - Ceiling","category":"Electrical","unit":"EA","laborCost":55.00,"materialCost":45.00,"equipmentCost":2.00,"notes":"Basic ceiling light hook-up"},
    {"id":uid(),"name":"Pendant Light Install","category":"Electrical","unit":"EA","laborCost":65.00,"materialCost":0.00,"equipmentCost":2.00,"notes":"Labor only pendant install"},
    {"id":uid(),"name":"Ceiling Fan Install - Standard","category":"Electrical","unit":"EA","laborCost":85.00,"materialCost":0.00,"equipmentCost":3.00,"notes":"Fan brace box and wiring"},
    {"id":uid(),"name":"Under Cabinet Lighting - LED Strip","category":"Electrical","unit":"LF","laborCost":12.00,"materialCost":8.50,"equipmentCost":0.50,"notes":"Low-voltage LED strip"},
    {"id":uid(),"name":"Track Lighting Install - 4 Foot","category":"Electrical","unit":"EA","laborCost":65.00,"materialCost":55.00,"equipmentCost":2.00,"notes":"4 ft track with 3 heads"},
    {"id":uid(),"name":"Exterior Wall Sconce Install","category":"Electrical","unit":"EA","laborCost":65.00,"materialCost":0.00,"equipmentCost":2.00,"notes":"Labor to install exterior sconce"},
    {"id":uid(),"name":"Vanity Light Bar Install","category":"Electrical","unit":"EA","laborCost":55.00,"materialCost":0.00,"equipmentCost":2.00,"notes":"Bathroom vanity light hook-up"},
    # ── Specialty Circuits ─────────────────────────────────────
    {"id":uid(),"name":"EV Charger Circuit - 240V 50A","category":"Electrical","unit":"EA","laborCost":185.00,"materialCost":65.00,"equipmentCost":10.00,"notes":"Level 2 EV charger circuit"},
    {"id":uid(),"name":"Generator Transfer Switch - 200A Manual","category":"Electrical","unit":"EA","laborCost":285.00,"materialCost":385.00,"equipmentCost":15.00,"notes":"Manual transfer switch interlock"},
    {"id":uid(),"name":"Generator Transfer Switch - 200A Auto","category":"Electrical","unit":"EA","laborCost":485.00,"materialCost":850.00,"equipmentCost":25.00,"notes":"Automatic transfer switch ATS"},
    {"id":uid(),"name":"Bathroom Fan Circuit - GFCI Protected","category":"Electrical","unit":"EA","laborCost":85.00,"materialCost":22.00,"equipmentCost":3.00,"notes":"Dedicated exhaust fan circuit"},
    {"id":uid(),"name":"Smoke Detector Install - Hardwired","category":"Electrical","unit":"EA","laborCost":55.00,"materialCost":28.00,"equipmentCost":2.00,"notes":"Code required smoke detector"},
    {"id":uid(),"name":"CO Detector Install - Hardwired","category":"Electrical","unit":"EA","laborCost":55.00,"materialCost":35.00,"equipmentCost":2.00,"notes":"Carbon monoxide detector"},
    {"id":uid(),"name":"Data Outlet Install - Cat6","category":"Electrical","unit":"EA","laborCost":45.00,"materialCost":15.00,"equipmentCost":2.00,"notes":"Cat6 network data port"},
    {"id":uid(),"name":"Coaxial Cable Outlet Install","category":"Electrical","unit":"EA","laborCost":35.00,"materialCost":5.50,"equipmentCost":1.00,"notes":"RG6 coaxial outlet"},
    # ── Grounding ─────────────────────────────────────────────
    {"id":uid(),"name":"Grounding Electrode Install - 8 Ft Rod","category":"Electrical","unit":"EA","laborCost":65.00,"materialCost":18.00,"equipmentCost":8.00,"notes":"Copper clad ground rod"},
    {"id":uid(),"name":"Ground Wire Install - Per LF","category":"Electrical","unit":"LF","laborCost":0.45,"materialCost":0.28,"equipmentCost":0.02,"notes":"Bare copper grounding conductor"},
    {"id":uid(),"name":"Water Pipe Bond Install","category":"Electrical","unit":"EA","laborCost":55.00,"materialCost":18.00,"equipmentCost":2.00,"notes":"Bond water pipe to panel"},
    # ── Rough-In ──────────────────────────────────────────────
    {"id":uid(),"name":"Rough Electrical - New Construction Per SF","category":"Electrical","unit":"SF","laborCost":2.85,"materialCost":1.25,"equipmentCost":0.15,"notes":"Complete rough-in new home"},
    {"id":uid(),"name":"Electrical Rough-In - Per Circuit","category":"Electrical","unit":"EA","laborCost":125.00,"materialCost":45.00,"equipmentCost":5.00,"notes":"Full outlet circuit rough-in"},
    # ── Permits and Inspections ────────────────────────────────
    {"id":uid(),"name":"Electrical Permit Fee - Residential","category":"Electrical","unit":"EA","laborCost":0.00,"materialCost":185.00,"equipmentCost":0.00,"notes":"County electrical permit"},
    {"id":uid(),"name":"Electrical Inspection Clearance","category":"Electrical","unit":"EA","laborCost":95.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Inspection scheduling and response"},
    {"id":uid(),"name":"Security Camera - Exterior Wi-Fi EA","category":"Electrical","unit":"EA","laborCost":85.00,"materialCost":145.00,"equipmentCost":5.00,"notes":"Mount and configure wireless cam"},
    {"id":uid(),"name":"Smart Doorbell - Video Intercom EA","category":"Electrical","unit":"EA","laborCost":65.00,"materialCost":185.00,"equipmentCost":2.00,"notes":"Video doorbell with chime"},
    {"id":uid(),"name":"Wall Mounted EV Charger - Level 2 EA","category":"Electrical","unit":"EA","laborCost":125.00,"materialCost":450.00,"equipmentCost":10.00,"notes":"Standard 40A EVSE install"},
    {"id":uid(),"name":"Tesla Wall Connector Install EA","category":"Electrical","unit":"EA","laborCost":145.00,"materialCost":480.00,"equipmentCost":10.00,"notes":"Tesla specific charging station"},
    {"id":uid(),"name":"Recessed Step Light - LED EA","category":"Electrical","unit":"EA","laborCost":45.00,"materialCost":22.00,"equipmentCost":1.00,"notes":"Stairway path lighting"},
    {"id":uid(),"name":"Under-Counter LED Driver - 60W EA","category":"Electrical","unit":"EA","laborCost":35.00,"materialCost":45.00,"equipmentCost":1.00,"notes":"Power supply for LED strips"},
    {"id":uid(),"name":"Low Voltage Lighting Transformer - 300W EA","category":"Electrical","unit":"EA","laborCost":85.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Landscape lighting power center"},
    {"id":uid(),"name":"Path Light - Cast Aluminum LED EA","category":"Electrical","unit":"EA","laborCost":35.00,"materialCost":45.00,"equipmentCost":1.00,"notes":"Landscape stake light"},
    {"id":uid(),"name":"Flood Light - Motion Activated LED EA","category":"Electrical","unit":"EA","laborCost":65.00,"materialCost":85.00,"equipmentCost":3.00,"notes":"Security perimeter lighting"},
    {"id":uid(),"name":"Pendant Light - Island Cluster EA","category":"Electrical","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":5.00,"notes":"Labor for multi-light fixture"},
    {"id":uid(),"name":"Track Lighting - 8 Foot Section EA","category":"Electrical","unit":"EA","laborCost":85.00,"materialCost":65.00,"equipmentCost":2.00,"notes":"Extended track lighting run"},
    {"id":uid(),"name":"Dimmable LED Driver - Magnetic EA","category":"Electrical","unit":"EA","laborCost":45.00,"materialCost":125.00,"equipmentCost":2.00,"notes":"High quality dimming driver"},
    {"id":uid(),"name":"LV Cable - 12/2 Low Voltage LF","category":"Electrical","unit":"LF","laborCost":0.35,"materialCost":0.45,"equipmentCost":0.01,"notes":"Direct burial landscape wire"},
    {"id":uid(),"name":"Cat6a Network Cable - Shielded LF","category":"Electrical","unit":"LF","laborCost":0.55,"materialCost":0.85,"equipmentCost":0.02,"notes":"High speed shielded data wire"},
    {"id":uid(),"name":"HDMI Cable - In-Wall Rated EA","category":"Electrical","unit":"EA","laborCost":45.00,"materialCost":35.00,"equipmentCost":1.00,"notes":"2.1 spec high speed HDMI"},
    {"id":uid(),"name":"Surround Sound Speaker Wiring - Per Point EA","category":"Electrical","unit":"EA","laborCost":55.00,"materialCost":18.00,"equipmentCost":2.00,"notes":"Audio wire run to speaker loc"},
    {"id":uid(),"name":"Home Theater Wall Plate - 7.1 Channel EA","category":"Electrical","unit":"EA","laborCost":45.00,"materialCost":35.00,"equipmentCost":1.00,"notes":"Media room connection plate"},
    {"id":uid(),"name":"Thermostat Wiring - 18/5 C-Wire LF","category":"Electrical","unit":"LF","laborCost":0.45,"materialCost":0.35,"equipmentCost":0.02,"notes":"HVAC control wiring"},
    {"id":uid(),"name":"Smart Thermostat - Nest/Ecobee Hookup EA","category":"Electrical","unit":"EA","laborCost":65.00,"materialCost":225.00,"equipmentCost":2.00,"notes":"Configure smart HVAC control"},
    {"id":uid(),"name":"Leak Detector Probe - Smart Home EA","category":"Electrical","unit":"EA","laborCost":45.00,"materialCost":35.00,"equipmentCost":1.00,"notes":"Water sensor integration"},
    {"id":uid(),"name":"Solar Panel - 400W Monocrystalline EA","category":"Electrical","unit":"EA","laborCost":185.00,"materialCost":350.00,"equipmentCost":45.00,"notes":"High efficiency PV module"},
    {"id":uid(),"name":"Solar Microinverter - Enphase EA","category":"Electrical","unit":"EA","laborCost":45.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Module level power electronics"},
    {"id":uid(),"name":"Roof Mounted Solar Racking - Per Rail LF","category":"Electrical","unit":"LF","laborCost":4.50,"materialCost":8.50,"equipmentCost":2.50,"notes":"Aluminum PV mounting rail"},
    {"id":uid(),"name":"Battery Storage System - 10kWh EA","category":"Electrical","unit":"EA","laborCost":1250.00,"materialCost":8500.00,"equipmentCost":450.00,"notes":"Whole home battery backup"},
    {"id":uid(),"name":"Electrical Panel Labeling - Full Service EA","category":"Electrical","unit":"EA","laborCost":85.00,"materialCost":5.00,"equipmentCost":0.00,"notes":"Circuit identification and tags"},
    {"id":uid(),"name":"Site Visit - Electrical Consultation EA","category":"Electrical","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"Professional project assessment"},
]
