"""HVACAgent — 100 items"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Forced Air Heating ─────────────────────────────────────
    {"id":uid(),"name":"Gas Furnace Install - 80K BTU 96% AFUE","category":"HVAC","unit":"EA","laborCost":485.00,"materialCost":985.00,"equipmentCost":25.00,"notes":"High efficiency gas furnace"},
    {"id":uid(),"name":"Gas Furnace Install - 100K BTU 96% AFUE","category":"HVAC","unit":"EA","laborCost":525.00,"materialCost":1150.00,"equipmentCost":25.00,"notes":"100K high efficiency furnace"},
    {"id":uid(),"name":"Gas Furnace Install - 120K BTU 96% AFUE","category":"HVAC","unit":"EA","laborCost":575.00,"materialCost":1285.00,"equipmentCost":25.00,"notes":"Large 120K high efficiency furnace"},
    {"id":uid(),"name":"Gas Furnace Install - 80% AFUE Standard","category":"HVAC","unit":"EA","laborCost":385.00,"materialCost":685.00,"equipmentCost":20.00,"notes":"Economy 80% efficiency furnace"},
    {"id":uid(),"name":"Electric Furnace Install - 15 KW","category":"HVAC","unit":"EA","laborCost":325.00,"materialCost":485.00,"equipmentCost":15.00,"notes":"Electric resistance furnace"},
    # ── Air Conditioning ───────────────────────────────────────
    {"id":uid(),"name":"Central AC Unit Install - 2 Ton 14 SEER","category":"HVAC","unit":"EA","laborCost":485.00,"materialCost":985.00,"equipmentCost":35.00,"notes":"2 ton split AC with line set"},
    {"id":uid(),"name":"Central AC Unit Install - 3 Ton 16 SEER","category":"HVAC","unit":"EA","laborCost":525.00,"materialCost":1285.00,"equipmentCost":35.00,"notes":"3 ton high efficiency split"},
    {"id":uid(),"name":"Central AC Unit Install - 4 Ton 16 SEER","category":"HVAC","unit":"EA","laborCost":565.00,"materialCost":1485.00,"equipmentCost":40.00,"notes":"4 ton AC split system"},
    {"id":uid(),"name":"Central AC Unit Install - 5 Ton 18 SEER","category":"HVAC","unit":"EA","laborCost":625.00,"materialCost":1850.00,"equipmentCost":45.00,"notes":"Large 5 ton high efficiency"},
    {"id":uid(),"name":"Refrigerant Line Set Install - 25 Ft","category":"HVAC","unit":"EA","laborCost":125.00,"materialCost":85.00,"equipmentCost":5.00,"notes":"Pre-insulated copper line set"},
    {"id":uid(),"name":"Refrigerant Recharge - R-410A","category":"HVAC","unit":"EA","laborCost":125.00,"materialCost":85.00,"equipmentCost":15.00,"notes":"Per pound recharge R-410A"},
    # ── Heat Pumps ─────────────────────────────────────────────
    {"id":uid(),"name":"Heat Pump Install - 2 Ton 16 SEER2","category":"HVAC","unit":"EA","laborCost":585.00,"materialCost":1485.00,"equipmentCost":35.00,"notes":"Air source heat pump 2 ton"},
    {"id":uid(),"name":"Heat Pump Install - 3 Ton 18 SEER2","category":"HVAC","unit":"EA","laborCost":625.00,"materialCost":1785.00,"equipmentCost":38.00,"notes":"3 ton high efficiency heat pump"},
    {"id":uid(),"name":"Heat Pump Install - 4 Ton 18 SEER2","category":"HVAC","unit":"EA","laborCost":675.00,"materialCost":2085.00,"equipmentCost":42.00,"notes":"4 ton heat pump"},
    {"id":uid(),"name":"Heat Pump Install - 5 Ton 20 SEER2","category":"HVAC","unit":"EA","laborCost":725.00,"materialCost":2485.00,"equipmentCost":48.00,"notes":"Large 5 ton premium heat pump"},
    {"id":uid(),"name":"Dual Fuel Heat Pump System - 3 Ton","category":"HVAC","unit":"EA","laborCost":850.00,"materialCost":2285.00,"equipmentCost":45.00,"notes":"Heat pump with gas backup"},
    {"id":uid(),"name":"Geothermal Heat Pump - 3 Ton","category":"HVAC","unit":"EA","laborCost":1850.00,"materialCost":4850.00,"equipmentCost":350.00,"notes":"Closed loop geothermal system"},
    # ── Mini-Splits ────────────────────────────────────────────
    {"id":uid(),"name":"Mini-Split Install - Single Zone 9K BTU","category":"HVAC","unit":"EA","laborCost":485.00,"materialCost":985.00,"equipmentCost":25.00,"notes":"Single zone ductless system"},
    {"id":uid(),"name":"Mini-Split Install - Single Zone 12K BTU","category":"HVAC","unit":"EA","laborCost":525.00,"materialCost":1085.00,"equipmentCost":25.00,"notes":"12000 BTU ductless"},
    {"id":uid(),"name":"Mini-Split Install - Single Zone 18K BTU","category":"HVAC","unit":"EA","laborCost":565.00,"materialCost":1285.00,"equipmentCost":28.00,"notes":"18K high wall unit"},
    {"id":uid(),"name":"Mini-Split Install - Single Zone 24K BTU","category":"HVAC","unit":"EA","laborCost":585.00,"materialCost":1485.00,"equipmentCost":30.00,"notes":"24K large room unit"},
    {"id":uid(),"name":"Multi-Zone Mini-Split - 2 Zone 24K BTU","category":"HVAC","unit":"EA","laborCost":785.00,"materialCost":2185.00,"equipmentCost":35.00,"notes":"Dual zone outdoor with 2 heads"},
    {"id":uid(),"name":"Multi-Zone Mini-Split - 3 Zone 36K BTU","category":"HVAC","unit":"EA","laborCost":985.00,"materialCost":2985.00,"equipmentCost":45.00,"notes":"Tri-zone mini-split system"},
    {"id":uid(),"name":"Mini-Split Cassette Install - 12K Ceiling","category":"HVAC","unit":"EA","laborCost":625.00,"materialCost":1385.00,"equipmentCost":30.00,"notes":"Ceiling cassette 4-way blow"},
    # ── Air Handlers ───────────────────────────────────────────
    {"id":uid(),"name":"Air Handler Install - 3 Ton","category":"HVAC","unit":"EA","laborCost":285.00,"materialCost":585.00,"equipmentCost":15.00,"notes":"Indoor air handler no compressor"},
    {"id":uid(),"name":"Air Handler Install - 4 Ton","category":"HVAC","unit":"EA","laborCost":325.00,"materialCost":685.00,"equipmentCost":18.00,"notes":"4 ton air handler"},
    {"id":uid(),"name":"Air Handler Install - 5 Ton","category":"HVAC","unit":"EA","laborCost":365.00,"materialCost":785.00,"equipmentCost":20.00,"notes":"5 ton air handler"},
    {"id":uid(),"name":"Coil Only Install - Evaporator 3 Ton","category":"HVAC","unit":"EA","laborCost":185.00,"materialCost":385.00,"equipmentCost":10.00,"notes":"Replacement evaporator coil"},
    # ── Ductwork ──────────────────────────────────────────────
    {"id":uid(),"name":"Flex Duct Install - 6 Inch Per LF","category":"HVAC","unit":"LF","laborCost":3.50,"materialCost":2.25,"equipmentCost":0.25,"notes":"R-6 flexible duct"},
    {"id":uid(),"name":"Flex Duct Install - 8 Inch Per LF","category":"HVAC","unit":"LF","laborCost":4.00,"materialCost":2.85,"equipmentCost":0.25,"notes":"R-6 flex 8 inch"},
    {"id":uid(),"name":"Flex Duct Install - 10 Inch Per LF","category":"HVAC","unit":"LF","laborCost":4.50,"materialCost":3.50,"equipmentCost":0.25,"notes":"R-6 flex 10 inch"},
    {"id":uid(),"name":"Sheet Metal Supply Duct - 6 Inch Per LF","category":"HVAC","unit":"LF","laborCost":5.50,"materialCost":3.25,"equipmentCost":0.50,"notes":"26 gauge galvanized duct"},
    {"id":uid(),"name":"Sheet Metal Supply Duct - 8 Inch Per LF","category":"HVAC","unit":"LF","laborCost":6.50,"materialCost":4.25,"equipmentCost":0.50,"notes":"8 in galvanized supply duct"},
    {"id":uid(),"name":"Sheet Metal Return Duct - 14x8 Per LF","category":"HVAC","unit":"LF","laborCost":8.50,"materialCost":5.50,"equipmentCost":0.50,"notes":"Main return duct rectangular"},
    {"id":uid(),"name":"Sheet Metal Return Duct - 20x12 Per LF","category":"HVAC","unit":"LF","laborCost":12.00,"materialCost":8.50,"equipmentCost":0.75,"notes":"Large return air duct"},
    {"id":uid(),"name":"Duct Takeoff - Boot and Fitting","category":"HVAC","unit":"EA","laborCost":18.00,"materialCost":12.00,"equipmentCost":0.50,"notes":"Branch takeoff with register boot"},
    {"id":uid(),"name":"Duct Sealing - Mastic Brush Apply","category":"HVAC","unit":"LF","laborCost":1.85,"materialCost":0.35,"equipmentCost":0.05,"notes":"Mastic sealant on joints"},
    {"id":uid(),"name":"Duct Insulation Wrap Existing - R-6","category":"HVAC","unit":"LF","laborCost":3.50,"materialCost":2.25,"equipmentCost":0.15,"notes":"Wrap bare metal duct"},
    {"id":uid(),"name":"Duct Leakage Test - Blower","category":"HVAC","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":65.00,"notes":"Total duct leakage CFM25"},
    # ── Thermostats and Controls ───────────────────────────────
    {"id":uid(),"name":"Programmable Thermostat Install","category":"HVAC","unit":"EA","laborCost":55.00,"materialCost":45.00,"equipmentCost":2.00,"notes":"7-day programmable thermostat"},
    {"id":uid(),"name":"Smart Thermostat Install - Wi-Fi","category":"HVAC","unit":"EA","laborCost":65.00,"materialCost":125.00,"equipmentCost":2.00,"notes":"Ecobee or Nest with app"},
    {"id":uid(),"name":"Zoning Control System Install - 2 Zone","category":"HVAC","unit":"EA","laborCost":485.00,"materialCost":385.00,"equipmentCost":15.00,"notes":"Two-zone motorized damper system"},
    {"id":uid(),"name":"Zone Damper Install - 8 Inch","category":"HVAC","unit":"EA","laborCost":65.00,"materialCost":85.00,"equipmentCost":3.00,"notes":"Motorized zone damper"},
    # ── Ventilation ────────────────────────────────────────────
    {"id":uid(),"name":"Bathroom Exhaust Fan Install - 110 CFM","category":"HVAC","unit":"EA","laborCost":85.00,"materialCost":55.00,"equipmentCost":3.00,"notes":"110 CFM bathroom fan"},
    {"id":uid(),"name":"Bathroom Exhaust Fan Install - 80 CFM","category":"HVAC","unit":"EA","laborCost":75.00,"materialCost":38.00,"equipmentCost":2.00,"notes":"80 CFM standard bath fan"},
    {"id":uid(),"name":"Kitchen Range Hood Install - Ducted","category":"HVAC","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":5.00,"notes":"Labor only hood install"},
    {"id":uid(),"name":"Kitchen Range Hood Duct - 6 Inch Roof","category":"HVAC","unit":"EA","laborCost":125.00,"materialCost":55.00,"equipmentCost":5.00,"notes":"6 in duct to roof cap"},
    {"id":uid(),"name":"ERV Install - Energy Recovery Ventilator","category":"HVAC","unit":"EA","laborCost":485.00,"materialCost":850.00,"equipmentCost":25.00,"notes":"Whole house ERV fresh air"},
    {"id":uid(),"name":"HRV Install - Heat Recovery Ventilator","category":"HVAC","unit":"EA","laborCost":485.00,"materialCost":985.00,"equipmentCost":25.00,"notes":"Whole house HRV"},
    {"id":uid(),"name":"Whole House Fan Install - 2 Speed","category":"HVAC","unit":"EA","laborCost":285.00,"materialCost":385.00,"equipmentCost":15.00,"notes":"Whole house ventilation fan"},
    # ── IAQ and Accessories ────────────────────────────────────
    {"id":uid(),"name":"Whole House Humidifier - Bypass Install","category":"HVAC","unit":"EA","laborCost":185.00,"materialCost":285.00,"equipmentCost":8.00,"notes":"Aprilaire bypass humidifier"},
    {"id":uid(),"name":"Whole House Humidifier - Power Install","category":"HVAC","unit":"EA","laborCost":225.00,"materialCost":385.00,"equipmentCost":8.00,"notes":"Aprilaire powered humidifier"},
    {"id":uid(),"name":"UV Air Purifier Install - In-Duct","category":"HVAC","unit":"EA","laborCost":125.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"UV germicidal duct unit"},
    {"id":uid(),"name":"Electronic Air Cleaner Install","category":"HVAC","unit":"EA","laborCost":185.00,"materialCost":285.00,"equipmentCost":8.00,"notes":"In-duct electronic air cleaner"},
    {"id":uid(),"name":"Media Air Filter Install - 5 Inch","category":"HVAC","unit":"EA","laborCost":85.00,"materialCost":85.00,"equipmentCost":3.00,"notes":"Deep media MERV 16 filter"},
    # ── Maintenance and Service ────────────────────────────────
    {"id":uid(),"name":"HVAC Tune-Up and Cleaning - AC","category":"HVAC","unit":"EA","laborCost":125.00,"materialCost":15.00,"equipmentCost":5.00,"notes":"Annual AC service visit"},
    {"id":uid(),"name":"HVAC Tune-Up and Cleaning - Furnace","category":"HVAC","unit":"EA","laborCost":125.00,"materialCost":15.00,"equipmentCost":5.00,"notes":"Annual furnace service visit"},
    {"id":uid(),"name":"Duct Cleaning - Per System","category":"HVAC","unit":"EA","laborCost":285.00,"materialCost":0.00,"equipmentCost":125.00,"notes":"Full duct cleaning with sanitize"},
    {"id":uid(),"name":"Refrigerant Leak Search and Repair","category":"HVAC","unit":"EA","laborCost":185.00,"materialCost":45.00,"equipmentCost":35.00,"notes":"Electronic leak detection"},
    {"id":uid(),"name":"HVAC Permit - Residential New","category":"HVAC","unit":"EA","laborCost":0.00,"materialCost":185.00,"equipmentCost":0.00,"notes":"Local HVAC permit fee"},
    {"id":uid(),"name":"HVAC Load Calculation - Manual J","category":"HVAC","unit":"EA","laborCost":285.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Manual J heating cooling load"},
    {"id":uid(),"name":"Condensate Pump Install","category":"HVAC","unit":"EA","laborCost":65.00,"materialCost":55.00,"equipmentCost":2.00,"notes":"Condensate drain pump"},
    {"id":uid(),"name":"Secondary Drain Pan Install - Under Air Handler","category":"HVAC","unit":"EA","laborCost":45.00,"materialCost":35.00,"equipmentCost":2.00,"notes":"Safety pan with sensor"},
    {"id":uid(),"name":"Condenser Pad - Precast Concrete","category":"HVAC","unit":"EA","laborCost":35.00,"materialCost":45.00,"equipmentCost":5.00,"notes":"Pre-cast AC condenser pad"},
    {"id":uid(),"name":"Radiant Floor Heat - PEX Per SF","category":"HVAC","unit":"SF","laborCost":2.50,"materialCost":2.85,"equipmentCost":0.25,"notes":"In-slab or above-floor PEX"},
    {"id":uid(),"name":"Radiant Floor Heat - Manifold Install","category":"HVAC","unit":"EA","laborCost":225.00,"materialCost":185.00,"equipmentCost":10.00,"notes":"Distribution manifold for radiant"},
    {"id":uid(),"name":"Boiler Install - Gas 100K BTU","category":"HVAC","unit":"EA","laborCost":485.00,"materialCost":1485.00,"equipmentCost":25.00,"notes":"Hot water gas boiler"},
    {"id":uid(),"name":"Boiler Circulator Pump Install","category":"HVAC","unit":"EA","laborCost":125.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Zone circulator pump"},
    {"id":uid(),"name":"Baseboard Radiation Install - Hot Water","category":"HVAC","unit":"LF","laborCost":5.50,"materialCost":12.00,"equipmentCost":0.50,"notes":"Fin-tube baseboard radiation"},
    {"id":uid(),"name":"Expansion Tank Install - Hydronic","category":"HVAC","unit":"EA","laborCost":85.00,"materialCost":85.00,"equipmentCost":3.00,"notes":"Hydronic expansion tank"},
    {"id":uid(),"name":"Package Unit Install - 3 Ton Gas Electric","category":"HVAC","unit":"EA","laborCost":685.00,"materialCost":2285.00,"equipmentCost":55.00,"notes":"Rooftop package unit RTU"},
    {"id":uid(),"name":"Steam Boiler - Gas 150K BTU EA","category":"HVAC","unit":"EA","laborCost":850.00,"materialCost":2850.00,"equipmentCost":45.00,"notes":"Standard steam heating boiler"},
    {"id":uid(),"name":"Steam Radiator Install - Cast Iron EA","category":"HVAC","unit":"EA","laborCost":185.00,"materialCost":350.00,"equipmentCost":15.00,"notes":"Sectional cast iron radiator"},
    {"id":uid(),"name":"Steam Trap Replacement - Per Unit EA","category":"HVAC","unit":"EA","laborCost":65.00,"materialCost":45.00,"equipmentCost":2.00,"notes":"Thermostatic or float trap"},
    {"id":uid(),"name":"Hydronic Towel Warmer Install EA","category":"HVAC","unit":"EA","laborCost":125.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Bathroom radiant towel rail"},
    {"id":uid(),"name":"Fan Coil Unit - Chilled Water EA","category":"HVAC","unit":"EA","laborCost":285.00,"materialCost":850.00,"equipmentCost":25.00,"notes":"Commercial 2-pipe fan coil"},
    {"id":uid(),"name":"PTAC Unit Install - Through-Wall EA","category":"HVAC","unit":"EA","laborCost":145.00,"materialCost":1250.00,"equipmentCost":15.00,"notes":"Package terminal air conditioner"},
    {"id":uid(),"name":"Mini-Split Indoor Unit - Wall Mount EA","category":"HVAC","unit":"EA","laborCost":185.00,"materialCost":350.00,"equipmentCost":10.00,"notes":"Ductless wall mounted head"},
    {"id":uid(),"name":"Mini-Split Indoor Unit - Ceiling Cassette EA","category":"HVAC","unit":"EA","laborCost":285.00,"materialCost":650.00,"equipmentCost":15.00,"notes":"Recessed ceiling mini-split"},
    {"id":uid(),"name":"Mini-Split Outdoor Unit - 2 Zone EA","category":"HVAC","unit":"EA","laborCost":450.00,"materialCost":1850.00,"equipmentCost":45.00,"notes":"Multi-zone heat pump condenser"},
    {"id":uid(),"name":"Mini-Split Outdoor Unit - 4 Zone EA","category":"HVAC","unit":"EA","laborCost":650.00,"materialCost":2850.00,"equipmentCost":65.00,"notes":"Large multi-zone condenser"},
    {"id":uid(),"name":"Lineset Cover - PVC 12 Ft Kit EA","category":"HVAC","unit":"EA","laborCost":45.00,"materialCost":85.00,"equipmentCost":2.00,"notes":"Slimduct or equivalent cover"},
    {"id":uid(),"name":"Lineset Install - Insulated Copper LF","category":"HVAC","unit":"LF","laborCost":4.50,"materialCost":6.50,"equipmentCost":0.50,"notes":"Refrigerant piping with insulation"},
    {"id":uid(),"name":"Refrigerant Charge - R-410A Per Lb","category":"HVAC","unit":"EA","laborCost":0.00,"materialCost":115.00,"equipmentCost":2.00,"notes":"Refrigerant gas top-off"},
    {"id":uid(),"name":"Thermal Expansion Valve (TXV) Replace EA","category":"HVAC","unit":"EA","laborCost":185.00,"materialCost":145.00,"equipmentCost":15.00,"notes":"Evaporator metering device repair"},
    {"id":uid(),"name":"HVAC Contactor Replacement EA","category":"HVAC","unit":"EA","laborCost":85.00,"materialCost":35.00,"equipmentCost":2.00,"notes":"Electrical contactor swap"},
    {"id":uid(),"name":"HVAC Capacitor Replacement - Run Cap EA","category":"HVAC","unit":"EA","laborCost":85.00,"materialCost":28.00,"equipmentCost":2.00,"notes":"Motor run capacitor swap"},
    {"id":uid(),"name":"HVAC Igniter Replacement - Hot Surface EA","category":"HVAC","unit":"EA","laborCost":65.00,"materialCost":45.00,"equipmentCost":2.00,"notes":"SiNi or similar ignitor"},
    {"id":uid(),"name":"HVAC Inducer Motor Replacement EA","category":"HVAC","unit":"EA","laborCost":145.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Draft inducer fan assembly"},
    {"id":uid(),"name":"HVAC Gas Valve Replacement EA","category":"HVAC","unit":"EA","laborCost":185.00,"materialCost":145.00,"equipmentCost":5.00,"notes":"Furnace gas control valve"},
    {"id":uid(),"name":"HVAC Condensate Drain Line Cleaning EA","category":"HVAC","unit":"EA","laborCost":85.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"Blow out and clear trap"},
    {"id":uid(),"name":"UV Light Air Purifier - In-Duct EA","category":"HVAC","unit":"EA","laborCost":125.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Germicidal air treatment"},
    {"id":uid(),"name":"Electronic Air Cleaner - Cabinet EA","category":"HVAC","unit":"EA","laborCost":225.00,"materialCost":850.00,"equipmentCost":10.00,"notes":"Electrostatic furnace filter"},
    {"id":uid(),"name":"HEPA Filter System - Whole House EA","category":"HVAC","unit":"EA","laborCost":285.00,"materialCost":1250.00,"equipmentCost":25.00,"notes":"Bypass HEPA filtration system"},
    {"id":uid(),"name":"Fresh Air Intake - Damper Controlled EA","category":"HVAC","unit":"EA","laborCost":145.00,"materialCost":285.00,"equipmentCost":10.00,"notes":"Motorized fresh air damper"},
    {"id":uid(),"name":"Kitchen Exhaust Hood - Commercial 6 Ft EA","category":"HVAC","unit":"EA","laborCost":850.00,"materialCost":2850.00,"equipmentCost":450.00,"notes":"Stainless steel canopy hood"},
    {"id":uid(),"name":"Make-Up Air Unit - Gas Fired EA","category":"HVAC","unit":"EA","laborCost":1250.00,"materialCost":8500.00,"equipmentCost":850.00,"notes":"MUA unit for commercial kitchen"},
    {"id":uid(),"name":"HVAC Design Consultation - Manual S/D EA","category":"HVAC","unit":"EA","laborCost":450.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"System sizing and duct design"},
    {"id":uid(),"name":"HVAC Site Visit - Professional Assessment","category":"HVAC","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"Expert diagnostic visit"},
]
