"""DrywallAgent — 100 items (moved from generate_all.py)"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    {"id":uid(),"name":"1/2 Inch Regular Drywall Hang - Walls","category":"Drywall","unit":"SF","laborCost":0.45,"materialCost":0.32,"equipmentCost":0.05,"notes":"Standard wall application"},
    {"id":uid(),"name":"5/8 Inch Firecode Type X Drywall Hang - Walls","category":"Drywall","unit":"SF","laborCost":0.50,"materialCost":0.38,"equipmentCost":0.05,"notes":"Type X fire rating"},
    {"id":uid(),"name":"1/2 Inch Moisture Resistant Drywall Hang - Walls","category":"Drywall","unit":"SF","laborCost":0.45,"materialCost":0.42,"equipmentCost":0.05,"notes":"Greenboard for damp areas"},
    {"id":uid(),"name":"1/4 Inch Flexible Drywall Hang - Curved Walls","category":"Drywall","unit":"SF","laborCost":0.65,"materialCost":0.48,"equipmentCost":0.05,"notes":"For curved or arched surfaces"},
    {"id":uid(),"name":"5/8 Inch Soundproof Drywall Hang - Walls","category":"Drywall","unit":"SF","laborCost":0.55,"materialCost":1.15,"equipmentCost":0.10,"notes":"QuietRock or equivalent"},
    {"id":uid(),"name":"1/2 Inch High Impact Drywall Hang - Walls","category":"Drywall","unit":"SF","laborCost":0.50,"materialCost":0.75,"equipmentCost":0.05,"notes":"High-traffic corridors"},
    {"id":uid(),"name":"3/8 Inch Drywall Hang - Walls","category":"Drywall","unit":"SF","laborCost":0.42,"materialCost":0.28,"equipmentCost":0.04,"notes":"Lightweight backing layer"},
    {"id":uid(),"name":"Double Layer 5/8 Inch Drywall Hang - Walls","category":"Drywall","unit":"SF","laborCost":0.90,"materialCost":0.76,"equipmentCost":0.08,"notes":"Two-layer fire-rated system"},
    {"id":uid(),"name":"5/8 Inch Mold Resistant Drywall Hang - Walls","category":"Drywall","unit":"SF","laborCost":0.50,"materialCost":0.52,"equipmentCost":0.05,"notes":"Purple board or equivalent"},
    {"id":uid(),"name":"1/2 Inch Abuse Resistant Drywall Hang - Walls","category":"Drywall","unit":"SF","laborCost":0.52,"materialCost":0.88,"equipmentCost":0.05,"notes":"Commercial hardened board"},
    {"id":uid(),"name":"1/2 Inch Regular Drywall Hang - Ceilings","category":"Drywall","unit":"SF","laborCost":0.65,"materialCost":0.32,"equipmentCost":0.15,"notes":"Ceiling application with lift"},
    {"id":uid(),"name":"5/8 Inch Type X Drywall Hang - Ceilings","category":"Drywall","unit":"SF","laborCost":0.70,"materialCost":0.38,"equipmentCost":0.18,"notes":"Rated ceiling application"},
    {"id":uid(),"name":"5/8 Inch Soundproof Drywall Hang - Ceilings","category":"Drywall","unit":"SF","laborCost":0.75,"materialCost":1.15,"equipmentCost":0.20,"notes":"Acoustic ceiling"},
    {"id":uid(),"name":"5/8 Inch Moisture Resistant Drywall Hang - Ceilings","category":"Drywall","unit":"SF","laborCost":0.70,"materialCost":0.52,"equipmentCost":0.15,"notes":"Bathrooms and high-humidity ceilings"},
    {"id":uid(),"name":"Double Layer 5/8 Drywall Hang - Ceilings","category":"Drywall","unit":"SF","laborCost":1.10,"materialCost":0.76,"equipmentCost":0.25,"notes":"Double layer fire-rated ceiling"},
    {"id":uid(),"name":"Tape and Finish - Level 1","category":"Drywall","unit":"SF","laborCost":0.25,"materialCost":0.08,"equipmentCost":0.01,"notes":"Fire taping only"},
    {"id":uid(),"name":"Tape and Finish - Level 2","category":"Drywall","unit":"SF","laborCost":0.42,"materialCost":0.10,"equipmentCost":0.01,"notes":"Skim coat for textured surfaces"},
    {"id":uid(),"name":"Tape and Finish - Level 3","category":"Drywall","unit":"SF","laborCost":0.60,"materialCost":0.15,"equipmentCost":0.02,"notes":"Ready for heavy texture"},
    {"id":uid(),"name":"Tape and Finish - Level 4","category":"Drywall","unit":"SF","laborCost":0.85,"materialCost":0.18,"equipmentCost":0.03,"notes":"Ready for flat or light texture"},
    {"id":uid(),"name":"Tape and Finish - Level 5","category":"Drywall","unit":"SF","laborCost":1.25,"materialCost":0.25,"equipmentCost":0.05,"notes":"Skim coat premium finish"},
    {"id":uid(),"name":"Level 5 Skim Coat Over Existing Drywall","category":"Drywall","unit":"SF","laborCost":0.95,"materialCost":0.25,"equipmentCost":0.05,"notes":"Applied to existing walls"},
    {"id":uid(),"name":"Spray Texture - Orange Peel","category":"Drywall","unit":"SF","laborCost":0.25,"materialCost":0.12,"equipmentCost":0.08,"notes":"Standard spray finish"},
    {"id":uid(),"name":"Spray Texture - Knockdown","category":"Drywall","unit":"SF","laborCost":0.35,"materialCost":0.12,"equipmentCost":0.08,"notes":"Knockdown spray finish"},
    {"id":uid(),"name":"Hand Texture - Skip Trowel","category":"Drywall","unit":"SF","laborCost":0.75,"materialCost":0.15,"equipmentCost":0.05,"notes":"Hand applied skip trowel"},
    {"id":uid(),"name":"Sand Texture Finish","category":"Drywall","unit":"SF","laborCost":0.55,"materialCost":0.14,"equipmentCost":0.06,"notes":"Fine sand aggregate spray"},
    {"id":uid(),"name":"Smooth Rolled Texture Finish","category":"Drywall","unit":"SF","laborCost":0.45,"materialCost":0.10,"equipmentCost":0.02,"notes":"Roller applied finish coat"},
    {"id":uid(),"name":"Popcorn Ceiling Texture - New","category":"Drywall","unit":"SF","laborCost":0.35,"materialCost":0.18,"equipmentCost":0.10,"notes":"Acoustic spray ceiling"},
    {"id":uid(),"name":"Acoustic Popcorn Ceiling Removal","category":"Drywall","unit":"SF","laborCost":1.10,"materialCost":0.10,"equipmentCost":0.20,"notes":"Assumes no asbestos present"},
    {"id":uid(),"name":"Venetian Plaster Skim Coat","category":"Drywall","unit":"SF","laborCost":2.50,"materialCost":0.85,"equipmentCost":0.10,"notes":"Premium decorative finish"},
    {"id":uid(),"name":"Elastomeric Coating Application","category":"Drywall","unit":"SF","laborCost":0.45,"materialCost":0.30,"equipmentCost":0.05,"notes":"Flexible waterproof finish"},
    {"id":uid(),"name":"Corner Bead Install - Metal 90 Degree","category":"Drywall","unit":"LF","laborCost":0.55,"materialCost":0.22,"equipmentCost":0.01,"notes":"Standard 90 degree"},
    {"id":uid(),"name":"Corner Bead Install - Bullnose","category":"Drywall","unit":"LF","laborCost":0.60,"materialCost":0.28,"equipmentCost":0.01,"notes":"Rounded edge"},
    {"id":uid(),"name":"Corner Bead Install - Vinyl","category":"Drywall","unit":"LF","laborCost":0.45,"materialCost":0.18,"equipmentCost":0.00,"notes":"Vinyl bead for taping edge"},
    {"id":uid(),"name":"L-Bead Install - Drywall Edge Termination","category":"Drywall","unit":"LF","laborCost":0.40,"materialCost":0.20,"equipmentCost":0.00,"notes":"Where drywall meets different surface"},
    {"id":uid(),"name":"J-Bead Install - Drywall Edge","category":"Drywall","unit":"LF","laborCost":0.38,"materialCost":0.18,"equipmentCost":0.00,"notes":"Exposed edge at windows or openings"},
    {"id":uid(),"name":"Archway Bead Install - Flexible","category":"Drywall","unit":"LF","laborCost":0.75,"materialCost":0.45,"equipmentCost":0.00,"notes":"Curved archways"},
    {"id":uid(),"name":"Shadow Bead and Reveal Install","category":"Drywall","unit":"LF","laborCost":0.80,"materialCost":0.55,"equipmentCost":0.01,"notes":"Architectural reveal trim"},
    {"id":uid(),"name":"Resilient Channel Install - RC-1","category":"Drywall","unit":"LF","laborCost":0.45,"materialCost":0.35,"equipmentCost":0.02,"notes":"Sound decoupling channel"},
    {"id":uid(),"name":"Isolation Clip Install - RSIC","category":"Drywall","unit":"EA","laborCost":2.50,"materialCost":4.50,"equipmentCost":0.25,"notes":"Sound isolation clips"},
    {"id":uid(),"name":"Hat Channel Install - 7/8 Inch","category":"Drywall","unit":"LF","laborCost":0.40,"materialCost":0.28,"equipmentCost":0.01,"notes":"Furring channel"},
    {"id":uid(),"name":"Z-Furring Channel Install","category":"Drywall","unit":"LF","laborCost":0.45,"materialCost":0.32,"equipmentCost":0.01,"notes":"Exterior wall furring"},
    {"id":uid(),"name":"Sound Attenuation Batt Install - 3.5 Inch","category":"Drywall","unit":"SF","laborCost":0.30,"materialCost":0.45,"equipmentCost":0.00,"notes":"SAB insulation for STC improvement"},
    {"id":uid(),"name":"Shaftwall Liner Install - 1 Inch Coreboard","category":"Drywall","unit":"SF","laborCost":0.85,"materialCost":0.95,"equipmentCost":0.10,"notes":"Vertical shaft applications"},
    {"id":uid(),"name":"Shaftwall C-H Stud Install","category":"Drywall","unit":"LF","laborCost":0.55,"materialCost":0.65,"equipmentCost":0.05,"notes":"C-H shaft framing"},
    {"id":uid(),"name":"High Shaft Double Layer 5/8 - Stairwell","category":"Drywall","unit":"SF","laborCost":1.20,"materialCost":0.76,"equipmentCost":0.35,"notes":"High access staging required"},
    {"id":uid(),"name":"Exterior Gypsum Sheathing Install","category":"Drywall","unit":"SF","laborCost":0.60,"materialCost":0.55,"equipmentCost":0.08,"notes":"Weather-rated exterior board"},
    {"id":uid(),"name":"Drywall Patch - Small Hole Up to 12x12 Inch","category":"Drywall","unit":"EA","laborCost":65.00,"materialCost":15.00,"equipmentCost":5.00,"notes":"California patch or mesh"},
    {"id":uid(),"name":"Drywall Patch - Medium Up to 24x24 Inch","category":"Drywall","unit":"EA","laborCost":95.00,"materialCost":22.00,"equipmentCost":5.00,"notes":"Backing board required"},
    {"id":uid(),"name":"Drywall Patch - Full 4x8 Sheet Replacement","category":"Drywall","unit":"EA","laborCost":125.00,"materialCost":25.00,"equipmentCost":10.00,"notes":"Full sheet cut-in"},
    {"id":uid(),"name":"Drywall Water Damage Repair - Per SF","category":"Drywall","unit":"SF","laborCost":3.50,"materialCost":1.20,"equipmentCost":0.50,"notes":"Includes mold check"},
    {"id":uid(),"name":"Drywall Crack Repair - Hairline","category":"Drywall","unit":"LF","laborCost":3.00,"materialCost":0.50,"equipmentCost":0.10,"notes":"Tape and skim finish"},
    {"id":uid(),"name":"Drywall Crack Repair - Structural","category":"Drywall","unit":"LF","laborCost":8.50,"materialCost":1.50,"equipmentCost":0.50,"notes":"Fiberglass reinforcement tape"},
    {"id":uid(),"name":"Drywall Demolition - Walls","category":"Drywall","unit":"SF","laborCost":0.38,"materialCost":0.00,"equipmentCost":0.05,"notes":"Tear out and stack for disposal"},
    {"id":uid(),"name":"Drywall Demolition - Ceilings","category":"Drywall","unit":"SF","laborCost":0.55,"materialCost":0.00,"equipmentCost":0.12,"notes":"Overhead demolition"},
    {"id":uid(),"name":"Scrap Removal and Disposal","category":"Drywall","unit":"EA","laborCost":85.00,"materialCost":0.00,"equipmentCost":40.00,"notes":"Haul away and dump fees"},
    {"id":uid(),"name":"Drywall Debris Dump Fee - Per Load","category":"Drywall","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":185.00,"notes":"Standard 10-yard dumpster load"},
    {"id":uid(),"name":"Drywall Delivery and Boom Truck Stocking","category":"Drywall","unit":"EA","laborCost":150.00,"materialCost":0.00,"equipmentCost":50.00,"notes":"Flat fee per delivery"},
    {"id":uid(),"name":"Drywall Hand Stock - Per Floor","category":"Drywall","unit":"EA","laborCost":85.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Add per floor above ground"},
    {"id":uid(),"name":"Lightweight Joint Compound Supply Only","category":"Drywall","unit":"EA","laborCost":0.00,"materialCost":18.50,"equipmentCost":0.00,"notes":"5 gallon bucket"},
    {"id":uid(),"name":"Setting Compound Supply Only - 45 Min","category":"Drywall","unit":"EA","laborCost":0.00,"materialCost":14.00,"equipmentCost":0.00,"notes":"25 lb bag"},
    {"id":uid(),"name":"Fiberglass Mesh Tape Supply Only","category":"Drywall","unit":"EA","laborCost":0.00,"materialCost":5.50,"equipmentCost":0.00,"notes":"300 ft roll"},
    {"id":uid(),"name":"Paper Tape Supply Only","category":"Drywall","unit":"EA","laborCost":0.00,"materialCost":3.25,"equipmentCost":0.00,"notes":"250 ft roll"},
    {"id":uid(),"name":"Coarse Thread Drywall Screw Supply - 5lb Box","category":"Drywall","unit":"EA","laborCost":0.00,"materialCost":9.75,"equipmentCost":0.00,"notes":"1-5/8 inch for wood stud"},
    {"id":uid(),"name":"Fine Thread Drywall Screw Supply - 5lb Box","category":"Drywall","unit":"EA","laborCost":0.00,"materialCost":9.75,"equipmentCost":0.00,"notes":"1-5/8 inch for metal stud"},
    {"id":uid(),"name":"Drywall Primer Application","category":"Drywall","unit":"SF","laborCost":0.18,"materialCost":0.08,"equipmentCost":0.02,"notes":"PVA drywall primer coat"},
    {"id":uid(),"name":"Scissor Lift Rental - Per Day","category":"Drywall","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":320.00,"notes":"19 ft electric scissor lift"},
    {"id":uid(),"name":"Scaffolding Rental - Per 1000 SF Per Week","category":"Drywall","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":450.00,"notes":"System scaffold per week"},
    {"id":uid(),"name":"Stilts Labor Add-On Per Day","category":"Drywall","unit":"EA","laborCost":95.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Ceiling pump and stilts add-on"},
    {"id":uid(),"name":"Intumescent Fire Caulk - Linear Joint","category":"Drywall","unit":"LF","laborCost":2.50,"materialCost":1.80,"equipmentCost":0.10,"notes":"Fire stop at wall-ceiling joint"},
    {"id":uid(),"name":"Fire Safing Insulation Install","category":"Drywall","unit":"LF","laborCost":3.50,"materialCost":2.20,"equipmentCost":0.10,"notes":"Between floor and curtain wall"},
    {"id":uid(),"name":"Penetration Fire Stop - Pipe Wrap","category":"Drywall","unit":"EA","laborCost":45.00,"materialCost":22.00,"equipmentCost":0.00,"notes":"Per pipe penetration through rated wall"},
    {"id":uid(),"name":"Cement Board Install - 1/2 Inch","category":"Drywall","unit":"SF","laborCost":0.75,"materialCost":0.95,"equipmentCost":0.05,"notes":"Tile backer in wet areas"},
    {"id":uid(),"name":"Cement Board Install - 5/8 Inch","category":"Drywall","unit":"SF","laborCost":0.80,"materialCost":1.10,"equipmentCost":0.05,"notes":"Heavy tile backer"},
    {"id":uid(),"name":"Foam Board Insulation Attach to Concrete","category":"Drywall","unit":"SF","laborCost":0.38,"materialCost":0.52,"equipmentCost":0.02,"notes":"2 inch EPS on CMU or concrete"},
    {"id":uid(),"name":"Vapor Barrier Install Behind Drywall","category":"Drywall","unit":"SF","laborCost":0.20,"materialCost":0.08,"equipmentCost":0.01,"notes":"6 mil poly sheeting"},
    {"id":uid(),"name":"Drywall Soffit Build-Out - Simple Box Shape","category":"Drywall","unit":"LF","laborCost":8.50,"materialCost":3.25,"equipmentCost":0.50,"notes":"Duct or pipe concealment soffit"},
    {"id":uid(),"name":"Drywall Column Wrap - Square","category":"Drywall","unit":"LF","laborCost":12.00,"materialCost":4.50,"equipmentCost":0.50,"notes":"Per LF height of column"},
    {"id":uid(),"name":"Drywall Curved Wall System","category":"Drywall","unit":"SF","laborCost":2.50,"materialCost":0.90,"equipmentCost":0.15,"notes":"Flexible track and 1/4 board"},
    {"id":uid(),"name":"Drywall Cove Lighting Trough Build-Out","category":"Drywall","unit":"LF","laborCost":15.00,"materialCost":5.50,"equipmentCost":0.50,"notes":"Indirect lighting reveal"},
    {"id":uid(),"name":"Drywall Inspection and Report","category":"Drywall","unit":"EA","laborCost":250.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Pre-paint inspection with report"},
    {"id":uid(),"name":"STC Wall Assembly Testing","category":"Drywall","unit":"EA","laborCost":850.00,"materialCost":0.00,"equipmentCost":125.00,"notes":"Field acoustics test for STC rating"},
    {"id":uid(),"name":"Drywall Control Joint Install","category":"Drywall","unit":"LF","laborCost":1.25,"materialCost":0.65,"equipmentCost":0.00,"notes":"Expansion joint in large walls"},
    {"id":uid(),"name":"Drywall Access Panel Install - 12x12","category":"Drywall","unit":"EA","laborCost":55.00,"materialCost":38.00,"equipmentCost":0.00,"notes":"Pre-made spring-loaded access door"},
    {"id":uid(),"name":"Drywall Access Panel Install - 24x24","category":"Drywall","unit":"EA","laborCost":75.00,"materialCost":65.00,"equipmentCost":0.00,"notes":"Full size drywall access door"},
    {"id":uid(),"name":"Window Return Drywall - Per Opening","category":"Drywall","unit":"EA","laborCost":35.00,"materialCost":12.00,"equipmentCost":0.00,"notes":"Window jamb and reveal wrap"},
    {"id":uid(),"name":"Door Return Drywall - Per Opening","category":"Drywall","unit":"EA","laborCost":28.00,"materialCost":10.00,"equipmentCost":0.00,"notes":"Door jamb wrap"},
    {"id":uid(),"name":"Drywall Backing Board for Heavy Fixture","category":"Drywall","unit":"EA","laborCost":18.00,"materialCost":8.50,"equipmentCost":0.00,"notes":"TV mount grab bar or cabinet reinforcement"},
    {"id":uid(),"name":"Drywall Protective Corner Guard Install","category":"Drywall","unit":"EA","laborCost":8.50,"materialCost":12.00,"equipmentCost":0.00,"notes":"Surface mount metal guard"},
    {"id":uid(),"name":"Drywall Niche Build-Out - Recessed Shelf","category":"Drywall","unit":"EA","laborCost":85.00,"materialCost":35.00,"equipmentCost":5.00,"notes":"Framed opening between studs"},
    {"id":uid(),"name":"Drywall Texture Matching - Existing","category":"Drywall","unit":"SF","laborCost":2.25,"materialCost":0.18,"equipmentCost":0.10,"notes":"Match existing texture on patches"},
    {"id":uid(),"name":"Drywall Shadow Line Trim - Z-Bead LF","category":"Drywall","unit":"LF","laborCost":1.85,"materialCost":1.25,"equipmentCost":0.00,"notes":"Architectural reveal trim"},
    {"id":uid(),"name":"Drywall Tear-Away Bead - Vinyl LF","category":"Drywall","unit":"LF","laborCost":0.85,"materialCost":0.55,"equipmentCost":0.00,"notes":"L-bead for windows and doors"},
    {"id":uid(),"name":"Drywall Ceiling Coffers - Custom Build EA","category":"Drywall","unit":"EA","laborCost":450.00,"materialCost":185.00,"equipmentCost":25.00,"notes":"Framed and finished coffers"},
    {"id":uid(),"name":"Drywall Barrel Vault - Radius Frame EA","category":"Drywall","unit":"EA","laborCost":650.00,"materialCost":285.00,"equipmentCost":45.00,"notes":"Curved ceiling architecture"},
    {"id":uid(),"name":"Drywall Scuttle Hole Kit - Insulated EA","category":"Drywall","unit":"EA","laborCost":85.00,"materialCost":125.00,"equipmentCost":0.00,"notes":"Pre-finished attic access"},
    {"id":uid(),"name":"Drywall Patch - Large 2x2 Ft Hole EA","category":"Drywall","unit":"EA","laborCost":125.00,"materialCost":15.00,"equipmentCost":5.00,"notes":"Cut out and repair major damage"},
    {"id":uid(),"name":"Drywall Joint Reinforcement - Mesh Tape","category":"Drywall","unit":"SF","laborCost":0.15,"materialCost":0.08,"equipmentCost":0.00,"notes":"Fiberglass mesh for repair"},
    {"id":uid(),"name":"Drywall Joint Reinforcement - Fibafuse","category":"Drywall","unit":"SF","laborCost":0.18,"materialCost":0.12,"equipmentCost":0.00,"notes":"Paperless fiber reinforcement"},
    {"id":uid(),"name":"Drywall Hand Stocking - High Load Add-On","category":"Drywall","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Specialty transport for tight site"},
]
