"""GeneralConditionsAgent — 100 items for overhead and project support"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Project Management ─────────────────────────────────────
    {"id":uid(),"name":"Project Manager - Per Day","category":"General Conditions","unit":"EA","laborCost":650.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Full day on-site PM"},
    {"id":uid(),"name":"Project Manager - Per Week","category":"General Conditions","unit":"EA","laborCost":2850.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Weekly PM rate"},
    {"id":uid(),"name":"Project Superintendent - Per Day","category":"General Conditions","unit":"EA","laborCost":485.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Full day site superintendent"},
    {"id":uid(),"name":"Project Superintendent - Per Week","category":"General Conditions","unit":"EA","laborCost":2200.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Weekly superintendent rate"},
    {"id":uid(),"name":"Foreman Labor - Per Day","category":"General Conditions","unit":"EA","laborCost":365.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Lead carpenter or foreman"},
    {"id":uid(),"name":"General Labor - Per Day","category":"General Conditions","unit":"EA","laborCost":245.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"General labor full work day"},
    {"id":uid(),"name":"General Labor - Per Hour","category":"General Conditions","unit":"HR","laborCost":48.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Hourly general labor"},
    {"id":uid(),"name":"Project Closeout Site Walk","category":"General Conditions","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Final walk and punch list"},
    {"id":uid(),"name":"Subcontractor Coordination Fee","category":"General Conditions","unit":"EA","laborCost":285.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Weekly sub coordination"},
    # ── Permits and Fees ──────────────────────────────────────
    {"id":uid(),"name":"Building Permit - Residential New Const","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":1850.00,"equipmentCost":0.00,"notes":"County building permit"},
    {"id":uid(),"name":"Building Permit - Small Addition","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":850.00,"equipmentCost":0.00,"notes":"Small scope addition permit"},
    {"id":uid(),"name":"Permit Expediting Service","category":"General Conditions","unit":"EA","laborCost":285.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Permit runner and expediting"},
    {"id":uid(),"name":"Building Department Inspection - Per Visit","category":"General Conditions","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Scheduling and inspection prep"},
    {"id":uid(),"name":"Plan Review Resubmission Fee","category":"General Conditions","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Respond to plan review comments"},
    {"id":uid(),"name":"Zoning Variance Application","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":650.00,"equipmentCost":0.00,"notes":"Filing fee varies by jurisdiction"},
    {"id":uid(),"name":"HOA Approval Submission","category":"General Conditions","unit":"EA","laborCost":95.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"HOA submittal preparation"},
    # ── Temporary Facilities ──────────────────────────────────
    {"id":uid(),"name":"Portable Toilet Rental - Per Month","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":195.00,"notes":"Chemical toilet monthly service"},
    {"id":uid(),"name":"Temporary Power - Hook Up Fee","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":185.00,"notes":"Temp pole and service hook-up"},
    {"id":uid(),"name":"Temporary Power - Per Month","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":125.00,"notes":"Monthly temp power"},
    {"id":uid(),"name":"Temporary Water - Service Hook-Up","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":95.00,"notes":"Temp water service"},
    {"id":uid(),"name":"Temporary Water - Per Month","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":65.00,"notes":"Monthly water bill estimate"},
    {"id":uid(),"name":"Temporary Office Trailer - Per Month","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":650.00,"notes":"Site office trailer rental"},
    {"id":uid(),"name":"Temporary Fence - Chain Link Rental Per Month","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":325.00,"notes":"Security fencing per month"},
    {"id":uid(),"name":"Construction Signs and Job ID","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":185.00,"equipmentCost":0.00,"notes":"Building permit sign and ID"},
    {"id":uid(),"name":"Temporary Heating - Propane Heater Per Week","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":185.00,"notes":"Propane forced air heater"},
    # ── Dumpsters and Waste ────────────────────────────────────
    {"id":uid(),"name":"Dumpster Rental - 10 Yard Per Week","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":325.00,"notes":"10 CY open top dumpster"},
    {"id":uid(),"name":"Dumpster Rental - 20 Yard Per Week","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":425.00,"notes":"20 CY roll-off dumpster"},
    {"id":uid(),"name":"Dumpster Rental - 30 Yard Per Week","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":525.00,"notes":"30 CY large dumpster"},
    {"id":uid(),"name":"Debris Haul Away - Pickup Truck Load","category":"General Conditions","unit":"EA","laborCost":65.00,"materialCost":35.00,"equipmentCost":0.00,"notes":"1 truck load haul and dump"},
    {"id":uid(),"name":"Daily Site Cleanup Labor","category":"General Conditions","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"End-of-day broom clean"},
    {"id":uid(),"name":"Final Site Cleanup and Broom Clean","category":"General Conditions","unit":"EA","laborCost":285.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Move-in ready final clean"},
    {"id":uid(),"name":"Window Cleaning - Post Construction","category":"General Conditions","unit":"EA","laborCost":185.00,"materialCost":15.00,"equipmentCost":5.00,"notes":"Per floor window wash"},
    # ── Safety ────────────────────────────────────────────────
    {"id":uid(),"name":"Safety Officer - Per Day","category":"General Conditions","unit":"EA","laborCost":485.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"On-site safety monitoring"},
    {"id":uid(),"name":"Safety Plan Preparation","category":"General Conditions","unit":"EA","laborCost":650.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Site-specific safety plan"},
    {"id":uid(),"name":"First Aid Kit Supply","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":95.00,"equipmentCost":0.00,"notes":"OSHA compliant first aid"},
    {"id":uid(),"name":"PPE Supply - Crew Per Month","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":85.00,"equipmentCost":0.00,"notes":"Hard hats vests and gloves"},
    {"id":uid(),"name":"Fall Protection Harness Setup","category":"General Conditions","unit":"EA","laborCost":45.00,"materialCost":0.00,"equipmentCost":25.00,"notes":"Anchor and harness per use"},
    {"id":uid(),"name":"Tool Box Talk - Safety Meeting","category":"General Conditions","unit":"EA","laborCost":95.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Weekly crew safety meeting"},
    # ── Insurance and Bonds ────────────────────────────────────
    {"id":uid(),"name":"General Liability Insurance - Per Month","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":385.00,"equipmentCost":0.00,"notes":"Monthly GL insurance cost"},
    {"id":uid(),"name":"Builders Risk Insurance - Per Month","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":285.00,"equipmentCost":0.00,"notes":"Course of construction policy"},
    {"id":uid(),"name":"Performance Bond - Per Project","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":1850.00,"equipmentCost":0.00,"notes":"Performance bond premium"},
    {"id":uid(),"name":"Workerscomp Insurance - Per Month","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":450.00,"equipmentCost":0.00,"notes":"WC monthly allocation"},
    # ── Equipment ─────────────────────────────────────────────
    {"id":uid(),"name":"Generator Rental - 25 KW Per Day","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":285.00,"notes":"Portable generator for temp power"},
    {"id":uid(),"name":"Job Site Lighting Tower - Per Week","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":185.00,"notes":"Portable light tower rental"},
    {"id":uid(),"name":"Power Tool Supply - Miscellaneous","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":85.00,"equipmentCost":0.00,"notes":"Bits blades and supplies"},
    {"id":uid(),"name":"Scaffold Rental - 5 Ft x 7 Ft Frame Per Week","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":55.00,"notes":"Per mason frame per week"},
    {"id":uid(),"name":"Boom Lift Rental - 45 Ft Per Day","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":485.00,"notes":"Electric articulating boom lift"},
    {"id":uid(),"name":"Scissor Lift Rental - 26 Ft Per Day","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":285.00,"notes":"Electric scissor lift per day"},
    # ── Communication and Documentation ───────────────────────
    {"id":uid(),"name":"Preconstruction Meeting - Per Event","category":"General Conditions","unit":"EA","laborCost":285.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"PM kickoff meeting"},
    {"id":uid(),"name":"Weekly OAC Meeting - Per Session","category":"General Conditions","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Owner architect contractor meeting"},
    {"id":uid(),"name":"RFI Preparation and Response","category":"General Conditions","unit":"EA","laborCost":85.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Per RFI document and response"},
    {"id":uid(),"name":"Submittal Processing - Per Package","category":"General Conditions","unit":"EA","laborCost":85.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Submittal log and distribution"},
    {"id":uid(),"name":"Project Photos - Per Week","category":"General Conditions","unit":"EA","laborCost":45.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Weekly progress photo log"},
    {"id":uid(),"name":"As-Built Drawing Preparation","category":"General Conditions","unit":"EA","laborCost":850.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Final as-built red lines"},
    {"id":uid(),"name":"O and M Manual Preparation","category":"General Conditions","unit":"EA","laborCost":450.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Operations and maintenance docs"},
    # ── Miscellaneous ─────────────────────────────────────────
    {"id":uid(),"name":"Material Delivery Coordination","category":"General Conditions","unit":"EA","laborCost":45.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Receiving and stacking materials"},
    {"id":uid(),"name":"Fuel Surcharge - Equipment Per Week","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":125.00,"equipmentCost":0.00,"notes":"Fuel cost for site equipment"},
    {"id":uid(),"name":"Small Tools and Consumables - Per Week","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":85.00,"equipmentCost":0.00,"notes":"Blades bits and consumables"},
    {"id":uid(),"name":"Travel Time - Crew Per Hr","category":"General Conditions","unit":"HR","laborCost":48.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"Mileage and drive time"},
    {"id":uid(),"name":"Cell Phone and Communication Per Month","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":85.00,"equipmentCost":0.00,"notes":"Field communication costs"},
    {"id":uid(),"name":"Project Software - Procore Per Month","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":375.00,"equipmentCost":0.00,"notes":"Project management platform"},
    {"id":uid(),"name":"Site Survey - Pre-Construction","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":850.00,"equipmentCost":0.00,"notes":"Licensed surveyor boundary"},
    {"id":uid(),"name":"Material Testing - Concrete and Soil","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":450.00,"equipmentCost":0.00,"notes":"Third party testing contract"},
    {"id":uid(),"name":"Clean Room Protection During Finish Work","category":"General Conditions","unit":"EA","laborCost":125.00,"materialCost":85.00,"equipmentCost":0.00,"notes":"Floor and surface protection"},
    {"id":uid(),"name":"Warranty Callback Labor - Per Hr","category":"General Conditions","unit":"HR","laborCost":75.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Post-completion warranty visit"},
    {"id":uid(),"name":"Construction Photography - Drone","category":"General Conditions","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Drone aerial progress shoot"},
    {"id":uid(),"name":"Truck Rental - Per Day","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":125.00,"notes":"3/4 ton pickup truck rental"},
    {"id":uid(),"name":"Concrete Washout Area Setup","category":"General Conditions","unit":"EA","laborCost":65.00,"materialCost":45.00,"equipmentCost":0.00,"notes":"Lined washout pit setup"},
    {"id":uid(),"name":"Site Sign Install - Project","category":"General Conditions","unit":"EA","laborCost":45.00,"materialCost":95.00,"equipmentCost":5.00,"notes":"Contractor project sign board"},
    {"id":uid(),"name":"Material Storage Container - Per Month","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":185.00,"notes":"20 ft Conex job site container"},
    {"id":uid(),"name":"Parking and Site Access Fee","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":85.00,"equipmentCost":0.00,"notes":"Monthly parking pass fees"},
    {"id":uid(),"name":"Noise Ordinance Compliance Fee","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":45.00,"equipmentCost":0.00,"notes":"Sound blanket or barrier rental"},
    {"id":uid(),"name":"Subtrade Qualification Review","category":"General Conditions","unit":"EA","laborCost":95.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Vetting and insurance verify"},
    {"id":uid(),"name":"Change Order Processing Fee","category":"General Conditions","unit":"EA","laborCost":85.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Per CO admin markup"},
    {"id":uid(),"name":"Subcontractor Back Charge Processing","category":"General Conditions","unit":"EA","laborCost":95.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Back-charge documentation"},
    {"id":uid(),"name":"Project Closeout Documentation","category":"General Conditions","unit":"EA","laborCost":285.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Lien waivers letters and docs"},
    {"id":uid(),"name":"Construction Manager - Senior Hourly Rate","category":"General Conditions","unit":"HR","laborCost":185.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"Lead PM senior management"},
    {"id":uid(),"name":"Field Engineer - Hourly Rate","category":"General Conditions","unit":"HR","laborCost":95.00,"materialCost":0.00,"equipmentCost":25.00,"notes":"Staking and technical layout"},
    {"id":uid(),"name":"Safety Officer - Hourly Rate","category":"General Conditions","unit":"HR","laborCost":85.00,"materialCost":0.00,"equipmentCost":5.00,"notes":"On-site OSHA compliance"},
    {"id":uid(),"name":"Estimator - Hourly Rate","category":"General Conditions","unit":"HR","laborCost":125.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Precon cost estimating"},
    {"id":uid(),"name":"Scheduler - Hourly Rate","category":"General Conditions","unit":"HR","laborCost":115.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"CPM schedule updates"},
    {"id":uid(),"name":"Bid Package Preparation - Per Trade EA","category":"General Conditions","unit":"EA","laborCost":285.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Scope of work and bid review"},
    {"id":uid(),"name":"Permitting Coordination - Hourly Rate","category":"General Conditions","unit":"HR","laborCost":75.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Expediting and city meetings"},
    {"id":uid(),"name":"Community Liaison - Hourly Rate","category":"General Conditions","unit":"HR","laborCost":85.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Neighbor and city relations"},
    {"id":uid(),"name":"Temporary Water Hookup - Per Event","category":"General Conditions","unit":"EA","laborCost":450.00,"materialCost":285.00,"equipmentCost":0.00,"notes":"Temp meter and plumbing"},
    {"id":uid(),"name":"Temporary Power Hookup - Per Event","category":"General Conditions","unit":"EA","laborCost":850.00,"materialCost":450.00,"equipmentCost":125.00,"notes":"Temp pole and panel setup"},
    {"id":uid(),"name":"Temporary Internet Setup - Per Event","category":"General Conditions","unit":"EA","laborCost":125.00,"materialCost":85.00,"equipmentCost":185.00,"notes":"Field office connectivity"},
    {"id":uid(),"name":"Site Trailer Setup and Hookup EA","category":"General Conditions","unit":"EA","laborCost":485.00,"materialCost":125.00,"equipmentCost":850.00,"notes":"Trailer positioning and leveling"},
    {"id":uid(),"name":"SWPPP Plan and Implementation EA","category":"General Conditions","unit":"EA","laborCost":1250.00,"materialCost":450.00,"equipmentCost":150.00,"notes":"Certified erosion control plan"},
    {"id":uid(),"name":"Erosion Control Maintenance - Weekly EA","category":"General Conditions","unit":"EA","laborCost":185.00,"materialCost":45.00,"equipmentCost":25.00,"notes":"Inspector and repair visit"},
    {"id":uid(),"name":"Dust Control - Water Truck Rental Day","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":450.00,"notes":"Daily water truck hire"},
    {"id":uid(),"name":"Project Signage - Regulatory and Safety","category":"General Conditions","unit":"EA","laborCost":85.00,"materialCost":350.00,"equipmentCost":5.00,"notes":"Required safety signage set"},
    {"id":uid(),"name":"Traffic Control Plan - Engineered EA","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":1850.00,"equipmentCost":0.00,"notes":"Stamped traffic detour plan"},
    {"id":uid(),"name":"Traffic Control Personnel - Flagging HR","category":"General Conditions","unit":"HR","laborCost":55.00,"materialCost":0.00,"equipmentCost":12.00,"notes":"Per person traffic control"},
    {"id":uid(),"name":"Crane Mobilization and Setup EA","category":"General Conditions","unit":"EA","laborCost":1250.00,"materialCost":0.00,"equipmentCost":3500.00,"notes":"Full mobilization for tower crane"},
    {"id":uid(),"name":"Scaffolding System - Rental Per Week","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":285.00,"notes":"2-tier scaffold tower per wk"},
    {"id":uid(),"name":"Trash Chute System - Rental Per Week","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":125.00,"notes":"Upper floor debris removal set"},
    {"id":uid(),"name":"Temporary Heat - Fuel Tank Rental Month","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":225.00,"notes":"Propane tank rental for site heat"},
    {"id":uid(),"name":"Portable Generator Rental - Per Day","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":85.00,"notes":"5000W contractor generator"},
    {"id":uid(),"name":"First Aid Station - Stocked Set EA","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":125.00,"equipmentCost":0.00,"notes":"Industrial safety medical kit"},
    {"id":uid(),"name":"Eye Wash Station - Portable EA","category":"General Conditions","unit":"EA","laborCost":0.00,"materialCost":85.00,"equipmentCost":0.00,"notes":"OSHA eye wash pedestal or port"},
    {"id":uid(),"name":"Fire Extinguisher Station - 3 Set EA","category":"General Conditions","unit":"EA","laborCost":45.00,"materialCost":185.00,"equipmentCost":0.00,"notes":"Mounted 10 lb ABC extinguishers"},
    {"id":uid(),"name":"Site Demobilization and Final Clean Trip","category":"General Conditions","unit":"EA","laborCost":485.00,"materialCost":125.00,"equipmentCost":150.00,"notes":"Final checkout and terminal clean"},
]
