"""FlatworkAgent — 100 items for asphalt, pavers, and hardscape"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Asphalt ───────────────────────────────────────────────
    {"id":uid(),"name":"Asphalt Paving - 2 Inch Topping Course","category":"Flatwork","unit":"SF","laborCost":0.35,"materialCost":0.55,"equipmentCost":0.25,"notes":"Type II surface course"},
    {"id":uid(),"name":"Asphalt Paving - 3 Inch Binder Course","category":"Flatwork","unit":"SF","laborCost":0.42,"materialCost":0.75,"equipmentCost":0.30,"notes":"Binder or base course"},
    {"id":uid(),"name":"Asphalt Paving - 4 Inch Full Depth","category":"Flatwork","unit":"SF","laborCost":0.55,"materialCost":1.00,"equipmentCost":0.38,"notes":"Full depth residential drive"},
    {"id":uid(),"name":"Asphalt Milling - 2 Inch Removal","category":"Flatwork","unit":"SF","laborCost":0.22,"materialCost":0.00,"equipmentCost":0.35,"notes":"Cold mill and haul"},
    {"id":uid(),"name":"Asphalt Crack Fill - Hot or Cold","category":"Flatwork","unit":"LF","laborCost":0.85,"materialCost":0.45,"equipmentCost":0.15,"notes":"Routed crack fill"},
    {"id":uid(),"name":"Asphalt Sealcoating - Per SF","category":"Flatwork","unit":"SF","laborCost":0.08,"materialCost":0.08,"equipmentCost":0.03,"notes":"Coal tar or asphalt sealer"},
    {"id":uid(),"name":"Asphalt Patching - Per SF","category":"Flatwork","unit":"SF","laborCost":2.85,"materialCost":1.25,"equipmentCost":0.85,"notes":"Remove defective and patch"},
    {"id":uid(),"name":"Asphalt Striping - Per LF","category":"Flatwork","unit":"LF","laborCost":0.35,"materialCost":0.15,"equipmentCost":0.08,"notes":"Traffic paint line stripe"},
    {"id":uid(),"name":"Asphalt Parking Stall Striping","category":"Flatwork","unit":"EA","laborCost":8.50,"materialCost":3.50,"equipmentCost":0.50,"notes":"Per stall paint stripe"},
    {"id":uid(),"name":"Asphalt Speed Bump Install","category":"Flatwork","unit":"EA","laborCost":85.00,"materialCost":125.00,"equipmentCost":15.00,"notes":"Rubber or asphalt speed bump"},
    # ── Concrete Flatwork (Exterior Hardscape) ─────────────────
    {"id":uid(),"name":"Concrete Sidewalk - 4 Inch Residential","category":"Flatwork","unit":"SF","laborCost":1.25,"materialCost":1.75,"equipmentCost":0.40,"notes":"Residential 4 in sidewalk"},
    {"id":uid(),"name":"Concrete Sidewalk - Public ROW 4 Inch","category":"Flatwork","unit":"SF","laborCost":1.35,"materialCost":1.85,"equipmentCost":0.45,"notes":"Right-of-way compliant walk"},
    {"id":uid(),"name":"Concrete Approach Apron - Commercial 6 Inch","category":"Flatwork","unit":"SF","laborCost":1.75,"materialCost":2.45,"equipmentCost":0.55,"notes":"Heavy commercial entry"},
    {"id":uid(),"name":"Concrete Pool Deck - 4 Inch Broom Finish","category":"Flatwork","unit":"SF","laborCost":1.45,"materialCost":1.95,"equipmentCost":0.45,"notes":"Standard pool deck concrete"},
    {"id":uid(),"name":"Concrete Pad - HVAC Equipment - 4 Inch","category":"Flatwork","unit":"SF","laborCost":1.25,"materialCost":1.75,"equipmentCost":0.40,"notes":"Equipment pad poured"},
    {"id":uid(),"name":"Concrete Trench Drain Install - Per LF","category":"Flatwork","unit":"LF","laborCost":12.00,"materialCost":18.00,"equipmentCost":3.50,"notes":"Cast iron or polymer grate drain"},
    {"id":uid(),"name":"Concrete Stem Wall - Landscape","category":"Flatwork","unit":"LF","laborCost":22.00,"materialCost":18.00,"equipmentCost":3.50,"notes":"Low landscape stem wall"},
    # ── Pavers and Hardscape ───────────────────────────────────
    {"id":uid(),"name":"Concrete Paver Install - 4x8 Standard","category":"Flatwork","unit":"SF","laborCost":4.50,"materialCost":3.25,"equipmentCost":0.35,"notes":"Concrete paver on gravel base"},
    {"id":uid(),"name":"Concrete Paver Install - 12x12 Square","category":"Flatwork","unit":"SF","laborCost":4.75,"materialCost":3.85,"equipmentCost":0.35,"notes":"12x12 paver on gravel bed"},
    {"id":uid(),"name":"Concrete Paver Install - Tumbled Look","category":"Flatwork","unit":"SF","laborCost":5.00,"materialCost":4.50,"equipmentCost":0.40,"notes":"Aged or tumbled paver look"},
    {"id":uid(),"name":"Permeable Paver Install - 4x8","category":"Flatwork","unit":"SF","laborCost":5.50,"materialCost":5.50,"equipmentCost":0.50,"notes":"Void paver with gravel fill"},
    {"id":uid(),"name":"Brick Paver Install - Running Bond","category":"Flatwork","unit":"SF","laborCost":6.50,"materialCost":5.50,"equipmentCost":0.45,"notes":"Genuine clay brick on sand"},
    {"id":uid(),"name":"Brick Paver Install - Herringbone","category":"Flatwork","unit":"SF","laborCost":7.50,"materialCost":5.50,"equipmentCost":0.50,"notes":"45 degree herringbone pattern"},
    {"id":uid(),"name":"Cobblestone Paver Install - Natural","category":"Flatwork","unit":"SF","laborCost":8.50,"materialCost":8.50,"equipmentCost":0.50,"notes":"Natural granite cobble set"},
    {"id":uid(),"name":"Travertine Paver Install - Exterior","category":"Flatwork","unit":"SF","laborCost":7.50,"materialCost":6.50,"equipmentCost":0.50,"notes":"Travertine outdoor paver"},
    {"id":uid(),"name":"Flagstone Install - Dry Laid","category":"Flatwork","unit":"SF","laborCost":6.50,"materialCost":7.50,"equipmentCost":0.45,"notes":"Natural flagstone dry laid"},
    {"id":uid(),"name":"Flagstone Install - Mortar Set","category":"Flatwork","unit":"SF","laborCost":8.50,"materialCost":7.50,"equipmentCost":0.55,"notes":"Flagstone mortar to concrete"},
    {"id":uid(),"name":"Slate Paver Install - Exterior","category":"Flatwork","unit":"SF","laborCost":7.50,"materialCost":6.50,"equipmentCost":0.45,"notes":"Slate paver on mortar bed"},
    {"id":uid(),"name":"Bluestone Paver Install - Thermal Cut","category":"Flatwork","unit":"SF","laborCost":7.50,"materialCost":9.50,"equipmentCost":0.50,"notes":"Premium bluestone cut paver"},
    # ── Paver Base and Prep ────────────────────────────────────
    {"id":uid(),"name":"Paver Base - 4 Inch Compacted Gravel","category":"Flatwork","unit":"SF","laborCost":0.45,"materialCost":0.55,"equipmentCost":0.15,"notes":"CA-6 base for paver prep"},
    {"id":uid(),"name":"Paver Base - 6 Inch Compacted Gravel","category":"Flatwork","unit":"SF","laborCost":0.55,"materialCost":0.75,"equipmentCost":0.18,"notes":"6 in base under pavers"},
    {"id":uid(),"name":"Paver Sand Bed - 1 Inch Screeded","category":"Flatwork","unit":"SF","laborCost":0.25,"materialCost":0.15,"equipmentCost":0.05,"notes":"Bedding sand level screed"},
    {"id":uid(),"name":"Paver Polymeric Sand Joint Fill","category":"Flatwork","unit":"SF","laborCost":0.25,"materialCost":0.22,"equipmentCost":0.03,"notes":"Polymeric joint filler"},
    {"id":uid(),"name":"Paver Sealer Application","category":"Flatwork","unit":"SF","laborCost":0.18,"materialCost":0.22,"equipmentCost":0.06,"notes":"Wet look or natural sealer"},
    {"id":uid(),"name":"Paver Edge Restraint - Plastic Flex","category":"Flatwork","unit":"LF","laborCost":0.55,"materialCost":0.45,"equipmentCost":0.03,"notes":"Snap Edge or similar"},
    {"id":uid(),"name":"Paver Edge Restraint - Steel Spike","category":"Flatwork","unit":"LF","laborCost":0.75,"materialCost":0.65,"equipmentCost":0.03,"notes":"Steel paver border restraint"},
    # ── Gravel ────────────────────────────────────────────────
    {"id":uid(),"name":"Crushed Stone Driveway - 4 Inch Depth","category":"Flatwork","unit":"SF","laborCost":0.18,"materialCost":0.38,"equipmentCost":0.12,"notes":"1.5 in crushed limestone"},
    {"id":uid(),"name":"Pea Gravel Path - 2 Inch Deep","category":"Flatwork","unit":"SF","laborCost":0.22,"materialCost":0.28,"equipmentCost":0.08,"notes":"Pea gravel groundcover"},
    {"id":uid(),"name":"Decorative River Rock - 3 Inch Bed","category":"Flatwork","unit":"SF","laborCost":0.28,"materialCost":0.55,"equipmentCost":0.08,"notes":"River rock decorative layer"},
    {"id":uid(),"name":"Gravel Parking Lot - 6 Inch Compact","category":"Flatwork","unit":"SF","laborCost":0.28,"materialCost":0.65,"equipmentCost":0.20,"notes":"Commercial gravel parking"},
    {"id":uid(),"name":"French Drain to Daylight - Per LF","category":"Flatwork","unit":"LF","laborCost":8.50,"materialCost":5.50,"equipmentCost":1.50,"notes":"Gravel wrapped drain pipe"},
    # ── Edging and Borders ─────────────────────────────────────
    {"id":uid(),"name":"Steel Landscape Edging - 4 Inch","category":"Flatwork","unit":"LF","laborCost":1.85,"materialCost":1.25,"equipmentCost":0.10,"notes":"Cor-Ten steel lawn edging"},
    {"id":uid(),"name":"Aluminum Landscape Edging","category":"Flatwork","unit":"LF","laborCost":1.25,"materialCost":0.65,"equipmentCost":0.05,"notes":"Dig in aluminum edging"},
    {"id":uid(),"name":"Plastic Landscape Edging - Per LF","category":"Flatwork","unit":"LF","laborCost":0.65,"materialCost":0.28,"equipmentCost":0.02,"notes":"Black plastic lawn border"},
    {"id":uid(),"name":"Timber Landscape Border - 4x4 Treated","category":"Flatwork","unit":"LF","laborCost":2.50,"materialCost":2.85,"equipmentCost":0.15,"notes":"Landscape timber border"},
    {"id":uid(),"name":"Concrete Mow Strip - 4 Inch Wide","category":"Flatwork","unit":"LF","laborCost":5.50,"materialCost":2.25,"equipmentCost":0.35,"notes":"Poured concrete mow strip"},
    # ── Specialty ─────────────────────────────────────────────
    {"id":uid(),"name":"Step and Cheekwall - Landscape Block","category":"Flatwork","unit":"EA","laborCost":85.00,"materialCost":55.00,"equipmentCost":5.00,"notes":"One step retaining landscape"},
    {"id":uid(),"name":"Retaining Wall - Segmental Block - Per SF","category":"Flatwork","unit":"SF","laborCost":8.50,"materialCost":6.50,"equipmentCost":0.75,"notes":"SRW block with gravel backer"},
    {"id":uid(),"name":"Pressure Washing - Hard Surface","category":"Flatwork","unit":"SF","laborCost":0.08,"materialCost":0.00,"equipmentCost":0.04,"notes":"Hot water pressure wash"},
    {"id":uid(),"name":"Snow Removal Machine - Per Push","category":"Flatwork","unit":"EA","laborCost":45.00,"materialCost":0.00,"equipmentCost":35.00,"notes":"Machine plow and removal pass"},
    {"id":uid(),"name":"Ice Melt Material Supply - 50 Lb Bag","category":"Flatwork","unit":"EA","laborCost":0.00,"materialCost":28.00,"equipmentCost":0.00,"notes":"Calcium chloride 50 lb bag"},
    {"id":uid(),"name":"Flatwork Inspection and Survey","category":"Flatwork","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":25.00,"notes":"Post-install elevation check"},
    {"id":uid(),"name":"Asphalt Sealcoating - Pro Grade SF","category":"Flatwork","unit":"SF","laborCost":0.12,"materialCost":0.08,"equipmentCost":0.05,"notes":"Commercial coal tar sealer"},
    {"id":uid(),"name":"Asphalt Crack Filling - Hot Pour LF","category":"Flatwork","unit":"LF","laborCost":0.85,"materialCost":0.45,"equipmentCost":0.15,"notes":"Hot rubberized crack filler"},
    {"id":uid(),"name":"Asphalt Patching - Cold Mix Per SF","category":"Flatwork","unit":"SF","laborCost":1.25,"materialCost":2.50,"equipmentCost":0.50,"notes":"Pothole repair cold patch"},
    {"id":uid(),"name":"Pervious Concrete Pavement - 6 Inch SF","category":"Flatwork","unit":"SF","laborCost":2.85,"materialCost":5.50,"equipmentCost":0.45,"notes":"Porous concrete for drainage"},
    {"id":uid(),"name":"Grass Pave System - Plastic Grid SF","category":"Flatwork","unit":"SF","laborCost":1.25,"materialCost":3.85,"equipmentCost":0.25,"notes":"Invisible geogrid for lawn parking"},
    {"id":uid(),"name":"Grass Pave System - Concrete Block SF","category":"Flatwork","unit":"SF","laborCost":2.25,"materialCost":4.50,"equipmentCost":0.45,"notes":"Open cell concrete pavers"},
    {"id":uid(),"name":"Exposed Aggregate Finish - Top Seed SF","category":"Flatwork","unit":"SF","laborCost":1.85,"materialCost":2.25,"equipmentCost":0.15,"notes":"Seeded pebble exposed finish"},
    {"id":uid(),"name":"Sandblast Finish - Concrete Surface SF","category":"Flatwork","unit":"SF","laborCost":1.50,"materialCost":0.00,"equipmentCost":1.25,"notes":"Light sandblast for texture"},
    {"id":uid(),"name":"Honed Concrete Finish - Exterior SF","category":"Flatwork","unit":"SF","laborCost":2.25,"materialCost":0.00,"equipmentCost":0.85,"notes":"Matte honed exterior slab"},
    {"id":uid(),"name":"Polished Concrete - Exterior Grade SF","category":"Flatwork","unit":"SF","laborCost":3.50,"materialCost":0.35,"equipmentCost":1.25,"notes":"High gloss exterior polish"},
    {"id":uid(),"name":"Slate Stone Pavers - Natural Per SF","category":"Flatwork","unit":"SF","laborCost":4.50,"materialCost":8.50,"equipmentCost":0.50,"notes":"Natural cleft slate pavers"},
    {"id":uid(),"name":"Travertine Pavers - 1.25 Inch SF","category":"Flatwork","unit":"SF","laborCost":4.50,"materialCost":12.00,"equipmentCost":0.50,"notes":"Premium travertine stone pavers"},
    {"id":uid(),"name":"Bluestone Pavers - Thermal Finish SF","category":"Flatwork","unit":"SF","laborCost":5.50,"materialCost":14.00,"equipmentCost":0.55,"notes":"Uniform thermal bluestone"},
    {"id":uid(),"name":"Bluestone Pavers - Natural Cleft SF","category":"Flatwork","unit":"SF","laborCost":5.50,"materialCost":12.50,"equipmentCost":0.55,"notes":"Rustic natural cleft bluestone"},
    {"id":uid(),"name":"Granite Setts - Belgian Block Per SF","category":"Flatwork","unit":"SF","laborCost":8.50,"materialCost":15.00,"equipmentCost":0.85,"notes":"Hand set granite block paving"},
    {"id":uid(),"name":"Cobblestone Inlay - Fan Pattern SF","category":"Flatwork","unit":"SF","laborCost":12.00,"materialCost":18.00,"equipmentCost":1.25,"notes":"Intricate fan cobblestone lay"},
    {"id":uid(),"name":"Brick Pavers - Herringbone Pattern SF","category":"Flatwork","unit":"SF","laborCost":4.50,"materialCost":6.50,"equipmentCost":0.45,"notes":"Classic brick herringbone style"},
    {"id":uid(),"name":"Concrete Curb - 6x12 High Back LF","category":"Flatwork","unit":"LF","laborCost":12.00,"materialCost":5.50,"equipmentCost":8.50,"notes":"Standard street-style curb"},
    {"id":uid(),"name":"Concrete Curb - Roll Curb 6 Inch LF","category":"Flatwork","unit":"LF","laborCost":12.00,"materialCost":4.50,"equipmentCost":8.50,"notes":"Driveway roll curb"},
    {"id":uid(),"name":"Concrete Curb - Header Curb 4 Inch LF","category":"Flatwork","unit":"LF","laborCost":8.50,"materialCost":3.50,"equipmentCost":5.50,"notes":"Flat header curb for pavers"},
    {"id":uid(),"name":"Parking Bumper - 6 Ft Concrete EA","category":"Flatwork","unit":"EA","laborCost":25.00,"materialCost":45.00,"equipmentCost":15.00,"notes":"Wheel stop precast concrete"},
    {"id":uid(),"name":"Parking Bumper - Recycled Rubber EA","category":"Flatwork","unit":"EA","laborCost":15.00,"materialCost":35.00,"equipmentCost":2.00,"notes":"Eco-friendly rubber wheel stop"},
    {"id":uid(),"name":"Trench Drain - 6 Inch Galvanized LF","category":"Flatwork","unit":"LF","laborCost":18.00,"materialCost":28.00,"equipmentCost":8.50,"notes":"Linear grate and channel drain"},
    {"id":uid(),"name":"Catch Basin - 12x12 Concrete EA","category":"Flatwork","unit":"EA","laborCost":125.00,"materialCost":185.00,"equipmentCost":45.00,"notes":"Standard utility catch basin"},
    {"id":uid(),"name":"Landscape Steps - Solid Granite EA","category":"Flatwork","unit":"EA","laborCost":185.00,"materialCost":250.00,"equipmentCost":125.00,"notes":"Single solid piece granite step"},
    {"id":uid(),"name":"Landscape Steps - Fieldstone Block EA","category":"Flatwork","unit":"EA","laborCost":125.00,"materialCost":85.00,"equipmentCost":45.00,"notes":"Stacked stone block step"},
    {"id":uid(),"name":"Landscape Steps - Timber and Gravel EA","category":"Flatwork","unit":"EA","laborCost":65.00,"materialCost":35.00,"equipmentCost":15.00,"notes":"Rustic timber railroad tie step"},
    {"id":uid(),"name":"Fire Pit - Poured Concrete EA","category":"Flatwork","unit":"EA","laborCost":450.00,"materialCost":185.00,"equipmentCost":45.00,"notes":"Custom formed round fire pit"},
    {"id":uid(),"name":"Fire Pit - Rimless Stone EA","category":"Flatwork","unit":"EA","laborCost":285.00,"materialCost":350.00,"equipmentCost":15.00,"notes":"Natural stone stack fire pit"},
    {"id":uid(),"name":"Outdoor Fireplace - Kit Assembly EA","category":"Flatwork","unit":"EA","laborCost":850.00,"materialCost":2850.00,"equipmentCost":150.00,"notes":"Prefabricated fireplace install"},
    {"id":uid(),"name":"Seat Wall - Stone Veneer SF","category":"Flatwork","unit":"SF","laborCost":12.00,"materialCost":15.00,"equipmentCost":1.25,"notes":"Stone faced low seat wall"},
    {"id":uid(),"name":"Pillar - Stone Veneer 24x24 EA","category":"Flatwork","unit":"EA","laborCost":285.00,"materialCost":350.00,"equipmentCost":45.00,"notes":"Stone faced landscape pillar"},
    {"id":uid(),"name":"Fountain Base - Prefab Concrete EA","category":"Flatwork","unit":"EA","laborCost":125.00,"materialCost":185.00,"equipmentCost":45.00,"notes":"Foundational slab for fountain"},
    {"id":uid(),"name":"Statuary Base - Cast Stone EA","category":"Flatwork","unit":"EA","laborCost":45.00,"materialCost":65.00,"equipmentCost":15.00,"notes":"Small base for garden art"},
    {"id":uid(),"name":"Concrete Bench - Post-Modern EA","category":"Flatwork","unit":"EA","laborCost":125.00,"materialCost":250.00,"equipmentCost":85.00,"notes":"Sleek post-modern concrete bench"},
    {"id":uid(),"name":"Concrete Table - Picnic Set EA","category":"Flatwork","unit":"EA","laborCost":285.00,"materialCost":850.00,"equipmentCost":150.00,"notes":"Permanent site furnishings"},
    {"id":uid(),"name":"Bollard Light - Concrete 3 Ft EA","category":"Flatwork","unit":"EA","laborCost":125.00,"materialCost":450.00,"equipmentCost":25.00,"notes":"Illuminated concrete bollard"},
    {"id":uid(),"name":"Low Voltage Wiring - Flatwork Burial LF","category":"Flatwork","unit":"LF","laborCost":3.50,"materialCost":1.85,"equipmentCost":1.50,"notes":"Direct burial conduit for lights"},
    {"id":uid(),"name":"Trenching for Utilities - Flatwork LF","category":"Flatwork","unit":"LF","laborCost":8.50,"materialCost":0.00,"equipmentCost":12.00,"notes":"Open trenching under flatwork"},
    {"id":uid(),"name":"Sub-Base - 3/4 Inch Minus 6 Inch SF","category":"Flatwork","unit":"SF","laborCost":0.35,"materialCost":0.85,"equipmentCost":0.45,"notes":"Standard road base compact"},
    {"id":uid(),"name":"Sub-Base - 3 Inch Surge Rock 4 Inch SF","category":"Flatwork","unit":"SF","laborCost":0.45,"materialCost":1.15,"equipmentCost":0.65,"notes":"Heavy structural rocky base"},
    {"id":uid(),"name":"Compaction - Vibratory Roller LF","category":"Flatwork","unit":"LF","laborCost":0.45,"materialCost":0.00,"equipmentCost":1.25,"notes":"Mechanical compaction pass"},
    {"id":uid(),"name":"Concrete Pumping - Reach Add-On EA","category":"Flatwork","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":850.00,"notes":"Pumper truck mobilization"},
    {"id":uid(),"name":"Conveyor Belt Service - Placement EA","category":"Flatwork","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":350.00,"notes":"Telebelt placement service"},
    {"id":uid(),"name":"Gravel Stop - Aluminum Per LF","category":"Flatwork","unit":"LF","laborCost":1.25,"materialCost":2.25,"equipmentCost":0.15,"notes":"Edge metal for gravel paths"},
    {"id":uid(),"name":"Expansion Joint - Fiber 1/4 Inch LF","category":"Flatwork","unit":"LF","laborCost":0.45,"materialCost":0.35,"equipmentCost":0.02,"notes":"Bituminous expansion filler"},
    {"id":uid(),"name":"Expansion Joint - Flexible PVC LF","category":"Flatwork","unit":"LF","laborCost":0.55,"materialCost":0.85,"equipmentCost":0.02,"notes":"PVC control joint insert"},
    {"id":uid(),"name":"Expansion Joint - Backer Rod and Seal LF","category":"Flatwork","unit":"LF","laborCost":1.25,"materialCost":0.65,"equipmentCost":0.05,"notes":"Caulked expansion joint"},
    {"id":uid(),"name":"Flatwork Demolition - Reinforced 6 Inch SF","category":"Flatwork","unit":"SF","laborCost":2.25,"materialCost":0.00,"equipmentCost":1.25,"notes":"Break and remove rebar slab"},
    {"id":uid(),"name":"Flatwork Saw Cutting - 4 Inch Deep LF","category":"Flatwork","unit":"LF","laborCost":1.85,"materialCost":0.55,"equipmentCost":2.25,"notes":"Diamond blade slab cutting"},
    {"id":uid(),"name":"Core Drilling - 4 Inch Masonry EA","category":"Flatwork","unit":"EA","laborCost":65.00,"materialCost":0.00,"equipmentCost":125.00,"notes":"Hole core through slab"},
    {"id":uid(),"name":"Concrete Sealer - Penetrating Silane SF","category":"Flatwork","unit":"SF","laborCost":0.22,"materialCost":0.65,"equipmentCost":0.04,"notes":"High performance salt protect"},
    {"id":uid(),"name":"Flatwork Site Protection - Plywood EA","category":"Flatwork","unit":"EA","laborCost":45.00,"materialCost":28.00,"equipmentCost":5.00,"notes":"Site access board mats"},
]
