"""PlumbingAgent — 100 items"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Water Supply Piping ────────────────────────────────────
    {"id":uid(),"name":"PEX-A Water Supply Pipe - 1/2 Inch Per LF","category":"Plumbing","unit":"LF","laborCost":1.25,"materialCost":0.65,"equipmentCost":0.05,"notes":"Uponor PEX-A hot or cold"},
    {"id":uid(),"name":"PEX-A Water Supply Pipe - 3/4 Inch Per LF","category":"Plumbing","unit":"LF","laborCost":1.45,"materialCost":0.88,"equipmentCost":0.05,"notes":"Main run 3/4 PEX-A"},
    {"id":uid(),"name":"PEX-A Water Supply Pipe - 1 Inch Per LF","category":"Plumbing","unit":"LF","laborCost":1.65,"materialCost":1.25,"equipmentCost":0.05,"notes":"1 inch main line PEX-A"},
    {"id":uid(),"name":"PEX-B Water Supply Pipe - 1/2 Inch Per LF","category":"Plumbing","unit":"LF","laborCost":1.15,"materialCost":0.48,"equipmentCost":0.04,"notes":"Economy PEX-B crimp system"},
    {"id":uid(),"name":"Copper Pipe - 1/2 Inch Type L Per LF","category":"Plumbing","unit":"LF","laborCost":1.85,"materialCost":1.85,"equipmentCost":0.10,"notes":"Type L copper sweat"},
    {"id":uid(),"name":"Copper Pipe - 3/4 Inch Type L Per LF","category":"Plumbing","unit":"LF","laborCost":2.10,"materialCost":2.65,"equipmentCost":0.12,"notes":"3/4 in Type L copper"},
    {"id":uid(),"name":"Copper Pipe - 1 Inch Type L Per LF","category":"Plumbing","unit":"LF","laborCost":2.35,"materialCost":3.85,"equipmentCost":0.15,"notes":"1 inch main line copper"},
    {"id":uid(),"name":"CPVC Supply Pipe - 1/2 Inch Per LF","category":"Plumbing","unit":"LF","laborCost":0.95,"materialCost":0.38,"equipmentCost":0.03,"notes":"CPVC cemented connections"},
    {"id":uid(),"name":"CPVC Supply Pipe - 3/4 Inch Per LF","category":"Plumbing","unit":"LF","laborCost":1.05,"materialCost":0.55,"equipmentCost":0.03,"notes":"3/4 CPVC main run"},
    {"id":uid(),"name":"Manifold PEX Homerun System Install","category":"Plumbing","unit":"EA","laborCost":285.00,"materialCost":185.00,"equipmentCost":10.00,"notes":"Multi-port manifold with individual PEX runs"},
    # ── DWV Piping ─────────────────────────────────────────────
    {"id":uid(),"name":"3 Inch PVC Schedule 40 DWV - Per LF","category":"Plumbing","unit":"LF","laborCost":2.25,"materialCost":1.85,"equipmentCost":0.08,"notes":"Drain waste vent 3 in PVC"},
    {"id":uid(),"name":"4 Inch PVC Schedule 40 DWV - Per LF","category":"Plumbing","unit":"LF","laborCost":2.85,"materialCost":2.45,"equipmentCost":0.10,"notes":"Main building drain 4 in PVC"},
    {"id":uid(),"name":"2 Inch PVC Schedule 40 DWV - Per LF","category":"Plumbing","unit":"LF","laborCost":1.85,"materialCost":1.25,"equipmentCost":0.06,"notes":"Branch drain 2 in"},
    {"id":uid(),"name":"1-1/2 Inch PVC DWV - Per LF","category":"Plumbing","unit":"LF","laborCost":1.65,"materialCost":0.95,"equipmentCost":0.05,"notes":"Sink and tub drain piping"},
    {"id":uid(),"name":"3 Inch ABS DWV Pipe - Per LF","category":"Plumbing","unit":"LF","laborCost":2.25,"materialCost":1.65,"equipmentCost":0.08,"notes":"ABS cement joint drain"},
    {"id":uid(),"name":"4 Inch Cast Iron Bell and Spigot - Per LF","category":"Plumbing","unit":"LF","laborCost":3.50,"materialCost":5.50,"equipmentCost":0.20,"notes":"Heavy cast iron main drain"},
    {"id":uid(),"name":"4 Inch No-Hub Cast Iron - Per LF","category":"Plumbing","unit":"LF","laborCost":3.25,"materialCost":5.00,"equipmentCost":0.18,"notes":"No-hub coupling DWV"},
    {"id":uid(),"name":"Plumbing Vent Stack - 2 Inch Through Roof","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":85.00,"equipmentCost":10.00,"notes":"Roof penetration with flashing"},
    {"id":uid(),"name":"Air Admittance Valve Install","category":"Plumbing","unit":"EA","laborCost":45.00,"materialCost":28.00,"equipmentCost":2.00,"notes":"AAV instead of full vent"},
    # ── Fixtures — Toilets ─────────────────────────────────────
    {"id":uid(),"name":"Toilet Install - Floor Mount - 2 Piece","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Standard 2-piece toilet"},
    {"id":uid(),"name":"Toilet Install - Floor Mount - 1 Piece","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":385.00,"equipmentCost":5.00,"notes":"One-piece toilet premium"},
    {"id":uid(),"name":"Bidet Install - Standalone","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":385.00,"equipmentCost":5.00,"notes":"Bidet with supply and drain"},
    {"id":uid(),"name":"Toilet Flange Install - PVC","category":"Plumbing","unit":"EA","laborCost":65.00,"materialCost":28.00,"equipmentCost":2.00,"notes":"PVC closet flange at slab"},
    {"id":uid(),"name":"Wax Ring and Closet Bolt Set","category":"Plumbing","unit":"EA","laborCost":25.00,"materialCost":8.50,"equipmentCost":0.50,"notes":"Standard wax ring set"},
    # ── Fixtures — Sinks and Lavatories ───────────────────────
    {"id":uid(),"name":"Bathroom Vanity Lavatory Install - Drop In","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":85.00,"equipmentCost":5.00,"notes":"Drop-in or undermount lav"},
    {"id":uid(),"name":"Pedestal Sink Install","category":"Plumbing","unit":"EA","laborCost":145.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Pedestal lav with P-trap"},
    {"id":uid(),"name":"Kitchen Sink Install - Double Bowl","category":"Plumbing","unit":"EA","laborCost":145.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Double bowl drop-in or undermount"},
    {"id":uid(),"name":"Kitchen Sink Install - Single Bowl","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":145.00,"equipmentCost":5.00,"notes":"Single bowl kitchen sink"},
    {"id":uid(),"name":"Utility Sink Install - Laundry Tub","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":125.00,"equipmentCost":5.00,"notes":"Laundry room utility sink"},
    {"id":uid(),"name":"Bar Sink Install - Small","category":"Plumbing","unit":"EA","laborCost":115.00,"materialCost":95.00,"equipmentCost":5.00,"notes":"15x15 bar sink w/ faucet"},
    # ── Fixtures — Tubs and Showers ────────────────────────────
    {"id":uid(),"name":"Alcove Bathtub Install - 5 Ft Standard","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":285.00,"equipmentCost":15.00,"notes":"Standard alcove tub and drain"},
    {"id":uid(),"name":"Freestanding Soaking Tub Install","category":"Plumbing","unit":"EA","laborCost":285.00,"materialCost":850.00,"equipmentCost":25.00,"notes":"Freestanding tub floor fill"},
    {"id":uid(),"name":"Walk-In Shower Pan Install - Tile","category":"Plumbing","unit":"EA","laborCost":285.00,"materialCost":185.00,"equipmentCost":15.00,"notes":"Mortar bed shower pan"},
    {"id":uid(),"name":"Prefab Shower Pan Install - Acrylic","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":225.00,"equipmentCost":10.00,"notes":"Prefab acrylic shower base"},
    {"id":uid(),"name":"Shower Valve Install - Thermostatic","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Pressure balance thermostatic valve"},
    {"id":uid(),"name":"Shower Head and Arm Install","category":"Plumbing","unit":"EA","laborCost":45.00,"materialCost":65.00,"equipmentCost":2.00,"notes":"Standard shower head set"},
    {"id":uid(),"name":"Rain Shower Head Install - Ceiling Mount","category":"Plumbing","unit":"EA","laborCost":85.00,"materialCost":145.00,"equipmentCost":5.00,"notes":"Ceiling mount rain head"},
    # ── Faucets ────────────────────────────────────────────────
    {"id":uid(),"name":"Kitchen Faucet Install - Standard","category":"Plumbing","unit":"EA","laborCost":75.00,"materialCost":85.00,"equipmentCost":2.00,"notes":"Standard pull-down kitchen faucet"},
    {"id":uid(),"name":"Bathroom Faucet Install - Single Handle","category":"Plumbing","unit":"EA","laborCost":65.00,"materialCost":65.00,"equipmentCost":2.00,"notes":"Single hole lavatory faucet"},
    {"id":uid(),"name":"Bathroom Faucet Install - Widespread","category":"Plumbing","unit":"EA","laborCost":85.00,"materialCost":125.00,"equipmentCost":2.00,"notes":"Widespread 3-hole lavatory faucet"},
    {"id":uid(),"name":"Tub Spout and Valve Trim Kit Install","category":"Plumbing","unit":"EA","laborCost":55.00,"materialCost":75.00,"equipmentCost":2.00,"notes":"Tub spout and diverter trim"},
    {"id":uid(),"name":"Exterior Hose Bib Install - Frost Free","category":"Plumbing","unit":"EA","laborCost":85.00,"materialCost":35.00,"equipmentCost":3.00,"notes":"Anti-siphon frost-free hose bib"},
    # ── Water Heaters ──────────────────────────────────────────
    {"id":uid(),"name":"Water Heater - 40 Gallon Gas Install","category":"Plumbing","unit":"EA","laborCost":225.00,"materialCost":585.00,"equipmentCost":15.00,"notes":"Natural gas 40 gal traditional"},
    {"id":uid(),"name":"Water Heater - 50 Gallon Gas Install","category":"Plumbing","unit":"EA","laborCost":245.00,"materialCost":685.00,"equipmentCost":15.00,"notes":"Natural gas 50 gal traditional"},
    {"id":uid(),"name":"Water Heater - 40 Gallon Electric Install","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":485.00,"equipmentCost":10.00,"notes":"Electric 40 gal tank"},
    {"id":uid(),"name":"Tankless Water Heater - Gas Install","category":"Plumbing","unit":"EA","laborCost":485.00,"materialCost":985.00,"equipmentCost":25.00,"notes":"On-demand gas tankless"},
    {"id":uid(),"name":"Tankless Water Heater - Electric Install","category":"Plumbing","unit":"EA","laborCost":285.00,"materialCost":485.00,"equipmentCost":15.00,"notes":"Point of use electric tankless"},
    {"id":uid(),"name":"Water Heater Expansion Tank Install","category":"Plumbing","unit":"EA","laborCost":65.00,"materialCost":45.00,"equipmentCost":2.00,"notes":"Required with closed system"},
    {"id":uid(),"name":"Water Heater T&P Relief Valve Install","category":"Plumbing","unit":"EA","laborCost":45.00,"materialCost":22.00,"equipmentCost":1.00,"notes":"Temperature pressure relief valve"},
    # ── Gas Piping ─────────────────────────────────────────────
    {"id":uid(),"name":"Black Iron Gas Pipe - 3/4 Inch Per LF","category":"Plumbing","unit":"LF","laborCost":3.50,"materialCost":2.25,"equipmentCost":0.15,"notes":"Schedule 40 black iron pipe"},
    {"id":uid(),"name":"Black Iron Gas Pipe - 1 Inch Per LF","category":"Plumbing","unit":"LF","laborCost":4.25,"materialCost":3.50,"equipmentCost":0.18,"notes":"1 inch main gas distribution"},
    {"id":uid(),"name":"CSST Gas Pipe - 3/4 Inch Per LF","category":"Plumbing","unit":"LF","laborCost":2.85,"materialCost":3.25,"equipmentCost":0.10,"notes":"Corrugated stainless steel tube"},
    {"id":uid(),"name":"Gas Appliance Connector - Flex 18 Inch","category":"Plumbing","unit":"EA","laborCost":35.00,"materialCost":18.00,"equipmentCost":1.00,"notes":"Appliance flex connector"},
    {"id":uid(),"name":"Gas Shutoff Valve Install - 1/2 Inch","category":"Plumbing","unit":"EA","laborCost":45.00,"materialCost":18.00,"equipmentCost":2.00,"notes":"Ball valve at appliance"},
    {"id":uid(),"name":"Gas Pressure Test - Per System","category":"Plumbing","unit":"EA","laborCost":95.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"30-min pressure hold test"},
    # ── Specialty Systems ──────────────────────────────────────
    {"id":uid(),"name":"Water Softener Install - Whole House","category":"Plumbing","unit":"EA","laborCost":285.00,"materialCost":850.00,"equipmentCost":15.00,"notes":"Ion exchange water softener"},
    {"id":uid(),"name":"Reverse Osmosis Filter Install - Under Sink","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":285.00,"equipmentCost":5.00,"notes":"5-stage RO drinking filter"},
    {"id":uid(),"name":"Backflow Preventer Install - 3/4 Inch","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":85.00,"equipmentCost":5.00,"notes":"RPZ or DCVA backflow device"},
    {"id":uid(),"name":"Sump Pump Install - 1/3 HP Submersible","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":185.00,"equipmentCost":10.00,"notes":"Pedestal or submersible sump"},
    {"id":uid(),"name":"Sump Pump Install - Battery Backup","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":285.00,"equipmentCost":5.00,"notes":"Battery backup sump system"},
    {"id":uid(),"name":"Pressure Reducing Valve Install","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":85.00,"equipmentCost":5.00,"notes":"PRV to limit supply pressure"},
    {"id":uid(),"name":"Main Water Shutoff Valve Install","category":"Plumbing","unit":"EA","laborCost":85.00,"materialCost":45.00,"equipmentCost":3.00,"notes":"Full port ball valve at entry"},
    {"id":uid(),"name":"Garbage Disposal Install - 1/2 HP","category":"Plumbing","unit":"EA","laborCost":85.00,"materialCost":95.00,"equipmentCost":2.00,"notes":"Standard disposal install"},
    {"id":uid(),"name":"Dishwasher Plumbing Rough-In","category":"Plumbing","unit":"EA","laborCost":85.00,"materialCost":35.00,"equipmentCost":3.00,"notes":"Supply drain and air gap"},
    {"id":uid(),"name":"Washing Machine Plumbing Rough-In","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":55.00,"equipmentCost":3.00,"notes":"Hot cold supply and drain"},
    {"id":uid(),"name":"Plumbing Rough-In - Per Fixture","category":"Plumbing","unit":"EA","laborCost":285.00,"materialCost":85.00,"equipmentCost":8.00,"notes":"Full rough-in per fixture"},
    {"id":uid(),"name":"Plumbing Trim-Out - Per Fixture","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":25.00,"equipmentCost":3.00,"notes":"Final connections per fixture"},
    {"id":uid(),"name":"Plumbing Permit - Residential New Const","category":"Plumbing","unit":"EA","laborCost":0.00,"materialCost":225.00,"equipmentCost":0.00,"notes":"Permit fee for new construction"},
    {"id":uid(),"name":"Drain Cleaning - Machine Rodding","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":35.00,"notes":"Electric snake drain clearing"},
    {"id":uid(),"name":"Camera Inspection - Drain Line","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":65.00,"notes":"Video camera line inspection"},
    {"id":uid(),"name":"Hydro Jetting - Main Sewer Line","category":"Plumbing","unit":"EA","laborCost":285.00,"materialCost":0.00,"equipmentCost":95.00,"notes":"High pressure water jetting"},
    {"id":uid(),"name":"Pipe Freeze Repair - Burst Pipe","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":65.00,"equipmentCost":10.00,"notes":"Locate cut and repair frozen pipe"},
    {"id":uid(),"name":"Water Meter Service Disconnect","category":"Plumbing","unit":"EA","laborCost":85.00,"materialCost":18.00,"equipmentCost":5.00,"notes":"Shut off at meter box"},
    {"id":uid(),"name":"Pot Filler Faucet Install - Over Range","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Wall mount pot filler"},
    {"id":uid(),"name":"Recirculation Pump Install - Hot Water","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":245.00,"equipmentCost":10.00,"notes":"Under-sink demand recirculation"},
    {"id":uid(),"name":"Commercial Urinal Install - Wall Mount EA","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":285.00,"equipmentCost":10.00,"notes":"Vitreous china urinal"},
    {"id":uid(),"name":"Commercial Sensor Faucet - Hands Free EA","category":"Plumbing","unit":"EA","laborCost":85.00,"materialCost":185.00,"equipmentCost":2.00,"notes":"Battery or hardwire sensor tap"},
    {"id":uid(),"name":"Drinking Fountain - Single Level EA","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":350.00,"equipmentCost":15.00,"notes":"Wall mount drinking fountain"},
    {"id":uid(),"name":"Bottle Filling Station - Retrofit EA","category":"Plumbing","unit":"EA","laborCost":145.00,"materialCost":650.00,"equipmentCost":15.00,"notes":"Add-on bottle filler for fountain"},
    {"id":uid(),"name":"Grease Interceptor - 50 Gallon EA","category":"Plumbing","unit":"EA","laborCost":285.00,"materialCost":450.00,"equipmentCost":25.00,"notes":"Kitchen waste grease trap"},
    {"id":uid(),"name":"Septic Tank - 1000 Gallon Concrete EA","category":"Plumbing","unit":"EA","laborCost":1250.00,"materialCost":1850.00,"equipmentCost":850.00,"notes":"Single chamber septic tank"},
    {"id":uid(),"name":"Septic Drain Field - Leach Line Per LF","category":"Plumbing","unit":"LF","laborCost":12.00,"materialCost":8.50,"equipmentCost":8.50,"notes":"Perforated leach line with gravel"},
    {"id":uid(),"name":"Sewer Ejector Pump - 1/2 HP EA","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":285.00,"equipmentCost":15.00,"notes":"Basement bathroom waste pump"},
    {"id":uid(),"name":"Grinder Pump - 2 HP Submersible EA","category":"Plumbing","unit":"EA","laborCost":225.00,"materialCost":850.00,"equipmentCost":25.00,"notes":"Heavy duty sewage grinder"},
    {"id":uid(),"name":"Water Main Connection - 1 Inch Copper Per LF","category":"Plumbing","unit":"LF","laborCost":18.00,"materialCost":8.50,"equipmentCost":12.00,"notes":"Street-to-house water supply"},
    {"id":uid(),"name":"Sewer Main Connection - 4 Inch PVC Per LF","category":"Plumbing","unit":"LF","laborCost":15.00,"materialCost":3.50,"equipmentCost":18.00,"notes":"House-to-street sewer line"},
    {"id":uid(),"name":"Yard Hydrant - Frost Proof EA","category":"Plumbing","unit":"EA","laborCost":85.00,"materialCost":65.00,"equipmentCost":15.00,"notes":"Freezeproof exterior yard hydrant"},
    {"id":uid(),"name":"Irrigation Backflow - 1 Inch PVB EA","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":85.00,"equipmentCost":5.00,"notes":"Pressure vacuum breaker"},
    {"id":uid(),"name":"Gas Water Heater - 50 Gal High Efficiency EA","category":"Plumbing","unit":"EA","laborCost":285.00,"materialCost":650.00,"equipmentCost":25.00,"notes":"Power vent natural gas heater"},
    {"id":uid(),"name":"Electric Water Heater - 50 Gal Heat Pump EA","category":"Plumbing","unit":"EA","laborCost":285.00,"materialCost":1250.00,"equipmentCost":25.00,"notes":"Hybrid heat pump efficiency"},
    {"id":uid(),"name":"Water Softener - Twin Tank High Flow EA","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":1150.00,"equipmentCost":15.00,"notes":"Continuous soft water system"},
    {"id":uid(),"name":"Whole House Water Filter - Sediment EA","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":45.00,"equipmentCost":5.00,"notes":"Spin-down or cartridge sediment"},
    {"id":uid(),"name":"Acid Neutralizer System - Calcite EA","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":650.00,"equipmentCost":15.00,"notes":"Filter to raise well water pH"},
    {"id":uid(),"name":"Iron Filter - Air Injection EA","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":850.00,"equipmentCost":15.00,"notes":"Birm or Manganese Greensand"},
    {"id":uid(),"name":"Well Pump - 1/2 HP Submersible EA","category":"Plumbing","unit":"EA","laborCost":450.00,"materialCost":650.00,"equipmentCost":125.00,"notes":"Deep well submersible pump"},
    {"id":uid(),"name":"Pressure Tank - 20 Gallon Vertical EA","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Well system expansion tank"},
    {"id":uid(),"name":"Well Inspection and Water Quality Test","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":125.00,"equipmentCost":15.00,"notes":"Lab analyzed water safety test"},
    {"id":uid(),"name":"Gas Leak Detection and Pressure Test","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":45.00,"notes":"Electronic leak scan and manom"},
    {"id":uid(),"name":"Professional Plumbing Consult - Per Visit","category":"Plumbing","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"Expert system assessment"},
]
