"""DeckAgent — 100 items"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Footings and Foundation ────────────────────────────────
    {"id":uid(),"name":"Deck Concrete Footing - 12x12x12 Poured","category":"Deck","unit":"EA","laborCost":85.00,"materialCost":65.00,"equipmentCost":15.00,"notes":"Hand dug 12 in poured footing"},
    {"id":uid(),"name":"Deck Concrete Footing - 16x16x24 Poured","category":"Deck","unit":"EA","laborCost":125.00,"materialCost":95.00,"equipmentCost":18.00,"notes":"Large footing for tall post"},
    {"id":uid(),"name":"Deck Helical Pier - 6 Inch Install","category":"Deck","unit":"EA","laborCost":225.00,"materialCost":185.00,"equipmentCost":95.00,"notes":"Helical pier with cap plate"},
    {"id":uid(),"name":"Deck Tube Form Footing - 12 In Sono Tube","category":"Deck","unit":"EA","laborCost":95.00,"materialCost":55.00,"equipmentCost":12.00,"notes":"12 in tube form below frost"},
    {"id":uid(),"name":"Deck Ground Contact Post Base - Retrofit","category":"Deck","unit":"EA","laborCost":25.00,"materialCost":18.00,"equipmentCost":2.00,"notes":"Adjustable post base anchor"},
    # ── Post and Structure ─────────────────────────────────────
    {"id":uid(),"name":"4x4 Pressure Treated Post Install - 8 Ft","category":"Deck","unit":"EA","laborCost":45.00,"materialCost":28.00,"equipmentCost":2.00,"notes":"4x4 PT post plumb and brace"},
    {"id":uid(),"name":"6x6 Pressure Treated Post Install - 10 Ft","category":"Deck","unit":"EA","laborCost":65.00,"materialCost":55.00,"equipmentCost":3.00,"notes":"6x6 PT heavy deck post"},
    {"id":uid(),"name":"Deck Beam - 2-Ply 2x10 PT - Per LF","category":"Deck","unit":"LF","laborCost":5.50,"materialCost":4.25,"equipmentCost":0.25,"notes":"Built-up 2-ply beam"},
    {"id":uid(),"name":"Deck Beam - 3-Ply 2x12 PT - Per LF","category":"Deck","unit":"LF","laborCost":7.50,"materialCost":6.50,"equipmentCost":0.35,"notes":"Heavy built-up beam"},
    {"id":uid(),"name":"Deck Ledger Board - 2x10 PT Bolted","category":"Deck","unit":"LF","laborCost":8.50,"materialCost":4.25,"equipmentCost":0.50,"notes":"Ledger with lag bolts per code"},
    {"id":uid(),"name":"Deck Ledger Joist Hanger Install","category":"Deck","unit":"EA","laborCost":5.50,"materialCost":3.50,"equipmentCost":0.25,"notes":"Per hanger Simpson or USP"},
    # ── Joists and Frame ───────────────────────────────────────
    {"id":uid(),"name":"Deck Joist 2x8 PT - 16 OC - Per LF","category":"Deck","unit":"LF","laborCost":1.65,"materialCost":1.55,"equipmentCost":0.10,"notes":"Pressure treated joist"},
    {"id":uid(),"name":"Deck Joist 2x10 PT - 16 OC - Per LF","category":"Deck","unit":"LF","laborCost":1.85,"materialCost":2.10,"equipmentCost":0.10,"notes":"Heavy joist 2x10 PT"},
    {"id":uid(),"name":"Deck Rim Joist - Double 2x10 PT","category":"Deck","unit":"LF","laborCost":3.50,"materialCost":4.25,"equipmentCost":0.15,"notes":"Perimeter rim joist"},
    {"id":uid(),"name":"Deck Blocking PT - Mid-Span","category":"Deck","unit":"EA","laborCost":8.50,"materialCost":3.50,"equipmentCost":0.25,"notes":"Joist block at mid-span per pair"},
    # ── Decking Surface ────────────────────────────────────────
    {"id":uid(),"name":"Pressure Treated Decking - 5/4x6 Per SF","category":"Deck","unit":"SF","laborCost":1.65,"materialCost":1.85,"equipmentCost":0.10,"notes":"Standard 5/4x6 PT decking"},
    {"id":uid(),"name":"Pressure Treated Decking - 2x6 Per SF","category":"Deck","unit":"SF","laborCost":1.85,"materialCost":2.25,"equipmentCost":0.10,"notes":"Thicker 2x6 PT decking"},
    {"id":uid(),"name":"Cedar Decking - 5/4x6 Clear Per SF","category":"Deck","unit":"SF","laborCost":2.25,"materialCost":3.85,"equipmentCost":0.10,"notes":"Clear cedar deck surface"},
    {"id":uid(),"name":"Redwood Decking - 5/4x6 Per SF","category":"Deck","unit":"SF","laborCost":2.25,"materialCost":4.85,"equipmentCost":0.10,"notes":"Premium redwood deck surface"},
    {"id":uid(),"name":"Ipe Hardwood Deck - 1x4 Per SF","category":"Deck","unit":"SF","laborCost":3.25,"materialCost":6.50,"equipmentCost":0.15,"notes":"Brazilian hardwood deck"},
    {"id":uid(),"name":"Composite Decking - Economy Per SF","category":"Deck","unit":"SF","laborCost":2.25,"materialCost":3.85,"equipmentCost":0.12,"notes":"Low-end composite deck board"},
    {"id":uid(),"name":"Composite Decking - Mid Grade Per SF","category":"Deck","unit":"SF","laborCost":2.50,"materialCost":5.25,"equipmentCost":0.12,"notes":"Trex Enhance or similar"},
    {"id":uid(),"name":"Composite Decking - Premium Per SF","category":"Deck","unit":"SF","laborCost":2.75,"materialCost":7.50,"equipmentCost":0.15,"notes":"Trex Transcend or TimberTech"},
    {"id":uid(),"name":"PVC Decking - Azek Per SF","category":"Deck","unit":"SF","laborCost":2.75,"materialCost":8.50,"equipmentCost":0.15,"notes":"Cellular PVC board no maintenance"},
    {"id":uid(),"name":"Deck Fascia Board - Composite 12 Ft","category":"Deck","unit":"LF","laborCost":3.50,"materialCost":4.50,"equipmentCost":0.15,"notes":"Fascia wrap on rim joist"},
    {"id":uid(),"name":"Deck Board Hidden Fastener System","category":"Deck","unit":"SF","laborCost":0.35,"materialCost":0.28,"equipmentCost":0.02,"notes":"Grooved board hidden clip system"},
    # ── Railings ──────────────────────────────────────────────
    {"id":uid(),"name":"Wood Railing - 2x4 Top and Bottom Rail","category":"Deck","unit":"LF","laborCost":18.00,"materialCost":12.00,"equipmentCost":0.50,"notes":"Standard PT wood rail system"},
    {"id":uid(),"name":"Composite Railing System - Trex Signature","category":"Deck","unit":"LF","laborCost":22.00,"materialCost":38.00,"equipmentCost":0.75,"notes":"Composite rail system"},
    {"id":uid(),"name":"Aluminum Railing System - Powder Coated","category":"Deck","unit":"LF","laborCost":22.00,"materialCost":32.00,"equipmentCost":0.75,"notes":"Aluminum extrusion rail"},
    {"id":uid(),"name":"Cable Railing System - Stainless","category":"Deck","unit":"LF","laborCost":28.00,"materialCost":45.00,"equipmentCost":1.00,"notes":"1/8 in cable stainless steel"},
    {"id":uid(),"name":"Glass Panel Railing System","category":"Deck","unit":"LF","laborCost":45.00,"materialCost":85.00,"equipmentCost":1.50,"notes":"Tempered glass panel railing"},
    {"id":uid(),"name":"Deck Railing Post Install - 4x4","category":"Deck","unit":"EA","laborCost":35.00,"materialCost":12.00,"equipmentCost":1.00,"notes":"Bolted railing post on rim"},
    {"id":uid(),"name":"Deck Railing Baluster - 36 Inch Spindle","category":"Deck","unit":"EA","laborCost":5.50,"materialCost":2.85,"equipmentCost":0.15,"notes":"Per baluster PT or composite"},
    # ── Stairs ────────────────────────────────────────────────
    {"id":uid(),"name":"Deck Stair Stringer - PT 2x12","category":"Deck","unit":"EA","laborCost":65.00,"materialCost":38.00,"equipmentCost":2.00,"notes":"Cut stringer per flight"},
    {"id":uid(),"name":"Deck Stair Tread - 5/4x12 PT","category":"Deck","unit":"EA","laborCost":18.00,"materialCost":8.50,"equipmentCost":0.50,"notes":"Per stair tread board"},
    {"id":uid(),"name":"Deck Stair Tread - Composite","category":"Deck","unit":"EA","laborCost":18.00,"materialCost":22.00,"equipmentCost":0.50,"notes":"Composite stair tread"},
    {"id":uid(),"name":"Deck Stair Landing - 4x4 PT","category":"Deck","unit":"EA","laborCost":225.00,"materialCost":145.00,"equipmentCost":10.00,"notes":"4x4 platform landing"},
    {"id":uid(),"name":"Deck Stair Handrail - Per LF","category":"Deck","unit":"LF","laborCost":8.50,"materialCost":5.50,"equipmentCost":0.25,"notes":"Graspable handrail at stairs"},
    # ── Hardware and Fasteners ─────────────────────────────────
    {"id":uid(),"name":"Deck Structural Connector - Beam to Post","category":"Deck","unit":"EA","laborCost":18.00,"materialCost":12.00,"equipmentCost":0.50,"notes":"Post cap connector"},
    {"id":uid(),"name":"Deck Lag Screw - 1/2 x 5 Inch Set","category":"Deck","unit":"EA","laborCost":3.50,"materialCost":1.25,"equipmentCost":0.25,"notes":"Ledger attachment lag set"},
    {"id":uid(),"name":"Deck Screw Supply - Star Drive Stainless","category":"Deck","unit":"EA","laborCost":0.00,"materialCost":45.00,"equipmentCost":0.00,"notes":"1 lb stainless deck screws"},
    {"id":uid(),"name":"Post Anchor - Adjustable Column Base","category":"Deck","unit":"EA","laborCost":22.00,"materialCost":18.00,"equipmentCost":1.00,"notes":"ABU post base adjustable"},
    # ── Lighting and Accessories ───────────────────────────────
    {"id":uid(),"name":"Deck Post Cap Light Install - LED","category":"Deck","unit":"EA","laborCost":28.00,"materialCost":38.00,"equipmentCost":1.00,"notes":"Solar or low voltage post cap"},
    {"id":uid(),"name":"Deck Stair Riser Light - LED","category":"Deck","unit":"EA","laborCost":22.00,"materialCost":25.00,"equipmentCost":0.50,"notes":"LED light at each step riser"},
    {"id":uid(),"name":"Deck String Light Outlet Install","category":"Deck","unit":"EA","laborCost":65.00,"materialCost":25.00,"equipmentCost":2.00,"notes":"GFCI outlet for string lights"},
    {"id":uid(),"name":"Deck Privacy Screen - Lattice","category":"Deck","unit":"SF","laborCost":2.50,"materialCost":1.85,"equipmentCost":0.10,"notes":"Lattice screen panel on frame"},
    {"id":uid(),"name":"Deck Privacy Screen - Composite Boards","category":"Deck","unit":"SF","laborCost":3.50,"materialCost":4.50,"equipmentCost":0.12,"notes":"Composite privacy wall"},
    {"id":uid(),"name":"Pergola Frame Install - Attached","category":"Deck","unit":"SF","laborCost":4.50,"materialCost":5.50,"equipmentCost":0.25,"notes":"PT or cedar pergola frame"},
    {"id":uid(),"name":"Deck Planters Built-In - Per Linear Ft","category":"Deck","unit":"LF","laborCost":28.00,"materialCost":18.00,"equipmentCost":1.00,"notes":"Pressure treated planter box"},
    {"id":uid(),"name":"Deck Bench Built-In","category":"Deck","unit":"LF","laborCost":22.00,"materialCost":12.00,"equipmentCost":0.75,"notes":"Built-in seating bench"},
    # ── Misc and Demo ─────────────────────────────────────────
    {"id":uid(),"name":"Old Deck Demolition - Per SF","category":"Deck","unit":"SF","laborCost":1.25,"materialCost":0.00,"equipmentCost":0.35,"notes":"Demo and haul old deck"},
    {"id":uid(),"name":"Deck Waterproofing Below - Kayak System","category":"Deck","unit":"SF","laborCost":2.85,"materialCost":3.25,"equipmentCost":0.25,"notes":"Underdeck waterproofing system"},
    {"id":uid(),"name":"Deck Paint or Stain - Per SF","category":"Deck","unit":"SF","laborCost":0.55,"materialCost":0.28,"equipmentCost":0.04,"notes":"Deck surface solid or semi-trans"},
    {"id":uid(),"name":"Deck Board Replacement Only Per SF","category":"Deck","unit":"SF","laborCost":1.25,"materialCost":1.85,"equipmentCost":0.10,"notes":"Replace worn decking boards"},
    {"id":uid(),"name":"Deck Inspection and Permit","category":"Deck","unit":"EA","laborCost":0.00,"materialCost":225.00,"equipmentCost":0.00,"notes":"Building permit for new deck"},
    {"id":uid(),"name":"Deck Structural Inspection","category":"Deck","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"Engineer or contractor inspection"},
    {"id":uid(),"name":"Deck Joist Tape - Flashing Tape Per LF","category":"Deck","unit":"LF","laborCost":0.25,"materialCost":0.45,"equipmentCost":0.01,"notes":"Joist Tape on top of joist"},
    {"id":uid(),"name":"Ipe Wood Decking - Exotic SF","category":"Deck","unit":"SF","laborCost":8.50,"materialCost":15.00,"equipmentCost":0.50,"notes":"Premium Brazilian walnut"},
    {"id":uid(),"name":"Tigerwood Decking - Exotic SF","category":"Deck","unit":"SF","laborCost":7.50,"materialCost":12.00,"equipmentCost":0.50,"notes":"Premium Goncalo Alves"},
    {"id":uid(),"name":"Cumaru Wood Decking - Exotic SF","category":"Deck","unit":"SF","laborCost":7.50,"materialCost":11.50,"equipmentCost":0.45,"notes":"Premium Brazilian teak"},
    {"id":uid(),"name":"Garapa Wood Decking - Exotic SF","category":"Deck","unit":"SF","laborCost":7.25,"materialCost":9.50,"equipmentCost":0.45,"notes":"Brazilian ash decking"},
    {"id":uid(),"name":"Teak Wood Decking - Premium SF","category":"Deck","unit":"SF","laborCost":12.00,"materialCost":35.00,"equipmentCost":0.75,"notes":"Natural premium teak"},
    {"id":uid(),"name":"Cypress Wood Decking - Natural SF","category":"Deck","unit":"SF","laborCost":4.50,"materialCost":6.50,"equipmentCost":0.15,"notes":"Rot-resistant natural cypress"},
    {"id":uid(),"name":"Redwood Decking - Premium Grade SF","category":"Deck","unit":"SF","laborCost":5.50,"materialCost":8.50,"equipmentCost":0.20,"notes":"California redwood heartwood"},
    {"id":uid(),"name":"Composite Decking - Capped Polymer SF","category":"Deck","unit":"SF","laborCost":4.50,"materialCost":12.50,"equipmentCost":0.15,"notes":"Trex Transcend or equivalent"},
    {"id":uid(),"name":"Composite Decking - Wood Plastic SF","category":"Deck","unit":"SF","laborCost":3.85,"materialCost":8.50,"equipmentCost":0.12,"notes":"Standard WPC composite"},
    {"id":uid(),"name":"Aluminum Decking - Water-Tight SF","category":"Deck","unit":"SF","laborCost":6.50,"materialCost":18.00,"equipmentCost":0.55,"notes":"Dry-deck aluminum system"},
    {"id":uid(),"name":"Vinyl Decking - Multi-Layer SF","category":"Deck","unit":"SF","laborCost":4.50,"materialCost":9.50,"equipmentCost":0.15,"notes":"Azek or similar PVC decking"},
    {"id":uid(),"name":"Cellular PVC Decking - Solid SF","category":"Deck","unit":"SF","laborCost":4.50,"materialCost":10.50,"equipmentCost":0.15,"notes":"Premium solid PVC decking"},
    {"id":uid(),"name":"Deck Framing - Douglas Fir PT SF","category":"Deck","unit":"SF","laborCost":2.25,"materialCost":1.85,"equipmentCost":0.35,"notes":"Standard PT framing setup"},
    {"id":uid(),"name":"Deck Framing - Ground Contact PT SF","category":"Deck","unit":"SF","laborCost":2.50,"materialCost":2.25,"equipmentCost":0.45,"notes":"Heavy duty framing at grade"},
    {"id":uid(),"name":"Deck Framing - Steel Joist System SF","category":"Deck","unit":"SF","laborCost":6.50,"materialCost":12.50,"equipmentCost":1.25,"notes":"Structural steel deck frame"},
    {"id":uid(),"name":"Deck Framing - Rim Joist Double-Up LF","category":"Deck","unit":"LF","laborCost":4.50,"materialCost":2.50,"equipmentCost":0.50,"notes":"Reinforced perimeter framing"},
    {"id":uid(),"name":"Deck Flashing - Copper Ledger LF","category":"Deck","unit":"LF","laborCost":3.50,"materialCost":12.00,"equipmentCost":0.50,"notes":"Premium copper ledger flashing"},
    {"id":uid(),"name":"Deck Flashing - Hidden Gutter LF","category":"Deck","unit":"LF","laborCost":4.50,"materialCost":8.50,"equipmentCost":0.85,"notes":"Eave gutter for dry-deck"},
    {"id":uid(),"name":"Deck Railing - Cable Railing LF","category":"Deck","unit":"LF","laborCost":12.00,"materialCost":28.00,"equipmentCost":5.00,"notes":"Stainless cable and hardware"},
    {"id":uid(),"name":"Deck Railing - Glass Panel System LF","category":"Deck","unit":"LF","laborCost":18.00,"materialCost":65.00,"equipmentCost":12.00,"notes":"Tempered glass with clips"},
    {"id":uid(),"name":"Deck Railing - Iron Baluster LF","category":"Deck","unit":"LF","laborCost":8.50,"materialCost":12.00,"equipmentCost":2.25,"notes":"Powder coated iron balusters"},
    {"id":uid(),"name":"Deck Railing - Wood Post with Cable LF","category":"Deck","unit":"LF","laborCost":9.50,"materialCost":18.00,"equipmentCost":3.50,"notes":"Hybrid wood/cable railing"},
    {"id":uid(),"name":"Deck Railing - Vinyl Rail Kit LF","category":"Deck","unit":"LF","laborCost":4.50,"materialCost":8.50,"equipmentCost":0.50,"notes":"Standard 6ft white vinyl rail"},
    {"id":uid(),"name":"Deck Railing - Composite Rail Kit LF","category":"Deck","unit":"LF","laborCost":6.50,"materialCost":14.50,"equipmentCost":0.85,"notes":"Matching composite rail system"},
    {"id":uid(),"name":"Deck Stairs - Closed Stringer EA","category":"Deck","unit":"EA","laborCost":125.00,"materialCost":95.00,"equipmentCost":15.00,"notes":"Boxed stringer per step"},
    {"id":uid(),"name":"Deck Stairs - Open Stringer EA","category":"Deck","unit":"EA","laborCost":85.00,"materialCost":65.00,"equipmentCost":10.00,"notes":"Standard cut stringer step"},
    {"id":uid(),"name":"Deck Stairs - Cantilevered Step EA","category":"Deck","unit":"EA","laborCost":185.00,"materialCost":125.00,"equipmentCost":25.00,"notes":"Floating look stair step"},
    {"id":uid(),"name":"Deck Stairs - Spiral Metal Kit EA","category":"Deck","unit":"EA","laborCost":1250.00,"materialCost":3500.00,"equipmentCost":250.00,"notes":"Full spiral staircase install"},
    {"id":uid(),"name":"Deck Landing - Mid-Stair Platform SF","category":"Deck","unit":"SF","laborCost":4.50,"materialCost":3.50,"equipmentCost":1.50,"notes":"Intermediate landing deck"},
    {"id":uid(),"name":"Deck Gate - Child/Pet Safety EA","category":"Deck","unit":"EA","laborCost":85.00,"materialCost":125.00,"equipmentCost":5.00,"notes":"Self-closing safety gate"},
    {"id":uid(),"name":"Deck Gate - Ornate Wood EA","category":"Deck","unit":"EA","laborCost":145.00,"materialCost":285.00,"equipmentCost":10.00,"notes":"Custom decorative wood gate"},
    {"id":uid(),"name":"Deck Curtain - Outdoor Mesh SF","category":"Deck","unit":"SF","laborCost":1.25,"materialCost":3.50,"equipmentCost":0.25,"notes":"Sunshade or privacy curtain"},
    {"id":uid(),"name":"Deck Awning - Retractable Manual EA","category":"Deck","unit":"EA","laborCost":185.00,"materialCost":850.00,"equipmentCost":25.00,"notes":"Manual crank wall awning"},
    {"id":uid(),"name":"Deck Awning - Motorized Smart EA","category":"Deck","unit":"EA","laborCost":285.00,"materialCost":1850.00,"equipmentCost":45.00,"notes":"App controlled power awning"},
    {"id":uid(),"name":"Deck Heater - Wall Mount Infrared EA","category":"Deck","unit":"EA","laborCost":125.00,"materialCost":350.00,"equipmentCost":5.00,"notes":"Direct heat electric infrared"},
    {"id":uid(),"name":"Deck Heater - Portable Propane EA","category":"Deck","unit":"EA","laborCost":0.00,"materialCost":125.00,"equipmentCost":0.00,"notes":"Tall patio gas heater standalone"},
    {"id":uid(),"name":"Deck Fan - Ceiling Exterior Rated EA","category":"Deck","unit":"EA","laborCost":125.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Wet-rated outdoor ceiling fan"},
    {"id":uid(),"name":"Deck Shower - Outdoor Hot/Cold EA","category":"Deck","unit":"EA","laborCost":450.00,"materialCost":350.00,"equipmentCost":25.00,"notes":"Full plumbing outdoor shower"},
    {"id":uid(),"name":"Deck Kitchen - BBQ Island Frame LF","category":"Deck","unit":"LF","laborCost":45.00,"materialCost":65.00,"equipmentCost":5.00,"notes":"Steel stud or PT kitchen frame"},
    {"id":uid(),"name":"Deck Kitchen - Countertop Granite SF","category":"Deck","unit":"SF","laborCost":22.00,"materialCost":65.00,"equipmentCost":15.00,"notes":"Exterior grade granite slab"},
    {"id":uid(),"name":"Deck Kitchen - Sink and Faucet EA","category":"Plumbing","unit":"EA","laborCost":185.00,"materialCost":245.00,"equipmentCost":5.00,"notes":"Under-mount outdoor sink"},
    {"id":uid(),"name":"Deck Storage - Under-Deck Box EA","category":"Deck","unit":"EA","laborCost":85.00,"materialCost":185.00,"equipmentCost":2.00,"notes":"Pre-built outdoor storage box"},
    {"id":uid(),"name":"Deck Skirting - Vinyl Lattice LF","category":"Deck","unit":"LF","laborCost":2.25,"materialCost":1.85,"equipmentCost":0.15,"notes":"Lattice perimeter skirting"},
    {"id":uid(),"name":"Deck Skirting - Stone Veneer SF","category":"Deck","unit":"SF","laborCost":12.00,"materialCost":15.00,"equipmentCost":1.25,"notes":"Solid stone facade skirting"},
    {"id":uid(),"name":"Deck Footing - Diamond Pier EA","category":"Deck","unit":"EA","laborCost":185.00,"materialCost":285.00,"equipmentCost":85.00,"notes":"Post-less pin foundation"},
    {"id":uid(),"name":"Deck Footing - Helical Pile EA","category":"Deck","unit":"EA","laborCost":225.00,"materialCost":450.00,"equipmentCost":185.00,"notes":"Screw-in structural pile"},
    {"id":uid(),"name":"Deck Footing - Sonotube 12 Inch EA","category":"Deck","unit":"EA","laborCost":125.00,"materialCost":65.00,"equipmentCost":45.00,"notes":"Concrete pier in forms"},
    {"id":uid(),"name":"Deck Footing - Big Foot Base EA","category":"Deck","unit":"EA","laborCost":45.00,"materialCost":35.00,"equipmentCost":5.00,"notes":"Plastic spread footing base"},
]
