"""FenceAgent — 100 items"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Wood Fence ────────────────────────────────────────────
    {"id":uid(),"name":"6 Ft Privacy Wood Fence - Dog Ear","category":"Fence","unit":"LF","laborCost":6.50,"materialCost":8.50,"equipmentCost":0.50,"notes":"Standard dog ear board on board"},
    {"id":uid(),"name":"6 Ft Privacy Wood Fence - Board on Board","category":"Fence","unit":"LF","laborCost":7.50,"materialCost":10.00,"equipmentCost":0.50,"notes":"Overlapping board on board"},
    {"id":uid(),"name":"6 Ft Privacy Wood Fence - Horizontal Slat","category":"Fence","unit":"LF","laborCost":8.50,"materialCost":11.00,"equipmentCost":0.50,"notes":"Modern horizontal board privacy"},
    {"id":uid(),"name":"8 Ft Privacy Wood Fence - Dog Ear","category":"Fence","unit":"LF","laborCost":8.50,"materialCost":12.00,"equipmentCost":0.75,"notes":"Tall 8 ft wood privacy"},
    {"id":uid(),"name":"4 Ft Picket Wood Fence - Gothic","category":"Fence","unit":"LF","laborCost":5.50,"materialCost":5.50,"equipmentCost":0.35,"notes":"Traditional gothic picket fence"},
    {"id":uid(),"name":"4 Ft Picket Wood Fence - Flat Top","category":"Fence","unit":"LF","laborCost":5.00,"materialCost":4.85,"equipmentCost":0.35,"notes":"Flat top picket fence"},
    {"id":uid(),"name":"4 Ft Split Rail Wood Fence - 2 Rail","category":"Fence","unit":"LF","laborCost":4.50,"materialCost":4.25,"equipmentCost":0.35,"notes":"Rustic 2-rail split rail"},
    {"id":uid(),"name":"4 Ft Split Rail Wood Fence - 3 Rail","category":"Fence","unit":"LF","laborCost":5.50,"materialCost":5.50,"equipmentCost":0.35,"notes":"3-rail split rail fence"},
    {"id":uid(),"name":"Shadowbox Wood Fence - 6 Ft","category":"Fence","unit":"LF","laborCost":7.00,"materialCost":9.50,"equipmentCost":0.50,"notes":"Alternating boards shadowbox"},
    {"id":uid(),"name":"Lattice Top Wood Fence - 6 Ft Total","category":"Fence","unit":"LF","laborCost":7.50,"materialCost":9.00,"equipmentCost":0.50,"notes":"Solid base with lattice top"},
    # ── Wood Posts ─────────────────────────────────────────────
    {"id":uid(),"name":"Wood Post - 4x4 PT Set in Concrete","category":"Fence","unit":"EA","laborCost":28.00,"materialCost":12.00,"equipmentCost":5.00,"notes":"4x4 post 8 ft with concrete"},
    {"id":uid(),"name":"Wood Post - 6x6 PT Set in Concrete","category":"Fence","unit":"EA","laborCost":38.00,"materialCost":22.00,"equipmentCost":6.00,"notes":"Heavy 6x6 post set"},
    {"id":uid(),"name":"Post Hole Digging - Per Hole","category":"Fence","unit":"EA","laborCost":22.00,"materialCost":0.00,"equipmentCost":8.50,"notes":"Manual or power auger"},
    {"id":uid(),"name":"Fast-Set Concrete Bag - Per Post","category":"Fence","unit":"EA","laborCost":0.00,"materialCost":6.50,"equipmentCost":0.00,"notes":"80 lb Quikrete fast-set post"},
    # ── Chain Link ─────────────────────────────────────────────
    {"id":uid(),"name":"Chain Link Fence - 4 Ft 9 Gauge Galv","category":"Fence","unit":"LF","laborCost":5.50,"materialCost":6.50,"equipmentCost":0.35,"notes":"4 ft galvanized chain link"},
    {"id":uid(),"name":"Chain Link Fence - 5 Ft 9 Gauge Galv","category":"Fence","unit":"LF","laborCost":6.00,"materialCost":7.50,"equipmentCost":0.35,"notes":"5 ft galvanized chain link"},
    {"id":uid(),"name":"Chain Link Fence - 6 Ft 9 Gauge Galv","category":"Fence","unit":"LF","laborCost":6.50,"materialCost":8.50,"equipmentCost":0.40,"notes":"6 ft galvanized chain link"},
    {"id":uid(),"name":"Chain Link Fence - 6 Ft PVC Coated Black","category":"Fence","unit":"LF","laborCost":6.50,"materialCost":10.00,"equipmentCost":0.40,"notes":"Black vinyl coated chain link"},
    {"id":uid(),"name":"Chain Link Fence - 6 Ft PVC Coated Green","category":"Fence","unit":"LF","laborCost":6.50,"materialCost":10.00,"equipmentCost":0.40,"notes":"Green vinyl coated chain link"},
    {"id":uid(),"name":"Chain Link Top Rail Install - Per LF","category":"Fence","unit":"LF","laborCost":0.85,"materialCost":0.55,"equipmentCost":0.05,"notes":"1-3/8 in top rail"},
    {"id":uid(),"name":"Chain Link Tension Wire - Bottom Per LF","category":"Fence","unit":"LF","laborCost":0.55,"materialCost":0.28,"equipmentCost":0.03,"notes":"Bottom tension wire"},
    {"id":uid(),"name":"Chain Link Barbed Wire - 3 Strand Top","category":"Fence","unit":"LF","laborCost":1.25,"materialCost":1.25,"equipmentCost":0.05,"notes":"Three strand barbed wire"},
    # ── Vinyl Fence ────────────────────────────────────────────
    {"id":uid(),"name":"Vinyl Privacy Fence - 6 Ft White","category":"Fence","unit":"LF","laborCost":7.50,"materialCost":12.00,"equipmentCost":0.50,"notes":"White PVC privacy fence"},
    {"id":uid(),"name":"Vinyl Semi-Privacy Fence - 5 Ft","category":"Fence","unit":"LF","laborCost":6.50,"materialCost":10.00,"equipmentCost":0.40,"notes":"PVC semi-privacy fence"},
    {"id":uid(),"name":"Vinyl Picket Fence - 3 Ft White","category":"Fence","unit":"LF","laborCost":5.50,"materialCost":8.50,"equipmentCost":0.35,"notes":"White PVC picket fence"},
    {"id":uid(),"name":"Vinyl Ranch Rail Fence - 3 Rail","category":"Fence","unit":"LF","laborCost":5.00,"materialCost":7.50,"equipmentCost":0.35,"notes":"3-rail ranch vinyl"},
    {"id":uid(),"name":"Vinyl Shadowbox Fence - 6 Ft","category":"Fence","unit":"LF","laborCost":7.50,"materialCost":13.00,"equipmentCost":0.50,"notes":"Vinyl shadowbox panels"},
    # ── Aluminum Ornamental ────────────────────────────────────
    {"id":uid(),"name":"Aluminum Ornamental Fence - 4 Ft","category":"Fence","unit":"LF","laborCost":6.50,"materialCost":12.00,"equipmentCost":0.45,"notes":"Aluminum spear top 4 ft"},
    {"id":uid(),"name":"Aluminum Ornamental Fence - 6 Ft","category":"Fence","unit":"LF","laborCost":7.50,"materialCost":16.00,"equipmentCost":0.50,"notes":"Aluminum ornamental 6 ft"},
    {"id":uid(),"name":"Aluminum Pool Safety Fence - 48 Inch","category":"Fence","unit":"LF","laborCost":7.50,"materialCost":14.00,"equipmentCost":0.50,"notes":"Code compliant pool barrier"},
    # ── Steel and Wrought Iron ─────────────────────────────────
    {"id":uid(),"name":"Steel Wrought Iron Style Fence - 4 Ft","category":"Fence","unit":"LF","laborCost":8.50,"materialCost":22.00,"equipmentCost":0.50,"notes":"Flat top steel iron fence"},
    {"id":uid(),"name":"Steel Wrought Iron Style Fence - 6 Ft","category":"Fence","unit":"LF","laborCost":9.50,"materialCost":28.00,"equipmentCost":0.60,"notes":"Taller steel wrought iron"},
    {"id":uid(),"name":"Powder Coat Paint - Steel Fence Per LF","category":"Fence","unit":"LF","laborCost":2.50,"materialCost":1.25,"equipmentCost":0.15,"notes":"Powder coat touch-up"},
    # ── Steel and Mesh Specialty ───────────────────────────────
    {"id":uid(),"name":"Deer Fence - 7 Ft Hex Wire Mesh","category":"Fence","unit":"LF","laborCost":3.50,"materialCost":2.85,"equipmentCost":0.25,"notes":"Hexagonal wire garden fence"},
    {"id":uid(),"name":"Welded Wire Animal Fence - 2x4 Mesh","category":"Fence","unit":"LF","laborCost":3.25,"materialCost":2.50,"equipmentCost":0.20,"notes":"Welded wire livestock fence"},
    {"id":uid(),"name":"Electric Fence Install - 3 Wire","category":"Fence","unit":"LF","laborCost":1.25,"materialCost":1.25,"equipmentCost":0.08,"notes":"Portable electric fence system"},
    # ── Gates ─────────────────────────────────────────────────
    {"id":uid(),"name":"Wood Walk Gate - 4 Ft Single Leaf","category":"Fence","unit":"EA","laborCost":185.00,"materialCost":145.00,"equipmentCost":8.00,"notes":"Single 4 ft swing gate"},
    {"id":uid(),"name":"Wood Walk Gate - 6 Ft Single Leaf","category":"Fence","unit":"EA","laborCost":225.00,"materialCost":185.00,"equipmentCost":10.00,"notes":"Tall single leaf gate"},
    {"id":uid(),"name":"Wood Double Drive Gate - 12 Ft Opening","category":"Fence","unit":"EA","laborCost":485.00,"materialCost":385.00,"equipmentCost":20.00,"notes":"Double swing driveway gate"},
    {"id":uid(),"name":"Chain Link Walk Gate - 4 Ft","category":"Fence","unit":"EA","laborCost":85.00,"materialCost":85.00,"equipmentCost":5.00,"notes":"4 ft chain link gate frame"},
    {"id":uid(),"name":"Chain Link Double Drive Gate - 12 Ft","category":"Fence","unit":"EA","laborCost":185.00,"materialCost":185.00,"equipmentCost":10.00,"notes":"Drive gate chain link"},
    {"id":uid(),"name":"Vinyl Gate - 6 Ft Single Leaf","category":"Fence","unit":"EA","laborCost":125.00,"materialCost":225.00,"equipmentCost":8.00,"notes":"PVC privacy gate"},
    {"id":uid(),"name":"Aluminum Ornamental Gate - 4 Ft","category":"Fence","unit":"EA","laborCost":125.00,"materialCost":285.00,"equipmentCost":8.00,"notes":"Aluminum single gate"},
    {"id":uid(),"name":"Slide Gate - Chain Link 16 Ft","category":"Fence","unit":"EA","laborCost":485.00,"materialCost":850.00,"equipmentCost":35.00,"notes":"Rolling slide commercial gate"},
    {"id":uid(),"name":"Automatic Gate Operator Install","category":"Fence","unit":"EA","laborCost":485.00,"materialCost":950.00,"equipmentCost":25.00,"notes":"Electric swing or slide operator"},
    # ── Hardware ──────────────────────────────────────────────
    {"id":uid(),"name":"Gate Hinge Set - Heavy Duty","category":"Fence","unit":"EA","laborCost":18.00,"materialCost":22.00,"equipmentCost":0.50,"notes":"Per pair heavy gate hinge"},
    {"id":uid(),"name":"Gate Latch Install - Cane Bolt","category":"Fence","unit":"EA","laborCost":12.00,"materialCost":12.00,"equipmentCost":0.25,"notes":"Cane bolt for double gate"},
    {"id":uid(),"name":"Gate Latch - Self-Closing Spring","category":"Fence","unit":"EA","laborCost":12.00,"materialCost":18.00,"equipmentCost":0.25,"notes":"Pool code compliant spring latch"},
    {"id":uid(),"name":"Post Cap Install - Wood or Vinyl","category":"Fence","unit":"EA","laborCost":5.00,"materialCost":4.50,"equipmentCost":0.10,"notes":"Per post cap decorative"},
    # ── Demolition and Repair ──────────────────────────────────
    {"id":uid(),"name":"Old Fence Demolition - Per LF","category":"Fence","unit":"LF","laborCost":3.50,"materialCost":0.00,"equipmentCost":0.50,"notes":"Remove and dispose per LF"},
    {"id":uid(),"name":"Post Replacement Only - Per Post","category":"Fence","unit":"EA","laborCost":65.00,"materialCost":22.00,"equipmentCost":8.00,"notes":"Dig out and reset post"},
    {"id":uid(),"name":"Fence Board Replacement Per LF","category":"Fence","unit":"LF","laborCost":4.50,"materialCost":2.85,"equipmentCost":0.25,"notes":"Replace individual boards"},
    {"id":uid(),"name":"Fence Repair General - Per Hour","category":"Fence","unit":"HR","laborCost":65.00,"materialCost":12.00,"equipmentCost":3.00,"notes":"Miscellaneous repair per hour"},
    # ── Special Applications ───────────────────────────────────
    {"id":uid(),"name":"Retaining Wall Fence - Composite Hill","category":"Fence","unit":"LF","laborCost":12.00,"materialCost":18.00,"equipmentCost":1.00,"notes":"Sloped grade stepped panels"},
    {"id":uid(),"name":"Fence Along Slope - Step Down Method","category":"Fence","unit":"LF","laborCost":9.50,"materialCost":8.50,"equipmentCost":0.50,"notes":"Racked panels or step down"},
    {"id":uid(),"name":"Fence Staining - Semi-Transparent","category":"Fence","unit":"SF","laborCost":0.45,"materialCost":0.22,"equipmentCost":0.04,"notes":"Spray or brush stain fence"},
    {"id":uid(),"name":"Fence Permit Fee - Residential","category":"Fence","unit":"EA","laborCost":0.00,"materialCost":85.00,"equipmentCost":0.00,"notes":"Local fence building permit"},
    {"id":uid(),"name":"Survey Stakes Before Fence Install","category":"Fence","unit":"EA","laborCost":0.00,"materialCost":185.00,"equipmentCost":0.00,"notes":"Surveyor to mark property line"},
    {"id":uid(),"name":"Fence Staining - Two Rails Split Rail","category":"Fence","unit":"LF","laborCost":0.85,"materialCost":0.28,"equipmentCost":0.04,"notes":"Split rail oil stain per LF"},
    {"id":uid(),"name":"Privacy Screen - Lattice Panel on Existing","category":"Fence","unit":"SF","laborCost":2.50,"materialCost":1.85,"equipmentCost":0.10,"notes":"Lattice frame add-on"},
    {"id":uid(),"name":"Fence Inspection and Layout","category":"Fence","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":5.00,"notes":"Pre-install measure and layout"},
    {"id":uid(),"name":"Cedar Fence - 6 Ft Shadowbox LF","category":"Fence","unit":"LF","laborCost":9.50,"materialCost":14.50,"equipmentCost":0.50,"notes":"Neighbor-friendly shadowbox"},
    {"id":uid(),"name":"Cedar Fence - 8 Ft Privacy LF","category":"Fence","unit":"LF","laborCost":12.50,"materialCost":18.50,"equipmentCost":0.85,"notes":"Extra tall privacy fence"},
    {"id":uid(),"name":"Bamboo Fence - Roll Install LF","category":"Fence","unit":"LF","laborCost":4.50,"materialCost":12.00,"equipmentCost":0.15,"notes":"Natural bamboo roll screen"},
    {"id":uid(),"name":"Reed Fence - Screen LF","category":"Fence","unit":"LF","laborCost":3.50,"materialCost":6.50,"equipmentCost":0.10,"notes":"Lightweight reed privacy screen"},
    {"id":uid(),"name":"Brushwood Fence - Panel LF","category":"Fence","unit":"LF","laborCost":12.00,"materialCost":28.00,"equipmentCost":1.50,"notes":"Natural brushwood panel fence"},
    {"id":uid(),"name":"Glass Fence - Pool Safety LF","category":"Fence","unit":"LF","laborCost":22.00,"materialCost":85.00,"equipmentCost":5.50,"notes":"Tempered glass with posts"},
    {"id":uid(),"name":"Glass Fence - Frameless Spigot SF","category":"Fence","unit":"SF","laborCost":18.00,"materialCost":65.00,"equipmentCost":4.50,"notes":"Minimalist glass spigot mount"},
    {"id":uid(),"name":"Composite Fence - Horizontal Slat LF","category":"Fence","unit":"LF","laborCost":8.50,"materialCost":22.00,"equipmentCost":0.75,"notes":"Modern horizontal composite slat"},
    {"id":uid(),"name":"Composite Fence - Vertical T&G LF","category":"Fence","unit":"LF","laborCost":7.50,"materialCost":18.50,"equipmentCost":0.65,"notes":"Vertical tongue and groove panel"},
    {"id":uid(),"name":"Aluminum Fence - Spear Top Ornate LF","category":"Fence","unit":"LF","laborCost":6.50,"materialCost":15.00,"equipmentCost":0.50,"notes":"Decorative spear top aluminum"},
    {"id":uid(),"name":"Aluminum Fence - Flat Top Industrial LF","category":"Fence","unit":"LF","laborCost":7.50,"materialCost":18.50,"equipmentCost":0.65,"notes":"Heavy duty flat top aluminum"},
    {"id":uid(),"name":"Wrought Iron Fence - Custom Forged LF","category":"Fence","unit":"LF","laborCost":25.00,"materialCost":45.00,"equipmentCost":12.00,"notes":"Custom artist forged iron"},
    {"id":uid(),"name":"Steel Security Fence - 8 Ft Pointed LF","category":"Fence","unit":"LF","laborCost":12.00,"materialCost":35.00,"equipmentCost":5.50,"notes":"High security steel vertical"},
    {"id":uid(),"name":"Barb Wire Fence - 3 Strand LF","category":"Fence","unit":"LF","laborCost":1.25,"materialCost":0.85,"equipmentCost":2.25,"notes":"Standard 3-strand barb wire"},
    {"id":uid(),"name":"Razor Wire - Concertina Coil LF","category":"Fence","unit":"LF","laborCost":4.50,"materialCost":8.50,"equipmentCost":5.00,"notes":"Perimeter security coil wire"},
    {"id":uid(),"name":"Electric Fence - High Tensile LF","category":"Fence","unit":"LF","laborCost":1.15,"materialCost":0.35,"equipmentCost":1.50,"notes":"Livestock electric wire fence"},
    {"id":uid(),"name":"Deer Fence - 8 Ft Poly Mesh LF","category":"Fence","unit":"LF","laborCost":2.25,"materialCost":1.85,"equipmentCost":0.50,"notes":"Black poly deer mesh"},
    {"id":uid(),"name":"Silt Fence - Erosion Control LF","category":"Fence","unit":"LF","laborCost":0.85,"materialCost":0.45,"equipmentCost":0.15,"notes":"Temp site erosion control"},
    {"id":uid(),"name":"Temp Construction Fence - Panel LF","category":"Fence","unit":"LF","laborCost":0.55,"materialCost":0.00,"equipmentCost":1.25,"notes":"6 ft steel panel rental"},
    {"id":uid(),"name":"Snow Fence - Orange Poly Mesh LF","category":"Fence","unit":"LF","laborCost":0.45,"materialCost":0.25,"equipmentCost":0.05,"notes":"Orange plastic drift fence"},
    {"id":uid(),"name":"Bollard - 4 Inch Concrete Filled EA","category":"Fence","unit":"EA","laborCost":85.00,"materialCost":45.00,"equipmentCost":45.00,"notes":"Protective steel pipe bollard"},
    {"id":uid(),"name":"Bollard - Removable Steel EA","category":"Fence","unit":"EA","laborCost":125.00,"materialCost":350.00,"equipmentCost":25.00,"notes":"Locking removable bollard"},
    {"id":uid(),"name":"Gate Closer - Hydraulic Per Door EA","category":"Fence","unit":"EA","laborCost":45.00,"materialCost":125.00,"equipmentCost":2.00,"notes":"Heavy duty hydraulic gate closer"},
    {"id":uid(),"name":"Gate Closer - Gravity Self-Close EA","category":"Fence","unit":"EA","laborCost":15.00,"materialCost":18.00,"equipmentCost":0.50,"notes":"Standard pool code closer"},
    {"id":uid(),"name":"Gate Handle - Ornate Black Iron EA","category":"Fence","unit":"EA","laborCost":12.00,"materialCost":35.00,"equipmentCost":0.50,"notes":"Decorative forged gate handle"},
    {"id":uid(),"name":"Gate Handle - Stainless Modern EA","category":"Fence","unit":"EA","laborCost":18.00,"materialCost":45.00,"equipmentCost":1.00,"notes":"Sleek stainless steel pull"},
    {"id":uid(),"name":"Post Sleeve - Vinyl 4x4 White LF","category":"Fence","unit":"LF","laborCost":1.25,"materialCost":4.50,"equipmentCost":0.10,"notes":"Vinyl post cover"},
    {"id":uid(),"name":"Post Sleeve - Stone Look Column EA","category":"Fence","unit":"EA","laborCost":45.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Faux stone column surround"},
    {"id":uid(),"name":"Rail Bracket - Deck/Fence Connect EA","category":"Fence","unit":"EA","laborCost":3.50,"materialCost":2.25,"equipmentCost":0.10,"notes":"Metal rail hung bracket"},
    {"id":uid(),"name":"Fence Light - Solar Post Accent EA","category":"Fence","unit":"EA","laborCost":12.00,"materialCost":25.00,"equipmentCost":0.00,"notes":"Solar post cap light"},
    {"id":uid(),"name":"Fence Light - Low Voltage Path LF","category":"Fence","unit":"LF","laborCost":4.50,"materialCost":2.85,"equipmentCost":0.50,"notes":"Wired landscape fence light"},
    {"id":uid(),"name":"Deer Repellent - Pro Scent Treatment EA","category":"Fence","unit":"EA","laborCost":85.00,"materialCost":45.00,"equipmentCost":5.00,"notes":"Chemical deer repellent barrier"},
    {"id":uid(),"name":"Tree Protection - Wood Frame EA","category":"Fence","unit":"EA","laborCost":45.00,"materialCost":35.00,"equipmentCost":10.00,"notes":"Construction site tree guard"},
    {"id":uid(),"name":"Sound Barrier Fence - Acoustic Grade SF","category":"Fence","unit":"SF","laborCost":4.50,"materialCost":12.50,"equipmentCost":1.25,"notes":"High density noise barrier"},
    {"id":uid(),"name":"Privacy Slats - Chain Link Insert SF","category":"Fence","unit":"SF","laborCost":1.25,"materialCost":2.50,"equipmentCost":0.10,"notes":"LDPE slats for chain link"},
    {"id":uid(),"name":"Wind Screen - Mesh for Chain Link SF","category":"Fence","unit":"SF","laborCost":0.22,"materialCost":0.35,"equipmentCost":0.02,"notes":"Privacy windscreen fabric"},
    {"id":uid(),"name":"Tension Wire - Bottom Rail LF","category":"Fence","unit":"LF","laborCost":0.45,"materialCost":0.25,"equipmentCost":0.15,"notes":"Bottom wire for chain link fence"},
    {"id":uid(),"name":"Barbed Wire Arm - Outrigger EA","category":"Fence","unit":"EA","laborCost":12.00,"materialCost":8.50,"equipmentCost":1.00,"notes":"V-arm or single arm barb wire"},
    {"id":uid(),"name":"Fence Cap - Lighted LED EA","category":"Fence","unit":"EA","laborCost":18.00,"materialCost":35.00,"equipmentCost":2.00,"notes":"Wired LED post cap"},
    {"id":uid(),"name":"Fence Cap - Decorative Copper EA","category":"Fence","unit":"EA","laborCost":8.50,"materialCost":22.00,"equipmentCost":0.00,"notes":"Solid copper post pyramid cap"},
    {"id":uid(),"name":"Fence Mowing Pad - Concrete Per LF","category":"Fence","unit":"LF","laborCost":12.00,"materialCost":8.50,"equipmentCost":22.00,"notes":"Concrete curb under fence line"},
    {"id":uid(),"name":"Fence Post - Galvanized 2-3/8 EA","category":"Fence","unit":"EA","laborCost":28.00,"materialCost":22.00,"equipmentCost":15.00,"notes":"Standard steel line post"},
    {"id":uid(),"name":"Fence Post - PT 6x6 Structural EA","category":"Fence","unit":"EA","laborCost":45.00,"materialCost":35.00,"equipmentCost":25.00,"notes":"Heavy duty gate post"},
    {"id":uid(),"name":"Fence Post - Aluminum Fluted EA","category":"Fence","unit":"EA","laborCost":35.00,"materialCost":65.00,"equipmentCost":15.00,"notes":"Decorative ornamental post"},
]
