"""ConcreteAgent — 100 items for concrete work"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    {"id":uid(),"name":"4 Inch Concrete Slab on Grade - Standard","category":"Concrete","unit":"SF","laborCost":1.25,"materialCost":1.85,"equipmentCost":0.45,"notes":"3000 psi with wire mesh"},
    {"id":uid(),"name":"6 Inch Concrete Slab on Grade - Reinforced","category":"Concrete","unit":"SF","laborCost":1.55,"materialCost":2.45,"equipmentCost":0.55,"notes":"4000 psi with rebar grid"},
    {"id":uid(),"name":"4 Inch Garage Concrete Slab - Broom Finish","category":"Concrete","unit":"SF","laborCost":1.35,"materialCost":1.95,"equipmentCost":0.45,"notes":"Includes saw cuts and drain"},
    {"id":uid(),"name":"6 Inch Industrial Warehouse Slab","category":"Concrete","unit":"SF","laborCost":1.75,"materialCost":2.85,"equipmentCost":0.65,"notes":"Heavy duty 4500 psi with fiber"},
    {"id":uid(),"name":"Concrete Slab Polished Finish","category":"Concrete","unit":"SF","laborCost":2.50,"materialCost":0.45,"equipmentCost":1.25,"notes":"3000 grit diamond polish"},
    {"id":uid(),"name":"Concrete Slab Sealed Surface","category":"Concrete","unit":"SF","laborCost":0.35,"materialCost":0.28,"equipmentCost":0.08,"notes":"Penetrating epoxy sealer"},
    {"id":uid(),"name":"Concrete Slab Epoxy Coat - 2 Part","category":"Concrete","unit":"SF","laborCost":1.25,"materialCost":1.85,"equipmentCost":0.25,"notes":"100% solids epoxy floor coat"},
    {"id":uid(),"name":"Concrete Slab Acid Etch and Stain","category":"Concrete","unit":"SF","laborCost":0.85,"materialCost":0.35,"equipmentCost":0.10,"notes":"Acid etch plus penetrating stain"},
    {"id":uid(),"name":"Concrete Slab Crack Repair - Epoxy Inject","category":"Concrete","unit":"LF","laborCost":8.50,"materialCost":4.50,"equipmentCost":1.50,"notes":"Epoxy injection structural repair"},
    {"id":uid(),"name":"Concrete Slab Control Joint Saw Cut","category":"Concrete","unit":"LF","laborCost":1.25,"materialCost":0.00,"equipmentCost":0.35,"notes":"1/4 depth green cut"},
    {"id":uid(),"name":"Continuous Concrete Footing - 12x12","category":"Concrete","unit":"LF","laborCost":12.50,"materialCost":14.00,"equipmentCost":2.50,"notes":"12 in wide x 12 in deep footing"},
    {"id":uid(),"name":"Continuous Concrete Footing - 16x8","category":"Concrete","unit":"LF","laborCost":14.00,"materialCost":16.50,"equipmentCost":2.50,"notes":"Wide shallow footing"},
    {"id":uid(),"name":"Spread Footing - 24x24x12","category":"Concrete","unit":"EA","laborCost":225.00,"materialCost":185.00,"equipmentCost":35.00,"notes":"Per column footing"},
    {"id":uid(),"name":"Spread Footing - 36x36x16","category":"Concrete","unit":"EA","laborCost":350.00,"materialCost":285.00,"equipmentCost":55.00,"notes":"Heavy column footing"},
    {"id":uid(),"name":"Concrete Grade Beam - 12x18","category":"Concrete","unit":"LF","laborCost":22.00,"materialCost":26.00,"equipmentCost":4.50,"notes":"Grade beam between piers"},
    {"id":uid(),"name":"Drilled Pier - 12 Inch Diameter","category":"Concrete","unit":"LF","laborCost":28.00,"materialCost":22.00,"equipmentCost":18.00,"notes":"Cast-in-place drilled pier"},
    {"id":uid(),"name":"Drilled Pier - 18 Inch Diameter","category":"Concrete","unit":"LF","laborCost":38.00,"materialCost":32.00,"equipmentCost":22.00,"notes":"Larger drilled pier"},
    {"id":uid(),"name":"8 Inch Concrete Foundation Wall - Formed","category":"Concrete","unit":"SF","laborCost":8.50,"materialCost":6.25,"equipmentCost":1.50,"notes":"Poured wall with snap ties"},
    {"id":uid(),"name":"10 Inch Concrete Foundation Wall - Formed","category":"Concrete","unit":"SF","laborCost":9.50,"materialCost":7.80,"equipmentCost":1.75,"notes":"Thicker poured wall"},
    {"id":uid(),"name":"12 Inch Concrete Retaining Wall","category":"Concrete","unit":"SF","laborCost":12.00,"materialCost":9.50,"equipmentCost":2.50,"notes":"Cantilevered retaining wall"},
    {"id":uid(),"name":"ICF Foundation Wall - 6 Inch Core","category":"Concrete","unit":"SF","laborCost":10.50,"materialCost":14.00,"equipmentCost":1.50,"notes":"Insulated concrete form"},
    {"id":uid(),"name":"Concrete Wall Waterproofing - Exterior","category":"Concrete","unit":"SF","laborCost":2.50,"materialCost":1.85,"equipmentCost":0.35,"notes":"Bituminous or crystalline coat"},
    {"id":uid(),"name":"Foundation Drain Board Install","category":"Concrete","unit":"SF","laborCost":0.85,"materialCost":1.25,"equipmentCost":0.10,"notes":"Dimple mat drainage board"},
    {"id":uid(),"name":"8 Inch Tilt-Up Concrete Panel - Per SF","category":"Concrete","unit":"SF","laborCost":4.50,"materialCost":6.50,"equipmentCost":2.50,"notes":"Cast and tilted in place"},
    {"id":uid(),"name":"Concrete Column - 12x12 Poured-in-Place","category":"Concrete","unit":"LF","laborCost":45.00,"materialCost":55.00,"equipmentCost":10.00,"notes":"Per LF column height"},
    {"id":uid(),"name":"Concrete Column - 18x18 Poured-in-Place","category":"Concrete","unit":"LF","laborCost":65.00,"materialCost":80.00,"equipmentCost":12.00,"notes":"Larger structural column"},
    {"id":uid(),"name":"CMU Block Wall - 8 Inch Standard","category":"Concrete","unit":"SF","laborCost":4.50,"materialCost":3.85,"equipmentCost":0.35,"notes":"8 inch hollow CMU"},
    {"id":uid(),"name":"CMU Block Wall - 12 Inch Reinforced","category":"Concrete","unit":"SF","laborCost":5.50,"materialCost":5.25,"equipmentCost":0.45,"notes":"12 inch grouted and reinforced"},
    {"id":uid(),"name":"CMU Fill and Grout - Per Core","category":"Concrete","unit":"EA","laborCost":3.50,"materialCost":2.50,"equipmentCost":0.25,"notes":"Core fill with rebar"},
    {"id":uid(),"name":"Concrete Sidewalk - 4 Inch","category":"Concrete","unit":"SF","laborCost":1.15,"materialCost":1.75,"equipmentCost":0.40,"notes":"Standard public sidewalk"},
    {"id":uid(),"name":"Concrete Driveway - 4 Inch","category":"Concrete","unit":"SF","laborCost":1.25,"materialCost":1.85,"equipmentCost":0.45,"notes":"Residential driveway"},
    {"id":uid(),"name":"Concrete Driveway - 6 Inch Heavy Duty","category":"Concrete","unit":"SF","laborCost":1.55,"materialCost":2.45,"equipmentCost":0.55,"notes":"RV or commercial vehicle driveway"},
    {"id":uid(),"name":"Concrete Apron at Garage - 4 Inch","category":"Concrete","unit":"SF","laborCost":1.25,"materialCost":1.85,"equipmentCost":0.45,"notes":"Approach apron with expansion"},
    {"id":uid(),"name":"Concrete Patio - 4 Inch Broom Finish","category":"Concrete","unit":"SF","laborCost":1.25,"materialCost":1.85,"equipmentCost":0.45,"notes":"Standard outdoor patio"},
    {"id":uid(),"name":"Stamped Concrete - Single Pattern","category":"Concrete","unit":"SF","laborCost":2.50,"materialCost":2.25,"equipmentCost":0.55,"notes":"One color single stamp pattern"},
    {"id":uid(),"name":"Stamped Concrete - Multi Pattern Colored","category":"Concrete","unit":"SF","laborCost":4.00,"materialCost":3.25,"equipmentCost":0.75,"notes":"Premium colored stamped"},
    {"id":uid(),"name":"Exposed Aggregate Finish - Seeded","category":"Concrete","unit":"SF","laborCost":1.85,"materialCost":0.65,"equipmentCost":0.25,"notes":"Washed exposed aggregate patio"},
    {"id":uid(),"name":"Concrete Curb - 6 Inch Single Faced","category":"Concrete","unit":"LF","laborCost":8.50,"materialCost":6.50,"equipmentCost":2.00,"notes":"Extruded or slip formed"},
    {"id":uid(),"name":"Concrete Curb and Gutter - Rollback","category":"Concrete","unit":"LF","laborCost":12.00,"materialCost":9.50,"equipmentCost":3.50,"notes":"Combination curb and gutter"},
    {"id":uid(),"name":"Concrete Wheel Stop Install","category":"Concrete","unit":"EA","laborCost":35.00,"materialCost":28.00,"equipmentCost":2.00,"notes":"Precast bolted wheel stop"},
    {"id":uid(),"name":"#3 Rebar Install - Grade 60","category":"Concrete","unit":"LF","laborCost":0.45,"materialCost":0.28,"equipmentCost":0.03,"notes":"3/8 inch rebar"},
    {"id":uid(),"name":"#4 Rebar Install - Grade 60","category":"Concrete","unit":"LF","laborCost":0.55,"materialCost":0.42,"equipmentCost":0.04,"notes":"1/2 inch rebar"},
    {"id":uid(),"name":"#5 Rebar Install - Grade 60","category":"Concrete","unit":"LF","laborCost":0.65,"materialCost":0.62,"equipmentCost":0.05,"notes":"5/8 inch rebar"},
    {"id":uid(),"name":"#6 Rebar Install - Grade 60","category":"Concrete","unit":"LF","laborCost":0.85,"materialCost":0.88,"equipmentCost":0.07,"notes":"3/4 inch rebar"},
    {"id":uid(),"name":"Welded Wire Mesh - 6x6 W1.4xW1.4","category":"Concrete","unit":"SF","laborCost":0.15,"materialCost":0.18,"equipmentCost":0.02,"notes":"Light mesh for slab"},
    {"id":uid(),"name":"Welded Wire Mesh - 4x4 W2.0xW2.0","category":"Concrete","unit":"SF","laborCost":0.18,"materialCost":0.25,"equipmentCost":0.02,"notes":"Heavy mesh for slab"},
    {"id":uid(),"name":"Fiber Reinforcement Additive - Per CY","category":"Concrete","unit":"CY","laborCost":0.00,"materialCost":8.50,"equipmentCost":0.00,"notes":"Polypropylene fiber mix add"},
    {"id":uid(),"name":"Rebar Tie Wire - Per Bundle","category":"Concrete","unit":"EA","laborCost":0.00,"materialCost":28.00,"equipmentCost":0.00,"notes":"16 gauge black annealed"},
    {"id":uid(),"name":"Concrete Chairs for Rebar Placement","category":"Concrete","unit":"EA","laborCost":0.10,"materialCost":0.15,"equipmentCost":0.00,"notes":"Per chair for 1.5 in cover"},
    {"id":uid(),"name":"Wood Form - Slab Edge 4 Inch","category":"Concrete","unit":"LF","laborCost":2.50,"materialCost":0.85,"equipmentCost":0.15,"notes":"2x4 lumber form set and strip"},
    {"id":uid(),"name":"Wood Form - Slab Edge 6 Inch","category":"Concrete","unit":"LF","laborCost":2.75,"materialCost":1.05,"equipmentCost":0.18,"notes":"2x6 lumber form"},
    {"id":uid(),"name":"Steel Gang Form - Wall - Per Use","category":"Concrete","unit":"SF","laborCost":6.50,"materialCost":3.50,"equipmentCost":2.50,"notes":"Modular gang form rental and labor"},
    {"id":uid(),"name":"Snap Ties and Wedges - Per SF of Wall","category":"Concrete","unit":"SF","laborCost":0.00,"materialCost":0.65,"equipmentCost":0.00,"notes":"Coil ties at 2 ft OC grid"},
    {"id":uid(),"name":"Form Release Agent - Per SF","category":"Concrete","unit":"SF","laborCost":0.00,"materialCost":0.05,"equipmentCost":0.00,"notes":"Petroleum or vegetable base"},
    {"id":uid(),"name":"Sono Tube Form - 10 Inch Diameter","category":"Concrete","unit":"LF","laborCost":4.50,"materialCost":3.25,"equipmentCost":0.50,"notes":"Round wax tube pier form"},
    {"id":uid(),"name":"Sono Tube Form - 18 Inch Diameter","category":"Concrete","unit":"LF","laborCost":6.50,"materialCost":5.50,"equipmentCost":0.75,"notes":"Large diameter tube form"},
    {"id":uid(),"name":"Concrete Pump - Boom Truck - Per Hour","category":"Concrete","unit":"HR","laborCost":0.00,"materialCost":0.00,"equipmentCost":185.00,"notes":"52 meter boom pump"},
    {"id":uid(),"name":"Concrete Pump - Line Pump - Per Hour","category":"Concrete","unit":"HR","laborCost":0.00,"materialCost":0.00,"equipmentCost":125.00,"notes":"Trailer line pump"},
    {"id":uid(),"name":"Concrete Delivery - Per Yard 3000 PSI","category":"Concrete","unit":"CY","laborCost":0.00,"materialCost":148.00,"equipmentCost":0.00,"notes":"Ready mix delivery price"},
    {"id":uid(),"name":"Concrete Delivery - Per Yard 4000 PSI","category":"Concrete","unit":"CY","laborCost":0.00,"materialCost":158.00,"equipmentCost":0.00,"notes":"High strength ready mix"},
    {"id":uid(),"name":"Concrete Delivery - Per Yard 5000 PSI","category":"Concrete","unit":"CY","laborCost":0.00,"materialCost":172.00,"equipmentCost":0.00,"notes":"Structural high strength"},
    {"id":uid(),"name":"Concrete Chute Discharge - Short Pour","category":"Concrete","unit":"CY","laborCost":18.00,"materialCost":0.00,"equipmentCost":5.00,"notes":"Direct chute spread and vibrate"},
    {"id":uid(),"name":"Wheelbarrow Concrete Placement","category":"Concrete","unit":"CY","laborCost":45.00,"materialCost":0.00,"equipmentCost":5.00,"notes":"Hand wheel for difficult access"},
    {"id":uid(),"name":"Concrete Screed and Float Finish","category":"Concrete","unit":"SF","laborCost":0.45,"materialCost":0.00,"equipmentCost":0.10,"notes":"Screed bull float and trowel"},
    {"id":uid(),"name":"Concrete Machine Trowel Finish - Smooth","category":"Concrete","unit":"SF","laborCost":0.35,"materialCost":0.00,"equipmentCost":0.15,"notes":"Power trowel smooth finish"},
    {"id":uid(),"name":"Concrete Broom Finish - Exposed","category":"Concrete","unit":"SF","laborCost":0.25,"materialCost":0.00,"equipmentCost":0.08,"notes":"Texture broom pass"},
    {"id":uid(),"name":"Concrete Curing Compound Application","category":"Concrete","unit":"SF","laborCost":0.08,"materialCost":0.06,"equipmentCost":0.02,"notes":"White pigmented curing compound"},
    {"id":uid(),"name":"Wet Burlap Curing - Per SF Per Day","category":"Concrete","unit":"SF","laborCost":0.08,"materialCost":0.04,"equipmentCost":0.01,"notes":"7-day wet cure method"},
    {"id":uid(),"name":"Concrete Hardener Application - Lithium","category":"Concrete","unit":"SF","laborCost":0.18,"materialCost":0.22,"equipmentCost":0.03,"notes":"Penetrating densifier"},
    {"id":uid(),"name":"Non-Shrink Grout - Column Base Plate","category":"Concrete","unit":"EA","laborCost":85.00,"materialCost":38.00,"equipmentCost":8.00,"notes":"Per base plate grout"},
    {"id":uid(),"name":"Concrete Saw Cutting - Walk Behind","category":"Concrete","unit":"LF","laborCost":2.50,"materialCost":0.00,"equipmentCost":1.25,"notes":"14 inch diamond blade"},
    {"id":uid(),"name":"Core Drilling - 4 Inch Diameter","category":"Concrete","unit":"EA","laborCost":85.00,"materialCost":0.00,"equipmentCost":25.00,"notes":"Per core through slab or wall"},
    {"id":uid(),"name":"Core Drilling - 6 Inch Diameter","category":"Concrete","unit":"EA","laborCost":105.00,"materialCost":0.00,"equipmentCost":35.00,"notes":"Larger diameter core drill"},
    {"id":uid(),"name":"Core Drilling - 12 Inch Diameter","category":"Concrete","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":65.00,"notes":"Large pipe or duct penetration"},
    {"id":uid(),"name":"Concrete Demolition - Slab on Grade 4 Inch","category":"Concrete","unit":"SF","laborCost":1.85,"materialCost":0.00,"equipmentCost":0.85,"notes":"Jackhammer break and pile"},
    {"id":uid(),"name":"Concrete Demolition - Foundation Wall","category":"Concrete","unit":"CF","laborCost":18.00,"materialCost":0.00,"equipmentCost":8.50,"notes":"Hydraulic hammer or saw"},
    {"id":uid(),"name":"Concrete Haul Away - Per Yard","category":"Concrete","unit":"CY","laborCost":35.00,"materialCost":0.00,"equipmentCost":48.00,"notes":"Load haul and dump"},
    {"id":uid(),"name":"Post Tension Slab - Engineer Design","category":"Concrete","unit":"SF","laborCost":1.85,"materialCost":1.25,"equipmentCost":0.35,"notes":"PT cable system per SF"},
    {"id":uid(),"name":"Concrete Staircase - Precast","category":"Concrete","unit":"EA","laborCost":450.00,"materialCost":1850.00,"equipmentCost":350.00,"notes":"Per flight precast stair"},
    {"id":uid(),"name":"Concrete Staircase - Poured in Place","category":"Concrete","unit":"EA","laborCost":850.00,"materialCost":450.00,"equipmentCost":85.00,"notes":"Per flight formed and poured"},
    {"id":uid(),"name":"Precast Concrete Deck Panel","category":"Concrete","unit":"SF","laborCost":2.50,"materialCost":8.50,"equipmentCost":1.85,"notes":"Precast structural deck panel"},
    {"id":uid(),"name":"Concrete Admixture - Accelerator Per CY","category":"Concrete","unit":"CY","laborCost":0.00,"materialCost":12.00,"equipmentCost":0.00,"notes":"Calcium chloride accelerator"},
    {"id":uid(),"name":"Concrete Admixture - Plasticizer Per CY","category":"Concrete","unit":"CY","laborCost":0.00,"materialCost":9.50,"equipmentCost":0.00,"notes":"High range water reducer"},
    {"id":uid(),"name":"Cold Weather Concrete Protection - Per Day","category":"Concrete","unit":"EA","laborCost":185.00,"materialCost":85.00,"equipmentCost":45.00,"notes":"Insulated blankets and heat"},
    {"id":uid(),"name":"Concrete Test Cylinders - Set of 4","category":"Concrete","unit":"EA","laborCost":45.00,"materialCost":28.00,"equipmentCost":5.00,"notes":"Onsite cast and lab tested"},
    {"id":uid(),"name":"Concrete Resurfacing - Worn Slab","category":"Concrete","unit":"SF","laborCost":0.85,"materialCost":1.25,"equipmentCost":0.35,"notes":"1/4 in overlay resurfacer"},
    {"id":uid(),"name":"Concrete Joint Sealant - Caulk","category":"Concrete","unit":"LF","laborCost":1.25,"materialCost":0.55,"equipmentCost":0.05,"notes":"Polyurethane joint filler"},
    {"id":uid(),"name":"Shotcrete - Gunite Application","category":"Concrete","unit":"CY","laborCost":185.00,"materialCost":125.00,"equipmentCost":65.00,"notes":"Pneumatically applied concrete"},
    {"id":uid(),"name":"Self-Leveling Underlayment - Per SF","category":"Concrete","unit":"SF","laborCost":0.65,"materialCost":0.95,"equipmentCost":0.15,"notes":"Gypsum or cement SLU"},
    {"id":uid(),"name":"Concrete Moisture Vapor Barrier - Epoxy","category":"Concrete","unit":"SF","laborCost":0.55,"materialCost":0.85,"equipmentCost":0.12,"notes":"2-part epoxy vapor seal"},
    {"id":uid(),"name":"Anchor Rod Install - Hilti Adhesive","category":"Concrete","unit":"EA","laborCost":18.50,"materialCost":12.50,"equipmentCost":2.50,"notes":"Chemical anchor into concrete"},
    {"id":uid(),"name":"Helical Anchor Install - Grade Beam","category":"Concrete","unit":"EA","laborCost":225.00,"materialCost":185.00,"equipmentCost":125.00,"notes":"Per anchor pier with cap"},
    {"id":uid(),"name":"Concrete Block Cap - Decorative","category":"Concrete","unit":"LF","laborCost":5.50,"materialCost":4.50,"equipmentCost":0.25,"notes":"Masonry wall cap block"},
    {"id":uid(),"name":"Efflorescence Treatment - Masonry","category":"Concrete","unit":"SF","laborCost":0.45,"materialCost":0.35,"equipmentCost":0.05,"notes":"Chemical efflorescence cleaner"},
    {"id":uid(),"name":"Masonry Tuckpointing - Per SF","category":"Concrete","unit":"SF","laborCost":6.50,"materialCost":1.25,"equipmentCost":0.50,"notes":"Repoint mortar joints"},
    {"id":uid(),"name":"Fiber Cement Board Topping - 1.5 Inch","category":"Concrete","unit":"SF","laborCost":0.95,"materialCost":1.10,"equipmentCost":0.15,"notes":"Thin topping slab for floors"},
    {"id":uid(),"name":"Concrete Vault - Precast Septic 1000 Gal","category":"Concrete","unit":"EA","laborCost":850.00,"materialCost":1850.00,"equipmentCost":450.00,"notes":"Standard septic tank install"},
    {"id":uid(),"name":"Concrete Splash Block - Precast","category":"Concrete","unit":"EA","laborCost":8.50,"materialCost":12.50,"equipmentCost":0.00,"notes":"Downspout splash block"},
    {"id":uid(),"name":"Concrete Pipe - 12 Inch RCP Per LF","category":"Concrete","unit":"LF","laborCost":12.00,"materialCost":18.00,"equipmentCost":6.50,"notes":"Reinforced concrete pipe"},
    {"id":uid(),"name":"Concrete Floating Floor Slab - Isolation","category":"Concrete","unit":"SF","laborCost":2.25,"materialCost":3.50,"equipmentCost":0.45,"notes":"Acoustic isolation slab"},
]
