"""ExcavationAgent — 100 items for site earthwork"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Site Clearing ──────────────────────────────────────────
    {"id":uid(),"name":"Brush Clearing and Grubbing - Light","category":"Excavation","unit":"SF","laborCost":0.08,"materialCost":0.00,"equipmentCost":0.04,"notes":"Light vegetation under 4 inch dia"},
    {"id":uid(),"name":"Brush Clearing and Grubbing - Heavy","category":"Excavation","unit":"SF","laborCost":0.18,"materialCost":0.00,"equipmentCost":0.10,"notes":"Dense brush and saplings"},
    {"id":uid(),"name":"Tree Removal - Up to 6 Inch Diameter","category":"Excavation","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":65.00,"notes":"Cut, limb and chip"},
    {"id":uid(),"name":"Tree Removal - 6 to 18 Inch Diameter","category":"Excavation","unit":"EA","laborCost":350.00,"materialCost":0.00,"equipmentCost":125.00,"notes":"Mid-size tree removal"},
    {"id":uid(),"name":"Tree Removal - Over 18 Inch Diameter","category":"Excavation","unit":"EA","laborCost":650.00,"materialCost":0.00,"equipmentCost":250.00,"notes":"Large tree felling and chipping"},
    {"id":uid(),"name":"Stump Grinding - Up to 12 Inch","category":"Excavation","unit":"EA","laborCost":95.00,"materialCost":0.00,"equipmentCost":55.00,"notes":"Grind stump 6 in below grade"},
    {"id":uid(),"name":"Stump Grinding - 12 to 24 Inch","category":"Excavation","unit":"EA","laborCost":145.00,"materialCost":0.00,"equipmentCost":75.00,"notes":"Large stump grinding"},
    {"id":uid(),"name":"Topsoil Strip and Stockpile - 6 Inch","category":"Excavation","unit":"SF","laborCost":0.05,"materialCost":0.00,"equipmentCost":0.08,"notes":"Machine strip and stockpile"},
    {"id":uid(),"name":"Topsoil Strip and Stockpile - 12 Inch","category":"Excavation","unit":"SF","laborCost":0.08,"materialCost":0.00,"equipmentCost":0.12,"notes":"Deep topsoil strip"},
    {"id":uid(),"name":"Site Demolition - Asphalt Removal","category":"Excavation","unit":"SF","laborCost":0.35,"materialCost":0.00,"equipmentCost":0.55,"notes":"Break, load and haul asphalt"},
    # ── Mass Excavation ────────────────────────────────────────
    {"id":uid(),"name":"Mass Excavation - Common Earth","category":"Excavation","unit":"CY","laborCost":4.50,"materialCost":0.00,"equipmentCost":6.50,"notes":"Dozer or excavator common soil"},
    {"id":uid(),"name":"Mass Excavation - Sandy Loam","category":"Excavation","unit":"CY","laborCost":3.50,"materialCost":0.00,"equipmentCost":5.50,"notes":"Easier sandy soil excavation"},
    {"id":uid(),"name":"Mass Excavation - Hardpan Clay","category":"Excavation","unit":"CY","laborCost":6.50,"materialCost":0.00,"equipmentCost":9.00,"notes":"Dense clay requires ripping"},
    {"id":uid(),"name":"Rock Excavation - Blasting Required","category":"Excavation","unit":"CY","laborCost":35.00,"materialCost":18.00,"equipmentCost":25.00,"notes":"Controlled blasting with permit"},
    {"id":uid(),"name":"Rock Excavation - Hydraulic Hammer","category":"Excavation","unit":"CY","laborCost":25.00,"materialCost":0.00,"equipmentCost":35.00,"notes":"Hydraulic breaker attachment"},
    {"id":uid(),"name":"Basement Excavation - Full Depth","category":"Excavation","unit":"CY","laborCost":8.00,"materialCost":0.00,"equipmentCost":10.00,"notes":"8 ft deep full basement"},
    {"id":uid(),"name":"Crawl Space Excavation","category":"Excavation","unit":"CY","laborCost":12.00,"materialCost":0.00,"equipmentCost":8.50,"notes":"Confined access excavation"},
    # ── Trench Excavation ──────────────────────────────────────
    {"id":uid(),"name":"Trench Excavation - 18 Inch Wide x 4 Ft Deep","category":"Excavation","unit":"LF","laborCost":5.50,"materialCost":0.00,"equipmentCost":4.50,"notes":"Standard utility trench"},
    {"id":uid(),"name":"Trench Excavation - 24 Inch Wide x 6 Ft Deep","category":"Excavation","unit":"LF","laborCost":9.50,"materialCost":0.00,"equipmentCost":7.50,"notes":"Deeper utility or drain trench"},
    {"id":uid(),"name":"Hand Trench Excavation - Narrow Access","category":"Excavation","unit":"LF","laborCost":18.00,"materialCost":0.00,"equipmentCost":2.00,"notes":"Tight access hand dig"},
    {"id":uid(),"name":"Trench Backfill - Compacted Select Fill","category":"Excavation","unit":"LF","laborCost":3.50,"materialCost":2.50,"equipmentCost":1.50,"notes":"Compacted in 6 in lifts"},
    {"id":uid(),"name":"Trench Bedding - Granular Material","category":"Excavation","unit":"LF","laborCost":2.00,"materialCost":3.50,"equipmentCost":0.50,"notes":"6 in gravel bed for pipe"},
    # ── Grading ────────────────────────────────────────────────
    {"id":uid(),"name":"Rough Grading - Dozer","category":"Excavation","unit":"SF","laborCost":0.04,"materialCost":0.00,"equipmentCost":0.08,"notes":"Establish rough subgrade elevation"},
    {"id":uid(),"name":"Fine Grading - Motor Grader","category":"Excavation","unit":"SF","laborCost":0.06,"materialCost":0.00,"equipmentCost":0.10,"notes":"Grade to within 0.1 ft of design"},
    {"id":uid(),"name":"Hand Fine Grading - Around Structures","category":"Excavation","unit":"SF","laborCost":0.18,"materialCost":0.00,"equipmentCost":0.02,"notes":"Rakes and shovels"},
    {"id":uid(),"name":"Subgrade Preparation - Proof Roll","category":"Excavation","unit":"SF","laborCost":0.05,"materialCost":0.00,"equipmentCost":0.08,"notes":"Loaded truck proof roll"},
    {"id":uid(),"name":"Swale Grading - Per LF","category":"Excavation","unit":"LF","laborCost":4.00,"materialCost":0.00,"equipmentCost":2.50,"notes":"Drainage swale cut and shape"},
    {"id":uid(),"name":"Slope Grading - 3:1 Finish","category":"Excavation","unit":"SF","laborCost":0.15,"materialCost":0.00,"equipmentCost":0.10,"notes":"Embankment slope trimming"},
    # ── Fill and Compaction ────────────────────────────────────
    {"id":uid(),"name":"Structural Fill - Compacted - Per CY","category":"Excavation","unit":"CY","laborCost":8.50,"materialCost":14.00,"equipmentCost":4.50,"notes":"3/4 minus crushed stone compacted"},
    {"id":uid(),"name":"Sand Fill - Compacted","category":"Excavation","unit":"CY","laborCost":6.50,"materialCost":18.00,"equipmentCost":3.50,"notes":"Clean sand fill"},
    {"id":uid(),"name":"Topsoil Import and Spread - 4 Inch","category":"Excavation","unit":"SF","laborCost":0.08,"materialCost":0.35,"equipmentCost":0.06,"notes":"Screened topsoil 4 in deep"},
    {"id":uid(),"name":"Topsoil Import and Spread - 6 Inch","category":"Excavation","unit":"SF","laborCost":0.10,"materialCost":0.52,"equipmentCost":0.08,"notes":"6 in depth topsoil"},
    {"id":uid(),"name":"Gravel Base Course - 4 Inch Compacted","category":"Excavation","unit":"SF","laborCost":0.18,"materialCost":0.45,"equipmentCost":0.12,"notes":"CA-6 limestone base course"},
    {"id":uid(),"name":"Gravel Base Course - 6 Inch Compacted","category":"Excavation","unit":"SF","laborCost":0.22,"materialCost":0.65,"equipmentCost":0.15,"notes":"CA-6 6 inch deep"},
    {"id":uid(),"name":"Compaction - Vibratory Plate","category":"Excavation","unit":"SF","laborCost":0.08,"materialCost":0.00,"equipmentCost":0.06,"notes":"Per lift plate compactor"},
    {"id":uid(),"name":"Compaction - Vibratory Roller - Large","category":"Excavation","unit":"SF","laborCost":0.04,"materialCost":0.00,"equipmentCost":0.10,"notes":"Large roller for mass areas"},
    {"id":uid(),"name":"Nuclear Density Test - Per Test","category":"Excavation","unit":"EA","laborCost":85.00,"materialCost":0.00,"equipmentCost":25.00,"notes":"Compaction verification test"},
    # ── Excavation Support ─────────────────────────────────────
    {"id":uid(),"name":"Shoring - Hydraulic Trench Box - Per Day","category":"Excavation","unit":"EA","laborCost":95.00,"materialCost":0.00,"equipmentCost":185.00,"notes":"Trench safety shoring"},
    {"id":uid(),"name":"Dewatering - Submersible Pump - Per Day","category":"Excavation","unit":"EA","laborCost":35.00,"materialCost":0.00,"equipmentCost":85.00,"notes":"Groundwater removal"},
    {"id":uid(),"name":"Dewatering - Wellpoint System - Per Week","category":"Excavation","unit":"EA","laborCost":450.00,"materialCost":0.00,"equipmentCost":850.00,"notes":"Wellpoint dewatering system"},
    {"id":uid(),"name":"Slope Stabilization - Geotextile Fabric","category":"Excavation","unit":"SF","laborCost":0.15,"materialCost":0.22,"equipmentCost":0.02,"notes":"Woven fabric for slope control"},
    # ── Erosion Control ────────────────────────────────────────
    {"id":uid(),"name":"Silt Fence Install","category":"Excavation","unit":"LF","laborCost":1.25,"materialCost":0.85,"equipmentCost":0.15,"notes":"Driven posts with filter fabric"},
    {"id":uid(),"name":"Straw Wattle Install","category":"Excavation","unit":"LF","laborCost":2.50,"materialCost":3.50,"equipmentCost":0.25,"notes":"12 inch fiber roll"},
    {"id":uid(),"name":"Inlet Protection - Rock Filter Dam","category":"Excavation","unit":"EA","laborCost":65.00,"materialCost":45.00,"equipmentCost":15.00,"notes":"Per storm inlet"},
    {"id":uid(),"name":"Erosion Control Blanket - Biodegradable","category":"Excavation","unit":"SF","laborCost":0.08,"materialCost":0.12,"equipmentCost":0.01,"notes":"Straw or coir blanket"},
    {"id":uid(),"name":"Hydroseeding - Temporary Erosion Control","category":"Excavation","unit":"SF","laborCost":0.08,"materialCost":0.12,"equipmentCost":0.04,"notes":"Seed mulch slurry spray"},
    {"id":uid(),"name":"Permanent Seeding and Fertilizer","category":"Excavation","unit":"SF","laborCost":0.06,"materialCost":0.10,"equipmentCost":0.03,"notes":"Lawn establishment seeding"},
    {"id":uid(),"name":"SWPPP Plan and Inspection","category":"Excavation","unit":"EA","laborCost":850.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Stormwater pollution prevention plan"},
    # ── Hauling and Disposal ───────────────────────────────────
    {"id":uid(),"name":"Spoil Hauling - On Site - Per CY","category":"Excavation","unit":"CY","laborCost":3.50,"materialCost":0.00,"equipmentCost":5.50,"notes":"Earthwork to stockpile"},
    {"id":uid(),"name":"Spoil Hauling - Off Site Disposal - Per CY","category":"Excavation","unit":"CY","laborCost":5.50,"materialCost":12.00,"equipmentCost":8.50,"notes":"Truck and dump fee"},
    {"id":uid(),"name":"Clean Soil Export - Per Load","category":"Excavation","unit":"EA","laborCost":95.00,"materialCost":55.00,"equipmentCost":0.00,"notes":"14 CY dump truck load"},
    {"id":uid(),"name":"Contaminated Soil Disposal - Per Ton","category":"Excavation","unit":"EA","laborCost":45.00,"materialCost":85.00,"equipmentCost":25.00,"notes":"Special handling manifest"},
    {"id":uid(),"name":"Import Fill - Trucked In - Per CY","category":"Excavation","unit":"CY","laborCost":0.00,"materialCost":22.00,"equipmentCost":0.00,"notes":"Delivered stockpile fill"},
    # ── Drainage ──────────────────────────────────────────────
    {"id":uid(),"name":"French Drain Install - 4 Inch Perf Pipe","category":"Excavation","unit":"LF","laborCost":6.50,"materialCost":4.50,"equipmentCost":1.50,"notes":"Gravel wrapped perforated drain"},
    {"id":uid(),"name":"French Drain Install - 6 Inch Perf Pipe","category":"Excavation","unit":"LF","laborCost":8.50,"materialCost":6.50,"equipmentCost":2.00,"notes":"Larger diameter drain"},
    {"id":uid(),"name":"Catch Basin Install - Precast","category":"Excavation","unit":"EA","laborCost":450.00,"materialCost":385.00,"equipmentCost":95.00,"notes":"24 in precast catch basin"},
    {"id":uid(),"name":"Area Drain Install - 12 Inch","category":"Excavation","unit":"EA","laborCost":185.00,"materialCost":125.00,"equipmentCost":35.00,"notes":"Yard drain with grate"},
    {"id":uid(),"name":"Storm Pipe - 12 Inch RCP Install","category":"Excavation","unit":"LF","laborCost":12.00,"materialCost":18.00,"equipmentCost":6.00,"notes":"Reinforced concrete pipe"},
    {"id":uid(),"name":"Storm Pipe - 18 Inch RCP Install","category":"Excavation","unit":"LF","laborCost":16.00,"materialCost":28.00,"equipmentCost":8.00,"notes":"Larger storm pipe"},
    {"id":uid(),"name":"Drainage Ditch Clean-Out","category":"Excavation","unit":"LF","laborCost":4.50,"materialCost":0.00,"equipmentCost":3.50,"notes":"Excavate and re-grade ditch"},
    {"id":uid(),"name":"Culvert Install - 18 Inch HDPE","category":"Excavation","unit":"LF","laborCost":8.50,"materialCost":22.00,"equipmentCost":5.00,"notes":"Driveway or roadway culvert"},
    # ── Site Utilities ─────────────────────────────────────────
    {"id":uid(),"name":"Electric Service Trench - Per LF","category":"Excavation","unit":"LF","laborCost":4.50,"materialCost":0.00,"equipmentCost":3.50,"notes":"18 in deep electrical trench"},
    {"id":uid(),"name":"Water Service Trench - Per LF","category":"Excavation","unit":"LF","laborCost":5.50,"materialCost":0.00,"equipmentCost":4.00,"notes":"Below frost depth excavation"},
    {"id":uid(),"name":"Gas Service Trench - Per LF","category":"Excavation","unit":"LF","laborCost":4.50,"materialCost":0.00,"equipmentCost":3.50,"notes":"18 in deep gas trench"},
    {"id":uid(),"name":"Sanitary Sewer Trench - Deep","category":"Excavation","unit":"LF","laborCost":12.00,"materialCost":0.00,"equipmentCost":8.50,"notes":"8 to 12 ft deep sewer trench"},
    {"id":uid(),"name":"Utility Potholing - Hydro Vac","category":"Excavation","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":125.00,"notes":"Pothole existing utility safe exposure"},
    # ── Specialty ─────────────────────────────────────────────
    {"id":uid(),"name":"Soil Boring - Geotechnical","category":"Excavation","unit":"EA","laborCost":650.00,"materialCost":0.00,"equipmentCost":350.00,"notes":"Per boring with lab analysis"},
    {"id":uid(),"name":"Underpinning - Helical Pile","category":"Excavation","unit":"EA","laborCost":350.00,"materialCost":450.00,"equipmentCost":185.00,"notes":"Per pier for foundation repair"},
    {"id":uid(),"name":"Sheet Pile Install - Per LF","category":"Excavation","unit":"LF","laborCost":28.00,"materialCost":45.00,"equipmentCost":22.00,"notes":"Steel sheet pile for deep excavation"},
    {"id":uid(),"name":"Excavation Safety Inspection","category":"Excavation","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"OSHA competent person inspection"},
    {"id":uid(),"name":"Soil Amendment - Lime Stabilization","category":"Excavation","unit":"CY","laborCost":4.50,"materialCost":8.50,"equipmentCost":3.50,"notes":"Hydrated lime for weak soils"},
    {"id":uid(),"name":"Geogrid Install for Road Base","category":"Excavation","unit":"SF","laborCost":0.10,"materialCost":0.18,"equipmentCost":0.02,"notes":"Biaxial geogrid for subgrade"},
    # ── Equipment ─────────────────────────────────────────────
    {"id":uid(),"name":"Excavator Rental - 20 Ton - Per Day","category":"Excavation","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":1450.00,"notes":"Cat 320 class excavator"},
    {"id":uid(),"name":"Dozer Rental - D6 Class - Per Day","category":"Excavation","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":1250.00,"notes":"Medium crawler dozer"},
    {"id":uid(),"name":"Skid Steer Rental - Per Day","category":"Excavation","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":485.00,"notes":"Standard skid loader with bucket"},
    {"id":uid(),"name":"Dump Truck Rental - 14 CY - Per Day","category":"Excavation","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":650.00,"notes":"Tandem axle dump truck"},
    {"id":uid(),"name":"Motor Grader Rental - Per Day","category":"Excavation","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":1150.00,"notes":"Fine grading equipment"},
    {"id":uid(),"name":"Compactor - Vibratory Drum Roller - Per Day","category":"Excavation","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":550.00,"notes":"Single drum walk behind"},
    # ── Miscellaneous ──────────────────────────────────────────
    {"id":uid(),"name":"Concrete Breaking - Sledge and Jackhammer","category":"Excavation","unit":"CY","laborCost":22.00,"materialCost":0.00,"equipmentCost":8.50,"notes":"Hand break unreinforced concrete"},
    {"id":uid(),"name":"Snow Fence - Temporary Site Control","category":"Excavation","unit":"LF","laborCost":0.85,"materialCost":0.45,"equipmentCost":0.10,"notes":"Orange safety fencing with stakes"},
    {"id":uid(),"name":"Construction Entrance - Aggregate Pad","category":"Excavation","unit":"EA","laborCost":185.00,"materialCost":245.00,"equipmentCost":65.00,"notes":"50 ft gravel wash pad"},
    {"id":uid(),"name":"Survey Staking - Building Lines","category":"Excavation","unit":"EA","laborCost":850.00,"materialCost":0.00,"equipmentCost":125.00,"notes":"Licensed surveyor building corners"},
    {"id":uid(),"name":"As-Built Survey After Grading","category":"Excavation","unit":"EA","laborCost":650.00,"materialCost":0.00,"equipmentCost":85.00,"notes":"Post-grade elevation survey"},
    {"id":uid(),"name":"General Site Cleanup After Excavation","category":"Excavation","unit":"EA","laborCost":350.00,"materialCost":0.00,"equipmentCost":65.00,"notes":"Broom clean and final inspection"},
    {"id":uid(),"name":"Clearing and Grubbing - Heavy Brush Per Acre","category":"Excavation","unit":"EA","laborCost":2850.00,"materialCost":0.00,"equipmentCost":1850.00,"notes":"Full acre clearance"},
    {"id":uid(),"name":"Silt Fence - Wired Reinforced Per LF","category":"Excavation","unit":"LF","laborCost":1.25,"materialCost":2.45,"equipmentCost":0.15,"notes":"Heavy duty erosion control"},
    {"id":uid(),"name":"Inlet Protection - Filter Bag Per Drain","category":"Excavation","unit":"EA","laborCost":45.00,"materialCost":85.00,"equipmentCost":5.00,"notes":"Catch basin filter insert"},
    {"id":uid(),"name":"Rock Hammer - Excavator Attachment Per Hr","category":"Excavation","unit":"HR","laborCost":0.00,"materialCost":0.00,"equipmentCost":125.00,"notes":"Hydraulic rock breaker add-on"},
    {"id":uid(),"name":"Dewatering Well - Per Day Operation","category":"Excavation","unit":"EA","laborCost":85.00,"materialCost":0.00,"equipmentCost":125.00,"notes":"Continuous pump operation"},
    {"id":uid(),"name":"Soil Lab Analysis - Proctor Test","category":"Excavation","unit":"EA","laborCost":125.00,"materialCost":185.00,"equipmentCost":25.00,"notes":"Lab test for max density"},
    {"id":uid(),"name":"Compaction Test - Nuclear Gauge Per Site","category":"Excavation","unit":"EA","laborCost":285.00,"materialCost":0.00,"equipmentCost":85.00,"notes":"On-site density verification"},
    {"id":uid(),"name":"Drainage Swale - Grass Lined Per LF","category":"Excavation","unit":"LF","laborCost":4.50,"materialCost":2.50,"equipmentCost":1.50,"notes":"Formed swale with erosion mat"},
    {"id":uid(),"name":"Rip Rap Slope Protection - Per Ton","category":"Excavation","unit":"EA","laborCost":18.00,"materialCost":65.00,"equipmentCost":22.00,"notes":"Stone armoring for slopes"},
    {"id":uid(),"name":"Site Survey - Topographic and Boundary","category":"Excavation","unit":"EA","laborCost":1850.00,"materialCost":0.00,"equipmentCost":250.00,"notes":"Full site pre-construction survey"},
]
