"""FramingAgent — 100 items moved from generate_all"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    {"id":uid(),"name":"3-5/8 Inch 20 Gauge Steel Stud Install","category":"Framing","unit":"LF","laborCost":1.05,"materialCost":0.88,"equipmentCost":0.05,"notes":"Standard interior partition stud"},
    {"id":uid(),"name":"3-5/8 Inch 25 Gauge Steel Stud Install","category":"Framing","unit":"LF","laborCost":0.90,"materialCost":0.65,"equipmentCost":0.04,"notes":"Light gauge non-load bearing"},
    {"id":uid(),"name":"6 Inch 20 Gauge Steel Stud Install","category":"Framing","unit":"LF","laborCost":1.15,"materialCost":1.05,"equipmentCost":0.05,"notes":"Wider partition or chase wall"},
    {"id":uid(),"name":"6 Inch 18 Gauge Steel Stud Install","category":"Framing","unit":"LF","laborCost":1.25,"materialCost":1.35,"equipmentCost":0.08,"notes":"Semi-structural steel stud"},
    {"id":uid(),"name":"8 Inch 16 Gauge Steel Stud Install","category":"Framing","unit":"LF","laborCost":1.45,"materialCost":1.85,"equipmentCost":0.10,"notes":"Heavy structural applications"},
    {"id":uid(),"name":"3-5/8 Inch Steel Track - Floor and Ceiling","category":"Framing","unit":"LF","laborCost":0.55,"materialCost":0.45,"equipmentCost":0.03,"notes":"Track for 3-5/8 studs"},
    {"id":uid(),"name":"6 Inch Steel Track - Floor and Ceiling","category":"Framing","unit":"LF","laborCost":0.65,"materialCost":0.58,"equipmentCost":0.03,"notes":"Track for 6 inch studs"},
    {"id":uid(),"name":"8 Inch Steel Track - Floor and Ceiling","category":"Framing","unit":"LF","laborCost":0.75,"materialCost":0.75,"equipmentCost":0.04,"notes":"Track for 8 inch heavy studs"},
    {"id":uid(),"name":"Steel Stud Double Header Install","category":"Framing","unit":"LF","laborCost":2.50,"materialCost":1.80,"equipmentCost":0.10,"notes":"Over openings and doors"},
    {"id":uid(),"name":"Steel Stud Cripple Install - Per Opening","category":"Framing","unit":"EA","laborCost":18.00,"materialCost":6.50,"equipmentCost":0.50,"notes":"Above or below opening rough-in"},
    {"id":uid(),"name":"2x4 Wood Stud Framing - 16 OC","category":"Framing","unit":"LF","laborCost":1.25,"materialCost":0.75,"equipmentCost":0.05,"notes":"Residential interior partition"},
    {"id":uid(),"name":"2x4 Wood Stud Framing - 24 OC","category":"Framing","unit":"LF","laborCost":1.00,"materialCost":0.65,"equipmentCost":0.05,"notes":"Residential 24 in on center"},
    {"id":uid(),"name":"2x6 Wood Stud Framing - 16 OC","category":"Framing","unit":"LF","laborCost":1.40,"materialCost":1.05,"equipmentCost":0.05,"notes":"Exterior or insulated walls"},
    {"id":uid(),"name":"2x6 Wood Stud Framing - 24 OC","category":"Framing","unit":"LF","laborCost":1.15,"materialCost":0.90,"equipmentCost":0.05,"notes":"24 OC exterior wall"},
    {"id":uid(),"name":"2x8 Wood Stud Framing - 16 OC","category":"Framing","unit":"LF","laborCost":1.65,"materialCost":1.55,"equipmentCost":0.08,"notes":"Heavy exterior or tall partition"},
    {"id":uid(),"name":"2x10 Wood Stud Framing","category":"Framing","unit":"LF","laborCost":1.85,"materialCost":2.10,"equipmentCost":0.08,"notes":"Structural framing member"},
    {"id":uid(),"name":"2x12 Wood Stud Framing","category":"Framing","unit":"LF","laborCost":2.00,"materialCost":2.75,"equipmentCost":0.10,"notes":"Large structural member"},
    {"id":uid(),"name":"Pressure Treated Bottom Plate Install","category":"Framing","unit":"LF","laborCost":1.20,"materialCost":1.15,"equipmentCost":0.05,"notes":"PT plate at slab or waterproofed condition"},
    {"id":uid(),"name":"Double Top Plate Install - Wood","category":"Framing","unit":"LF","laborCost":1.45,"materialCost":1.50,"equipmentCost":0.05,"notes":"Load bearing double top plate"},
    {"id":uid(),"name":"Fire Blocking Install - Horizontal","category":"Framing","unit":"LF","laborCost":2.25,"materialCost":0.85,"equipmentCost":0.05,"notes":"Code-required blocking between studs"},
    {"id":uid(),"name":"Built-Up 2-Ply 2x6 Door Header","category":"Framing","unit":"EA","laborCost":65.00,"materialCost":22.00,"equipmentCost":2.00,"notes":"Per opening up to 4 ft wide"},
    {"id":uid(),"name":"Built-Up 3-Ply 2x8 Window Header","category":"Framing","unit":"EA","laborCost":85.00,"materialCost":38.00,"equipmentCost":2.00,"notes":"Per opening up to 6 ft wide"},
    {"id":uid(),"name":"LVL Beam Header - 3-1/2 x 9-1/4","category":"Framing","unit":"LF","laborCost":8.50,"materialCost":18.50,"equipmentCost":2.50,"notes":"Laminated veneer lumber header"},
    {"id":uid(),"name":"LVL Beam Header - 3-1/2 x 11-7/8","category":"Framing","unit":"LF","laborCost":9.50,"materialCost":24.00,"equipmentCost":2.50,"notes":"Wider span header"},
    {"id":uid(),"name":"PSL Post Column - 3-1/2 x 3-1/2","category":"Framing","unit":"LF","laborCost":6.50,"materialCost":12.50,"equipmentCost":0.50,"notes":"Parallel strand lumber post"},
    {"id":uid(),"name":"Solid Wood Blocking Between Studs","category":"Framing","unit":"EA","laborCost":12.00,"materialCost":3.50,"equipmentCost":0.50,"notes":"Per block, cabinetry or grab bar backing"},
    {"id":uid(),"name":"Joist Bridging - Steel Cross Strap","category":"Framing","unit":"EA","laborCost":4.50,"materialCost":2.25,"equipmentCost":0.25,"notes":"Per pair of joists"},
    {"id":uid(),"name":"Solid Wood Joist Blocking","category":"Framing","unit":"EA","laborCost":10.00,"materialCost":4.00,"equipmentCost":0.50,"notes":"End blocking or mid-span"},
    {"id":uid(),"name":"Rim Joist Install","category":"Framing","unit":"LF","laborCost":2.50,"materialCost":1.85,"equipmentCost":0.10,"notes":"Band joist at floor perimeter"},
    {"id":uid(),"name":"LVL Rim Board Install - 1-3/4 Inch","category":"Framing","unit":"LF","laborCost":2.75,"materialCost":3.25,"equipmentCost":0.10,"notes":"Engineered rim board"},
    {"id":uid(),"name":"2x10 Floor Joist - 16 OC","category":"Framing","unit":"LF","laborCost":1.75,"materialCost":2.10,"equipmentCost":0.10,"notes":"Residential floor joist"},
    {"id":uid(),"name":"2x12 Floor Joist - 12 OC","category":"Framing","unit":"LF","laborCost":1.95,"materialCost":2.75,"equipmentCost":0.10,"notes":"Heavy load floor joist"},
    {"id":uid(),"name":"I-Joist Install - 9-1/2 Inch 16 OC","category":"Framing","unit":"LF","laborCost":1.85,"materialCost":3.50,"equipmentCost":0.15,"notes":"Engineered floor I-joist"},
    {"id":uid(),"name":"I-Joist Install - 11-7/8 Inch 16 OC","category":"Framing","unit":"LF","laborCost":2.00,"materialCost":4.25,"equipmentCost":0.15,"notes":"Deeper I-joist larger span"},
    {"id":uid(),"name":"Girder Truss Install - Floor","category":"Framing","unit":"EA","laborCost":125.00,"materialCost":285.00,"equipmentCost":45.00,"notes":"Engineered floor truss"},
    {"id":uid(),"name":"3/4 Inch OSB Subfloor Install","category":"Framing","unit":"SF","laborCost":0.55,"materialCost":0.85,"equipmentCost":0.05,"notes":"Glued and screwed subfloor"},
    {"id":uid(),"name":"3/4 Inch Plywood Subfloor Install","category":"Framing","unit":"SF","laborCost":0.55,"materialCost":1.10,"equipmentCost":0.05,"notes":"Structural 1 plywood subfloor"},
    {"id":uid(),"name":"Roof Rafter Install - 2x8 24 OC","category":"Framing","unit":"LF","laborCost":2.50,"materialCost":1.55,"equipmentCost":0.20,"notes":"Conventionally framed rafter"},
    {"id":uid(),"name":"Roof Rafter Install - 2x10 24 OC","category":"Framing","unit":"LF","laborCost":2.75,"materialCost":2.10,"equipmentCost":0.20,"notes":"Heavier rafter with greater span"},
    {"id":uid(),"name":"Prefab Roof Truss Install","category":"Framing","unit":"EA","laborCost":85.00,"materialCost":185.00,"equipmentCost":35.00,"notes":"Per truss with crane set"},
    {"id":uid(),"name":"Ridge Board Install","category":"Framing","unit":"LF","laborCost":3.50,"materialCost":2.25,"equipmentCost":0.25,"notes":"2x10 ridge"},
    {"id":uid(),"name":"Collar Tie Install","category":"Framing","unit":"EA","laborCost":18.00,"materialCost":8.50,"equipmentCost":0.50,"notes":"Per pair at upper third of rafters"},
    {"id":uid(),"name":"Hip Rafter Install","category":"Framing","unit":"LF","laborCost":4.50,"materialCost":2.50,"equipmentCost":0.25,"notes":"Diagonal hip rafter"},
    {"id":uid(),"name":"Valley Rafter Install","category":"Framing","unit":"LF","laborCost":4.25,"materialCost":2.50,"equipmentCost":0.25,"notes":"Interior valley rafter"},
    {"id":uid(),"name":"Rafter Hurricane Tie Install","category":"Framing","unit":"EA","laborCost":3.50,"materialCost":2.25,"equipmentCost":0.00,"notes":"Metal connector per rafter"},
    {"id":uid(),"name":"7/16 Inch OSB Wall Sheathing Install","category":"Framing","unit":"SF","laborCost":0.45,"materialCost":0.55,"equipmentCost":0.04,"notes":"Standard exterior wall sheathing"},
    {"id":uid(),"name":"1/2 Inch Plywood Wall Sheathing Install","category":"Framing","unit":"SF","laborCost":0.48,"materialCost":0.75,"equipmentCost":0.04,"notes":"Structural plywood sheathing"},
    {"id":uid(),"name":"Rigid Foam Sheathing - 1 Inch Install","category":"Framing","unit":"SF","laborCost":0.42,"materialCost":0.55,"equipmentCost":0.02,"notes":"CI foam over sheathing"},
    {"id":uid(),"name":"7/16 Inch OSB Roof Sheathing Install","category":"Framing","unit":"SF","laborCost":0.55,"materialCost":0.55,"equipmentCost":0.08,"notes":"Roof deck sheathing"},
    {"id":uid(),"name":"5/8 Inch Plywood Roof Sheathing Install","category":"Framing","unit":"SF","laborCost":0.58,"materialCost":0.95,"equipmentCost":0.08,"notes":"Heavy roof deck"},
    {"id":uid(),"name":"Glulam Beam Install - 6x12","category":"Framing","unit":"LF","laborCost":18.50,"materialCost":45.00,"equipmentCost":5.00,"notes":"Glue laminated timber beam"},
    {"id":uid(),"name":"Glulam Beam Install - 6x16","category":"Framing","unit":"LF","laborCost":22.00,"materialCost":62.00,"equipmentCost":8.00,"notes":"Larger glulam"},
    {"id":uid(),"name":"Microlam LVL Install - 3-1/2 x 14","category":"Framing","unit":"LF","laborCost":12.50,"materialCost":32.00,"equipmentCost":3.00,"notes":"LVL beam structural"},
    {"id":uid(),"name":"Steel Post Base Anchor Install","category":"Framing","unit":"EA","laborCost":22.00,"materialCost":18.50,"equipmentCost":2.00,"notes":"Post-to-concrete connector"},
    {"id":uid(),"name":"Framing Angle and Joist Hanger Install","category":"Framing","unit":"EA","laborCost":8.50,"materialCost":5.25,"equipmentCost":0.25,"notes":"Per Simpson or USP connector"},
    {"id":uid(),"name":"Knee Wall Framing Build-Out","category":"Framing","unit":"LF","laborCost":5.50,"materialCost":2.25,"equipmentCost":0.25,"notes":"Short wall at attic perimeter"},
    {"id":uid(),"name":"Cripple Wall Framing Below Floor","category":"Framing","unit":"SF","laborCost":3.50,"materialCost":1.85,"equipmentCost":0.25,"notes":"Crawl space cripple framing"},
    {"id":uid(),"name":"Stud Wall Full Assembly Per SF","category":"Framing","unit":"SF","laborCost":2.50,"materialCost":1.25,"equipmentCost":0.10,"notes":"Includes plates, studs and blocking"},
    {"id":uid(),"name":"Lookout Framing for Gable Overhang","category":"Framing","unit":"EA","laborCost":18.00,"materialCost":7.50,"equipmentCost":0.50,"notes":"Per lookout member"},
    {"id":uid(),"name":"Garage Door Header - Double Ply LVL","category":"Framing","unit":"EA","laborCost":145.00,"materialCost":185.00,"equipmentCost":15.00,"notes":"16 ft opening double LVL"},
    {"id":uid(),"name":"Stairwell Rough Framing","category":"Framing","unit":"EA","laborCost":450.00,"materialCost":185.00,"equipmentCost":20.00,"notes":"Per floor stair rough opening"},
    {"id":uid(),"name":"Stair Stringer - Open Riser","category":"Framing","unit":"EA","laborCost":125.00,"materialCost":65.00,"equipmentCost":5.00,"notes":"Per stringer 3 piece set"},
    {"id":uid(),"name":"Stud Wall Demolition - Per SF of Wall","category":"Framing","unit":"SF","laborCost":0.65,"materialCost":0.00,"equipmentCost":0.08,"notes":"Tear out and stack"},
    {"id":uid(),"name":"Roof Framing Demolition - Per SF of Roof","category":"Framing","unit":"SF","laborCost":1.15,"materialCost":0.00,"equipmentCost":0.20,"notes":"After sheathing removal"},
    {"id":uid(),"name":"Floor Joist Demolition","category":"Framing","unit":"SF","laborCost":0.85,"materialCost":0.00,"equipmentCost":0.15,"notes":"Tear out floor joists"},
    {"id":uid(),"name":"Subfloor Demolition - OSB or Plywood","category":"Framing","unit":"SF","laborCost":0.55,"materialCost":0.00,"equipmentCost":0.10,"notes":"Pry up and stack"},
    {"id":uid(),"name":"Framing Debris Haul Away - Per Load","category":"Framing","unit":"EA","laborCost":95.00,"materialCost":0.00,"equipmentCost":185.00,"notes":"10-yard dumpster load"},
    {"id":uid(),"name":"Framing Nail Supply - 16D Sinker - Box","category":"Framing","unit":"EA","laborCost":0.00,"materialCost":52.00,"equipmentCost":0.00,"notes":"50 lb box sinker nails"},
    {"id":uid(),"name":"Structural Screw Supply - LedgerLOK Box","category":"Framing","unit":"EA","laborCost":0.00,"materialCost":38.00,"equipmentCost":0.00,"notes":"50 count structural screws"},
    {"id":uid(),"name":"Anchor Bolt Set - 1/2 Inch x 10 Inch","category":"Framing","unit":"EA","laborCost":8.50,"materialCost":3.25,"equipmentCost":0.50,"notes":"Sill plate to foundation anchor"},
    {"id":uid(),"name":"Hold Down Anchor Install - HDU2","category":"Framing","unit":"EA","laborCost":35.00,"materialCost":25.00,"equipmentCost":2.00,"notes":"Shear wall hold down anchor"},
    {"id":uid(),"name":"Strap Tie Install - Rafter to Plate","category":"Framing","unit":"EA","laborCost":5.50,"materialCost":3.50,"equipmentCost":0.25,"notes":"Metal strap hurricane tie"},
    {"id":uid(),"name":"Structural Framing Layout - Per 1000 SF","category":"Framing","unit":"EA","laborCost":450.00,"materialCost":0.00,"equipmentCost":25.00,"notes":"Layout, snap lines, confirm plumb"},
    {"id":uid(),"name":"Framing Inspection Correction Items","category":"Framing","unit":"HR","laborCost":95.00,"materialCost":12.00,"equipmentCost":5.00,"notes":"Framing correction labor per hour"},
    {"id":uid(),"name":"Structural Engineer Review - Per Visit","category":"Framing","unit":"EA","laborCost":350.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Field inspection and report"},
    {"id":uid(),"name":"Crane Rental for Beam Set - Half Day","category":"Framing","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":850.00,"notes":"50 ton crane 4 hrs"},
    {"id":uid(),"name":"Forklift Rental for Material Staging","category":"Framing","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":325.00,"notes":"Per day rental with operator"},
    {"id":uid(),"name":"Framing Nailer Air Compressor - Per Day","category":"Framing","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":55.00,"notes":"Small compressor and hose"},
    {"id":uid(),"name":"Temporary Wall Brace Install","category":"Framing","unit":"EA","laborCost":45.00,"materialCost":12.00,"equipmentCost":2.00,"notes":"Diagonal kicker per panel"},
    {"id":uid(),"name":"Wall Straightening and Plumbing - Per LF","category":"Framing","unit":"LF","laborCost":8.50,"materialCost":2.00,"equipmentCost":0.50,"notes":"Correct out-of-plumb walls"},
    {"id":uid(),"name":"Window Rough Opening Frame-Out","category":"Framing","unit":"EA","laborCost":55.00,"materialCost":18.00,"equipmentCost":2.00,"notes":"Sill cripples trimmer king"},
    {"id":uid(),"name":"Exterior Door Rough Opening Frame-Out","category":"Framing","unit":"EA","laborCost":65.00,"materialCost":22.00,"equipmentCost":2.00,"notes":"Full door RO framing"},
    {"id":uid(),"name":"Pocket Door Frame Kit Install","category":"Framing","unit":"EA","laborCost":95.00,"materialCost":125.00,"equipmentCost":5.00,"notes":"Pocket door frame hardware"},
    {"id":uid(),"name":"Furring Strip Install - 1x3 Wood","category":"Framing","unit":"LF","laborCost":0.55,"materialCost":0.35,"equipmentCost":0.02,"notes":"Strapping for level surface"},
    {"id":uid(),"name":"Ledger Board Attachment to Concrete","category":"Framing","unit":"LF","laborCost":8.50,"materialCost":4.25,"equipmentCost":1.50,"notes":"Tapcon or epoxy anchor"},
    {"id":uid(),"name":"Box Beam Build-Up - Hollow","category":"Framing","unit":"LF","laborCost":12.00,"materialCost":6.50,"equipmentCost":0.50,"notes":"Hollow decorative wood beam"},
    {"id":uid(),"name":"Scissor Truss Install - Vaulted Ceiling","category":"Framing","unit":"EA","laborCost":95.00,"materialCost":215.00,"equipmentCost":35.00,"notes":"Per truss with crane set"},
    {"id":uid(),"name":"Framing Protection Wrap - Per Week","category":"Framing","unit":"EA","laborCost":45.00,"materialCost":85.00,"equipmentCost":0.00,"notes":"Tarp and moisture protection"},
    {"id":uid(),"name":"Attic Knee Wall Framing - Per SF","category":"Framing","unit":"SF","laborCost":3.00,"materialCost":1.50,"equipmentCost":0.10,"notes":"Sloped ceiling knee wall"},
    {"id":uid(),"name":"Strongback Install for Floor Joists","category":"Framing","unit":"LF","laborCost":2.75,"materialCost":1.25,"equipmentCost":0.10,"notes":"Mid-span stiffener on joists"},
    {"id":uid(),"name":"Beam Pocket Preparation in Masonry","category":"Framing","unit":"EA","laborCost":65.00,"materialCost":12.00,"equipmentCost":15.00,"notes":"Core drill and grout beam pocket"},
    {"id":uid(),"name":"Metal Plate Repair - Notched or Bored Stud","category":"Framing","unit":"EA","laborCost":8.00,"materialCost":3.50,"equipmentCost":0.25,"notes":"Nail plate to protect cuts"},
    {"id":uid(),"name":"Bay Window Platform Framing","category":"Framing","unit":"EA","laborCost":185.00,"materialCost":95.00,"equipmentCost":10.00,"notes":"Cantilever platform per bay"},
    {"id":uid(),"name":"Cantilevered Floor Extension - Per SF","category":"Framing","unit":"SF","laborCost":4.50,"materialCost":2.50,"equipmentCost":0.25,"notes":"Per SF of cantilevered floor"},
    {"id":uid(),"name":"Tray Ceiling Framing Build-Down","category":"Framing","unit":"LF","laborCost":9.50,"materialCost":3.50,"equipmentCost":0.50,"notes":"Boxed ceiling perimeter"},
    {"id":uid(),"name":"Cathedral Ceiling Rafter - Insulated","category":"Framing","unit":"LF","laborCost":3.25,"materialCost":2.15,"equipmentCost":0.22,"notes":"With insulation baffle space"},
    {"id":uid(),"name":"Steel Beam - W8x15 Structural Per LF","category":"Framing","unit":"LF","laborCost":12.50,"materialCost":35.00,"equipmentCost":25.00,"notes":"Standard steel I-beam"},
    {"id":uid(),"name":"Wood Column - 6x6 Pressure Treated Per LF","category":"Framing","unit":"LF","laborCost":8.50,"materialCost":12.00,"equipmentCost":2.50,"notes":"Structural timber post"},
    {"id":uid(),"name":"Joist Hanger - Heavy Duty Sloped EA","category":"Framing","unit":"EA","laborCost":12.00,"materialCost":18.00,"equipmentCost":0.50,"notes":"Sloped seat joist hanger"},
]
