"""InsulationAgent — 100 items"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Fiberglass Batt ────────────────────────────────────────
    {"id":uid(),"name":"Fiberglass Batt Insulation R-11 - 2x4 Wall","category":"Insulation","unit":"SF","laborCost":0.22,"materialCost":0.28,"equipmentCost":0.00,"notes":"3.5 in batt for 2x4 wall"},
    {"id":uid(),"name":"Fiberglass Batt Insulation R-13 - 2x4 Wall","category":"Insulation","unit":"SF","laborCost":0.22,"materialCost":0.32,"equipmentCost":0.00,"notes":"High density 3.5 in batt"},
    {"id":uid(),"name":"Fiberglass Batt Insulation R-19 - 2x6 Wall","category":"Insulation","unit":"SF","laborCost":0.25,"materialCost":0.42,"equipmentCost":0.00,"notes":"5.5 in batt for 2x6 wall"},
    {"id":uid(),"name":"Fiberglass Batt Insulation R-21 - 2x6 Wall","category":"Insulation","unit":"SF","laborCost":0.25,"materialCost":0.48,"equipmentCost":0.00,"notes":"High density 5.5 in batt"},
    {"id":uid(),"name":"Fiberglass Batt Insulation R-30 - Attic","category":"Insulation","unit":"SF","laborCost":0.28,"materialCost":0.62,"equipmentCost":0.00,"notes":"Attic floor batt 9.5 in"},
    {"id":uid(),"name":"Fiberglass Batt Insulation R-38 - Attic","category":"Insulation","unit":"SF","laborCost":0.32,"materialCost":0.82,"equipmentCost":0.00,"notes":"Attic floor batt 12 in"},
    {"id":uid(),"name":"Kraft-Faced Fiberglass Batt - Vapor Retarder","category":"Insulation","unit":"SF","laborCost":0.25,"materialCost":0.38,"equipmentCost":0.00,"notes":"Paper facing toward warm side"},
    {"id":uid(),"name":"Unfaced Fiberglass Batt - 3.5 Inch","category":"Insulation","unit":"SF","laborCost":0.22,"materialCost":0.28,"equipmentCost":0.00,"notes":"No facing for second layer"},
    {"id":uid(),"name":"Floor Batt Insulation R-19 - Crawl Space","category":"Insulation","unit":"SF","laborCost":0.35,"materialCost":0.42,"equipmentCost":0.00,"notes":"Between floor joists"},
    {"id":uid(),"name":"Floor Batt Insulation R-30 - Crawl Space","category":"Insulation","unit":"SF","laborCost":0.38,"materialCost":0.62,"equipmentCost":0.00,"notes":"Deep batt between joists"},
    # ── Mineral Wool Batt ──────────────────────────────────────
    {"id":uid(),"name":"Mineral Wool Batt R-15 - 2x4 Wall","category":"Insulation","unit":"SF","laborCost":0.25,"materialCost":0.65,"equipmentCost":0.00,"notes":"Rockwool ComfortBatt 3.5 in"},
    {"id":uid(),"name":"Mineral Wool Batt R-23 - 2x6 Wall","category":"Insulation","unit":"SF","laborCost":0.28,"materialCost":0.88,"equipmentCost":0.00,"notes":"5.5 in mineral wool batt"},
    {"id":uid(),"name":"Mineral Wool Fire Insulation - Interior Wall","category":"Insulation","unit":"SF","laborCost":0.25,"materialCost":0.75,"equipmentCost":0.00,"notes":"Fire and sound rated partition"},
    {"id":uid(),"name":"Mineral Wool Safe and Sound - Partition","category":"Insulation","unit":"SF","laborCost":0.25,"materialCost":0.68,"equipmentCost":0.00,"notes":"Acoustic mineral wool partition"},
    # ── Blown-In Insulation ────────────────────────────────────
    {"id":uid(),"name":"Blown-In Cellulose - Attic R-38","category":"Insulation","unit":"SF","laborCost":0.25,"materialCost":0.55,"equipmentCost":0.05,"notes":"11 in cellulose attic floor"},
    {"id":uid(),"name":"Blown-In Cellulose - Attic R-49","category":"Insulation","unit":"SF","laborCost":0.28,"materialCost":0.72,"equipmentCost":0.05,"notes":"14 in cellulose attic floor"},
    {"id":uid(),"name":"Blown-In Cellulose - Attic R-60","category":"Insulation","unit":"SF","laborCost":0.32,"materialCost":0.90,"equipmentCost":0.05,"notes":"17 in cellulose attic floor"},
    {"id":uid(),"name":"Blown-In Fiberglass - Attic R-38","category":"Insulation","unit":"SF","laborCost":0.25,"materialCost":0.48,"equipmentCost":0.05,"notes":"11 in fiberglass attic"},
    {"id":uid(),"name":"Blown-In Fiberglass - Attic R-49","category":"Insulation","unit":"SF","laborCost":0.28,"materialCost":0.62,"equipmentCost":0.05,"notes":"14 in fiberglass attic"},
    {"id":uid(),"name":"Dense Pack Cellulose - Existing Wall Cavity","category":"Insulation","unit":"SF","laborCost":0.85,"materialCost":0.55,"equipmentCost":0.15,"notes":"Drill and fill retrofit"},
    {"id":uid(),"name":"Dense Pack Fiberglass - Existing Wall Cavity","category":"Insulation","unit":"SF","laborCost":0.85,"materialCost":0.48,"equipmentCost":0.15,"notes":"Retrofit wall blow-in"},
    # ── Open-Cell Spray Foam ───────────────────────────────────
    {"id":uid(),"name":"Open Cell Spray Foam - 3.5 Inch Wall","category":"Insulation","unit":"SF","laborCost":0.55,"materialCost":0.65,"equipmentCost":0.15,"notes":"R-13 open cell wall cavity"},
    {"id":uid(),"name":"Open Cell Spray Foam - 5.5 Inch Wall","category":"Insulation","unit":"SF","laborCost":0.65,"materialCost":0.95,"equipmentCost":0.18,"notes":"R-20 open cell 2x6 wall"},
    {"id":uid(),"name":"Open Cell Spray Foam - 6 Inch Attic","category":"Insulation","unit":"SF","laborCost":0.75,"materialCost":1.05,"equipmentCost":0.20,"notes":"Cathedral ceiling underside"},
    {"id":uid(),"name":"Open Cell Spray Foam - 12 Inch Attic","category":"Insulation","unit":"SF","laborCost":1.05,"materialCost":1.85,"equipmentCost":0.25,"notes":"R-44 deep attic application"},
    # ── Closed-Cell Spray Foam ─────────────────────────────────
    {"id":uid(),"name":"Closed Cell Spray Foam - 2 Inch Wall","category":"Insulation","unit":"SF","laborCost":0.85,"materialCost":1.25,"equipmentCost":0.20,"notes":"R-12 closed cell 2 in"},
    {"id":uid(),"name":"Closed Cell Spray Foam - 3 Inch Wall","category":"Insulation","unit":"SF","laborCost":1.05,"materialCost":1.85,"equipmentCost":0.22,"notes":"R-19 closed cell 3 in"},
    {"id":uid(),"name":"Closed Cell Spray Foam - 4 Inch Roof Deck","category":"Insulation","unit":"SF","laborCost":1.25,"materialCost":2.35,"equipmentCost":0.25,"notes":"R-25 spray under roof deck"},
    {"id":uid(),"name":"Closed Cell Spray Foam - 6 Inch Roof Deck","category":"Insulation","unit":"SF","laborCost":1.65,"materialCost":3.25,"equipmentCost":0.28,"notes":"R-39 deep roof deck spray"},
    {"id":uid(),"name":"Closed Cell Foam - Rim Joist Cavity","category":"Insulation","unit":"LF","laborCost":2.50,"materialCost":3.25,"equipmentCost":0.25,"notes":"2 in seal at rim joist"},
    {"id":uid(),"name":"Closed Cell Foam - Crawl Space Walls","category":"Insulation","unit":"SF","laborCost":0.85,"materialCost":1.25,"equipmentCost":0.20,"notes":"Foundation wall conditioning"},
    # ── Rigid Foam Boards ──────────────────────────────────────
    {"id":uid(),"name":"EPS Rigid Foam - 1 Inch Install","category":"Insulation","unit":"SF","laborCost":0.25,"materialCost":0.35,"equipmentCost":0.02,"notes":"R-4 expanded polystyrene"},
    {"id":uid(),"name":"EPS Rigid Foam - 2 Inch Install","category":"Insulation","unit":"SF","laborCost":0.28,"materialCost":0.65,"equipmentCost":0.02,"notes":"R-8 EPS board"},
    {"id":uid(),"name":"XPS Rigid Foam Pink Board - 1 Inch","category":"Insulation","unit":"SF","laborCost":0.25,"materialCost":0.45,"equipmentCost":0.02,"notes":"R-5 extruded polystyrene"},
    {"id":uid(),"name":"XPS Rigid Foam Pink Board - 2 Inch","category":"Insulation","unit":"SF","laborCost":0.28,"materialCost":0.85,"equipmentCost":0.02,"notes":"R-10 XPS board"},
    {"id":uid(),"name":"XPS Rigid Foam Pink Board - 3 Inch","category":"Insulation","unit":"SF","laborCost":0.30,"materialCost":1.25,"equipmentCost":0.03,"notes":"R-15 XPS board"},
    {"id":uid(),"name":"Polyiso Rigid Foam - 2 Inch","category":"Insulation","unit":"SF","laborCost":0.28,"materialCost":0.95,"equipmentCost":0.02,"notes":"R-13 polyisocyanurate board"},
    {"id":uid(),"name":"Polyiso Rigid Foam - 3 Inch","category":"Insulation","unit":"SF","laborCost":0.30,"materialCost":1.35,"equipmentCost":0.03,"notes":"R-19 polyiso board"},
    {"id":uid(),"name":"Rigid Foam Taped Joint and Seam Seal","category":"Insulation","unit":"LF","laborCost":0.25,"materialCost":0.18,"equipmentCost":0.00,"notes":"Foil tape at panel seams"},
    {"id":uid(),"name":"Rigid Foam Adhesive Attachment","category":"Insulation","unit":"SF","laborCost":0.10,"materialCost":0.08,"equipmentCost":0.00,"notes":"Construction adhesive apply"},
    # ── Radiant Barriers ──────────────────────────────────────
    {"id":uid(),"name":"Radiant Barrier Foil Install - Attic","category":"Insulation","unit":"SF","laborCost":0.22,"materialCost":0.22,"equipmentCost":0.02,"notes":"Foil staple to rafters"},
    {"id":uid(),"name":"Radiant Barrier - Sheathing Integral","category":"Insulation","unit":"SF","laborCost":0.00,"materialCost":0.18,"equipmentCost":0.00,"notes":"Foil-faced integral roof sheathing"},
    # ── Pipe and Duct Insulation ───────────────────────────────
    {"id":uid(),"name":"Pipe Insulation - Foam Tube 1/2 Inch Pipe","category":"Insulation","unit":"LF","laborCost":0.55,"materialCost":0.45,"equipmentCost":0.00,"notes":"Polyethylene foam tube"},
    {"id":uid(),"name":"Pipe Insulation - Foam Tube 3/4 Inch Pipe","category":"Insulation","unit":"LF","laborCost":0.60,"materialCost":0.52,"equipmentCost":0.00,"notes":"3/4 in pipe foam insulation"},
    {"id":uid(),"name":"Pipe Insulation - Foam Tube 1 Inch Pipe","category":"Insulation","unit":"LF","laborCost":0.65,"materialCost":0.65,"equipmentCost":0.00,"notes":"1 in pipe foam insulation"},
    {"id":uid(),"name":"Pipe Insulation - Fiberglass Wrap 2 Inch","category":"Insulation","unit":"LF","laborCost":1.25,"materialCost":1.85,"equipmentCost":0.05,"notes":"Fiberglass pipe wrap"},
    {"id":uid(),"name":"Duct Insulation Wrap - R-6 Flex Duct","category":"Insulation","unit":"LF","laborCost":1.50,"materialCost":1.25,"equipmentCost":0.05,"notes":"Flex duct with insulation jacket"},
    {"id":uid(),"name":"Rigid Duct Insulation Wrap - R-4 Board","category":"Insulation","unit":"SF","laborCost":0.85,"materialCost":0.75,"equipmentCost":0.05,"notes":"Duct board wrap with foil face"},
    {"id":uid(),"name":"Pipe Freeze Protection Heat Tape","category":"Insulation","unit":"LF","laborCost":2.25,"materialCost":3.50,"equipmentCost":0.25,"notes":"Electric heat cable on pipes"},
    # ── Vapor Control ─────────────────────────────────────────
    {"id":uid(),"name":"6 Mil Poly Vapor Barrier - Crawl Space","category":"Insulation","unit":"SF","laborCost":0.18,"materialCost":0.08,"equipmentCost":0.01,"notes":"Ground cover vapor barrier"},
    {"id":uid(),"name":"20 Mil Reinforced Vapor Barrier - Crawl Space","category":"Insulation","unit":"SF","laborCost":0.22,"materialCost":0.18,"equipmentCost":0.01,"notes":"Heavy duty crawl vapor barrier"},
    {"id":uid(),"name":"Vapor Retarder Paint - Interior","category":"Insulation","unit":"SF","laborCost":0.18,"materialCost":0.12,"equipmentCost":0.02,"notes":"Vapor retarder primer coat"},
    {"id":uid(),"name":"Variable Permeance Smart Vapor Retarder","category":"Insulation","unit":"SF","laborCost":0.28,"materialCost":0.45,"equipmentCost":0.02,"notes":"Intello or MemBrain membrane"},
    # ── Air Sealing ────────────────────────────────────────────
    {"id":uid(),"name":"Attic Air Sealing - Blower Door Guided","category":"Insulation","unit":"EA","laborCost":485.00,"materialCost":85.00,"equipmentCost":45.00,"notes":"Full attic air sealing package"},
    {"id":uid(),"name":"Rim Joist Air Sealing - Caulk and Foam","category":"Insulation","unit":"LF","laborCost":1.85,"materialCost":0.45,"equipmentCost":0.05,"notes":"Foam and caulk at rim joist"},
    {"id":uid(),"name":"Top Plate Air Sealing","category":"Insulation","unit":"LF","laborCost":0.75,"materialCost":0.25,"equipmentCost":0.02,"notes":"Caulk at top plate ceiling joint"},
    {"id":uid(),"name":"Window and Door Rough Opening Air Seal","category":"Insulation","unit":"EA","laborCost":8.50,"materialCost":1.85,"equipmentCost":0.25,"notes":"Low-expansion foam per opening"},
    {"id":uid(),"name":"Penetration Air Sealing - Per Opening","category":"Insulation","unit":"EA","laborCost":4.50,"materialCost":1.25,"equipmentCost":0.25,"notes":"Foam at pipe or wire penetration"},
    {"id":uid(),"name":"Blower Door Test - Diagnostic","category":"Insulation","unit":"EA","laborCost":285.00,"materialCost":0.00,"equipmentCost":85.00,"notes":"ACH50 blower door test report"},
    # ── Specialty ─────────────────────────────────────────────
    {"id":uid(),"name":"Attic Insulation Baffle Install","category":"Insulation","unit":"EA","laborCost":3.50,"materialCost":1.85,"equipmentCost":0.10,"notes":"Cardboard or foam baffle per bay"},
    {"id":uid(),"name":"Spray Foam - Gap Fill at Penetrations","category":"Insulation","unit":"EA","laborCost":2.50,"materialCost":0.85,"equipmentCost":0.15,"notes":"Canned foam at small gaps"},
    {"id":uid(),"name":"Insulation Removal - Blown Attic","category":"Insulation","unit":"SF","laborCost":0.45,"materialCost":0.00,"equipmentCost":0.18,"notes":"Vacuum removal and disposal"},
    {"id":uid(),"name":"Insulation Removal - Batt Wall","category":"Insulation","unit":"SF","laborCost":0.35,"materialCost":0.00,"equipmentCost":0.05,"notes":"Remove existing batt insulation"},
    {"id":uid(),"name":"Asbestos Insulation Abatement","category":"Insulation","unit":"SF","laborCost":8.50,"materialCost":0.00,"equipmentCost":5.50,"notes":"Licensed abatement contractor"},
    {"id":uid(),"name":"Thermal Imaging Scan - Insulation Audit","category":"Insulation","unit":"EA","laborCost":285.00,"materialCost":0.00,"equipmentCost":85.00,"notes":"IR scan and written findings"},
    {"id":uid(),"name":"Sound Insulation - STC Wall Upgrade","category":"Insulation","unit":"SF","laborCost":0.35,"materialCost":0.65,"equipmentCost":0.02,"notes":"Mineral wool for STC improvement"},
    {"id":uid(),"name":"Insulation Certificate and Test","category":"Insulation","unit":"EA","laborCost":45.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Post-install certificate of completion"},
    {"id":uid(),"name":"Blown-In Insulation Rental - Machine","category":"Insulation","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":65.00,"notes":"Blower machine rental per day"},
    {"id":uid(),"name":"Foam Board Mechanically Fastened - Screw","category":"Insulation","unit":"SF","laborCost":0.18,"materialCost":0.12,"equipmentCost":0.02,"notes":"Cap screws for exterior CI"},
    {"id":uid(),"name":"Mineral Wool Continuous Exterior - 1.5 Inch","category":"Insulation","unit":"SF","laborCost":0.45,"materialCost":1.15,"equipmentCost":0.04,"notes":"Exterior mineral wool CI layer"},
    {"id":uid(),"name":"Spray Foam Portable Kit - Single Use","category":"Insulation","unit":"EA","laborCost":0.00,"materialCost":85.00,"equipmentCost":0.00,"notes":"2-part foam kit 600 bf yield"},
    {"id":uid(),"name":"Radiant Floor Insulation - Under Slab","category":"Insulation","unit":"SF","laborCost":0.22,"materialCost":0.45,"equipmentCost":0.02,"notes":"2 in EPS under heated slab"},
    {"id":uid(),"name":"Cavity Wall Insulation - Injection Foam","category":"Insulation","unit":"SF","laborCost":1.25,"materialCost":0.95,"equipmentCost":0.15,"notes":"Injection foam retrofit method"},
    {"id":uid(),"name":"Insulation Flat Rate - New Construction","category":"Insulation","unit":"EA","laborCost":1850.00,"materialCost":1450.00,"equipmentCost":125.00,"notes":"Full house insulation package"},
    {"id":uid(),"name":"Taped Rigid Foam - Exterior Wall System","category":"Insulation","unit":"SF","laborCost":0.55,"materialCost":1.15,"equipmentCost":0.04,"notes":"Foil faced polyiso taped joints"},
    {"id":uid(),"name":"Acoustic Sealant - Electrical Box","category":"Insulation","unit":"EA","laborCost":3.50,"materialCost":1.25,"equipmentCost":0.10,"notes":"Acoustic putty at outlet box"},
    {"id":uid(),"name":"Insulated Concrete Form - Wall System","category":"Insulation","unit":"SF","laborCost":2.50,"materialCost":4.50,"equipmentCost":0.50,"notes":"ICF stay-in-place wall insulation"},
    {"id":uid(),"name":"Cellulose Blown-In - Dense Pack Wall SF","category":"Insulation","unit":"SF","laborCost":0.85,"materialCost":0.65,"equipmentCost":0.15,"notes":"Dense pack retrofit insulation"},
    {"id":uid(),"name":"Mineral Wool Loose Fill - Attic Per SF","category":"Insulation","unit":"SF","laborCost":0.45,"materialCost":1.15,"equipmentCost":0.10,"notes":"Blown mineral wool attic fill"},
    {"id":uid(),"name":"Wood Fiber Insulation - Rigid Board SF","category":"Insulation","unit":"SF","laborCost":0.65,"materialCost":1.85,"equipmentCost":0.05,"notes":"Natural wood fiber board"},
    {"id":uid(),"name":"Sheep Wool Insulation - Batt Per SF","category":"Insulation","unit":"SF","laborCost":0.55,"materialCost":2.25,"equipmentCost":0.02,"notes":"Natural sheep wool batt"},
    {"id":uid(),"name":"Denim Insulation - Recycled Cotton Batt SF","category":"Insulation","unit":"SF","laborCost":0.45,"materialCost":1.25,"equipmentCost":0.02,"notes":"Recycled cotton fiber batt"},
    {"id":uid(),"name":"Cork Insulation - Natural Rigid Board SF","category":"Insulation","unit":"SF","laborCost":0.65,"materialCost":3.50,"equipmentCost":0.05,"notes":"Sustainable natural cork board"},
    {"id":uid(),"name":"Vacuum Insulated Panel (VIP) - Per SF","category":"Insulation","unit":"SF","laborCost":2.50,"materialCost":12.50,"equipmentCost":0.15,"notes":"High performance R-60/inch"},
    {"id":uid(),"name":"Aerogel Insulation Blanket - Per SF","category":"Insulation","unit":"SF","laborCost":1.85,"materialCost":8.50,"equipmentCost":0.10,"notes":"Ultra-thin silica aerogel"},
    {"id":uid(),"name":"Foil Faced Bubble Insulation - Radiant SF","category":"Insulation","unit":"SF","laborCost":0.22,"materialCost":0.35,"equipmentCost":0.02,"notes":"Double bubble radiant barrier"},
    {"id":uid(),"name":"House Wrap - Grade D Paper LF","category":"Insulation","unit":"LF","laborCost":0.45,"materialCost":0.28,"equipmentCost":0.02,"notes":"Standard asphalt impregnated paper"},
    {"id":uid(),"name":"House Wrap - Synthetic Perforated LF","category":"Insulation","unit":"LF","laborCost":0.35,"materialCost":0.18,"equipmentCost":0.02,"notes":"Economy synthetic house wrap"},
    {"id":uid(),"name":"Liquid Applied Weather Barrier - Per SF","category":"Insulation","unit":"SF","laborCost":1.25,"materialCost":1.45,"equipmentCost":0.15,"notes":"Fluid applied air/water barrier"},
    {"id":uid(),"name":"Flashing Tape - 4 Inch Acrylic LF","category":"Insulation","unit":"LF","laborCost":0.45,"materialCost":0.85,"equipmentCost":0.02,"notes":"High adhesion acrylic tape"},
    {"id":uid(),"name":"Flashing Tape - 6 Inch Butyl LF","category":"Insulation","unit":"LF","laborCost":0.55,"materialCost":1.15,"equipmentCost":0.02,"notes":"Heavy duty butyl window tape"},
    {"id":uid(),"name":"Sill Sealer - 5.5 Inch Poly Foam LF","category":"Insulation","unit":"LF","laborCost":0.25,"materialCost":0.15,"equipmentCost":0.02,"notes":"Polyethylene sill gasket"},
    {"id":uid(),"name":"Caulking - Fire Retardant Per Tube","category":"Insulation","unit":"EA","laborCost":12.00,"materialCost":18.00,"equipmentCost":0.50,"notes":"Intumescent firestop sealant"},
    {"id":uid(),"name":"Acoustic Caulking - Per Tube","category":"Insulation","unit":"EA","laborCost":8.50,"materialCost":12.50,"equipmentCost":0.50,"notes":"Non-hardening acoustic sealant"},
    {"id":uid(),"name":"Spray Foam - 2-Part Kit 200 BF EA","category":"Insulation","unit":"EA","laborCost":0.00,"materialCost":350.00,"equipmentCost":0.00,"notes":"Small portable foam kit"},
    {"id":uid(),"name":"Spray Foam - 2-Part Kit 600 BF EA","category":"Insulation","unit":"EA","laborCost":0.00,"materialCost":850.00,"equipmentCost":0.00,"notes":"Large portable foam kit"},
    {"id":uid(),"name":"Attic Hatch - Insulated Tent Cover EA","category":"Insulation","unit":"EA","laborCost":45.00,"materialCost":125.00,"equipmentCost":0.00,"notes":"Zippered R-value attic cover"},
    {"id":uid(),"name":"Crawlspace Vapor Barrier - 10 Mil SF","category":"Insulation","unit":"SF","laborCost":0.35,"materialCost":0.45,"equipmentCost":0.02,"notes":"Reinforced poly vapor barrier"},
    {"id":uid(),"name":"Crawlspace Vapor Barrier - 20 Mil SF","category":"Insulation","unit":"SF","laborCost":0.45,"materialCost":0.85,"equipmentCost":0.05,"notes":"Extra heavy duty vapor barrier"},
]
