"""RoofingAgent — 100 items"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Tear-Off ───────────────────────────────────────────────
    {"id":uid(),"name":"Shingle Tear-Off - Single Layer","category":"Roofing","unit":"SQ","laborCost":45.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"Remove and dispose 1 layer shingles"},
    {"id":uid(),"name":"Shingle Tear-Off - Double Layer","category":"Roofing","unit":"SQ","laborCost":65.00,"materialCost":0.00,"equipmentCost":18.00,"notes":"Remove and dispose 2 layers shingles"},
    {"id":uid(),"name":"Flat Roof Tear-Off - EPDM","category":"Roofing","unit":"SQ","laborCost":55.00,"materialCost":0.00,"equipmentCost":12.00,"notes":"Peel and dispose rubber membrane"},
    {"id":uid(),"name":"Flat Roof Tear-Off - Built-Up Roofing","category":"Roofing","unit":"SQ","laborCost":95.00,"materialCost":0.00,"equipmentCost":25.00,"notes":"BUR tear-off to deck"},
    {"id":uid(),"name":"Wood Shake Tear-Off","category":"Roofing","unit":"SQ","laborCost":75.00,"materialCost":0.00,"equipmentCost":18.00,"notes":"Cedar shake removal"},
    # ── Underlayment ───────────────────────────────────────────
    {"id":uid(),"name":"15 Lb Felt Underlayment Install","category":"Roofing","unit":"SQ","laborCost":8.50,"materialCost":6.50,"equipmentCost":0.50,"notes":"Standard felt paper"},
    {"id":uid(),"name":"30 Lb Felt Underlayment Install","category":"Roofing","unit":"SQ","laborCost":9.50,"materialCost":9.50,"equipmentCost":0.50,"notes":"Heavier felt paper"},
    {"id":uid(),"name":"Synthetic Underlayment Install - Light","category":"Roofing","unit":"SQ","laborCost":9.00,"materialCost":12.00,"equipmentCost":0.50,"notes":"Polypropylene synthetic felt"},
    {"id":uid(),"name":"Synthetic Underlayment Install - Heavy Duty","category":"Roofing","unit":"SQ","laborCost":10.00,"materialCost":18.00,"equipmentCost":0.50,"notes":"Premium walk-able synthetic"},
    {"id":uid(),"name":"Ice and Water Shield - Eaves","category":"Roofing","unit":"SQ","laborCost":15.00,"materialCost":28.00,"equipmentCost":0.50,"notes":"Self-adhered first 6 ft at eave"},
    {"id":uid(),"name":"Ice and Water Shield - Full Coverage","category":"Roofing","unit":"SQ","laborCost":15.00,"materialCost":28.00,"equipmentCost":0.50,"notes":"Full roof self-adhered membrane"},
    # ── Asphalt Shingles ───────────────────────────────────────
    {"id":uid(),"name":"3-Tab Shingle Install - Standard","category":"Roofing","unit":"SQ","laborCost":75.00,"materialCost":85.00,"equipmentCost":5.00,"notes":"Economy 3-tab shingle"},
    {"id":uid(),"name":"Architectural Shingle Install - Std","category":"Roofing","unit":"SQ","laborCost":85.00,"materialCost":115.00,"equipmentCost":5.00,"notes":"Dimensional architectural shingle"},
    {"id":uid(),"name":"Architectural Shingle Install - Premium","category":"Roofing","unit":"SQ","laborCost":95.00,"materialCost":155.00,"equipmentCost":5.00,"notes":"50-year premium laminate"},
    {"id":uid(),"name":"Impact Resistant Class 4 Shingle Install","category":"Roofing","unit":"SQ","laborCost":95.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Hail rated Class 4 shingle"},
    {"id":uid(),"name":"Hip and Ridge Cap Shingles Install","category":"Roofing","unit":"LF","laborCost":2.25,"materialCost":3.50,"equipmentCost":0.25,"notes":"Pre-cut ridge cap shingles"},
    {"id":uid(),"name":"Starter Strip Shingles Install","category":"Roofing","unit":"LF","laborCost":0.85,"materialCost":1.25,"equipmentCost":0.10,"notes":"First course starter strip"},
    # ── Metal Roofing ──────────────────────────────────────────
    {"id":uid(),"name":"Standing Seam Metal Roof - 24 Gauge Steel","category":"Roofing","unit":"SQ","laborCost":185.00,"materialCost":285.00,"equipmentCost":15.00,"notes":"Hidden fastener standing seam"},
    {"id":uid(),"name":"Standing Seam Metal Roof - 26 Gauge","category":"Roofing","unit":"SQ","laborCost":165.00,"materialCost":235.00,"equipmentCost":12.00,"notes":"Lighter gauge standing seam"},
    {"id":uid(),"name":"R-Panel Metal Roof - 26 Gauge","category":"Roofing","unit":"SQ","laborCost":95.00,"materialCost":125.00,"equipmentCost":8.00,"notes":"Exposed fastener through-screw"},
    {"id":uid(),"name":"Corrugated Metal Roof - 29 Gauge","category":"Roofing","unit":"SQ","laborCost":75.00,"materialCost":85.00,"equipmentCost":6.00,"notes":"Economy corrugated panels"},
    {"id":uid(),"name":"Metal Shingle Install - Aluminum","category":"Roofing","unit":"SQ","laborCost":145.00,"materialCost":185.00,"equipmentCost":10.00,"notes":"Interlocking aluminum shingles"},
    {"id":uid(),"name":"Copper Standing Seam Install","category":"Roofing","unit":"SQ","laborCost":225.00,"materialCost":650.00,"equipmentCost":20.00,"notes":"Premium copper roof system"},
    # ── Flat Roofing ───────────────────────────────────────────
    {"id":uid(),"name":"TPO Membrane Install - 60 Mil","category":"Roofing","unit":"SQ","laborCost":85.00,"materialCost":125.00,"equipmentCost":12.00,"notes":"Thermoplastic polyolefin fully adhered"},
    {"id":uid(),"name":"TPO Membrane Install - 80 Mil","category":"Roofing","unit":"SQ","laborCost":95.00,"materialCost":155.00,"equipmentCost":12.00,"notes":"Heavy duty TPO fully adhered"},
    {"id":uid(),"name":"EPDM Membrane Install - 60 Mil","category":"Roofing","unit":"SQ","laborCost":75.00,"materialCost":95.00,"equipmentCost":8.00,"notes":"Rubber sheet fully adhered"},
    {"id":uid(),"name":"EPDM Membrane Install - 90 Mil","category":"Roofing","unit":"SQ","laborCost":85.00,"materialCost":125.00,"equipmentCost":8.00,"notes":"Heavy rubber sheet"},
    {"id":uid(),"name":"Modified Bitumen - Torch Down App","category":"Roofing","unit":"SQ","laborCost":85.00,"materialCost":95.00,"equipmentCost":10.00,"notes":"Torch applied modified bitumen"},
    {"id":uid(),"name":"Modified Bitumen - Cold Adhesive App","category":"Roofing","unit":"SQ","laborCost":75.00,"materialCost":105.00,"equipmentCost":5.00,"notes":"Cold adhesive application"},
    {"id":uid(),"name":"Built-Up Roofing - 3 Ply Gravel","category":"Roofing","unit":"SQ","laborCost":125.00,"materialCost":145.00,"equipmentCost":18.00,"notes":"3 ply BUR with gravel ballast"},
    {"id":uid(),"name":"PVC Membrane Install - 60 Mil","category":"Roofing","unit":"SQ","laborCost":95.00,"materialCost":145.00,"equipmentCost":12.00,"notes":"Welded PVC roofing membrane"},
    {"id":uid(),"name":"Roof Insulation - Polyiso 2 Inch","category":"Roofing","unit":"SQ","laborCost":18.00,"materialCost":55.00,"equipmentCost":2.00,"notes":"Polyisocyanurate insulation board"},
    {"id":uid(),"name":"Roof Insulation - Polyiso 3 Inch","category":"Roofing","unit":"SQ","laborCost":20.00,"materialCost":75.00,"equipmentCost":2.00,"notes":"3 inch polyiso flat roof insulation"},
    # ── Flashing ──────────────────────────────────────────────
    {"id":uid(),"name":"Step Flashing Install - Galvanized","category":"Roofing","unit":"LF","laborCost":4.50,"materialCost":2.50,"equipmentCost":0.25,"notes":"Step flash at wall juncture"},
    {"id":uid(),"name":"Counter Flashing Install","category":"Roofing","unit":"LF","laborCost":5.50,"materialCost":3.50,"equipmentCost":0.25,"notes":"Cap flashing in reglet"},
    {"id":uid(),"name":"Valley Flashing - Open Metal","category":"Roofing","unit":"LF","laborCost":6.50,"materialCost":4.50,"equipmentCost":0.50,"notes":"Open W-valley metal"},
    {"id":uid(),"name":"Pipe Jack Flashing Install","category":"Roofing","unit":"EA","laborCost":45.00,"materialCost":22.00,"equipmentCost":2.00,"notes":"Rubber boot pipe flashing"},
    {"id":uid(),"name":"Chimney Flashing - Full Set","category":"Roofing","unit":"EA","laborCost":195.00,"materialCost":85.00,"equipmentCost":5.00,"notes":"Counter step and cap flashing"},
    {"id":uid(),"name":"Drip Edge Install - Aluminum","category":"Roofing","unit":"LF","laborCost":0.85,"materialCost":0.65,"equipmentCost":0.05,"notes":"Eave and rake drip edge"},
    {"id":uid(),"name":"Skylights Curb Mount - 2x4 Fixed","category":"Roofing","unit":"EA","laborCost":285.00,"materialCost":485.00,"equipmentCost":15.00,"notes":"Factory curb mount fixed skylight"},
    {"id":uid(),"name":"Skylight - 2x4 Venting","category":"Roofing","unit":"EA","laborCost":350.00,"materialCost":650.00,"equipmentCost":15.00,"notes":"Venting skylight with flashing kit"},
    {"id":uid(),"name":"Skylight Curb Install Only","category":"Roofing","unit":"EA","laborCost":85.00,"materialCost":45.00,"equipmentCost":5.00,"notes":"2x4 or 2x6 curb framing"},
    # ── Ventilation ────────────────────────────────────────────
    {"id":uid(),"name":"Ridge Vent Install - Shingle Over","category":"Roofing","unit":"LF","laborCost":3.50,"materialCost":3.25,"equipmentCost":0.25,"notes":"Continuous ridge vent"},
    {"id":uid(),"name":"Soffit Vent Install - Aluminum Baffled","category":"Roofing","unit":"EA","laborCost":12.00,"materialCost":5.50,"equipmentCost":0.50,"notes":"8x16 soffit vent"},
    {"id":uid(),"name":"Power Attic Ventilator - Electric","category":"Roofing","unit":"EA","laborCost":125.00,"materialCost":175.00,"equipmentCost":8.00,"notes":"Solar or electric attic fan"},
    {"id":uid(),"name":"Roof Turbine Vent Install","category":"Roofing","unit":"EA","laborCost":65.00,"materialCost":45.00,"equipmentCost":3.00,"notes":"12 in wind turbine vent"},
    {"id":uid(),"name":"Static Box Vent Install","category":"Roofing","unit":"EA","laborCost":45.00,"materialCost":18.00,"equipmentCost":2.00,"notes":"4 in or 8 in box vent"},
    # ── Roof Decking ───────────────────────────────────────────
    {"id":uid(),"name":"Rotten Decking Replacement - Per Sheet","category":"Roofing","unit":"EA","laborCost":55.00,"materialCost":45.00,"equipmentCost":3.00,"notes":"4x8 sheet replace and nail"},
    {"id":uid(),"name":"Plank Decking Board Replacement - Per LF","category":"Roofing","unit":"LF","laborCost":4.50,"materialCost":2.85,"equipmentCost":0.50,"notes":"1x6 board on old homes"},
    # ── Gutters and Drainage ───────────────────────────────────
    {"id":uid(),"name":"Aluminum Gutter - 5 Inch K-Style","category":"Roofing","unit":"LF","laborCost":3.50,"materialCost":3.25,"equipmentCost":0.25,"notes":"Seamless aluminum gutter"},
    {"id":uid(),"name":"Aluminum Gutter - 6 Inch K-Style","category":"Roofing","unit":"LF","laborCost":4.00,"materialCost":4.25,"equipmentCost":0.25,"notes":"Large commercial gutter"},
    {"id":uid(),"name":"Half Round Gutter - Aluminum","category":"Roofing","unit":"LF","laborCost":4.00,"materialCost":4.85,"equipmentCost":0.25,"notes":"Traditional half round profile"},
    {"id":uid(),"name":"Copper Gutter - 5 Inch K-Style","category":"Roofing","unit":"LF","laborCost":6.50,"materialCost":22.00,"equipmentCost":0.50,"notes":"Premium copper gutter"},
    {"id":uid(),"name":"Steel Gutter - 5 Inch K-Style","category":"Roofing","unit":"LF","laborCost":3.75,"materialCost":4.50,"equipmentCost":0.25,"notes":"Painted steel gutter"},
    {"id":uid(),"name":"Downspout - 2x3 Inch Aluminum","category":"Roofing","unit":"LF","laborCost":2.50,"materialCost":1.85,"equipmentCost":0.10,"notes":"Standard rectangular downspout"},
    {"id":uid(),"name":"Downspout - 3x4 Inch Aluminum","category":"Roofing","unit":"LF","laborCost":2.75,"materialCost":2.25,"equipmentCost":0.10,"notes":"Large aluminum downspout"},
    {"id":uid(),"name":"Downspout Extension - Surface Drain","category":"Roofing","unit":"EA","laborCost":18.00,"materialCost":15.00,"equipmentCost":1.00,"notes":"Direct water away from foundation"},
    {"id":uid(),"name":"Gutter Guard Install - Metal Micro Mesh","category":"Roofing","unit":"LF","laborCost":2.50,"materialCost":6.50,"equipmentCost":0.25,"notes":"Premium micro mesh gutter cover"},
    {"id":uid(),"name":"Gutter Guard Install - Snap-In Screen","category":"Roofing","unit":"LF","laborCost":1.25,"materialCost":2.50,"equipmentCost":0.10,"notes":"Economy snap-in screen guard"},
    {"id":uid(),"name":"Gutter Cleaning - Single Story","category":"Roofing","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"Per cleaning visit"},
    # ── Specialty Roofing ──────────────────────────────────────
    {"id":uid(),"name":"Concrete Tile Roof Install","category":"Roofing","unit":"SQ","laborCost":145.00,"materialCost":195.00,"equipmentCost":12.00,"notes":"Concrete flat or barrel tile"},
    {"id":uid(),"name":"Clay Tile Roof Install","category":"Roofing","unit":"SQ","laborCost":185.00,"materialCost":350.00,"equipmentCost":15.00,"notes":"Premium clay mission tile"},
    {"id":uid(),"name":"Slate Roofing Install - Natural","category":"Roofing","unit":"SQ","laborCost":350.00,"materialCost":650.00,"equipmentCost":25.00,"notes":"Natural slate 3/4 in medium grade"},
    {"id":uid(),"name":"Synthetic Slate Install - Composite","category":"Roofing","unit":"SQ","laborCost":145.00,"materialCost":285.00,"equipmentCost":10.00,"notes":"Composite synthetic slate"},
    {"id":uid(),"name":"Cedar Shake Install - Hand Split","category":"Roofing","unit":"SQ","laborCost":165.00,"materialCost":245.00,"equipmentCost":10.00,"notes":"Hand split 24 in shake"},
    {"id":uid(),"name":"Solar Integrated Roofing - Per SQ","category":"Roofing","unit":"SQ","laborCost":285.00,"materialCost":850.00,"equipmentCost":25.00,"notes":"Building integrated photovoltaic"},
    # ── Repairs and Maintenance ────────────────────────────────
    {"id":uid(),"name":"Shingle Repair - Per Square","category":"Roofing","unit":"SQ","laborCost":125.00,"materialCost":85.00,"equipmentCost":5.00,"notes":"Spot repair existing roof"},
    {"id":uid(),"name":"Roof Leak Repair - Locate and Seal","category":"Roofing","unit":"EA","laborCost":185.00,"materialCost":25.00,"equipmentCost":10.00,"notes":"Find and seal single leak"},
    {"id":uid(),"name":"Re-Caulk Roof Penetrations","category":"Roofing","unit":"EA","laborCost":8.50,"materialCost":3.50,"equipmentCost":0.50,"notes":"Per penetration re-seal"},
    {"id":uid(),"name":"Roof Coating - Elastomeric Silver","category":"Roofing","unit":"SQ","laborCost":22.00,"materialCost":28.00,"equipmentCost":3.00,"notes":"Reflective elastomeric coat"},
    {"id":uid(),"name":"Flat Roof Ponding Repair - Tapered Insulation","category":"Roofing","unit":"SQ","laborCost":25.00,"materialCost":65.00,"equipmentCost":3.00,"notes":"Tapered polyiso for drainage"},
    # ── Equipment and Access ───────────────────────────────────
    {"id":uid(),"name":"Scaffolding Rental - Per SQ Per Week","category":"Roofing","unit":"SQ","laborCost":0.00,"materialCost":0.00,"equipmentCost":18.00,"notes":"Perimeter scaffold system"},
    {"id":uid(),"name":"Rooftop Debris Removal - Per Load","category":"Roofing","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":95.00,"notes":"Haul truck and dump fee"},
    {"id":uid(),"name":"Safety Harness System Setup - Per Day","category":"Roofing","unit":"EA","laborCost":45.00,"materialCost":0.00,"equipmentCost":25.00,"notes":"OSHA fall protection anchorage"},
    {"id":uid(),"name":"Roof Inspection and Report","category":"Roofing","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"Moisture scan and written report"},
    {"id":uid(),"name":"Infrared Moisture Scan - Per SQ","category":"Roofing","unit":"SQ","laborCost":8.50,"materialCost":0.00,"equipmentCost":5.50,"notes":"IR scan for trapped moisture"},
    {"id":uid(),"name":"Copper Roofing - Standing Seam Per SQ","category":"Roofing","unit":"SQ","laborCost":650.00,"materialCost":1250.00,"equipmentCost":45.00,"notes":"Premium copper roofing"},
    {"id":uid(),"name":"Zinc Roofing - Standing Seam Per SQ","category":"Roofing","unit":"SQ","laborCost":550.00,"materialCost":950.00,"equipmentCost":45.00,"notes":"Natural zinc roofing"},
    {"id":uid(),"name":"EPDM Membrane - 60 Mil Fully Adhered","category":"Roofing","unit":"SQ","laborCost":125.00,"materialCost":165.00,"equipmentCost":15.00,"notes":"Flat roof rubber membrane"},
    {"id":uid(),"name":"TPO Membrane - 60 Mil Heat Welded","category":"Roofing","unit":"SQ","laborCost":135.00,"materialCost":185.00,"equipmentCost":25.00,"notes":"White reflective thermoplastic"},
    {"id":uid(),"name":"Modified Bitumen - 2 Ply Torch Down","category":"Roofing","unit":"SQ","laborCost":115.00,"materialCost":145.00,"equipmentCost":15.00,"notes":"Multi-ply flat roofing"},
    {"id":uid(),"name":"Built-Up Roofing (BUR) - 4 Ply Gravel","category":"Roofing","unit":"SQ","laborCost":185.00,"materialCost":125.00,"equipmentCost":25.00,"notes":"Hot asphalt and gravel roof"},
    {"id":uid(),"name":"Green Roof System - Sedum Tray Per SF","category":"Roofing","unit":"SF","laborCost":12.00,"materialCost":28.00,"equipmentCost":8.50,"notes":"Extensive modular green roof"},
    {"id":uid(),"name":"Thatch Roofing - Synthetic Per SQ","category":"Roofing","unit":"SQ","laborCost":225.00,"materialCost":450.00,"equipmentCost":15.00,"notes":"Commercial synthetic thatch"},
    {"id":uid(),"name":"Wood Shingle Install - Eastern White Cedar","category":"Roofing","unit":"SQ","laborCost":145.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Grade A white cedar shingles"},
    {"id":uid(),"name":"Snow Guard - Bar System Per LF","category":"Roofing","unit":"LF","laborCost":12.00,"materialCost":22.00,"equipmentCost":2.00,"notes":"Continuous snow fence bar"},
    {"id":uid(),"name":"Snow Guard - Individual Pad EA","category":"Roofing","unit":"EA","laborCost":8.50,"materialCost":12.50,"equipmentCost":0.50,"notes":"Individual pad snow guard"},
    {"id":uid(),"name":"Roof Hatch - 30x36 Insulated EA","category":"Roofing","unit":"EA","laborCost":285.00,"materialCost":850.00,"equipmentCost":45.00,"notes":"Galvanized steel roof access"},
    {"id":uid(),"name":"Gravity Vent - 12 Inch Turbine EA","category":"Roofing","unit":"EA","laborCost":65.00,"materialCost":95.00,"equipmentCost":5.00,"notes":"Whirlybird attic vent"},
    {"id":uid(),"name":"Ridge Vent - Shingle Over 4 Ft PC","category":"Roofing","unit":"EA","laborCost":22.00,"materialCost":28.00,"equipmentCost":1.00,"notes":"Low profile ridge ventilation"},
    {"id":uid(),"name":"Static Vent - Box Style EA","category":"Roofing","unit":"EA","laborCost":35.00,"materialCost":18.00,"equipmentCost":1.50,"notes":"Metal or plastic box vent"},
    {"id":uid(),"name":"Eave Vent - Drip Edge Style LF","category":"Roofing","unit":"LF","laborCost":4.50,"materialCost":3.25,"equipmentCost":0.25,"notes":"Vented drip edge perimeter"},
    {"id":uid(),"name":"Soffit Vent - Continuous Aluminum LF","category":"Roofing","unit":"LF","laborCost":3.50,"materialCost":2.25,"equipmentCost":0.15,"notes":"Louvered soffit intake"},
    {"id":uid(),"name":"Fascia Board - 1x6 PVC Per LF","category":"Roofing","unit":"LF","laborCost":4.50,"materialCost":5.50,"equipmentCost":0.35,"notes":"Azek or similar PVC fascia"},
    {"id":uid(),"name":"Fascia Board - 1x8 Cedar Per LF","category":"Roofing","unit":"LF","laborCost":3.85,"materialCost":4.25,"equipmentCost":0.25,"notes":"Rough sawn cedar fascia"},
    {"id":uid(),"name":"Rake Edge Metal - 2 Inch Per LF","category":"Roofing","unit":"LF","laborCost":2.25,"materialCost":1.15,"equipmentCost":0.15,"notes":"Standard rake trim metal"},
    {"id":uid(),"name":"Counter Flashing - Surface Mounted LF","category":"Roofing","unit":"LF","laborCost":6.50,"materialCost":4.50,"equipmentCost":1.50,"notes":"Termination bar flashing"},
    {"id":uid(),"name":"Step Flashing - 4x4x8 Copper EA","category":"Roofing","unit":"EA","laborCost":4.50,"materialCost":8.50,"equipmentCost":0.10,"notes":"Chimney sidewall flashing"},
    {"id":uid(),"name":"Valley Flashing - Open W-Metal LF","category":"Roofing","unit":"LF","laborCost":5.50,"materialCost":6.50,"equipmentCost":1.25,"notes":"Metal W-valley flashing"},
]
