"""SidingAgent — 100 items"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Vinyl Siding ───────────────────────────────────────────
    {"id":uid(),"name":"Vinyl Siding - Horizontal Lap Double 4","category":"Siding","unit":"SF","laborCost":1.25,"materialCost":1.15,"equipmentCost":0.08,"notes":"Economy vinyl horizontal lap"},
    {"id":uid(),"name":"Vinyl Siding - Horizontal Lap Double 5","category":"Siding","unit":"SF","laborCost":1.25,"materialCost":1.25,"equipmentCost":0.08,"notes":"Standard double 5 inch lap"},
    {"id":uid(),"name":"Vinyl Siding - Dutch Lap Profile","category":"Siding","unit":"SF","laborCost":1.35,"materialCost":1.35,"equipmentCost":0.08,"notes":"Shadow line Dutch lap"},
    {"id":uid(),"name":"Vinyl Siding - Beaded Profile","category":"Siding","unit":"SF","laborCost":1.35,"materialCost":1.45,"equipmentCost":0.08,"notes":"Beaded edge vinyl panel"},
    {"id":uid(),"name":"Vinyl Siding - Shake Panel","category":"Siding","unit":"SF","laborCost":1.50,"materialCost":1.65,"equipmentCost":0.08,"notes":"Hand-split shake look vinyl"},
    {"id":uid(),"name":"Vinyl Siding - Vertical - Board and Batten","category":"Siding","unit":"SF","laborCost":1.45,"materialCost":1.55,"equipmentCost":0.08,"notes":"Vertical vinyl B&B style"},
    {"id":uid(),"name":"Vinyl Soffit Install - Vented","category":"Siding","unit":"SF","laborCost":1.50,"materialCost":1.25,"equipmentCost":0.10,"notes":"Vented vinyl soffit panel"},
    {"id":uid(),"name":"Vinyl Soffit Install - Solid","category":"Siding","unit":"SF","laborCost":1.50,"materialCost":1.10,"equipmentCost":0.10,"notes":"Solid vinyl soffit"},
    {"id":uid(),"name":"Vinyl Fascia Cover Install","category":"Siding","unit":"LF","laborCost":2.25,"materialCost":1.85,"equipmentCost":0.10,"notes":"Aluminum-backed vinyl fascia wrap"},
    {"id":uid(),"name":"Vinyl J-Channel Install","category":"Siding","unit":"LF","laborCost":0.85,"materialCost":0.55,"equipmentCost":0.05,"notes":"Receiving channel at openings"},
    # ── Fiber Cement ───────────────────────────────────────────
    {"id":uid(),"name":"Fiber Cement Lap Siding - 6.25 Inch","category":"Siding","unit":"SF","laborCost":1.85,"materialCost":1.75,"equipmentCost":0.10,"notes":"HardiePlank 6.25 lap"},
    {"id":uid(),"name":"Fiber Cement Lap Siding - 8.25 Inch","category":"Siding","unit":"SF","laborCost":1.75,"materialCost":1.85,"equipmentCost":0.10,"notes":"HardiePlank 8.25 lap"},
    {"id":uid(),"name":"Fiber Cement Lap Siding - 12 Inch Wide","category":"Siding","unit":"SF","laborCost":1.65,"materialCost":2.05,"equipmentCost":0.10,"notes":"Wide plank fiber cement"},
    {"id":uid(),"name":"Fiber Cement Panel Siding - 4x8","category":"Siding","unit":"SF","laborCost":1.65,"materialCost":1.55,"equipmentCost":0.10,"notes":"HardiePanel smooth or grooved"},
    {"id":uid(),"name":"Fiber Cement Shingle Siding - Staggered","category":"Siding","unit":"SF","laborCost":2.25,"materialCost":2.15,"equipmentCost":0.12,"notes":"Staggered bottom shingle course"},
    {"id":uid(),"name":"Fiber Cement Soffit Install","category":"Siding","unit":"SF","laborCost":1.75,"materialCost":1.45,"equipmentCost":0.10,"notes":"Primed fiber cement soffit"},
    {"id":uid(),"name":"Fiber Cement Fascia Install - 5/4x8","category":"Siding","unit":"LF","laborCost":2.50,"materialCost":2.25,"equipmentCost":0.10,"notes":"Flat fascia board fiber cement"},
    {"id":uid(),"name":"Fiber Cement Trim Install","category":"Siding","unit":"LF","laborCost":2.25,"materialCost":1.85,"equipmentCost":0.08,"notes":"Casing and corner trim pieces"},
    # ── Wood Siding ────────────────────────────────────────────
    {"id":uid(),"name":"Cedar Bevel Siding - 1x6 Clear A","category":"Siding","unit":"SF","laborCost":2.25,"materialCost":3.85,"equipmentCost":0.12,"notes":"Clear grade cedar lap"},
    {"id":uid(),"name":"Cedar Bevel Siding - 1x8 Knotty","category":"Siding","unit":"SF","laborCost":2.10,"materialCost":2.95,"equipmentCost":0.12,"notes":"Knotty cedar bevel"},
    {"id":uid(),"name":"Cedar Shingle Siding - 16 Inch Perfection","category":"Siding","unit":"SF","laborCost":2.85,"materialCost":3.25,"equipmentCost":0.12,"notes":"Cedar perfection shingle"},
    {"id":uid(),"name":"Shiplap Siding - Cedar 1x6","category":"Siding","unit":"SF","laborCost":2.25,"materialCost":2.85,"equipmentCost":0.10,"notes":"Horizontal shiplap profile"},
    {"id":uid(),"name":"Board and Batten Siding - Wood","category":"Siding","unit":"SF","laborCost":2.50,"materialCost":3.25,"equipmentCost":0.12,"notes":"Vertical B&B with 1x8 boards"},
    {"id":uid(),"name":"Tongue and Groove Siding - 1x6 Cedar","category":"Siding","unit":"SF","laborCost":2.35,"materialCost":3.15,"equipmentCost":0.10,"notes":"T&G vertical siding"},
    # ── Engineered Wood ────────────────────────────────────────
    {"id":uid(),"name":"LP SmartSide Lap Siding - 6 Inch","category":"Siding","unit":"SF","laborCost":1.75,"materialCost":1.55,"equipmentCost":0.10,"notes":"Engineered treated wood lap"},
    {"id":uid(),"name":"LP SmartSide Lap Siding - 12 Inch","category":"Siding","unit":"SF","laborCost":1.65,"materialCost":1.85,"equipmentCost":0.10,"notes":"Wide plank engineered wood"},
    {"id":uid(),"name":"LP SmartSide Panel - 4x8","category":"Siding","unit":"SF","laborCost":1.55,"materialCost":1.45,"equipmentCost":0.10,"notes":"Large format panel siding"},
    {"id":uid(),"name":"LP SmartSide Trim and Fascia","category":"Siding","unit":"LF","laborCost":2.00,"materialCost":1.65,"equipmentCost":0.08,"notes":"Engineered trim lumber"},
    # ── Metal Panels ───────────────────────────────────────────
    {"id":uid(),"name":"Steel Siding Panel - Horizontal Lap","category":"Siding","unit":"SF","laborCost":1.75,"materialCost":2.25,"equipmentCost":0.12,"notes":"Pre-finished steel panels"},
    {"id":uid(),"name":"Aluminum Siding Panel - Vertical","category":"Siding","unit":"SF","laborCost":1.85,"materialCost":2.15,"equipmentCost":0.12,"notes":"Vertical aluminum panels"},
    {"id":uid(),"name":"Metal Rainscreen Panel - Aluminum","category":"Siding","unit":"SF","laborCost":3.25,"materialCost":6.50,"equipmentCost":0.25,"notes":"Architectural rainscreen system"},
    {"id":uid(),"name":"Cor-Ten Steel Panel - Exposed","category":"Siding","unit":"SF","laborCost":2.85,"materialCost":8.50,"equipmentCost":0.18,"notes":"Weathering steel cladding"},
    # ── Stucco and EIFS ────────────────────────────────────────
    {"id":uid(),"name":"3-Coat Stucco System - Smooth Finish","category":"Siding","unit":"SF","laborCost":4.50,"materialCost":2.25,"equipmentCost":0.25,"notes":"Scratch brown and finish coat"},
    {"id":uid(),"name":"3-Coat Stucco System - Sand Finish","category":"Siding","unit":"SF","laborCost":4.25,"materialCost":2.10,"equipmentCost":0.25,"notes":"Light sand texture finish"},
    {"id":uid(),"name":"1-Coat Stucco System - Acrylic","category":"Siding","unit":"SF","laborCost":3.25,"materialCost":1.85,"equipmentCost":0.20,"notes":"Single coat acrylic plaster"},
    {"id":uid(),"name":"EIFS System - Class PB","category":"Siding","unit":"SF","laborCost":4.85,"materialCost":3.50,"equipmentCost":0.25,"notes":"Polymer-based exterior foam"},
    {"id":uid(),"name":"Stucco Repair - Patch Per SF","category":"Siding","unit":"SF","laborCost":8.50,"materialCost":2.50,"equipmentCost":0.50,"notes":"Match existing stucco texture"},
    # ── Brick and Stone ────────────────────────────────────────
    {"id":uid(),"name":"Brick Veneer Install - Running Bond","category":"Siding","unit":"SF","laborCost":8.50,"materialCost":6.50,"equipmentCost":0.50,"notes":"Standard modular brick veneer"},
    {"id":uid(),"name":"Brick Veneer Install - Flemish Bond","category":"Siding","unit":"SF","laborCost":10.50,"materialCost":6.50,"equipmentCost":0.50,"notes":"Decorative Flemish pattern"},
    {"id":uid(),"name":"Manufactured Stone Veneer Install","category":"Siding","unit":"SF","laborCost":8.50,"materialCost":9.50,"equipmentCost":0.50,"notes":"Cultured stone veneer"},
    {"id":uid(),"name":"Natural Thin Stone Veneer Install","category":"Siding","unit":"SF","laborCost":12.00,"materialCost":18.00,"equipmentCost":0.75,"notes":"Real thin-cut natural stone"},
    {"id":uid(),"name":"Fieldstone Veneer Install","category":"Siding","unit":"SF","laborCost":14.00,"materialCost":14.00,"equipmentCost":0.75,"notes":"Irregular fieldstone patterns"},
    # ── Air Barriers and WRB ───────────────────────────────────
    {"id":uid(),"name":"House Wrap Install - Tyvek Standard","category":"Siding","unit":"SF","laborCost":0.18,"materialCost":0.18,"equipmentCost":0.02,"notes":"Standard DuPont Tyvek WRB"},
    {"id":uid(),"name":"House Wrap Install - Tyvek Commercial D","category":"Siding","unit":"SF","laborCost":0.20,"materialCost":0.28,"equipmentCost":0.02,"notes":"Commercial grade house wrap"},
    {"id":uid(),"name":"Zip System Sheathing With Tape","category":"Siding","unit":"SF","laborCost":0.45,"materialCost":0.95,"equipmentCost":0.04,"notes":"Integrated air barrier sheathing"},
    {"id":uid(),"name":"Self-Adhered WRB - Premium","category":"Siding","unit":"SF","laborCost":0.35,"materialCost":0.55,"equipmentCost":0.03,"notes":"Peel-and-stick air barrier"},
    {"id":uid(),"name":"Window and Door Flashing Tape","category":"Siding","unit":"LF","laborCost":0.45,"materialCost":0.55,"equipmentCost":0.02,"notes":"Self-adhered flashing at openings"},
    # ── Trim and Accessories ───────────────────────────────────
    {"id":uid(),"name":"PVC Trim Board - 5/4x6","category":"Siding","unit":"LF","laborCost":1.85,"materialCost":1.55,"equipmentCost":0.05,"notes":"Cellular PVC corner or casing"},
    {"id":uid(),"name":"PVC Trim Board - 5/4x4","category":"Siding","unit":"LF","laborCost":1.65,"materialCost":1.25,"equipmentCost":0.05,"notes":"Narrow PVC trim"},
    {"id":uid(),"name":"Aluminum Corner Post - 4 Inch","category":"Siding","unit":"LF","laborCost":1.50,"materialCost":1.25,"equipmentCost":0.05,"notes":"Inside or outside corner post"},
    {"id":uid(),"name":"Starter Strip for Vinyl Siding","category":"Siding","unit":"LF","laborCost":0.55,"materialCost":0.45,"equipmentCost":0.02,"notes":"First course alignment strip"},
    {"id":uid(),"name":"Siding Nailing Hem - Utility Trim","category":"Siding","unit":"LF","laborCost":0.65,"materialCost":0.35,"equipmentCost":0.02,"notes":"J channel or finishing trim"},
    # ── Demolition and Repair ──────────────────────────────────
    {"id":uid(),"name":"Siding Removal and Disposal - Vinyl","category":"Siding","unit":"SF","laborCost":0.35,"materialCost":0.00,"equipmentCost":0.05,"notes":"Strip and stack for disposal"},
    {"id":uid(),"name":"Siding Removal and Disposal - Wood","category":"Siding","unit":"SF","laborCost":0.48,"materialCost":0.00,"equipmentCost":0.08,"notes":"Pry and remove wood siding"},
    {"id":uid(),"name":"Siding Removal - Brick Veneer","category":"Siding","unit":"SF","laborCost":2.50,"materialCost":0.00,"equipmentCost":0.85,"notes":"Demo and haul brick veneer"},
    {"id":uid(),"name":"Wood Rot Repair Behind Siding - Per SF","category":"Siding","unit":"SF","laborCost":5.50,"materialCost":3.25,"equipmentCost":0.50,"notes":"Sheathing or stud repair"},
    {"id":uid(),"name":"Siding Caulk and Seal - Per LF","category":"Siding","unit":"LF","laborCost":1.25,"materialCost":0.45,"equipmentCost":0.05,"notes":"Paintable sealant at transitions"},
    # ── Specialty ─────────────────────────────────────────────
    {"id":uid(),"name":"Rain Screen Batten System Install","category":"Siding","unit":"SF","laborCost":0.55,"materialCost":0.38,"equipmentCost":0.04,"notes":"1x3 vertical ventilation battens"},
    {"id":uid(),"name":"Insulated Vinyl Siding Install","category":"Siding","unit":"SF","laborCost":1.45,"materialCost":2.25,"equipmentCost":0.08,"notes":"Foam-backed vinyl siding"},
    {"id":uid(),"name":"Siding Painting - Masonry or Stucco","category":"Siding","unit":"SF","laborCost":0.65,"materialCost":0.28,"equipmentCost":0.04,"notes":"Two coat exterior masonry paint"},
    {"id":uid(),"name":"Fiber Cement Factory Paint - 2 Coat","category":"Siding","unit":"SF","laborCost":0.00,"materialCost":0.35,"equipmentCost":0.00,"notes":"Factory applied premium paint"},
    {"id":uid(),"name":"Siding Inspection and Report","category":"Siding","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"Moisture probe and written report"},
    {"id":uid(),"name":"Reclaimed Wood Siding Install","category":"Siding","unit":"SF","laborCost":3.25,"materialCost":4.85,"equipmentCost":0.15,"notes":"Salvaged barn wood siding"},
    {"id":uid(),"name":"Thermally Modified Wood Siding","category":"Siding","unit":"SF","laborCost":2.85,"materialCost":5.50,"equipmentCost":0.12,"notes":"Heat treated durability wood"},
    {"id":uid(),"name":"Porcelain Tile Exterior Cladding","category":"Siding","unit":"SF","laborCost":8.50,"materialCost":6.50,"equipmentCost":0.50,"notes":"Large format tile cladding"},
    {"id":uid(),"name":"ACM Panel System - Aluminum Composite","category":"Siding","unit":"SF","laborCost":4.50,"materialCost":8.50,"equipmentCost":0.50,"notes":"Aluminum composite cladding panels"},
    {"id":uid(),"name":"Hardboard Siding Install","category":"Siding","unit":"SF","laborCost":1.50,"materialCost":1.15,"equipmentCost":0.08,"notes":"Hardboard pressed siding"},
    {"id":uid(),"name":"Cementboard Stucco Base Coat","category":"Siding","unit":"SF","laborCost":1.85,"materialCost":1.10,"equipmentCost":0.10,"notes":"Scratch coat on cement board"},
    {"id":uid(),"name":"Drainable Housewrap with Fabric Face","category":"Siding","unit":"SF","laborCost":0.22,"materialCost":0.35,"equipmentCost":0.02,"notes":"Drainage plane house wrap"},
    {"id":uid(),"name":"Continuous Rigid Insulation Thermal Break","category":"Siding","unit":"SF","laborCost":0.55,"materialCost":0.85,"equipmentCost":0.04,"notes":"1 inch XPS or polyiso CI layer"},
    {"id":uid(),"name":"Fiber Cement Priming - Field Cut Ends","category":"Siding","unit":"EA","laborCost":0.75,"materialCost":0.15,"equipmentCost":0.00,"notes":"Per cut end prime per code"},
    {"id":uid(),"name":"Siding Attachment - Wind Load Zone","category":"Siding","unit":"SF","laborCost":0.25,"materialCost":0.08,"equipmentCost":0.01,"notes":"Additional fastening at corners"},
    {"id":uid(),"name":"Expansion Gap and Caulk at Grade","category":"Siding","unit":"LF","laborCost":1.25,"materialCost":0.35,"equipmentCost":0.02,"notes":"1 inch clearance with backer rod"},
    {"id":uid(),"name":"Metal Flashing at Base of Wall","category":"Siding","unit":"LF","laborCost":1.85,"materialCost":1.25,"equipmentCost":0.08,"notes":"Sheet metal Z-flashing at grade"},
    {"id":uid(),"name":"Deck Ledger Flashing at Wall","category":"Siding","unit":"LF","laborCost":2.50,"materialCost":1.85,"equipmentCost":0.08,"notes":"Water-tight flashing at deck attach"},
    {"id":uid(),"name":"Fiber Cement Gable End Install","category":"Siding","unit":"SF","laborCost":2.25,"materialCost":1.85,"equipmentCost":0.20,"notes":"High reach gable end siding"},
    {"id":uid(),"name":"Vinyl Wrap Kit - Window and Door","category":"Siding","unit":"EA","laborCost":45.00,"materialCost":22.00,"equipmentCost":2.00,"notes":"Per opening trim wrap kit"},
    {"id":uid(),"name":"Inside Corner Post - Vinyl","category":"Siding","unit":"LF","laborCost":1.25,"materialCost":0.75,"equipmentCost":0.04,"notes":"Inside corner vinyl post"},
    {"id":uid(),"name":"Undersill Trim at Window","category":"Siding","unit":"LF","laborCost":1.25,"materialCost":0.55,"equipmentCost":0.03,"notes":"Snap lock under sill trim"},
    {"id":uid(),"name":"Steel Siding - 26 Gauge Box Rib Per SF","category":"Siding","unit":"SF","laborCost":2.25,"materialCost":2.85,"equipmentCost":0.15,"notes":"Industrial steel siding"},
    {"id":uid(),"name":"Corrugated Metal Siding - Galvanized SF","category":"Roofing","unit":"SF","laborCost":1.85,"materialCost":2.15,"equipmentCost":0.10,"notes":"Standard corrugated metal"},
    {"id":uid(),"name":"Slate Siding - Vertical Install Per SF","category":"Siding","unit":"SF","laborCost":6.50,"materialCost":7.50,"equipmentCost":0.45,"notes":"Natural slate wall cladding"},
    {"id":uid(),"name":"Limestone Veneer - Thin Cut Per SF","category":"Siding","unit":"SF","laborCost":8.50,"materialCost":12.50,"equipmentCost":0.55,"notes":"Natural thin-cut limestone"},
    {"id":uid(),"name":"Sandstone Veneer - Mortar Set Per SF","category":"Siding","unit":"SF","laborCost":9.50,"materialCost":14.00,"equipmentCost":0.65,"notes":"Full bed sandstone veneer"},
    {"id":uid(),"name":"River Rock Siding - Hand Set Per SF","category":"Siding","unit":"SF","laborCost":12.00,"materialCost":8.50,"equipmentCost":0.75,"notes":"Natural river stone veneer"},
    {"id":uid(),"name":"Ledger Stone Siding - Dry Stack Per SF","category":"Siding","unit":"SF","laborCost":7.50,"materialCost":9.50,"equipmentCost":0.45,"notes":"Pre-assembled ledger panels"},
    {"id":uid(),"name":"PVC Siding - Vertical Board and Batten SF","category":"Siding","unit":"SF","laborCost":2.25,"materialCost":1.85,"equipmentCost":0.10,"notes":"Premium vinyl vertical siding"},
    {"id":uid(),"name":"Fiber Cement Soffit - Vented 12 Inch LF","category":"Siding","unit":"LF","laborCost":1.25,"materialCost":1.85,"equipmentCost":0.15,"notes":"HardieSoffit or equivalent"},
    {"id":uid(),"name":"Fiber Cement Soffit - Solid 16 Inch LF","category":"Siding","unit":"LF","laborCost":1.25,"materialCost":2.10,"equipmentCost":0.15,"notes":"Solid fiber cement soffit"},
    {"id":uid(),"name":"Aluminum Soffit - Triple 4 Vented LF","category":"Siding","unit":"LF","laborCost":0.95,"materialCost":1.25,"equipmentCost":0.08,"notes":"Vented aluminum soffit panel"},
    {"id":uid(),"name":"Aluminum Soffit - Solid Triple 4 LF","category":"Siding","unit":"LF","laborCost":0.95,"materialCost":1.15,"equipmentCost":0.08,"notes":"Solid aluminum soffit panel"},
    {"id":uid(),"name":"J-Channel Trim - Color Matched LF","category":"Siding","unit":"LF","laborCost":0.55,"materialCost":0.45,"equipmentCost":0.02,"notes":"Vinyl J-channel trim"},
    {"id":uid(),"name":"F-Channel Trim - Aluminum LF","category":"Siding","unit":"LF","laborCost":0.65,"materialCost":0.85,"equipmentCost":0.02,"notes":"Aluminum soffit support F-channel"},
    {"id":uid(),"name":"Starter Strip - Galvanized LF","category":"Siding","unit":"LF","laborCost":0.45,"materialCost":0.35,"equipmentCost":0.02,"notes":"Metal siding starter strip"},
    {"id":uid(),"name":"H-Molding Joint Cover EA","category":"Siding","unit":"EA","laborCost":1.25,"materialCost":2.50,"equipmentCost":0.05,"notes":"Joint cover for horizontal runs"},
    {"id":uid(),"name":"Siding Vent - Exhaust 4 Inch EA","category":"Siding","unit":"EA","laborCost":22.00,"materialCost":35.00,"equipmentCost":2.00,"notes":"Dryer or bath vent for siding"},
    {"id":uid(),"name":"Siding Vent - Intake 4 Inch EA","category":"Siding","unit":"EA","laborCost":22.00,"materialCost":28.00,"equipmentCost":2.00,"notes":"Fresh air intake for siding"},
    {"id":uid(),"name":"Kick-Out Flashing - Polypropylene EA","category":"Siding","unit":"EA","laborCost":4.50,"materialCost":12.50,"equipmentCost":0.50,"notes":"Diverter flashing at wall/roof"},
    {"id":uid(),"name":"Scaffolding Set-Up for Siding EA","category":"Siding","unit":"EA","laborCost":185.00,"materialCost":0.00,"equipmentCost":250.00,"notes":"Equipment transport and assembly"},
]
