"""FlooringAgent — 100 items"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Hardwood Flooring ─────────────────────────────────────
    {"id":uid(),"name":"Solid Hardwood Floor - 3/4 Inch 3.25 Wide Oak","category":"Flooring","unit":"SF","laborCost":3.25,"materialCost":4.85,"equipmentCost":0.25,"notes":"3/4 solid oak T&G nail-down"},
    {"id":uid(),"name":"Solid Hardwood Floor - 3/4 Inch 5 Wide Oak","category":"Flooring","unit":"SF","laborCost":3.50,"materialCost":5.50,"equipmentCost":0.28,"notes":"Wide plank solid oak"},
    {"id":uid(),"name":"Solid Hardwood Floor - 3/4 Inch Maple","category":"Flooring","unit":"SF","laborCost":3.25,"materialCost":5.25,"equipmentCost":0.25,"notes":"Hard maple solid floor"},
    {"id":uid(),"name":"Solid Hardwood Floor - 3/4 Inch Hickory","category":"Flooring","unit":"SF","laborCost":3.50,"materialCost":6.50,"equipmentCost":0.28,"notes":"Hickory solid hardwood"},
    {"id":uid(),"name":"Engineered Hardwood - 1/2 Inch 5 Wide Oak","category":"Flooring","unit":"SF","laborCost":2.85,"materialCost":4.25,"equipmentCost":0.18,"notes":"Engineered OAK glue or float"},
    {"id":uid(),"name":"Engineered Hardwood - 3/4 Inch 7.5 Wide","category":"Flooring","unit":"SF","laborCost":3.25,"materialCost":6.25,"equipmentCost":0.22,"notes":"Wide plank engineered floor"},
    {"id":uid(),"name":"Hardwood Floor Sand and Refinish - 3 Coat","category":"Flooring","unit":"SF","laborCost":2.50,"materialCost":0.85,"equipmentCost":0.45,"notes":"Drum sand screen and 3 coats poly"},
    {"id":uid(),"name":"Hardwood Floor Screen and Recoat","category":"Flooring","unit":"SF","laborCost":0.85,"materialCost":0.35,"equipmentCost":0.15,"notes":"Scuff sand and single recoat"},
    {"id":uid(),"name":"Hardwood Floor Stain - Per Coat","category":"Flooring","unit":"SF","laborCost":0.55,"materialCost":0.22,"equipmentCost":0.08,"notes":"Penetrating oil stain"},
    {"id":uid(),"name":"Parquet Hardwood Floor Install","category":"Flooring","unit":"SF","laborCost":4.50,"materialCost":5.50,"equipmentCost":0.35,"notes":"12x12 parquet glue-down"},
    # ── LVP and LVT ───────────────────────────────────────────
    {"id":uid(),"name":"LVP Flooring - Economy Click Lock","category":"Flooring","unit":"SF","laborCost":1.85,"materialCost":1.25,"equipmentCost":0.10,"notes":"6mm LVP floating floor"},
    {"id":uid(),"name":"LVP Flooring - Mid Grade 8mm","category":"Flooring","unit":"SF","laborCost":1.85,"materialCost":2.25,"equipmentCost":0.10,"notes":"8mm LVP with attached pad"},
    {"id":uid(),"name":"LVP Flooring - Premium 12mm","category":"Flooring","unit":"SF","laborCost":1.95,"materialCost":3.25,"equipmentCost":0.10,"notes":"12mm premium LVP click"},
    {"id":uid(),"name":"LVP Flooring - Glue Down","category":"Flooring","unit":"SF","laborCost":2.25,"materialCost":2.85,"equipmentCost":0.12,"notes":"Glue-down LVP sheets"},
    {"id":uid(),"name":"LVT Tile - Peel and Stick","category":"Flooring","unit":"SF","laborCost":0.85,"materialCost":0.85,"equipmentCost":0.05,"notes":"Self-adhesive commercial tile"},
    {"id":uid(),"name":"LVT Tile - Glue Down 12x24","category":"Flooring","unit":"SF","laborCost":1.85,"materialCost":2.25,"equipmentCost":0.10,"notes":"Full spread adhesive LVT"},
    # ── Laminate ──────────────────────────────────────────────
    {"id":uid(),"name":"Laminate Flooring - 7mm Economy","category":"Flooring","unit":"SF","laborCost":1.65,"materialCost":0.85,"equipmentCost":0.08,"notes":"Economy click laminate"},
    {"id":uid(),"name":"Laminate Flooring - 12mm Premium","category":"Flooring","unit":"SF","laborCost":1.75,"materialCost":1.85,"equipmentCost":0.08,"notes":"Premium thick laminate"},
    # ── Ceramic and Porcelain Tile ─────────────────────────────
    {"id":uid(),"name":"Ceramic Floor Tile - 12x12 Set","category":"Flooring","unit":"SF","laborCost":4.50,"materialCost":1.85,"equipmentCost":0.25,"notes":"Floor setting with grout"},
    {"id":uid(),"name":"Ceramic Floor Tile - 18x18 Set","category":"Flooring","unit":"SF","laborCost":4.75,"materialCost":2.25,"equipmentCost":0.28,"notes":"18x18 ceramic floor install"},
    {"id":uid(),"name":"Ceramic Floor Tile - 12x24 Set","category":"Flooring","unit":"SF","laborCost":5.00,"materialCost":2.85,"equipmentCost":0.30,"notes":"Large format ceramic tile"},
    {"id":uid(),"name":"Porcelain Floor Tile - 12x12 Set","category":"Flooring","unit":"SF","laborCost":5.00,"materialCost":2.85,"equipmentCost":0.30,"notes":"Porcelain floor tile set"},
    {"id":uid(),"name":"Porcelain Floor Tile - 24x24 Set","category":"Flooring","unit":"SF","laborCost":5.50,"materialCost":3.85,"equipmentCost":0.35,"notes":"Large format 24x24 porcelain"},
    {"id":uid(),"name":"Porcelain Plank Tile - 4x24 Wood Look","category":"Flooring","unit":"SF","laborCost":5.25,"materialCost":3.25,"equipmentCost":0.30,"notes":"Wood plank porcelain stack"},
    {"id":uid(),"name":"Mosaic Tile Floor - Glass or Stone","category":"Flooring","unit":"SF","laborCost":8.50,"materialCost":5.50,"equipmentCost":0.45,"notes":"Small format mesh mounted tile"},
    {"id":uid(),"name":"Tile Grout - Unsanded Standard","category":"Flooring","unit":"SF","laborCost":0.75,"materialCost":0.18,"equipmentCost":0.05,"notes":"Unsanded grout at joints"},
    {"id":uid(),"name":"Tile Grout - Epoxy Grout","category":"Flooring","unit":"SF","laborCost":1.25,"materialCost":0.55,"equipmentCost":0.08,"notes":"Premium stain resistant epoxy"},
    {"id":uid(),"name":"Tile Underlayment - Schluter DITRA","category":"Flooring","unit":"SF","laborCost":0.55,"materialCost":1.85,"equipmentCost":0.05,"notes":"Uncoupling membrane for tile"},
    {"id":uid(),"name":"Tile Underlayment - 1/4 Inch Cement Board","category":"Flooring","unit":"SF","laborCost":0.65,"materialCost":0.55,"equipmentCost":0.05,"notes":"Cement board tile backer floor"},
    # ── Natural Stone ─────────────────────────────────────────
    {"id":uid(),"name":"Travertine Tile Floor - 12x12 Set","category":"Flooring","unit":"SF","laborCost":6.50,"materialCost":5.50,"equipmentCost":0.40,"notes":"Natural travertine floor fill and hone"},
    {"id":uid(),"name":"Marble Floor Tile - 12x12 Polished","category":"Flooring","unit":"SF","laborCost":7.50,"materialCost":8.50,"equipmentCost":0.50,"notes":"Marble tile set and sealer"},
    {"id":uid(),"name":"Slate Floor Tile - 12x12 Natural Cleft","category":"Flooring","unit":"SF","laborCost":6.50,"materialCost":5.25,"equipmentCost":0.40,"notes":"Slate natural floor install"},
    {"id":uid(),"name":"Limestone Floor Tile - 16x16","category":"Flooring","unit":"SF","laborCost":7.00,"materialCost":7.50,"equipmentCost":0.45,"notes":"Filled honed limestone"},
    {"id":uid(),"name":"Natural Stone Sealer - Per Coat","category":"Flooring","unit":"SF","laborCost":0.35,"materialCost":0.22,"equipmentCost":0.03,"notes":"Penetrating stone sealer"},
    # ── Carpet ────────────────────────────────────────────────
    {"id":uid(),"name":"Carpet - Level Loop Commercial","category":"Flooring","unit":"SF","laborCost":1.25,"materialCost":1.25,"equipmentCost":0.08,"notes":"Commercial loop tile or broadloom"},
    {"id":uid(),"name":"Carpet - Cut Pile Residential Economy","category":"Flooring","unit":"SF","laborCost":1.25,"materialCost":1.65,"equipmentCost":0.08,"notes":"Standard residential carpet"},
    {"id":uid(),"name":"Carpet - Cut Pile Premium Thick","category":"Flooring","unit":"SF","laborCost":1.45,"materialCost":2.85,"equipmentCost":0.10,"notes":"Premium plush or Saxony carpet"},
    {"id":uid(),"name":"Carpet - Frieze Pattern","category":"Flooring","unit":"SF","laborCost":1.35,"materialCost":2.25,"equipmentCost":0.08,"notes":"Textured frieze carpet"},
    {"id":uid(),"name":"Carpet Pad - 8 lb Rebond","category":"Flooring","unit":"SF","laborCost":0.25,"materialCost":0.38,"equipmentCost":0.02,"notes":"Standard rebond carpet cushion"},
    {"id":uid(),"name":"Carpet Pad - 10 lb Premium","category":"Flooring","unit":"SF","laborCost":0.25,"materialCost":0.55,"equipmentCost":0.02,"notes":"Thick premium carpet pad"},
    {"id":uid(),"name":"Carpet Removal and Disposal","category":"Flooring","unit":"SF","laborCost":0.55,"materialCost":0.00,"equipmentCost":0.08,"notes":"Pull staples and roll for disposal"},
    # ── Specialty Flooring ─────────────────────────────────────
    {"id":uid(),"name":"Cork Flooring - Floating Click","category":"Flooring","unit":"SF","laborCost":1.85,"materialCost":2.85,"equipmentCost":0.10,"notes":"Cork click floor tiles"},
    {"id":uid(),"name":"Bamboo Flooring - Solid Strand","category":"Flooring","unit":"SF","laborCost":2.85,"materialCost":3.85,"equipmentCost":0.20,"notes":"Strand woven bamboo nail down"},
    {"id":uid(),"name":"Rubber Flooring - Commercial Gym","category":"Flooring","unit":"SF","laborCost":1.85,"materialCost":2.85,"equipmentCost":0.12,"notes":"Rubber roll or tile glue down"},
    {"id":uid(),"name":"Concrete Floor - Polished","category":"Flooring","unit":"SF","laborCost":2.50,"materialCost":0.45,"equipmentCost":1.25,"notes":"Grind and polish existing slab"},
    {"id":uid(),"name":"Concrete Floor - Microtopping","category":"Flooring","unit":"SF","laborCost":3.50,"materialCost":2.25,"equipmentCost":0.35,"notes":"Thin cement microtopping coat"},
    {"id":uid(),"name":"Heated Floor Mat - Electric","category":"Flooring","unit":"SF","laborCost":2.25,"materialCost":5.50,"equipmentCost":0.25,"notes":"Electric radiant mat under tile"},
    # ── SubFloor Prep ─────────────────────────────────────────
    {"id":uid(),"name":"Subfloor Leveling - Self-Leveling Compound","category":"Flooring","unit":"SF","laborCost":0.55,"materialCost":0.75,"equipmentCost":0.10,"notes":"Up to 1/4 inch pour"},
    {"id":uid(),"name":"Subfloor Repair - Squeaky Floor Screws","category":"Flooring","unit":"SF","laborCost":0.35,"materialCost":0.05,"equipmentCost":0.02,"notes":"Counter-sink screws squeak stop"},
    {"id":uid(),"name":"Plywood Underlayment Install - 1/4 Inch","category":"Flooring","unit":"SF","laborCost":0.65,"materialCost":0.45,"equipmentCost":0.05,"notes":"Smooth substrate for resilient"},
    {"id":uid(),"name":"Plywood Underlayment Install - 1/2 Inch","category":"Flooring","unit":"SF","laborCost":0.75,"materialCost":0.65,"equipmentCost":0.05,"notes":"Added stiffness for tile"},
    {"id":uid(),"name":"Old Floor Removal - Vinyl Sheet","category":"Flooring","unit":"SF","laborCost":0.45,"materialCost":0.00,"equipmentCost":0.05,"notes":"Peel up and dispose sheet vinyl"},
    {"id":uid(),"name":"Old Floor Removal - Ceramic Tile","category":"Flooring","unit":"SF","laborCost":1.85,"materialCost":0.00,"equipmentCost":0.25,"notes":"Chip out and dispose tile"},
    {"id":uid(),"name":"Old Floor Removal - Hardwood","category":"Flooring","unit":"SF","laborCost":1.25,"materialCost":0.00,"equipmentCost":0.15,"notes":"Pry up and dispose hardwood"},
    # ── Transitions and Accessories ────────────────────────────
    {"id":uid(),"name":"Floor Transition Strip - T-Molding","category":"Flooring","unit":"LF","laborCost":2.50,"materialCost":3.85,"equipmentCost":0.15,"notes":"Transition between same height floors"},
    {"id":uid(),"name":"Floor Transition Strip - Reducer","category":"Flooring","unit":"LF","laborCost":2.50,"materialCost":3.25,"equipmentCost":0.15,"notes":"Step down transition"},
    {"id":uid(),"name":"Floor Transition Strip - End Cap","category":"Flooring","unit":"LF","laborCost":2.00,"materialCost":2.85,"equipmentCost":0.10,"notes":"Flooring termination at wall"},
    {"id":uid(),"name":"Threshold - Wood or Metal","category":"Flooring","unit":"EA","laborCost":22.00,"materialCost":18.00,"equipmentCost":0.50,"notes":"Door opening threshold"},
    {"id":uid(),"name":"Quarter Round Trim Install","category":"Flooring","unit":"LF","laborCost":0.85,"materialCost":0.55,"equipmentCost":0.03,"notes":"Base shoe at floating floor"},
    {"id":uid(),"name":"Stair Nose Install - Wood","category":"Flooring","unit":"EA","laborCost":28.00,"materialCost":22.00,"equipmentCost":0.50,"notes":"Matching stair nose per step"},
    {"id":uid(),"name":"Stair Tread Install - Solid Oak","category":"Flooring","unit":"EA","laborCost":55.00,"materialCost":45.00,"equipmentCost":1.00,"notes":"Solid stair tread and riser"},
    {"id":uid(),"name":"Carpet Runner on Stairs","category":"Flooring","unit":"LF","laborCost":8.50,"materialCost":6.50,"equipmentCost":0.35,"notes":"Waterfall or Hollywood stair wrap"},
    {"id":uid(),"name":"Floor Glue Supply - Adhesive Per Gallon","category":"Flooring","unit":"EA","laborCost":0.00,"materialCost":28.00,"equipmentCost":0.00,"notes":"Floor adhesive 1 gallon"},
    {"id":uid(),"name":"Floor Moisture Barrier - 6 Mil Poly","category":"Flooring","unit":"SF","laborCost":0.08,"materialCost":0.05,"equipmentCost":0.00,"notes":"Vapor barrier under floating floor"},
    {"id":uid(),"name":"Tile Spacers Supply - Per Bag","category":"Flooring","unit":"EA","laborCost":0.00,"materialCost":5.50,"equipmentCost":0.00,"notes":"100 pc tile spacer bag"},
    {"id":uid(),"name":"Thinset Mortar Supply - 50 lb Bag","category":"Flooring","unit":"EA","laborCost":0.00,"materialCost":18.00,"equipmentCost":0.00,"notes":"Modified thinset per bag"},
    {"id":uid(),"name":"Flooring Inspection - Pre-Install","category":"Flooring","unit":"EA","laborCost":95.00,"materialCost":0.00,"equipmentCost":15.00,"notes":"Moisture and substrate inspection"},
    {"id":uid(),"name":"Terrazzo Flooring - Poured-in-Place Per SF","category":"Flooring","unit":"SF","laborCost":12.00,"materialCost":18.00,"equipmentCost":25.00,"notes":"Premium seamless terrazzo"},
    {"id":uid(),"name":"Rubber Tile Flooring - Interlocking SF","category":"Flooring","unit":"SF","laborCost":0.85,"materialCost":4.50,"equipmentCost":0.10,"notes":"Gym or weight room tiles"},
    {"id":uid(),"name":"Rubber Sheet Flooring - Commercial SF","category":"Flooring","unit":"SF","laborCost":1.25,"materialCost":5.50,"equipmentCost":0.25,"notes":"Glue down commercial rubber"},
    {"id":uid(),"name":"Sports Floor - Maple Plank Per SF","category":"Flooring","unit":"SF","laborCost":3.50,"materialCost":12.50,"equipmentCost":1.50,"notes":"Hardwood basketball court floor"},
    {"id":uid(),"name":"Athletic Turf - Indoor Per SF","category":"Flooring","unit":"SF","laborCost":1.15,"materialCost":3.85,"equipmentCost":0.50,"notes":"Padded indoor turf field"},
    {"id":uid(),"name":"Pebble Stone Tile Floor - Per SF","category":"Flooring","unit":"SF","laborCost":4.50,"materialCost":6.50,"equipmentCost":0.35,"notes":"Shower floor pebble tile"},
    {"id":uid(),"name":"River Rock Floor - Sieve Set Per SF","category":"Flooring","unit":"SF","laborCost":12.00,"materialCost":14.00,"equipmentCost":0.75,"notes":"Hand set river rock flooring"},
    {"id":uid(),"name":"Mosaic Tile Floor - Intricate Per SF","category":"Flooring","unit":"SF","laborCost":15.00,"materialCost":12.00,"equipmentCost":0.55,"notes":"Small format mosaic pattern"},
    {"id":uid(),"name":"Medallion Inlay - Stone or Wood EA","category":"Flooring","unit":"EA","laborCost":285.00,"materialCost":450.00,"equipmentCost":15.00,"notes":"Pre-assembled floor medallion"},
    {"id":uid(),"name":"Border Inlay - Contrasting Wood LF","category":"Flooring","unit":"LF","laborCost":12.00,"materialCost":8.50,"equipmentCost":5.00,"notes":"Custom feature strip border"},
    {"id":uid(),"name":"Radiant Heat Film - Under Laminate SF","category":"Flooring","unit":"SF","laborCost":1.25,"materialCost":3.50,"equipmentCost":0.25,"notes":"Electric film heat system"},
    {"id":uid(),"name":"Sound Mat - High Density Rubber SF","category":"Flooring","unit":"SF","laborCost":0.35,"materialCost":1.15,"equipmentCost":0.02,"notes":"Acoustic floor underlayment"},
    {"id":uid(),"name":"Cork Underlayment - 1/4 Inch SF","category":"Flooring","unit":"SF","laborCost":0.25,"materialCost":0.85,"equipmentCost":0.02,"notes":"Natural cork underlayment"},
    {"id":uid(),"name":"Plywood Subfloor - 3/4 Inch T&G SF","category":"Flooring","unit":"SF","laborCost":0.85,"materialCost":1.15,"equipmentCost":0.15,"notes":"Subfloor replacement or overlay"},
    {"id":uid(),"name":"Cement Backer Board - 1/4 Inch SF","category":"Flooring","unit":"SF","laborCost":0.95,"materialCost":0.85,"equipmentCost":0.10,"notes":"Tile substrate over wood"},
    {"id":uid(),"name":"Self-Leveling Underlayment - Per SF","category":"Flooring","unit":"SF","laborCost":0.55,"materialCost":1.25,"equipmentCost":0.15,"notes":"Pourable floor leveler"},
    {"id":uid(),"name":"Gypcrete Pour - Second Floor Per SF","category":"Flooring","unit":"SF","laborCost":0.45,"materialCost":1.10,"equipmentCost":0.85,"notes":"Lightweight concrete topping"},
    {"id":uid(),"name":"Dust Barrier Setup - ZipWall EA","category":"Flooring","unit":"EA","laborCost":45.00,"materialCost":18.00,"equipmentCost":12.00,"notes":"Temp dust wall for renovation"},
    {"id":uid(),"name":"HEPA Air Scrubber Rental - Per Day","category":"Flooring","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":65.00,"notes":"Portable air filtration unit"},
    {"id":uid(),"name":"Floor Sanding Machine Rental - Per Day","category":"Flooring","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":85.00,"notes":"Drum or orbital floor sander"},
    {"id":uid(),"name":"Tile Saw Rental - Large Format Per Day","category":"Flooring","unit":"EA","laborCost":0.00,"materialCost":0.00,"equipmentCost":125.00,"notes":"Skid set bridge saw rental"},
    {"id":uid(),"name":"Vinyl Wall Base - 4 Inch Cove LF","category":"Flooring","unit":"LF","laborCost":0.85,"materialCost":1.15,"equipmentCost":0.02,"notes":"Commercial glue-on wall base"},
    {"id":uid(),"name":"Metal Transition - Schlueter Reno-U LF","category":"Flooring","unit":"LF","laborCost":2.25,"materialCost":3.85,"equipmentCost":0.15,"notes":"Premium aluminum floor trim"},
    {"id":uid(),"name":"Metal Transition - Schlueter Dilex LF","category":"Flooring","unit":"LF","laborCost":3.50,"materialCost":5.50,"equipmentCost":0.25,"notes":"Movement joint transition"},
    {"id":uid(),"name":"Floor Drain - Stainless Steel EA","category":"Flooring","unit":"EA","laborCost":125.00,"materialCost":85.00,"equipmentCost":10.00,"notes":"Linear or square floor drain"},
    {"id":uid(),"name":"Cleanout Cover - Brass EA","category":"Flooring","unit":"EA","laborCost":45.00,"materialCost":65.00,"equipmentCost":2.00,"notes":"Access cover for sewer line"},
    {"id":uid(),"name":"Floor Vent - Flush Mount Wood EA","category":"Flooring","unit":"EA","laborCost":12.00,"materialCost":28.00,"equipmentCost":2.00,"notes":"Matching wood HVAC floor vent"},
    {"id":uid(),"name":"Professional Floor Buff and Wax EA","category":"Flooring","unit":"EA","laborCost":185.00,"materialCost":45.00,"equipmentCost":65.00,"notes":"Commercial VCT maintenance"},
    {"id":uid(),"name":"Flooring Disposal - Landfill Fee Per Ton","category":"Flooring","unit":"EA","laborCost":0.00,"materialCost":125.00,"equipmentCost":0.00,"notes":"Disposal cost at local facility"},
    {"id":uid(),"name":"Site Measurement and Flooring Estimate","category":"Flooring","unit":"EA","laborCost":85.00,"materialCost":0.00,"equipmentCost":5.00,"notes":"Professional measurement trip"},
]
