"""PaintingAgent — 100 items"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Interior Walls ─────────────────────────────────────────
    {"id":uid(),"name":"Interior Wall Paint - 1 Coat Latex","category":"Painting","unit":"SF","laborCost":0.35,"materialCost":0.12,"equipmentCost":0.02,"notes":"Single coat touch up painting"},
    {"id":uid(),"name":"Interior Wall Paint - 2 Coat Latex","category":"Painting","unit":"SF","laborCost":0.55,"materialCost":0.22,"equipmentCost":0.02,"notes":"Standard 2 coat wall painting"},
    {"id":uid(),"name":"Interior Wall Paint - Primer Plus 2 Coats","category":"Painting","unit":"SF","laborCost":0.75,"materialCost":0.32,"equipmentCost":0.03,"notes":"Full primer plus 2 finish coats"},
    {"id":uid(),"name":"Interior Wall Paint - Semi-Gloss","category":"Painting","unit":"SF","laborCost":0.58,"materialCost":0.28,"equipmentCost":0.02,"notes":"Semi-gloss sheen kitchen or bath"},
    {"id":uid(),"name":"Interior Wall Paint - High Gloss","category":"Painting","unit":"SF","laborCost":0.65,"materialCost":0.35,"equipmentCost":0.02,"notes":"High gloss trim-grade wall"},
    {"id":uid(),"name":"Interior Wall Primer Only - PVA","category":"Painting","unit":"SF","laborCost":0.22,"materialCost":0.10,"equipmentCost":0.02,"notes":"PVA drywall primer one coat"},
    {"id":uid(),"name":"Interior Wall Paint - Accent Color","category":"Painting","unit":"SF","laborCost":0.75,"materialCost":0.35,"equipmentCost":0.02,"notes":"Full mask and cut accent wall"},
    # ── Interior Ceilings ─────────────────────────────────────
    {"id":uid(),"name":"Interior Ceiling Paint - 2 Coat Flat","category":"Painting","unit":"SF","laborCost":0.45,"materialCost":0.18,"equipmentCost":0.05,"notes":"Ceiling flat latex two coats"},
    {"id":uid(),"name":"Interior Ceiling Paint - 1 Coat Touch Up","category":"Painting","unit":"SF","laborCost":0.30,"materialCost":0.10,"equipmentCost":0.04,"notes":"Single coat scuff and repaint"},
    {"id":uid(),"name":"Interior Ceiling Paint - Primer Plus 2 Coats","category":"Painting","unit":"SF","laborCost":0.65,"materialCost":0.28,"equipmentCost":0.05,"notes":"Ceiling primer and two coats"},
    # ── Interior Trim ──────────────────────────────────────────
    {"id":uid(),"name":"Interior Trim Paint - Baseboard Per LF","category":"Painting","unit":"LF","laborCost":1.25,"materialCost":0.25,"equipmentCost":0.05,"notes":"Baseboard cut and roll"},
    {"id":uid(),"name":"Interior Trim Paint - Crown Molding Per LF","category":"Painting","unit":"LF","laborCost":1.50,"materialCost":0.28,"equipmentCost":0.05,"notes":"Crown molding paint"},
    {"id":uid(),"name":"Interior Trim Paint - Window Casing Per Opening","category":"Painting","unit":"EA","laborCost":35.00,"materialCost":5.50,"equipmentCost":0.50,"notes":"Per window full casing paint"},
    {"id":uid(),"name":"Interior Trim Paint - Door Casing Per Opening","category":"Painting","unit":"EA","laborCost":28.00,"materialCost":4.50,"equipmentCost":0.50,"notes":"Per door casing both sides"},
    {"id":uid(),"name":"Interior Door Paint - Hollow Core","category":"Painting","unit":"EA","laborCost":55.00,"materialCost":8.50,"equipmentCost":1.00,"notes":"Slab door two sides and edges"},
    {"id":uid(),"name":"Interior Door Paint - Solid Core","category":"Painting","unit":"EA","laborCost":65.00,"materialCost":10.00,"equipmentCost":1.00,"notes":"Heavy solid core door paint"},
    {"id":uid(),"name":"Interior Door Paint - Panel Door","category":"Painting","unit":"EA","laborCost":75.00,"materialCost":10.00,"equipmentCost":1.00,"notes":"6 panel door brush and roll"},
    # ── Exterior Body ─────────────────────────────────────────
    {"id":uid(),"name":"Exterior Body Paint - 1 Coat Acrylic","category":"Painting","unit":"SF","laborCost":0.65,"materialCost":0.25,"equipmentCost":0.05,"notes":"Single coat exterior touch up"},
    {"id":uid(),"name":"Exterior Body Paint - 2 Coat Acrylic","category":"Painting","unit":"SF","laborCost":0.95,"materialCost":0.45,"equipmentCost":0.05,"notes":"Full 2 coat exterior paint"},
    {"id":uid(),"name":"Exterior Body Paint - Primer Plus 2 Coats","category":"Painting","unit":"SF","laborCost":1.25,"materialCost":0.65,"equipmentCost":0.06,"notes":"Full prime plus 2 finish coats"},
    {"id":uid(),"name":"Exterior Brick Paint - 2 Coats","category":"Painting","unit":"SF","laborCost":0.85,"materialCost":0.38,"equipmentCost":0.06,"notes":"Masonry paint on brick"},
    {"id":uid(),"name":"Exterior Stucco Paint - Elastomeric","category":"Painting","unit":"SF","laborCost":0.75,"materialCost":0.45,"equipmentCost":0.05,"notes":"Elastomeric waterproof coat"},
    {"id":uid(),"name":"Exterior Block or CMU Paint - 2 Coats","category":"Painting","unit":"SF","laborCost":0.75,"materialCost":0.38,"equipmentCost":0.05,"notes":"Block filler plus finish coat"},
    # ── Exterior Trim ─────────────────────────────────────────
    {"id":uid(),"name":"Exterior Trim Paint - Fascia Per LF","category":"Painting","unit":"LF","laborCost":1.85,"materialCost":0.35,"equipmentCost":0.08,"notes":"Fascia board brush coat"},
    {"id":uid(),"name":"Exterior Trim Paint - Window Casing Per Opening","category":"Painting","unit":"EA","laborCost":45.00,"materialCost":6.50,"equipmentCost":0.50,"notes":"Exterior window casing and sill"},
    {"id":uid(),"name":"Exterior Door Paint - Steel Entry","category":"Painting","unit":"EA","laborCost":95.00,"materialCost":12.00,"equipmentCost":1.50,"notes":"Entry door two sides and frame"},
    {"id":uid(),"name":"Exterior Door Paint - Wood Panel","category":"Painting","unit":"EA","laborCost":125.00,"materialCost":15.00,"equipmentCost":1.50,"notes":"Wood panel exterior door"},
    {"id":uid(),"name":"Exterior Soffit Paint - 2 Coats","category":"Painting","unit":"SF","laborCost":0.75,"materialCost":0.25,"equipmentCost":0.05,"notes":"Soffit overhead primer and coat"},
    {"id":uid(),"name":"Exterior Garage Door Paint - 2 Car","category":"Painting","unit":"EA","laborCost":185.00,"materialCost":22.00,"equipmentCost":3.00,"notes":"16 ft garage door full paint"},
    # ── Primers ────────────────────────────────────────────────
    {"id":uid(),"name":"Oil Based Primer - Interior","category":"Painting","unit":"SF","laborCost":0.35,"materialCost":0.28,"equipmentCost":0.03,"notes":"Stain blocking oil primer"},
    {"id":uid(),"name":"Shellac Primer - Stain Blocking","category":"Painting","unit":"SF","laborCost":0.38,"materialCost":0.45,"equipmentCost":0.03,"notes":"Zinsser BIN shellac primer"},
    {"id":uid(),"name":"Exterior Masonry Primer","category":"Painting","unit":"SF","laborCost":0.35,"materialCost":0.22,"equipmentCost":0.04,"notes":"Penetrating masonry prime"},
    {"id":uid(),"name":"Spray Applied Primer - Whole Room","category":"Painting","unit":"SF","laborCost":0.22,"materialCost":0.12,"equipmentCost":0.05,"notes":"Airless sprayer prime coat"},
    # ── Stains and Clear Coats ─────────────────────────────────
    {"id":uid(),"name":"Interior Wood Stain - Per Coat","category":"Painting","unit":"SF","laborCost":0.55,"materialCost":0.28,"equipmentCost":0.03,"notes":"Penetrating oil stain"},
    {"id":uid(),"name":"Interior Polyurethane Finish - Per Coat","category":"Painting","unit":"SF","laborCost":0.55,"materialCost":0.22,"equipmentCost":0.03,"notes":"Water based polyurethane"},
    {"id":uid(),"name":"Cabinet Stain and Clear Coat","category":"Painting","unit":"EA","laborCost":25.00,"materialCost":5.50,"equipmentCost":0.50,"notes":"Per door or drawer front"},
    {"id":uid(),"name":"Deck Stain - Semi Transparent","category":"Painting","unit":"SF","laborCost":0.55,"materialCost":0.28,"equipmentCost":0.05,"notes":"Semi-transparent oil deck stain"},
    {"id":uid(),"name":"Deck Stain - Solid Color","category":"Painting","unit":"SF","laborCost":0.65,"materialCost":0.35,"equipmentCost":0.05,"notes":"Solid color deck coating"},
    {"id":uid(),"name":"Fence Stain - Natural Cedar Tone","category":"Painting","unit":"SF","laborCost":0.45,"materialCost":0.22,"equipmentCost":0.04,"notes":"Cedar tone preservative fence stain"},
    {"id":uid(),"name":"Log Home Stain and Sealant","category":"Painting","unit":"SF","laborCost":0.85,"materialCost":0.55,"equipmentCost":0.08,"notes":"2 coat log home treatment"},
    # ── Specialty Coatings ─────────────────────────────────────
    {"id":uid(),"name":"Epoxy Floor Coating - 1 Part","category":"Painting","unit":"SF","laborCost":0.55,"materialCost":0.45,"equipmentCost":0.08,"notes":"1-part epoxy floor paint"},
    {"id":uid(),"name":"Epoxy Floor Coating - 2 Part","category":"Painting","unit":"SF","laborCost":1.25,"materialCost":1.85,"equipmentCost":0.15,"notes":"100% solids 2-part garage epoxy"},
    {"id":uid(),"name":"Epoxy Floor with Broadcast Flake","category":"Painting","unit":"SF","laborCost":1.65,"materialCost":2.25,"equipmentCost":0.18,"notes":"Flake system with topcoat"},
    {"id":uid(),"name":"Anti-Graffiti Coating - Exterior","category":"Painting","unit":"SF","laborCost":0.55,"materialCost":0.85,"equipmentCost":0.05,"notes":"Sacrificial anti-graffiti layer"},
    {"id":uid(),"name":"Waterproof Coating - Basement Wall","category":"Painting","unit":"SF","laborCost":0.65,"materialCost":0.85,"equipmentCost":0.06,"notes":"Drylok or Xypex crystalline"},
    {"id":uid(),"name":"Fire Retardant Paint - Intumescent","category":"Painting","unit":"SF","laborCost":0.85,"materialCost":1.25,"equipmentCost":0.08,"notes":"1 hour intumescent coating"},
    {"id":uid(),"name":"Anti-Rust Primer - Metal Surfaces","category":"Painting","unit":"SF","laborCost":0.55,"materialCost":0.45,"equipmentCost":0.06,"notes":"Rust inhibiting metal primer"},
    {"id":uid(),"name":"Metal Roof Paint - Elastomeric","category":"Painting","unit":"SF","laborCost":0.35,"materialCost":0.45,"equipmentCost":0.06,"notes":"White elastomeric roof coat"},
    # ── Cabinet Painting ──────────────────────────────────────
    {"id":uid(),"name":"Cabinet Painting - Interior Per Door","category":"Painting","unit":"EA","laborCost":35.00,"materialCost":6.50,"equipmentCost":0.50,"notes":"Cup and drawer front strip sand paint"},
    {"id":uid(),"name":"Cabinet Box Painting - Interior","category":"Painting","unit":"EA","laborCost":45.00,"materialCost":8.50,"equipmentCost":0.50,"notes":"Inside box paint with brush"},
    {"id":uid(),"name":"Cabinet Painting - Full Kitchen Set Labor Only","category":"Painting","unit":"EA","laborCost":1850.00,"materialCost":185.00,"equipmentCost":85.00,"notes":"Full kitchen cabinet repaint"},
    # ── Surface Prep ──────────────────────────────────────────
    {"id":uid(),"name":"Pressure Washing - Exterior Prep","category":"Painting","unit":"SF","laborCost":0.08,"materialCost":0.00,"equipmentCost":0.04,"notes":"3500 PSI pressure wash prep"},
    {"id":uid(),"name":"Caulking Before Paint - All Joints","category":"Painting","unit":"LF","laborCost":0.85,"materialCost":0.25,"equipmentCost":0.02,"notes":"Paintable acrylic caulk"},
    {"id":uid(),"name":"Sanding and Prep - Per Room","category":"Painting","unit":"EA","laborCost":125.00,"materialCost":15.00,"equipmentCost":8.00,"notes":"Full room sanding and prep"},
    {"id":uid(),"name":"Patching and Skim Before Paint - Per SF","category":"Painting","unit":"SF","laborCost":0.65,"materialCost":0.18,"equipmentCost":0.03,"notes":"Skim and sand before paint"},
    {"id":uid(),"name":"Paint Removal - Chemical Stripping","category":"Painting","unit":"SF","laborCost":1.25,"materialCost":0.65,"equipmentCost":0.08,"notes":"Gel stripper and scraper"},
    {"id":uid(),"name":"Lead Paint Encapsulation Coat","category":"Painting","unit":"SF","laborCost":0.75,"materialCost":0.55,"equipmentCost":0.06,"notes":"EPA compliant encapsulation"},
    # ── Specialty Techniques ───────────────────────────────────
    {"id":uid(),"name":"Faux Finish - Color Wash","category":"Painting","unit":"SF","laborCost":1.85,"materialCost":0.35,"equipmentCost":0.05,"notes":"Decorative color wash technique"},
    {"id":uid(),"name":"Faux Finish - Venetian Plaster","category":"Painting","unit":"SF","laborCost":3.50,"materialCost":0.85,"equipmentCost":0.08,"notes":"Multi-layer venetian plaster"},
    {"id":uid(),"name":"Spray Painting - Airless - Per Room","category":"Painting","unit":"EA","laborCost":185.00,"materialCost":45.00,"equipmentCost":25.00,"notes":"Airless spray new construction"},
    {"id":uid(),"name":"Paint Touchup - Per Hour","category":"Painting","unit":"HR","laborCost":75.00,"materialCost":8.50,"equipmentCost":2.00,"notes":"Punch list touch-up labor"},
    {"id":uid(),"name":"Painting Permit - Commercial","category":"Painting","unit":"EA","laborCost":0.00,"materialCost":85.00,"equipmentCost":0.00,"notes":"Commercial painting permit fee"},
    {"id":uid(),"name":"Color Consultation - Per Session","category":"Painting","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":0.00,"notes":"Full hour color consult"},
    {"id":uid(),"name":"New Construction Paint - Full House Per SF","category":"Painting","unit":"SF","laborCost":1.25,"materialCost":0.55,"equipmentCost":0.08,"notes":"Complete interior paint package"},
    {"id":uid(),"name":"Metallic Paint Accent Wall - Per SF","category":"Painting","unit":"SF","laborCost":2.25,"materialCost":1.85,"equipmentCost":0.15,"notes":"Decorative metallic finish"},
    {"id":uid(),"name":"Chalkboard Paint Application - Per SF","category":"Painting","unit":"SF","laborCost":0.85,"materialCost":0.45,"equipmentCost":0.05,"notes":"Black chalkboard paint area"},
    {"id":uid(),"name":"Magnetic Primer Application - Per SF","category":"Painting","unit":"SF","laborCost":0.75,"materialCost":0.65,"equipmentCost":0.05,"notes":"Base coat for magnet surfaces"},
    {"id":uid(),"name":"Whiteboard Paint - Clear or White SF","category":"Painting","unit":"SF","laborCost":1.25,"materialCost":2.85,"equipmentCost":0.25,"notes":"High gloss dry-erase wall"},
    {"id":uid(),"name":"Concrete Floor Sealer - High Gloss SF","category":"Painting","unit":"SF","laborCost":0.28,"materialCost":0.18,"equipmentCost":0.04,"notes":"Clear wet-look concrete sealer"},
    {"id":uid(),"name":"Concrete Floor Stain - Water Based SF","category":"Painting","unit":"SF","laborCost":0.65,"materialCost":0.35,"equipmentCost":0.08,"notes":"Semi-transparent floor stain"},
    {"id":uid(),"name":"Concrete Floor Stain - Acid Etched SF","category":"Painting","unit":"SF","laborCost":1.25,"materialCost":0.45,"equipmentCost":0.15,"notes":"Reactive acid stain finish"},
    {"id":uid(),"name":"Garage Floor Epoxy - 2 Part Kit SF","category":"Painting","unit":"SF","laborCost":1.85,"materialCost":1.15,"equipmentCost":0.10,"notes":"Standard 2-part epoxy floor"},
    {"id":uid(),"name":"Garage Floor Epoxy - Full Flake SF","category":"Painting","unit":"SF","laborCost":2.50,"materialCost":1.85,"equipmentCost":0.15,"notes":"Industrial broadcast flake system"},
    {"id":uid(),"name":"Basement Floor Paint - Anti-Slip SF","category":"Painting","unit":"SF","laborCost":0.45,"materialCost":0.28,"equipmentCost":0.04,"notes":"Enamel floor paint with grit"},
    {"id":uid(),"name":"Deck Staining - Transparent Per SF","category":"Painting","unit":"SF","laborCost":0.75,"materialCost":0.35,"equipmentCost":0.08,"notes":"Clear oil deck sealer"},
    {"id":uid(),"name":"Deck Staining - Semi-Transparent SF","category":"Painting","unit":"SF","laborCost":0.85,"materialCost":0.45,"equipmentCost":0.08,"notes":"Pigmented deck stain"},
    {"id":uid(),"name":"Fence Staining - Power Spray Per LF","category":"Painting","unit":"LF","laborCost":1.25,"materialCost":0.85,"equipmentCost":0.25,"notes":"Airless spray for privacy fence"},
    {"id":uid(),"name":"Exterior Trim Painting - Detailed LF","category":"Painting","unit":"LF","laborCost":2.25,"materialCost":0.45,"equipmentCost":0.10,"notes":"Ornate molding and dentils"},
    {"id":uid(),"name":"Shutters Painting - Per Pair EA","category":"Painting","unit":"EA","laborCost":45.00,"materialCost":12.00,"equipmentCost":5.00,"notes":"Clean and repaint exterior shutters"},
    {"id":uid(),"name":"Exterior Door Painting - Front Door EA","category":"Painting","unit":"EA","laborCost":125.00,"materialCost":22.00,"equipmentCost":5.00,"notes":"Clean prep and 2 coat front door"},
    {"id":uid(),"name":"Garage Door Painting - 2 Car Sectional","category":"Painting","unit":"EA","laborCost":225.00,"materialCost":45.00,"equipmentCost":15.00,"notes":"Spray sectional metal garage door"},
    {"id":uid(),"name":"Wrought Iron Railing Painting - Per LF","category":"Painting","unit":"LF","laborCost":6.50,"materialCost":1.25,"equipmentCost":2.50,"notes":"Rust brush and black enamel"},
    {"id":uid(),"name":"Pipe Painting - Color Coded Per LF","category":"Painting","unit":"LF","laborCost":1.50,"materialCost":0.35,"equipmentCost":0.05,"notes":"Identification paint for utilities"},
    {"id":uid(),"name":"Fire Hydrant Painting - Safety Yellow EA","category":"Painting","unit":"EA","laborCost":65.00,"materialCost":12.00,"equipmentCost":2.00,"notes":"Code compliant hydrant paint"},
    {"id":uid(),"name":"Safety Stripe Painting - Warehouse LF","category":"Painting","unit":"LF","laborCost":0.45,"materialCost":0.25,"equipmentCost":0.15,"notes":"Yellow safety line painting"},
    {"id":uid(),"name":"Parking Lot Stripping - Single Stall EA","category":"Painting","unit":"EA","laborCost":12.00,"materialCost":4.50,"equipmentCost":15.00,"notes":"White parking stall line"},
    {"id":uid(),"name":"Parking Lot Stripping - Handicap Symbol","category":"Painting","unit":"EA","laborCost":45.00,"materialCost":12.00,"equipmentCost":5.00,"notes":"Blue and white accessible symbol"},
    {"id":uid(),"name":"Wallpaper Primer - Shielding Per SF","category":"Painting","unit":"SF","laborCost":0.22,"materialCost":0.18,"equipmentCost":0.02,"notes":"Sizing coat before paper"},
    {"id":uid(),"name":"Wallpaper Installation - Non-Woven SF","category":"Painting","unit":"SF","laborCost":1.85,"materialCost":0.00,"equipmentCost":0.10,"notes":"Professional hang labor only"},
    {"id":uid(),"name":"Wallpaper Installation - Grasscloth SF","category":"Painting","unit":"SF","laborCost":2.85,"materialCost":0.00,"equipmentCost":0.15,"notes":"Delicate natural fiber hang"},
    {"id":uid(),"name":"Wall Liner Installation - Per SF","category":"Painting","unit":"SF","laborCost":0.65,"materialCost":0.45,"equipmentCost":0.05,"notes":"Canvas or paper wall liner"},
    {"id":uid(),"name":"Murals and Hand-Painted Graphics SF","category":"Painting","unit":"SF","laborCost":12.00,"materialCost":1.25,"equipmentCost":0.55,"notes":"Custom artist hand painting"},
    {"id":uid(),"name":"Stencil Pattern Painting - Per SF","category":"Painting","unit":"SF","laborCost":4.50,"materialCost":0.35,"equipmentCost":0.15,"notes":"Repeat pattern stencil work"},
    {"id":uid(),"name":"Anti-Microbial Paint Additive Per Gal","category":"Painting","unit":"EA","laborCost":0.00,"materialCost":12.50,"equipmentCost":0.00,"notes":"Silver ion additive for clinics"},
    {"id":uid(),"name":"Heavy Duty Scaffolding Setup EA","category":"Painting","unit":"EA","laborCost":285.00,"materialCost":0.00,"equipmentCost":450.00,"notes":"Multi-tier internal scaffold"},
    {"id":uid(),"name":"Paint Odor Neutralizer - Per Gal EA","category":"Painting","unit":"EA","laborCost":0.00,"materialCost":8.50,"equipmentCost":0.00,"notes":"Vanilla or similar scent additive"},
    {"id":uid(),"name":"Glistening Glitter Additive - Per Gal EA","category":"Painting","unit":"EA","laborCost":0.00,"materialCost":15.00,"equipmentCost":0.00,"notes":"Decorative glitter suspension"},
    {"id":uid(),"name":"Dry Erase Wall Clear Topcoat SF","category":"Painting","unit":"SF","laborCost":1.25,"materialCost":2.25,"equipmentCost":0.15,"notes":"Clear dry-erase over color"},
    {"id":uid(),"name":"Painting Site Visit - Detailed Estimating","category":"Painting","unit":"EA","laborCost":85.00,"materialCost":0.00,"equipmentCost":5.00,"notes":"Professional measurement trip"},
]
