"""TrimAgent — 100 items for millwork and interior trim"""
import uuid
def uid(): return str(uuid.uuid4())
ITEMS = [
    # ── Baseboard ─────────────────────────────────────────────
    {"id":uid(),"name":"Baseboard Install - 3.5 Inch MDF Colonial","category":"Trim","unit":"LF","laborCost":1.85,"materialCost":0.75,"equipmentCost":0.05,"notes":"Standard colonial MDF base"},
    {"id":uid(),"name":"Baseboard Install - 5.5 Inch MDF Craftsman","category":"Trim","unit":"LF","laborCost":2.25,"materialCost":1.25,"equipmentCost":0.05,"notes":"Tall craftsman MDF base"},
    {"id":uid(),"name":"Baseboard Install - 3.5 Inch Wood Pine","category":"Trim","unit":"LF","laborCost":1.95,"materialCost":0.95,"equipmentCost":0.05,"notes":"Solid pine base paint grade"},
    {"id":uid(),"name":"Baseboard Install - 5.5 Inch Solid Wood","category":"Trim","unit":"LF","laborCost":2.50,"materialCost":1.65,"equipmentCost":0.05,"notes":"Tall solid wood base"},
    {"id":uid(),"name":"Baseboard Install - 7.25 Inch Solid Wood","category":"Trim","unit":"LF","laborCost":3.25,"materialCost":2.50,"equipmentCost":0.05,"notes":"Premium tall baseboard"},
    {"id":uid(),"name":"Base Shoe Quarter Round Install","category":"Trim","unit":"LF","laborCost":0.85,"materialCost":0.35,"equipmentCost":0.02,"notes":"Base shoe at flooring"},
    {"id":uid(),"name":"Baseboard Removal and Disposal","category":"Trim","unit":"LF","laborCost":0.55,"materialCost":0.00,"equipmentCost":0.02,"notes":"Pry and remove existing base"},
    # ── Crown Molding ─────────────────────────────────────────
    {"id":uid(),"name":"Crown Molding Install - 3.5 Inch MDF","category":"Trim","unit":"LF","laborCost":2.85,"materialCost":0.95,"equipmentCost":0.05,"notes":"Standard spring crown MDF"},
    {"id":uid(),"name":"Crown Molding Install - 5.5 Inch MDF","category":"Trim","unit":"LF","laborCost":3.50,"materialCost":1.65,"equipmentCost":0.05,"notes":"Large spring crown MDF"},
    {"id":uid(),"name":"Crown Molding Install - 5.5 Inch Solid Wood","category":"Trim","unit":"LF","laborCost":4.25,"materialCost":2.50,"equipmentCost":0.05,"notes":"Solid wood premium crown"},
    {"id":uid(),"name":"Built-Up Crown Assembly - 3 Piece","category":"Trim","unit":"LF","laborCost":6.50,"materialCost":3.50,"equipmentCost":0.10,"notes":"Blocking cove and cap assembly"},
    {"id":uid(),"name":"Coffered Ceiling Box Trim","category":"Trim","unit":"EA","laborCost":125.00,"materialCost":85.00,"equipmentCost":5.00,"notes":"Per box opening frame and crown"},
    # ── Window and Door Casing ─────────────────────────────────
    {"id":uid(),"name":"Window Casing Install - Craftsman 3.5 Inch","category":"Trim","unit":"EA","laborCost":55.00,"materialCost":18.00,"equipmentCost":1.00,"notes":"Per window three-sided casing"},
    {"id":uid(),"name":"Window Casing Install - Colonial 2.25 Inch","category":"Trim","unit":"EA","laborCost":45.00,"materialCost":12.00,"equipmentCost":1.00,"notes":"Traditional colonial profile"},
    {"id":uid(),"name":"Window Casing Install - Picture Frame","category":"Trim","unit":"EA","laborCost":65.00,"materialCost":22.00,"equipmentCost":1.00,"notes":"Four sided picture frame"},
    {"id":uid(),"name":"Door Casing Install - Interior Per Opening","category":"Trim","unit":"EA","laborCost":75.00,"materialCost":22.00,"equipmentCost":1.00,"notes":"Both sides of opening"},
    {"id":uid(),"name":"Door Casing Install - Craftsman Block","category":"Trim","unit":"EA","laborCost":85.00,"materialCost":28.00,"equipmentCost":1.00,"notes":"Craftsman with plinth blocks"},
    {"id":uid(),"name":"Window Stool and Apron Install","category":"Trim","unit":"EA","laborCost":45.00,"materialCost":15.00,"equipmentCost":0.50,"notes":"Interior window ledge and apron"},
    # ── Chair Rail and Wainscoting ─────────────────────────────
    {"id":uid(),"name":"Chair Rail Install - 3 Inch MDF","category":"Trim","unit":"LF","laborCost":2.25,"materialCost":0.85,"equipmentCost":0.05,"notes":"Mid-wall chair rail"},
    {"id":uid(),"name":"Chair Rail Install - Solid Wood","category":"Trim","unit":"LF","laborCost":2.85,"materialCost":1.25,"equipmentCost":0.05,"notes":"Solid profile chair rail"},
    {"id":uid(),"name":"Shaker Panel Wainscoting - Per SF","category":"Trim","unit":"SF","laborCost":4.50,"materialCost":3.25,"equipmentCost":0.25,"notes":"Frame and panel wainscoting"},
    {"id":uid(),"name":"Board and Batten Wainscoting - Per SF","category":"Trim","unit":"SF","laborCost":3.50,"materialCost":2.25,"equipmentCost":0.15,"notes":"Vertical boards with cap"},
    {"id":uid(),"name":"Raised Panel Wainscoting - MDF","category":"Trim","unit":"SF","laborCost":5.50,"materialCost":4.50,"equipmentCost":0.30,"notes":"Full raised panel wainscoting"},
    {"id":uid(),"name":"Picture Frame Wainscoting Molding","category":"Trim","unit":"EA","laborCost":12.00,"materialCost":6.50,"equipmentCost":0.25,"notes":"Per frame box install"},
    # ── Door Hardware ─────────────────────────────────────────
    {"id":uid(),"name":"Interior Door Handle Install - Passage","category":"Trim","unit":"EA","laborCost":25.00,"materialCost":28.00,"equipmentCost":0.50,"notes":"Passage no lock set"},
    {"id":uid(),"name":"Interior Door Handle Install - Privacy","category":"Trim","unit":"EA","laborCost":28.00,"materialCost":38.00,"equipmentCost":0.50,"notes":"Privacy bedroom or bath lock"},
    {"id":uid(),"name":"Interior Door Handle Install - Dummy","category":"Trim","unit":"EA","laborCost":18.00,"materialCost":18.00,"equipmentCost":0.25,"notes":"Non-turning dummy handle"},
    {"id":uid(),"name":"Exterior Door Lockset Install - Keyed","category":"Trim","unit":"EA","laborCost":55.00,"materialCost":65.00,"equipmentCost":1.00,"notes":"Exterior knob or lever keyed"},
    {"id":uid(),"name":"Deadbolt Lock Install - Single Cylinder","category":"Trim","unit":"EA","laborCost":45.00,"materialCost":45.00,"equipmentCost":0.50,"notes":"Single cylinder deadbolt"},
    {"id":uid(),"name":"Door Hinge Install - 3.5 Inch Butt","category":"Trim","unit":"EA","laborCost":12.00,"materialCost":5.50,"equipmentCost":0.25,"notes":"Per hinge mortised install"},
    {"id":uid(),"name":"Door Stop Install - Spring or Rigid","category":"Trim","unit":"EA","laborCost":5.00,"materialCost":3.50,"equipmentCost":0.10,"notes":"Per door stop baseplate"},
    {"id":uid(),"name":"Door Closer Install - Commercial","category":"Trim","unit":"EA","laborCost":55.00,"materialCost":85.00,"equipmentCost":2.00,"notes":"ADA compliant door closer"},
    {"id":uid(),"name":"Barn Door Hardware Install - Sliding","category":"Trim","unit":"EA","laborCost":85.00,"materialCost":185.00,"equipmentCost":5.00,"notes":"Track and hardware 6 ft"},
    # ── Built-Ins and Shelving ────────────────────────────────
    {"id":uid(),"name":"Built-In Shelving - Simple Fixed Shelf","category":"Trim","unit":"LF","laborCost":18.00,"materialCost":12.00,"equipmentCost":0.50,"notes":"Single shelf with cleats"},
    {"id":uid(),"name":"Built-In Bookcase - 3 Shelf Paint Grade","category":"Trim","unit":"LF","laborCost":55.00,"materialCost":38.00,"equipmentCost":2.00,"notes":"Wall-to-wall bookcase per LF width"},
    {"id":uid(),"name":"Built-In Entertainment Center - Custom","category":"Trim","unit":"LF","laborCost":125.00,"materialCost":95.00,"equipmentCost":5.00,"notes":"Per LF width custom millwork"},
    {"id":uid(),"name":"Window Seat Built-In","category":"Trim","unit":"LF","laborCost":85.00,"materialCost":55.00,"equipmentCost":3.00,"notes":"Box seat with hinge lid storage"},
    {"id":uid(),"name":"Floating Shelf Install - Wood","category":"Trim","unit":"EA","laborCost":35.00,"materialCost":25.00,"equipmentCost":1.00,"notes":"Floating shelf with blind mount"},
    # ── Closets and Systems ────────────────────────────────────
    {"id":uid(),"name":"Closet Shelf and Rod Install - Standard","category":"Trim","unit":"EA","laborCost":125.00,"materialCost":65.00,"equipmentCost":3.00,"notes":"Single rod and shelf walk-in"},
    {"id":uid(),"name":"Closet Organizer System Install - Wire","category":"Trim","unit":"EA","laborCost":185.00,"materialCost":125.00,"equipmentCost":5.00,"notes":"Full wire organizer walk-in"},
    {"id":uid(),"name":"Closet Organizer System - Custom Wood","category":"Trim","unit":"EA","laborCost":285.00,"materialCost":485.00,"equipmentCost":10.00,"notes":"Full wood custom closet"},
    {"id":uid(),"name":"Closet Rod Install - Wooden","category":"Trim","unit":"LF","laborCost":4.50,"materialCost":2.85,"equipmentCost":0.25,"notes":"Wood closet bar with flanges"},
    {"id":uid(),"name":"Linen Closet Shelving - Fixed","category":"Trim","unit":"EA","laborCost":95.00,"materialCost":45.00,"equipmentCost":2.00,"notes":"5 adjustable shelves in linen"},
    # ── Stair Components ──────────────────────────────────────
    {"id":uid(),"name":"Stair Handrail Install - Wood Profile","category":"Trim","unit":"LF","laborCost":8.50,"materialCost":6.50,"equipmentCost":0.25,"notes":"Graspable wood handrail"},
    {"id":uid(),"name":"Stair Baluster Install - Turned Wood","category":"Trim","unit":"EA","laborCost":22.00,"materialCost":8.50,"equipmentCost":0.50,"notes":"Per turned baluster"},
    {"id":uid(),"name":"Stair Baluster Install - Square Metal","category":"Trim","unit":"EA","laborCost":18.00,"materialCost":12.00,"equipmentCost":0.50,"notes":"Iron square baluster"},
    {"id":uid(),"name":"Newel Post Install - Box Style","category":"Trim","unit":"EA","laborCost":85.00,"materialCost":65.00,"equipmentCost":3.00,"notes":"Box newel at stair base"},
    {"id":uid(),"name":"Newel Post Install - Turned","category":"Trim","unit":"EA","laborCost":65.00,"materialCost":45.00,"equipmentCost":2.00,"notes":"Classic turned newel post"},
    {"id":uid(),"name":"Stair Skirt Board Install","category":"Trim","unit":"LF","laborCost":5.50,"materialCost":2.50,"equipmentCost":0.15,"notes":"Finish board along stringer"},
    {"id":uid(),"name":"Stair Riser Install - Paint Grade MDF","category":"Trim","unit":"EA","laborCost":22.00,"materialCost":8.50,"equipmentCost":0.50,"notes":"Per riser MDF install"},
    # ── Specialty Trim ─────────────────────────────────────────
    {"id":uid(),"name":"Ceiling Medallion Install - Round","category":"Trim","unit":"EA","laborCost":45.00,"materialCost":35.00,"equipmentCost":1.00,"notes":"Ornate ceiling medallion"},
    {"id":uid(),"name":"Beam Wrap Install - Faux Wood","category":"Trim","unit":"LF","laborCost":8.50,"materialCost":6.50,"equipmentCost":0.25,"notes":"Hollow faux beam wrap"},
    {"id":uid(),"name":"Panel Molding - Raised Flush Dado","category":"Trim","unit":"LF","laborCost":3.25,"materialCost":1.25,"equipmentCost":0.10,"notes":"Decorative dado wall molding"},
    {"id":uid(),"name":"Fireplace Mantel Install - Stock","category":"Trim","unit":"EA","laborCost":185.00,"materialCost":385.00,"equipmentCost":10.00,"notes":"Pre-built mantel set install"},
    {"id":uid(),"name":"Fireplace Mantel Install - Custom","category":"Trim","unit":"EA","laborCost":485.00,"materialCost":850.00,"equipmentCost":15.00,"notes":"Custom millwork mantel"},
    {"id":uid(),"name":"Attic Access Door and Frame Install","category":"Trim","unit":"EA","laborCost":95.00,"materialCost":45.00,"equipmentCost":3.00,"notes":"Insulated attic access door"},
    {"id":uid(),"name":"Interior Door Install - Pre-Hung","category":"Trim","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":3.00,"notes":"Labor to hang pre-hung door"},
    {"id":uid(),"name":"Interior Door Install - Slab Door Reframe","category":"Trim","unit":"EA","laborCost":155.00,"materialCost":15.00,"equipmentCost":5.00,"notes":"Slab in existing jamb"},
    {"id":uid(),"name":"Pocket Door Frame Kit Install","category":"Trim","unit":"EA","laborCost":125.00,"materialCost":145.00,"equipmentCost":5.00,"notes":"Complete pocket door kit"},
    {"id":uid(),"name":"Bi-Fold Door Install","category":"Trim","unit":"EA","laborCost":75.00,"materialCost":0.00,"equipmentCost":2.00,"notes":"Labor to hang bi-fold panel"},
    {"id":uid(),"name":"Bypass Closet Door Install","category":"Trim","unit":"EA","laborCost":85.00,"materialCost":0.00,"equipmentCost":2.00,"notes":"Two panel bypass track"},
    {"id":uid(),"name":"Trim Caulk and Fill - Per LF","category":"Trim","unit":"LF","laborCost":0.55,"materialCost":0.12,"equipmentCost":0.02,"notes":"Paintable caulk and nail fill"},
    {"id":uid(),"name":"Trim Adhesive and Nail - Finish","category":"Trim","unit":"LF","laborCost":0.35,"materialCost":0.08,"equipmentCost":0.02,"notes":"Liquid nails and brad nail finish"},
    {"id":uid(),"name":"Picture Frame Molding - Per SF Area","category":"Trim","unit":"SF","laborCost":3.50,"materialCost":1.85,"equipmentCost":0.15,"notes":"Custom wall picture framing"},
    {"id":uid(),"name":"Dentil Crown Molding - Hand Stacked LF","category":"Trim","unit":"LF","laborCost":6.50,"materialCost":4.50,"equipmentCost":0.25,"notes":"Premium dentil detail crown"},
    {"id":uid(),"name":"Rope Mold Accent - Gilded LF","category":"Trim","unit":"LF","laborCost":2.25,"materialCost":5.50,"equipmentCost":0.10,"notes":"Decorative rope transition mold"},
    {"id":uid(),"name":"Frieze Board Trim - Ornate LF","category":"Trim","unit":"LF","laborCost":3.85,"materialCost":4.25,"equipmentCost":0.15,"notes":"High wall frieze molding"},
    {"id":uid(),"name":"Corner Block - Bullnose EA","category":"Trim","unit":"EA","laborCost":8.50,"materialCost":12.50,"equipmentCost":0.50,"notes":"Plinth or bullnose transition block"},
    {"id":uid(),"name":"Rosette Block - Ornate EA","category":"Trim","unit":"EA","laborCost":6.50,"materialCost":8.50,"equipmentCost":0.50,"notes":"Casing corner decorative block"},
    {"id":uid(),"name":"Plinth Block - High Design EA","category":"Trim","unit":"EA","laborCost":12.00,"materialCost":18.00,"equipmentCost":0.50,"notes":"Decorative base to casing block"},
    {"id":uid(),"name":"Ceiling Medallion - Plaster 24 Inch EA","category":"Trim","unit":"EA","laborCost":85.00,"materialCost":125.00,"equipmentCost":5.00,"notes":"Ornate ceiling feature medallion"},
    {"id":uid(),"name":"Corbel Support - Decorative Wood EA","category":"Trim","unit":"EA","laborCost":45.00,"materialCost":65.00,"equipmentCost":2.00,"notes":"Shelf or overhang decorative support"},
    {"id":uid(),"name":"Closet Pole and Socket - Heavy Duty LF","category":"Trim","unit":"LF","laborCost":4.50,"materialCost":8.50,"equipmentCost":0.50,"notes":"Steel pole with end sockets"},
    {"id":uid(),"name":"Closet Shelf - Wire Ventilated LF","category":"Trim","unit":"LF","laborCost":3.50,"materialCost":5.50,"equipmentCost":0.25,"notes":"Rubbermaid/ClosetMaid style shelf"},
    {"id":uid(),"name":"Closet Shelf - Wood Veneer LF","category":"Trim","unit":"LF","laborCost":5.50,"materialCost":12.00,"equipmentCost":0.50,"notes":"Adjustable wood closet shelving"},
    {"id":uid(),"name":"Dutch Door Conversion - Labor EA","category":"Trim","unit":"EA","laborCost":185.00,"materialCost":35.00,"equipmentCost":5.00,"notes":"Cut and hinge existing door"},
    {"id":uid(),"name":"French Door Trim Set - Double Opening EA","category":"Trim","unit":"EA","laborCost":145.00,"materialCost":65.00,"equipmentCost":5.00,"notes":"Labor only to casing double door"},
    {"id":uid(),"name":"Transom Window Trim - Interior EA","category":"Trim","unit":"EA","laborCost":85.00,"materialCost":35.00,"equipmentCost":2.00,"notes":"Detailed trim around transom"},
    {"id":uid(),"name":"Archway Casing Wrap - Flexible Trim LF","category":"Trim","unit":"LF","laborCost":12.00,"materialCost":18.00,"equipmentCost":5.00,"notes":"Curved wall casing installation"},
    {"id":uid(),"name":"Column Wrap - Fluted Square EA","category":"Trim","unit":"EA","laborCost":185.00,"materialCost":245.00,"equipmentCost":10.00,"notes":"4-sided fluted column wrap"},
    {"id":uid(),"name":"Column Wrap - Smooth Round EA","category":"Trim","unit":"EA","laborCost":225.00,"materialCost":350.00,"equipmentCost":15.00,"notes":"Segmented round column wrap"},
    {"id":uid(),"name":"Wainscoting - Shiplap Vertical Per SF","category":"Trim","unit":"SF","laborCost":2.50,"materialCost":1.85,"equipmentCost":0.15,"notes":"Vertical nickel gap shiplap"},
    {"id":uid(),"name":"Wainscoting - Raised Panel Wood SF","category":"Trim","unit":"SF","laborCost":8.50,"materialCost":12.50,"equipmentCost":0.50,"notes":"Traditional raised panel wall"},
    {"id":uid(),"name":"Plate Rail Molding - High Wall LF","category":"Trim","unit":"LF","laborCost":4.50,"materialCost":6.50,"equipmentCost":0.25,"notes":"Horizontal plate display shelf"},
    {"id":uid(),"name":"Picture Rail Molding - Solid Oak LF","category":"Trim","unit":"LF","laborCost":3.25,"materialCost":5.50,"equipmentCost":0.15,"notes":"Wall hook rail for hanging art"},
    {"id":uid(),"name":"Chair Rail - Two Piece Build Up LF","category":"Trim","unit":"LF","laborCost":2.85,"materialCost":1.25,"equipmentCost":0.10,"notes":"Standard 3-inch chair rail"},
    {"id":uid(),"name":"Baseboard - Three Piece Build Up LF","category":"Trim","unit":"LF","laborCost":3.50,"materialCost":2.25,"equipmentCost":0.15,"notes":"Layered baseboard detail"},
    {"id":uid(),"name":"Door Stop - Solid Brass EA","category":"Trim","unit":"EA","laborCost":8.50,"materialCost":12.00,"equipmentCost":0.00,"notes":"Spring or solid floor door stop"},
    {"id":uid(),"name":"Hinge - Heavy Duty Ball Bearing Set EA","category":"Trim","unit":"EA","laborCost":12.00,"materialCost":22.00,"equipmentCost":1.00,"notes":"Per set of 3 hinges"},
    {"id":uid(),"name":"Door Handle - Privacy Lever Set EA","category":"Trim","unit":"EA","laborCost":35.00,"materialCost":45.00,"equipmentCost":1.00,"notes":"Bathroom/Bedroom lever set"},
    {"id":uid(),"name":"Door Handle - Entry Mortise Lock EA","category":"Trim","unit":"EA","laborCost":185.00,"materialCost":350.00,"equipmentCost":15.00,"notes":"High security mortise lock set"},
    {"id":uid(),"name":"Door Viewer - Peep Hole Brass EA","category":"Trim","unit":"EA","laborCost":25.00,"materialCost":12.00,"equipmentCost":2.00,"notes":"Security door viewer install"},
    {"id":uid(),"name":"Trim Site Audit and Punch List Trip","category":"Trim","unit":"EA","laborCost":125.00,"materialCost":0.00,"equipmentCost":5.00,"notes":"Final quality control visit"},
]
